import type { Language } from './storage';

export interface CityData {
  name: { pl: string; native: string; };
  description: { pl: string; native: string; };
  facts: {
    population: string;
    area: { pl: string; native: string; };
    landmark: { pl: string; native: string; };
    founded: { pl: string; native: string; };
    nickname: { pl: string; native: string; };
  };
}

export interface CitiesPageData {
  lang: Language;
  countryName: { pl: string; native: string; };
  cities: CityData[];
  ui: {
    title: { pl: string; native: string; };
    backButton: { pl: string; native: string; };
    language: { pl: string; native: string; };
    population: { pl: string; native: string; };
    area: { pl: string; native: string; };
    landmark: { pl: string; native: string; };
    founded: { pl: string; native: string; };
    nickname: { pl: string; native: string; };
  }
}

export const allCitiesData: Record<Language, CitiesPageData> = {
  en: {
    lang: 'en',
    countryName: { pl: 'Anglia', native: 'England' },
    cities: [
      { name: { pl: 'Londyn', native: 'London' }, description: { pl: 'Stolica Anglii, globalne centrum finansów, kultury i mody. Miasto oferuje nieskończoną liczbę atrakcji, od ikonicznych zabytków jak Tower of London, przez światowej klasy muzea (British Museum, Tate Modern), po tętniące życiem teatry West Endu i różnorodne dzielnice, takie jak Notting Hill czy Camden.', native: 'The capital of England, a global hub for finance, culture, and fashion. The city offers an endless number of attractions, from iconic landmarks like the Tower of London, through world-class museums (British Museum, Tate Modern), to the vibrant theatres of the West End and diverse districts like Notting Hill or Camden.' }, facts: { population: '~9.0 million', area: { pl: '1,572 km²', native: '607 sq mi' }, landmark: { pl: 'Pałac Buckingham', native: 'Buckingham Palace' }, founded: {pl: '47 n.e.', native: '47 AD'}, nickname: { pl: 'The Big Smoke', native: 'The Big Smoke' } } },
      { name: { pl: 'Manchester', native: 'Manchester' }, description: { pl: 'Serce rewolucji przemysłowej, znane z bogatej sceny muzycznej, która wydała takie zespoły jak The Smiths i Oasis. Miasto łączy dziedzictwo industrialne z nowoczesną energią, będąc domem dla dwóch potężnych klubów piłkarskich i dynamicznie rozwijającego się centrum medialnego w Salford Quays.', native: 'The heart of the Industrial Revolution, known for its rich music scene that produced bands like The Smiths and Oasis. The city blends industrial heritage with modern energy, being home to two powerful football clubs and a rapidly growing media hub at Salford Quays.' }, facts: { population: '~550,000', area: { pl: '115 km²', native: '44.6 sq mi' }, landmark: { pl: 'Stadion Old Trafford', native: 'Old Trafford Stadium' }, founded: {pl: '79 n.e.', native: '79 AD'}, nickname: { pl: 'Cottonopolis', native: 'Cottonopolis' } } },
      { name: { pl: 'Birmingham', native: 'Birmingham' }, description: { pl: 'Kluczowe miasto przemysłowe z rozległą siecią kanałów, większą niż w Wenecji. Dziś to tętniące życiem centrum handlu, z nowoczesnym centrum handlowym Bullring, oraz bogatej sceny kulinarnej, w tym słynnego "Balti Triangle". Miasto jest również gospodarzem wielu międzynarodowych wydarzeń.', native: 'A key industrial city with an extensive canal network, larger than Venice\'s. Today, it is a bustling hub for commerce, with the modern Bullring shopping centre, and a rich culinary scene, including the famous "Balti Triangle". The city also hosts many international events.' }, facts: { population: '~1.1 million', area: { pl: '267 km²', native: '103.4 sq mi' }, landmark: { pl: 'Biblioteka w Birmingham', native: 'Library of Birmingham' }, founded: {pl: 'XII wiek', native: '12th century'}, nickname: { pl: 'Miasto Tysiąca Fachów', native: 'City of a Thousand Trades' } } },
      { name: { pl: 'Liverpool', native: 'Liverpool' }, description: { pl: 'Miasto Beatlesów i morskiej historii, które szczyci się większą liczbą muzeów i galerii niż jakiekolwiek inne miasto w Wielkiej Brytanii poza Londynem. Jego nabrzeże, z historycznym Albert Dock, jest wpisane na listę UNESCO i tętni życiem, kulturą i muzyką.', native: 'The city of The Beatles and maritime history, boasting more museums and galleries than any other UK city outside of London. Its waterfront, with the historic Albert Dock, is a UNESCO World Heritage site and buzzes with life, culture, and music.' }, facts: { population: '~500,000', area: { pl: '111 km²', native: '43.2 sq mi' }, landmark: { pl: 'Albert Dock', native: 'Albert Dock' }, founded: {pl: '1207', native: '1207'}, nickname: { pl: 'Basen Życia', native: 'The Pool of Life' } } },
      { name: { pl: 'Bristol', native: 'Bristol' }, description: { pl: 'Znany z prężnej sceny kulturalnej, sztuki ulicznej (w tym Banksy\'ego) i ikonicznego mostu wiszącego Clifton. To miasto kreatywności i innowacji, z silnym duchem niezależności, co widać w licznych niezależnych sklepach, kawiarniach i festiwalach.', native: 'Known for its vibrant cultural scene, street art (including Banksy), and the iconic Clifton Suspension Bridge. It is a city of creativity and innovation, with a strong independent spirit reflected in its many independent shops, cafes, and festivals.' }, facts: { population: '~470,000', area: { pl: '110 km²', native: '42 sq mi' }, landmark: { pl: 'Most Wiszący Clifton', native: 'Clifton Suspension Bridge' }, founded: {pl: 'ok. 1000', native: 'c. 1000'}, nickname: { pl: 'Brizzle', native: 'Brizzle' } } },
    ],
    ui: { title: { pl: 'Miasta Anglii', native: 'Cities of England' }, backButton: { pl: 'Powrót do Kultury', native: 'Back to Culture' }, language: { pl: 'Język', native: 'Language' }, population: { pl: 'Populacja', native: 'Population' }, area: { pl: 'Powierzchnia', native: 'Area' }, landmark: { pl: 'Główny zabytek', native: 'Key Landmark' }, founded: { pl: 'Założenie', native: 'Founded' }, nickname: { pl: 'Przydomek', native: 'Nickname' } }
  },
  de: {
    lang: 'de',
    countryName: { pl: 'Niemcy', native: 'Deutschland' },
    cities: [
      { name: { pl: 'Berlin', native: 'Berlin' }, description: { pl: 'Stolica Niemiec, miasto historii, sztuki i nieskończonych możliwości. Symbolami są Brama Brandenburska i pozostałości Muru Berlińskiego. Berlin jest znany ze swojej otwartej atmosfery, życia nocnego i dynamicznej sceny artystycznej, przyciągając twórców z całego świata.', native: 'The capital of Germany, a city of history, art, and endless possibilities. Its symbols are the Brandenburg Gate and the remnants of the Berlin Wall. Berlin is known for its open atmosphere, nightlife, and dynamic art scene, attracting creators from all over the world.' }, facts: { population: '~3.7 million', area: { pl: '891 km²', native: '344 sq mi' }, landmark: { pl: 'Brama Brandenburska', native: 'Brandenburger Tor' }, founded: {pl: '1237', native: '1237'}, nickname: { pl: 'Szare Miasto', native: 'Die Graue Stadt' } } },
      { name: { pl: 'Hamburg', native: 'Hamburg' }, description: { pl: 'Główne miasto portowe Niemiec z siecią kanałów i historycznym Speicherstadt, wpisanym na listę UNESCO. Słynie z Elbphilharmonie i tętniącego życiem portu, a także dzielnicy rozrywki St. Pauli z ulicą Reeperbahn, oferując unikalne połączenie kultury i zabawy.', native: 'Germany\'s main port city with a network of canals and the historic Speicherstadt, a UNESCO World Heritage site. Famous for the Elbphilharmonie and its bustling harbor, as well as the St. Pauli entertainment district with the Reeperbahn street, offering a unique blend of culture and fun.' }, facts: { population: '~1.8 million', area: { pl: '755 km²', native: '292 sq mi' }, landmark: { pl: 'Speicherstadt', native: 'Speicherstadt' }, founded: {pl: 'IX wiek', native: '9th century'}, nickname: { pl: 'Brama do Świata', native: 'Das Tor zur Welt' } } },
      { name: { pl: 'Monachium', native: 'München' }, description: { pl: 'Stolica Bawarii, znana z Oktoberfest, kultury piwnej i bliskości Alp. Serce miasta to tętniący życiem Marienplatz. Monachium to także ważne centrum technologiczne i siedziba wielu międzynarodowych korporacji, łącząc tradycję z nowoczesnością.', native: 'The capital of Bavaria, known for Oktoberfest, beer culture, and proximity to the Alps. The heart of the city is the vibrant Marienplatz. Munich is also a major technology hub and home to many international corporations, blending tradition with modernity.' }, facts: { population: '~1.5 million', area: { pl: '310 km²', native: '120 sq mi' }, landmark: { pl: 'Marienplatz', native: 'Marienplatz' }, founded: {pl: '1158', native: '1158'}, nickname: { pl: 'Miasto z sercem', native: 'Die Weltstadt mit Herz' } } },
      { name: { pl: 'Frankfurt nad Menem', native: 'Frankfurt am Main' }, description: { pl: 'Finansowe centrum Niemiec i Europy, siedziba Europejskiego Banku Centralnego. Charakterystyczna panorama wieżowców nadaje mu przydomek "Mainhattan". Miasto oferuje również bogatą scenę kulturalną, z licznymi muzeami wzdłuż brzegu Menu.', native: 'The financial center of Germany and Europe, home to the European Central Bank. Its characteristic skyline of skyscrapers gives it the nickname "Mainhattan". The city also offers a rich cultural scene, with numerous museums along the banks of the Main.' }, facts: { population: '~770,000', area: { pl: '248 km²', native: '95.8 sq mi' }, landmark: { pl: 'Dzielnica bankowa', native: 'Bankenviertel' }, founded: {pl: '794', native: '794'}, nickname: { pl: 'Mainhattan', native: 'Mainhattan' } } },
      { name: { pl: 'Kolonia', native: 'Köln' }, description: { pl: 'Miasto o ponad 2000-letniej historii z majestatyczną katedrą (Kölner Dom), wpisaną na listę UNESCO, która przetrwała bombardowania II wojny światowej. Znane z radosnej atmosfery, słynnego na cały świat karnawału oraz lokalnego piwa Kölsch.', native: 'A city with over 2000 years of history, featuring the majestic Cologne Cathedral (Kölner Dom), a UNESCO World Heritage site that survived the bombings of WWII. Known for its cheerful atmosphere, the world-famous carnival, and the local Kölsch beer.' }, facts: { population: '~1.1 million', area: { pl: '405 km²', native: '156 sq mi' }, landmark: { pl: 'Katedra w Kolonii', native: 'Kölner Dom' }, founded: {pl: '50 n.e.', native: '50 AD'}, nickname: { pl: 'Miasto Katedralne', native: 'Die Domstadt' } } },
    ],
    ui: { title: { pl: 'Miasta Niemiec', native: 'Städte Deutschlands' }, backButton: { pl: 'Powrót do Kultury', native: 'Zurück zur Kultur' }, language: { pl: 'Język', native: 'Sprache' }, population: { pl: 'Populacja', native: 'Bevölkerung' }, area: { pl: 'Powierzchnia', native: 'Fläche' }, landmark: { pl: 'Główny zabytek', native: 'Hauptsehenswürdigkeit' }, founded: { pl: 'Założenie', native: 'Gegründet' }, nickname: { pl: 'Przydomek', native: 'Spitzname' } }
  },
  fr: {
    lang: 'fr',
    countryName: { pl: 'Francja', native: 'France' },
    cities: [
      { name: { pl: 'Paryż', native: 'Paris' }, description: { pl: 'Stolica Francji, miasto miłości, sztuki i świateł. Dom ikonicznej Wieży Eiffla, Luwru i katedry Notre-Dame. Paryż oferuje niezapomniane spacery wzdłuż Sekwany, urokliwe kawiarnie na Montmartre i luksusowe zakupy na Polach Elizejskich.', native: 'The capital of France, the city of love, art, and lights. Home to the iconic Eiffel Tower, the Louvre, and Notre-Dame Cathedral. Paris offers unforgettable walks along the Seine, charming cafes in Montmartre, and luxury shopping on the Champs-Élysées.' }, facts: { population: '~2.1 million', area: { pl: '105 km²', native: '40.7 sq mi' }, landmark: { pl: 'Wieża Eiffla', native: 'Tour Eiffel' }, founded: {pl: 'III w. p.n.e.', native: '3rd cent. BC'}, nickname: { pl: 'Miasto Świateł', native: 'La Ville Lumière' } } },
      { name: { pl: 'Marsylia', native: 'Marseille' }, description: { pl: 'Najstarsze miasto Francji i największy port, łączący wpływy europejskie i afrykańskie. Tętniący życiem Vieux-Port (Stary Port) jest sercem miasta, pełnym restauracji i łodzi. Warto również odwiedzić Park Narodowy Calanques z jego spektakularnymi klifami.', native: 'The oldest city in France and its largest port, blending European and African influences. The bustling Vieux-Port (Old Port) is the heart of the city, filled with restaurants and boats. The Calanques National Park with its spectacular cliffs is also worth a visit.' }, facts: { population: '~870,000', area: { pl: '240 km²', native: '93 sq mi' }, landmark: { pl: 'Vieux-Port', native: 'Vieux-Port' }, founded: {pl: 'ok. 600 p.n.e.', native: 'c. 600 BC'}, nickname: { pl: 'Miasto Fokajskie', native: 'La Cité Phocéenne' } } },
      { name: { pl: 'Lyon', native: 'Lyon' }, description: { pl: 'Uważany za gastronomiczną stolicę Francji, słynący z tradycyjnych restauracji "bouchons". Miasto posiada piękną starówkę (Vieux Lyon), wpisaną na listę UNESCO, i słynie z corocznego Festiwalu Świateł, który przyciąga miliony turystów.', native: 'Considered the gastronomic capital of France, famous for its traditional "bouchons" restaurants. The city has a beautiful old town (Vieux Lyon), a UNESCO World Heritage site, and is famous for its annual Festival of Lights, which attracts millions of tourists.' }, facts: { population: '~520,000', area: { pl: '48 km²', native: '18.5 sq mi' }, landmark: { pl: 'Vieux Lyon', native: 'Vieux Lyon' }, founded: {pl: '43 p.n.e.', native: '43 BC'}, nickname: { pl: 'Stolica Galów', native: 'Capitale des Gaules' } } },
      { name: { pl: 'Nicea', native: 'Nice' }, description: { pl: 'Perła Lazurowego Wybrzeża, słynąca ze słonecznych plaż, błękitnego morza i słynnej Promenade des Anglais. Miasto inspirowało wielu artystów, w tym Matisse\'a i Chagalla, których muzea można tu zwiedzać. Jego stare miasto (Vieux Nice) zachwyca wąskimi uliczkami i barokową architekturą.', native: 'The pearl of the French Riviera, famous for its sunny beaches, blue sea, and the famous Promenade des Anglais. The city has inspired many artists, including Matisse and Chagall, whose museums can be visited here. Its old town (Vieux Nice) delights with narrow streets and Baroque architecture.' }, facts: { population: '~340,000', area: { pl: '72 km²', native: '27.8 sq mi' }, landmark: { pl: 'Promenada Anglików', native: 'Promenade des Anglais' }, founded: {pl: 'ok. 350 p.n.e.', native: 'c. 350 BC'}, nickname: { pl: 'Nissa la Bella', native: 'Nissa la Bella' } } },
      { name: { pl: 'Strasburg', native: 'Strasbourg' }, description: { pl: 'Stolica Alzacji i siedziba Parlamentu Europejskiego. Urzeka malowniczą dzielnicą La Petite France z domami z muru pruskiego i kanałami. W okresie świątecznym miasto słynie z jednego z najstarszych i najpiękniejszych jarmarków bożonarodzeniowych w Europie.', native: 'The capital of Alsace and home to the European Parliament. It charms with its picturesque La Petite France district with half-timbered houses and canals. During the Christmas season, the city is famous for one of the oldest and most beautiful Christmas markets in Europe.' }, facts: { population: '~290,000', area: { pl: '78 km²', native: '30 sq mi' }, landmark: { pl: 'La Petite France', native: 'La Petite France' }, founded: {pl: '12 p.n.e.', native: '12 BC'}, nickname: { pl: 'Stolica Europy', native: 'Capitale de l\'Europe' } } },
    ],
    ui: { title: { pl: 'Miasta Francji', native: 'Villes de France' }, backButton: { pl: 'Powrót do Kultury', native: 'Retour à la Culture' }, language: { pl: 'Język', native: 'Langue' }, population: { pl: 'Populacja', native: 'Population' }, area: { pl: 'Powierzchnia', native: 'Superficie' }, landmark: { pl: 'Główny zabytek', native: 'Monument Principal' }, founded: { pl: 'Założenie', native: 'Fondé' }, nickname: { pl: 'Przydomek', native: 'Surnom' } }
  },
  it: {
    lang: 'it',
    countryName: { pl: 'Włochy', native: 'Italia' },
    cities: [
      { name: { pl: 'Rzym', native: 'Roma' }, description: { pl: 'Wieczne Miasto, stolica Włoch i kolebka cywilizacji zachodniej. Pełne antycznych ruin, jak Koloseum i Forum Romanum, oraz siedziba Watykanu. Rzym to także miasto fontann, placów i niezrównanej kuchni, gdzie historia spotyka się z pulsującym życiem współczesnej metropolii.', native: 'The Eternal City, capital of Italy and cradle of Western civilization. Full of ancient ruins like the Colosseum and Roman Forum, and home to the Vatican. Rome is also a city of fountains, squares, and unparalleled cuisine, where history meets the pulsating life of a modern metropolis.' }, facts: { population: '~2.8 million', area: { pl: '1,285 km²', native: '496 sq mi' }, landmark: { pl: 'Koloseum', native: 'Colosseo' }, founded: {pl: '753 p.n.e.', native: '753 BC'}, nickname: { pl: 'Wieczne Miasto', native: 'La Città Eterna' } } },
      { name: { pl: 'Mediolan', native: 'Milano' }, description: { pl: 'Światowa stolica mody i finansowe serce Włoch. Słynie z imponującej, gotyckiej katedry Duomo, opery La Scala oraz "Ostatniej Wieczerzy" Leonarda da Vinci. Mediolan to dynamiczne miasto biznesu, designu i nowoczesnego stylu życia.', native: 'The world\'s fashion capital and the financial heart of Italy. Famous for its impressive Gothic Duomo cathedral, La Scala opera house, and Leonardo da Vinci\'s "The Last Supper". Milan is a dynamic city of business, design, and modern lifestyle.' }, facts: { population: '~1.4 million', area: { pl: '181 km²', native: '70 sq mi' }, landmark: { pl: 'Katedra w Mediolanie', native: 'Duomo di Milano' }, founded: {pl: 'ok. 600 p.n.e.', native: 'c. 600 BC'}, nickname: { pl: 'Moralna Stolica Włoch', native: 'Capitale morale d\'Italia' } } },
      { name: { pl: 'Wenecja', native: 'Venezia' }, description: { pl: 'Unikalne miasto zbudowane na wodzie, słynące z kanałów, gondoli i romantycznej atmosfery. Plac Świętego Marka z jego bazyliką jest sercem miasta. Wenecja to labirynt wąskich uliczek i mostów, gdzie każdy zakątek kryje historyczne skarby i niezapomniane widoki.', native: 'A unique city built on water, famous for its canals, gondolas, and romantic atmosphere. St. Mark\'s Square with its basilica is the heart of the city. Venice is a labyrinth of narrow streets and bridges, where every corner hides historical treasures and unforgettable views.' }, facts: { population: '~260,000', area: { pl: '414 km²', native: '160 sq mi' }, landmark: { pl: 'Canal Grande', native: 'Canal Grande' }, founded: {pl: '421 n.e.', native: '421 AD'}, nickname: { pl: 'La Serenissima', native: 'La Serenissima' } } },
      { name: { pl: 'Florencja', native: 'Firenze' }, description: { pl: 'Kolebka renesansu, dom dzieł Michała Anioła i Leonarda da Vinci. Galeria Uffizi i katedra z kopułą Brunelleschiego to miejsca obowiązkowe. Miasto, położone w sercu Toskanii, zachwyca sztuką na każdym kroku, od rzeźb po architekturę.', native: 'The cradle of the Renaissance, home to the works of Michelangelo and Leonardo da Vinci. The Uffizi Gallery and the cathedral with Brunelleschi\'s dome are must-see sites. The city, located in the heart of Tuscany, delights with art at every turn, from sculptures to architecture.' }, facts: { population: '~380,000', area: { pl: '102 km²', native: '39 sq mi' }, landmark: { pl: 'Katedra we Florencji', native: 'Cattedrale di Firenze' }, founded: {pl: '59 p.n.e.', native: '59 BC'}, nickname: { pl: 'Kolebka Renesansu', native: 'Culla del Rinascimento' } } },
      { name: { pl: 'Neapol', native: 'Napoli' }, description: { pl: 'Tętniące życiem miasto w cieniu Wezuwiusza, uważane za kolebkę pizzy. Jego historyczne centrum jest wpisane na listę UNESCO. Neapol to brama do historycznych ruin Pompei i Herkulanum oraz malowniczego Wybrzeża Amalfitańskiego.', native: 'A vibrant city in the shadow of Vesuvius, considered the birthplace of pizza. Its historic center is a UNESCO World Heritage site. Naples is the gateway to the historic ruins of Pompeii and Herculaneum and the picturesque Amalfi Coast.' }, facts: { population: '~960,000', area: { pl: '117 km²', native: '45 sq mi' }, landmark: { pl: 'Wezuwiusz', native: 'Vesuvio' }, founded: {pl: '470 p.n.e.', native: '470 BC'}, nickname: { pl: 'Miasto Słońca', native: 'Città del Sole' } } },
    ],
    ui: { title: { pl: 'Miasta Włoch', native: 'Città d\'Italia' }, backButton: { pl: 'Powrót do Kultury', native: 'Torna a Cultura' }, language: { pl: 'Język', native: 'Lingua' }, population: { pl: 'Populacja', native: 'Popolazione' }, area: { pl: 'Powierzchnia', native: 'Superficie' }, landmark: { pl: 'Główny zabytek', native: 'Monumento principale' }, founded: { pl: 'Założenie', native: 'Fondato' }, nickname: { pl: 'Przydomek', native: 'Soprannome' } }
  },
  es: {
    lang: 'es',
    countryName: { pl: 'Hiszpania', native: 'España' },
    cities: [
      { name: { pl: 'Madryt', native: 'Madrid' }, description: { pl: 'Tętniąca życiem stolica Hiszpanii, znana z bogatego życia nocnego, światowej klasy muzeów w "Trójkącie Sztuki" (Prado, Reina Sofía, Thyssen) i pięknych parków jak Retiro. Madryt to miasto, które nigdy nie śpi, oferując niezliczone bary tapas i energetyczną atmosferę.', native: 'The vibrant capital of Spain, known for its rich nightlife, world-class museums in the "Art Triangle" (Prado, Reina Sofía, Thyssen), and beautiful parks like Retiro. Madrid is a city that never sleeps, offering countless tapas bars and an energetic atmosphere.' }, facts: { population: '~3.3 million', area: { pl: '604 km²', native: '233 sq mi' }, landmark: { pl: 'Pałac Królewski', native: 'Palacio Real' }, founded: {pl: 'IX wiek', native: '9th century'}, nickname: { pl: 'Forum', native: 'El Foro' } } },
      { name: { pl: 'Barcelona', native: 'Barcelona' }, description: { pl: 'Miasto Gaudíego, słynące z unikalnej architektury modernistycznej, w tym nieukończonej Sagrada Família i Parku Güell. Łączy kulturę, plaże i energię metropolii, a jej gotycka dzielnica (Barri Gòtic) kryje labirynt urokliwych uliczek.', native: 'Gaudí\'s city, famous for its unique modernist architecture, including the unfinished Sagrada Família and Park Güell. It combines culture, beaches, and metropolitan energy, and its Gothic Quarter (Barri Gòtic) hides a labyrinth of charming streets.' }, facts: { population: '~1.6 million', area: { pl: '101 km²', native: '39 sq mi' }, landmark: { pl: 'Sagrada Família', native: 'Sagrada Família' }, founded: {pl: 'I w. p.n.e.', native: '1st cent. BC'}, nickname: { pl: 'Wielka Czarodziejka', native: 'La Gran Encantadora' } } },
      { name: { pl: 'Sewilla', native: 'Sevilla' }, description: { pl: 'Stolica Andaluzji i serce flamenco. Urzeka mauretańskim pałacem Alcázar, ogromną gotycką katedrą, w której znajduje się grób Kolumba, i klimatycznymi uliczkami dzielnicy Santa Cruz. To miasto pasji, słońca i tradycji.', native: 'The capital of Andalusia and the heart of flamenco. It captivates with the Moorish Alcázar palace, the huge Gothic cathedral housing Columbus\'s tomb, and the atmospheric streets of the Santa Cruz district. It is a city of passion, sun, and tradition.' }, facts: { population: '~680,000', area: { pl: '140 km²', native: '54 sq mi' }, landmark: { pl: 'Plac Hiszpański', native: 'Plaza de España' }, founded: {pl: 'VIII w. p.n.e.', native: '8th cent. BC'}, nickname: { pl: 'Perła Andaluzji', native: 'La Perla de Andalucía' } } },
      { name: { pl: 'Walencja', native: 'Valencia' }, description: { pl: 'Miasto kontrastów, gdzie historyczne centrum spotyka się z futurystycznym Miastem Sztuki i Nauki. Słynie z autentycznej paelli, jedwabnej giełdy La Lonja (UNESCO) i spektakularnego festiwalu ognia Las Fallas, odbywającego się w marcu.', native: 'A city of contrasts, where the historic center meets the futuristic City of Arts and Sciences. Famous for its authentic paella, the La Lonja silk exchange (UNESCO), and the spectacular Las Fallas festival of fire held in March.' }, facts: { population: '~800,000', area: { pl: '134 km²', native: '52 sq mi' }, landmark: { pl: 'Miasto Sztuki i Nauki', native: 'Ciudad de las Artes y las Ciencias' }, founded: {pl: '138 p.n.e.', native: '138 BC'}, nickname: { pl: 'Miasto Kwiatów', native: 'La Ciudad de las Flores' } } },
      { name: { pl: 'Granada', native: 'Granada' }, description: { pl: 'Dom jednego z najwspanialszych zabytków świata, pałacu Alhambra, arcydzieła architektury mauretańskiej. Położone u podnóża gór Sierra Nevada, miasto oferuje unikalną mieszankę kultury andaluzyjskiej i arabskiej, widoczną w dzielnicy Albaicín.', native: 'Home to one of the world\'s most magnificent monuments, the Alhambra Palace, a masterpiece of Moorish architecture. Located at the foot of the Sierra Nevada mountains, the city offers a unique blend of Andalusian and Arab culture, visible in the Albaicín district.' }, facts: { population: '~230,000', area: { pl: '88 km²', native: '34 sq mi' }, landmark: { pl: 'Alhambra', native: 'Alhambra' }, founded: {pl: 'VII w. p.n.e.', native: '7th cent. BC'}, nickname: { pl: 'Kraina Tysiąca Zamków', native: 'La Tierra de los Mil Castillos' } } },
    ],
    ui: { title: { pl: 'Miasta Hiszpanii', native: 'Ciudades de España' }, backButton: { pl: 'Powrót do Kultury', native: 'Volver a Cultura' }, language: { pl: 'Język', native: 'Idioma' }, population: { pl: 'Populacja', native: 'Población' }, area: { pl: 'Powierzchnia', native: 'Superficie' }, landmark: { pl: 'Główny zabytek', native: 'Monumento principal' }, founded: { pl: 'Założenie', native: 'Fundado' }, nickname: { pl: 'Przydomek', native: 'Apodo' } }
  },
};
