import type { Language } from './storage';

export interface HistoricalEvent {
  date: string;
  name: { pl: string; native: string; };
  description: { pl: string; native: string; };
}

export interface HistoryPageData {
  lang: Language;
  events: HistoricalEvent[];
  ui: {
    title: { pl: string; native: string; };
    backButton: { pl: string; native: string; };
  }
}

export const allHistoryData: Record<Language, HistoryPageData> = {
  en: {
    lang: 'en',
    events: [
        { date: '1066', name: { pl: 'Podbój normański', native: 'Norman Conquest' }, description: { pl: 'Bitwa pod Hastings i koronacja Wilhelma Zdobywcy na króla Anglii, co zapoczątkowało głębokie zmiany w angielskim społeczeństwie, języku i kulturze.', native: 'The Battle of Hastings and the coronation of William the Conqueror as King of England, initiating profound changes in English society, language, and culture.' } },
        { date: '1215', name: { pl: 'Magna Carta', native: 'Magna Carta' }, description: { pl: 'Wielka Karta Swobód, podpisana przez króla Jana bez Ziemi, ograniczyła władzę monarchy i ustanowiła zasadę, że nikt nie jest ponad prawem. Jest to fundamentalny dokument dla zachodniego konstytucjonalizmu.', native: 'The Great Charter of Freedoms, signed by King John, limited the monarch\'s power and established the principle that no one is above the law. It is a foundational document for Western constitutionalism.' } },
        { date: '1534', name: { pl: 'Akt Supremacji', native: 'Act of Supremacy' }, description: { pl: 'Król Henryk VIII ogłasza się głową Kościoła Anglii, zrywając z Rzymem. To początek reformacji angielskiej i powstania anglikanizmu.', native: 'King Henry VIII declares himself the head of the Church of England, breaking with Rome. This marks the beginning of the English Reformation and the rise of Anglicanism.' } },
        { date: '1588', name: { pl: 'Pokonanie Hiszpańskiej Armady', native: 'Defeat of the Spanish Armada' }, description: { pl: 'Zwycięstwo floty angielskiej nad potężną hiszpańską flotą inwazyjną umocniło pozycję Anglii jako morskiej potęgi i zapewniło jej niezależność.', native: 'The victory of the English fleet over the powerful Spanish invasion fleet strengthened England\'s position as a naval power and secured its independence.' } },
        { date: '1642-1651', name: { pl: 'Angielska wojna domowa', native: 'English Civil War' }, description: { pl: 'Konflikt między zwolennikami parlamentu a rojalistami, który doprowadził do egzekucji króla Karola I i krótkiego okresu republiki pod wodzą Olivera Cromwella.', native: 'A conflict between Parliamentarians and Royalists that led to the execution of King Charles I and a brief period of republican rule under Oliver Cromwell.' } },
        { date: '1707', name: { pl: 'Akty Unii', native: 'Acts of Union' }, description: { pl: 'Połączenie Królestwa Anglii i Królestwa Szkocji, które stworzyło Królestwo Wielkiej Brytanii.', native: 'The union of the Kingdom of England and the Kingdom of Scotland, creating the Kingdom of Great Britain.' } },
        { date: '1837-1901', name: { pl: 'Epoka wiktoriańska', native: 'Victorian Era' }, description: { pl: 'Długie panowanie królowej Wiktorii, okres szczytu potęgi Imperium Brytyjskiego, rewolucji przemysłowej, ogromnego postępu technologicznego i głębokich zmian społecznych.', native: 'The long reign of Queen Victoria, a period of peak power for the British Empire, industrial revolution, immense technological progress, and profound social changes.' } },
        { date: '1914-1918', name: { pl: 'I wojna światowa', native: 'World War I' }, description: { pl: 'Globalny konflikt, w którym Wielka Brytania i jej sojusznicy walczyli przeciwko państwom centralnym. Wojna przyniosła ogromne straty ludzkie i zapoczątkowała upadek wielu imperiów.', native: 'A global conflict in which Great Britain and its allies fought against the Central Powers. The war brought enormous human losses and initiated the decline of many empires.' } },
        { date: '1940', name: { pl: 'Bitwa o Anglię', native: 'Battle of Britain' }, description: { pl: 'Kluczowa kampania powietrzna II wojny światowej, w której Royal Air Force (z udziałem polskich pilotów) obroniła Wielką Brytanię przed niemiecką inwazją.', native: 'A key air campaign of World War II, in which the Royal Air Force (with the participation of Polish pilots) defended Great Britain against a German invasion.' } },
        { date: '1973', name: { pl: 'Przystąpienie do EWG', native: 'Accession to the EEC' }, description: { pl: 'Wielka Brytania dołącza do Europejskiej Wspólnoty Gospodarczej, poprzedniczki Unii Europejskiej, co miało głęboki wpływ na jej gospodarkę i politykę.', native: 'The United Kingdom joins the European Economic Community, the forerunner of the European Union, which had a profound impact on its economy and politics.' } }
    ],
    ui: { title: { pl: 'Historia Anglii', native: 'History of England' }, backButton: { pl: 'Powrót do Kultury', native: 'Back to Culture' } }
  },
  de: {
    lang: 'de',
    events: [
        { date: '800', name: { pl: 'Koronacja Karola Wielkiego', native: 'Krönung Karls des Großen' }, description: { pl: 'W Boże Narodzenie 800 roku papież Leon III koronował króla Franków Karola Wielkiego na cesarza, odnawiając ideę Cesarstwa Rzymskiego na Zachodzie i tworząc podwaliny pod przyszłe Święte Cesarstwo Rzymskie.', native: 'An Weihnachten 800 krönte Papst Leo III. den Frankenkönig Karl den Großen zum Kaiser und erneuerte damit die Idee des Römischen Reiches im Westen, was den Grundstein für das spätere Heilige Römische Reich legte.' } },
        { date: '962', name: { pl: 'Powstanie Świętego Cesarstwa Rzymskiego', native: 'Gründung des Heiligen Römischen Reiches' }, description: { pl: 'Koronacja Ottona I na cesarza w Rzymie jest uważana za formalny początek Świętego Cesarstwa Rzymskiego Narodu Niemieckiego, które istniało przez prawie tysiąc lat.', native: 'Die Krönung Ottos I. zum Kaiser in Rom gilt als formeller Beginn des Heiligen Römischen Reiches Deutscher Nation, das fast tausend Jahre Bestand hatte.' } },
        { date: '1517', name: { pl: 'Początek Reformacji', native: 'Beginn der Reformation' }, description: { pl: 'Marcin Luter ogłasza swoje 95 tez w Wittenberdze, krytykując praktykę sprzedaży odpustów. To wydarzenie zapoczątkowało reformację i podział zachodniego chrześcijaństwa.', native: 'Martin Luther veröffentlicht seine 95 Thesen in Wittenberg und kritisiert die Praxis des Ablasshandels. Dieses Ereignis löste die Reformation und die Spaltung des westlichen Christentums aus.' } },
        { date: '1815', name: { pl: 'Kongres Wiedeński', native: 'Wiener Kongress' }, description: { pl: 'Po klęsce Napoleona, europejskie mocarstwa na nowo zorganizowały porządek polityczny na kontynencie. Utworzono Związek Niemiecki, luźną konfederację państw niemieckich.', native: 'Nach der Niederlage Napoleons ordneten die europäischen Mächte die politische Ordnung des Kontinents neu. Der Deutsche Bund, eine lose Konföderation deutscher Staaten, wurde gegründet.' } },
        { date: '1871', name: { pl: 'Zjednoczenie Niemiec', native: 'Deutsche Einigung' }, description: { pl: 'Po zwycięstwie w wojnie francusko-pruskiej, w Sali Lustrzanej w Wersalu proklamowano powstanie Cesarstwa Niemieckiego, z królem Prus Wilhelmem I jako cesarzem.', native: 'Nach dem Sieg im Deutsch-Französischen Krieg wurde im Spiegelsaal von Versailles das Deutsche Kaiserreich ausgerufen, mit dem preußischen König Wilhelm I. als Kaiser.' } },
        { date: '1914-1918', name: { pl: 'I wojna światowa', native: 'Erster Weltkrieg' }, description: { pl: 'Niemcy jako jedno z państw centralnych poniosły klęskę w wyniszczającej wojnie. Jej skutkiem były abdykacja cesarza, upadek monarchii i powstanie Republiki Weimarskiej.', native: 'Deutschland erlitt als eine der Mittelmächte eine Niederlage in dem verheerenden Krieg. Die Folgen waren die Abdankung des Kaisers, der Untergang der Monarchie und die Gründung der Weimarer Republik.' } },
        { date: '1933', name: { pl: 'Przejęcie władzy przez Hitlera', native: 'Hitlers Machtergreifung' }, description: { pl: 'Adolf Hitler zostaje kanclerzem Niemiec, co zapoczątkowało szybką transformację Republiki Weimarskiej w totalitarną III Rzeszę.', native: 'Adolf Hitler wird Reichskanzler, was den schnellen Umbau der Weimarer Republik in das totalitäre Dritte Reich einleitete.' } },
        { date: '1949', name: { pl: 'Podział Niemiec', native: 'Teilung Deutschlands' }, description: { pl: 'Po II wojnie światowej Niemcy zostały podzielone na dwa państwa: Republikę Federalną Niemiec (RFN) na zachodzie i Niemiecką Republikę Demokratyczną (NRD) na wschodzie.', native: 'Nach dem Zweiten Weltkrieg wurde Deutschland in zwei Staaten geteilt: die Bundesrepublik Deutschland (BRD) im Westen und die Deutsche Demokratische Republik (DDR) im Osten.' } },
        { date: '1961', name: { pl: 'Budowa Muru Berlińskiego', native: 'Bau der Berliner Mauer' }, description: { pl: 'Władze NRD zbudowały mur dzielący Berlin, aby powstrzymać masową ucieczkę swoich obywateli na Zachód. Stał się on symbolem zimnej wojny.', native: 'Die DDR-Regierung errichtete eine Mauer, die Berlin teilte, um die Massenflucht ihrer Bürger in den Westen zu stoppen. Sie wurde zum Symbol des Kalten Krieges.' } },
        { date: '1990', name: { pl: 'Zjednoczenie Niemiec', native: 'Deutsche Wiedervereinigung' }, description: { pl: 'Po upadku Muru Berlińskiego w 1989 roku, Niemiecka Republika Demokratyczna została włączona do Republiki Federalnej Niemiec, kończąc ponad 40-letni podział kraju.', native: 'Nach dem Fall der Berliner Mauer 1989 wurde die Deutsche Demokratische Republik in die Bundesrepublik Deutschland eingegliedert, was die über 40-jährige Teilung des Landes beendete.' } }
    ],
    ui: { title: { pl: 'Historia Niemiec', native: 'Geschichte Deutschlands' }, backButton: { pl: 'Powrót do Kultury', native: 'Zurück zur Kultur' } }
  },
  fr: {
    lang: 'fr',
    events: [
        { date: '481', name: { pl: 'Chlodwig I zostaje królem Franków', native: 'Clovis Ier devient roi des Francs' }, description: { pl: 'Chlodwig zjednoczył większość plemion frankijskich pod jednym przywództwem, założył dynastię Merowingów i przyjął chrześcijaństwo, co miało kluczowe znaczenie dla przyszłości Francji.', native: 'Clovis a unifié la plupart des tribus franques sous un seul dirigeant, fondé la dynastie mérovingienne et s\'est converti au christianisme, ce qui a été crucial pour l\'avenir de la France.' } },
        { date: '800', name: { pl: 'Koronacja Karola Wielkiego', native: 'Couronnement de Charlemagne' }, description: { pl: 'Król Franków Karol Wielki został koronowany na cesarza przez papieża w Rzymie, tworząc potężne imperium, które obejmowało większość zachodniej i środkowej Europy.', native: 'Le roi des Francs, Charlemagne, fut couronné empereur par le pape à Rome, créant un puissant empire qui englobait la majeure partie de l\'Europe occidentale et centrale.' } },
        { date: '1429', name: { pl: 'Joanna d\'Arc w Orleanie', native: 'Jeanne d\'Arc à Orléans' }, description: { pl: 'Podczas wojny stuletniej Joanna d\'Arc poprowadziła armię francuską do spektakularnego zwycięstwa, znosząc oblężenie Orleanu i odwracając losy wojny na korzyść Francji.', native: 'Pendant la guerre de Cent Ans, Jeanne d\'Arc mena l\'armée française à une victoire spectaculaire, levant le siège d\'Orléans et renversant le cours de la guerre en faveur de la France.' } },
        { date: '1789', name: { pl: 'Początek Rewolucji Francuskiej', native: 'Début de la Révolution Française' }, description: { pl: 'Zdobycie Bastylii 14 lipca 1789 roku jest symbolicznym początkiem rewolucji, która obaliła monarchię i ustanowiła republikę opartą na zasadach "Wolności, Równości, Braterstwa".', native: 'La prise de la Bastille le 14 juillet 1789 est le début symbolique de la révolution qui a renversé la monarchie et établi une république fondée sur les principes de "Liberté, Égalité, Fraternité".' } },
        { date: '1804', name: { pl: 'Napoleon zostaje cesarzem', native: 'Napoléon devient Empereur' }, description: { pl: 'Napoleon Bonaparte koronował się na Cesarza Francuzów. Jego rządy przyniosły reformy prawne (Kodeks Napoleona) i serię wojen, które zmieniły mapę Europy.', native: 'Napoléon Bonaparte se couronne Empereur des Français. Son règne a apporté des réformes juridiques (le Code Napoléon) et une série de guerres qui ont redessiné la carte de l\'Europe.' } },
        { date: '1889', name: { pl: 'Budowa Wieży Eiffla', native: 'Construction de la Tour Eiffel' }, description: { pl: 'Zbudowana jako brama wejściowa na Wystawę Światową w Paryżu, wieża zaprojektowana przez Gustave\'a Eiffla stała się trwałym symbolem Francji i cudem inżynierii.', native: 'Construite comme porte d\'entrée de l\'Exposition universelle de Paris, la tour conçue par Gustave Eiffel est devenue un symbole durable de la France et une merveille d\'ingénierie.' } },
        { date: '1914-1918', name: { pl: 'I wojna światowa', native: 'Première Guerre mondiale' }, description: { pl: 'Francja była jednym z głównych teatrów działań wojennych na froncie zachodnim. Wojna przyniosła ogromne zniszczenia i straty ludzkie, ale zakończyła się zwycięstwem aliantów.', native: 'La France fut l\'un des principaux théâtres d\'opérations sur le front occidental. La guerre a causé d\'énormes destructions et pertes humaines, mais s\'est terminée par la victoire des Alliés.' } },
        { date: '1944', name: { pl: 'Lądowanie w Normandii (D-Day)', native: 'Débarquement de Normandie (Jour J)' }, description: { pl: '6 czerwca 1944 roku siły alianckie wylądowały na plażach Normandii, otwierając drugi front w Europie Zachodniej i rozpoczynając wyzwalanie Francji spod okupacji niemieckiej.', native: 'Le 6 juin 1944, les forces alliées ont débarqué sur les plages de Normandie, ouvrant un second front en Europe occidentale et commençant la libération de la France de l\'occupation allemande.' } },
        { date: '1958', name: { pl: 'Ustanowienie Piątej Republiki', native: 'Instauration de la Ve République' }, description: { pl: 'W obliczu kryzysu algierskiego, Charles de Gaulle powrócił do władzy i wprowadził nową konstytucję, tworząc system prezydencki, który obowiązuje do dziś.', native: 'Face à la crise algérienne, Charles de Gaulle est revenu au pouvoir et a introduit une nouvelle constitution, créant le système présidentiel qui est toujours en vigueur aujourd\'hui.' } },
        { date: '1992', name: { pl: 'Traktat z Maastricht', native: 'Traité de Maastricht' }, description: { pl: 'Francja była jednym z sygnatariuszy traktatu, który formalnie ustanowił Unię Europejską i stworzył podwaliny pod wspólną walutę euro.', native: 'La France fut l\'un des signataires du traité qui a formellement établi l\'Union européenne et a jeté les bases de la monnaie unique, l\'euro.' } }
    ],
    ui: { title: { pl: 'Historia Francji', native: 'Histoire de France' }, backButton: { pl: 'Powrót do Kultury', native: 'Retour à la Culture' } }
  },
  it: {
    lang: 'it',
    events: [
        { date: '753 p.n.e.', name: { pl: 'Założenie Rzymu', native: 'Fondazione di Roma' }, description: { pl: 'Według legendy, Rzym został założony przez braci Romulusa i Remusa. To symboliczny początek historii miasta, które miało stać się stolicą potężnego imperium.', native: 'Secondo la leggenda, Roma fu fondata dai fratelli Romolo e Remo. È l\'inizio simbolico della storia della città che sarebbe diventata la capitale di un potente impero.' } },
        { date: '476', name: { pl: 'Upadek Cesarstwa Rzymskiego', native: 'Caduta dell\'Impero Romano' }, description: { pl: 'Obalenie ostatniego cesarza zachodniorzymskiego, Romulusa Augustulusa, jest tradycyjnie uważane za koniec starożytności i początek średniowiecza w Europie.', native: 'La deposizione dell\'ultimo imperatore romano d\'Occidente, Romolo Augusto, è tradizionalmente considerata la fine dell\'antichità e l\'inizio del Medioevo in Europa.' } },
        { date: '~1300', name: { pl: 'Początek Renesansu', native: 'Inizio del Rinascimento' }, description: { pl: 'Odrodzenie sztuki, nauki i kultury, które rozpoczęło się we Florencji i rozprzestrzeniło na całą Europę, z postaciami takimi jak Dante, Petrarka, a później Leonardo da Vinci i Michał Anioł.', native: 'Una rinascita delle arti, delle scienze e della cultura che iniziò a Firenze e si diffuse in tutta Europa, con figure come Dante, Petrarca e più tardi Leonardo da Vinci e Michelangelo.' } },
        { date: '1492', name: { pl: 'Odkrycie Ameryki przez Kolumba', native: 'Scoperta dell\'America' }, description: { pl: 'Genueńczyk Krzysztof Kolumb, w służbie Hiszpanii, dopłynął do Ameryki, rozpoczynając epokę wielkich odkryć geograficznych i globalnej wymiany.', native: 'Il genovese Cristoforo Colombo, al servizio della Spagna, raggiunse l\'America, dando inizio all\'era delle grandi scoperte geografiche e degli scambi globali.' } },
        { date: '1861', name: { pl: 'Zjednoczenie Włoch', native: 'Unificazione d\'Italia' }, description: { pl: 'Proces zjednoczenia państw Półwyspu Apenińskiego (Risorgimento) zakończył się proklamowaniem Królestwa Włoch z Wiktorem Emanuelem II jako pierwszym królem.', native: 'Il processo di unificazione degli stati della penisola italiana (Risorgimento) si concluse con la proclamazione del Regno d\'Italia con Vittorio Emanuele II come primo re.' } },
        { date: '1922', name: { pl: 'Marsz na Rzym', native: 'Marcia su Roma' }, description: { pl: 'Benito Mussolini i jego faszyści przejęli władzę we Włoszech, co doprowadziło do ustanowienia dyktatury i końca demokracji parlamentarnej.', native: 'Benito Mussolini e i suoi fascisti presero il potere in Italia, portando all\'instaurazione di una dittatura e alla fine della democrazia parlamentare.' } },
        { date: '1946', name: { pl: 'Proklamowanie Republiki', native: 'Proclamazione della Repubblica' }, description: { pl: 'Po II wojnie światowej Włosi w referendum opowiedzieli się za zniesieniem monarchii i ustanowieniem republiki.', native: 'Dopo la Seconda Guerra Mondiale, gli italiani votarono in un referendum per abolire la monarchia e istituire una repubblica.' } },
        { date: '1957', name: { pl: 'Traktat Rzymski', native: 'Trattato di Roma' }, description: { pl: 'Włochy były jednym z sześciu krajów założycielskich Europejskiej Wspólnoty Gospodarczej, poprzedniczki Unii Europejskiej, podpisując traktat w Rzymie.', native: 'L\'Italia fu uno dei sei paesi fondatori della Comunità Economica Europea, precursore dell\'Unione Europea, firmando il trattato a Roma.' } },
        { date: '1992', name: { pl: 'Operacja Czyste Ręce', native: 'Mani pulite' }, description: { pl: 'Seria dochodzeń sądowych, które ujawniły ogromny system korupcji w polityce i biznesie, prowadząc do upadku tzw. Pierwszej Republiki.', native: 'Una serie di indagini giudiziarie che svelarono un vasto sistema di corruzione nella politica e negli affari, portando alla caduta della cosiddetta Prima Repubblica.' } },
        { date: '2002', name: { pl: 'Wprowadzenie euro', native: 'Adozione dell\'Euro' }, description: { pl: 'Włochy, jako jeden z pierwszych krajów, zastąpiły swoją walutę narodową, lira, wspólną europejską walutą euro.', native: 'L\'Italia, come uno dei primi paesi, sostituì la sua valuta nazionale, la lira, con la moneta unica europea, l\'euro.' } }
    ],
    ui: { title: { pl: 'Historia Włoch', native: 'Storia d\'Italia' }, backButton: { pl: 'Powrót do Kultury', native: 'Torna a Cultura' } }
  },
  es: {
    lang: 'es',
    events: [
        { date: '711', name: { pl: 'Podbój muzułmański', native: 'Conquista musulmana' }, description: { pl: 'Wojska muzułmańskie z Afryki Północnej przekroczyły Cieśninę Gibraltarską, rozpoczynając podbój Półwyspu Iberyjskiego, co zapoczątkowało prawie 800-letni okres obecności islamu w Hiszpanii (Al-Andalus).', native: 'Las tropas musulmanas del norte de África cruzaron el Estrecho de Gibraltar, iniciando la conquista de la Península Ibérica, lo que dio comienzo a un período de casi 800 años de presencia islámica en España (Al-Andalus).' } },
        { date: '1492', name: { pl: 'Koniec Rekonkwisty i odkrycie Ameryki', native: 'Fin de la Reconquista y descubrimiento de América' }, description: { pl: 'Upadek Granady, ostatniego emiratu muzułmańskiego, zakończył rekonkwistę. W tym samym roku Krzysztof Kolumb dotarł do Ameryki, rozpoczynając epokę hiszpańskiego imperium kolonialnego.', native: 'La caída de Granada, el último emirato musulmán, puso fin a la Reconquista. Ese mismo año, Cristóbal Colón llegó a América, dando inicio a la era del imperio colonial español.' } },
        { date: '1588', name: { pl: 'Klęska Wielkiej Armady', native: 'Derrota de la Armada Invencible' }, description: { pl: 'Niezwyciężona Armada, potężna flota wysłana przez króla Filipa II w celu inwazji na Anglię, została pokonana przez flotę angielską i sztormy, co zapoczątkowało schyłek hiszpańskiej potęgi morskiej.', native: 'La Armada Invencible, una poderosa flota enviada por el rey Felipe II para invadir Inglaterra, fue derrotada por la flota inglesa y las tormentas, lo que marcó el inicio del declive del poderío naval español.' } },
        { date: '1808-1814', name: { pl: 'Wojna na Półwyspie Iberyjskim', native: 'Guerra de la Independencia' }, description: { pl: 'Narodowe powstanie przeciwko okupacji napoleońskiej. Był to brutalny konflikt, który doprowadził do powstania pierwszej hiszpańskiej konstytucji w 1812 roku.', native: 'Un levantamiento nacional contra la ocupación napoleónica. Fue un conflicto brutal que condujo a la creación de la primera constitución española en 1812.' } },
        { date: '1936-1939', name: { pl: 'Hiszpańska wojna domowa', native: 'Guerra Civil Española' }, description: { pl: 'Krwawy konflikt między siłami republikańskimi a nacjonalistami pod wodzą generała Franco. Zakończył się zwycięstwem Franco i ustanowieniem dyktatury.', native: 'Un sangriento conflicto entre las fuerzas republicanas y los nacionalistas liderados por el general Franco. Terminó con la victoria de Franco y el establecimiento de una dictadura.' } },
        { date: '1939-1975', name: { pl: 'Hiszpania frankistowska', native: 'España franquista' }, description: { pl: 'Okres autorytarnej dyktatury generała Francisco Franco, charakteryzujący się represjami politycznymi, izolacją międzynarodową, a później gwałtownym rozwojem gospodarczym.', native: 'El período de la dictadura autoritaria del general Francisco Franco, caracterizado por la represión política, el aislamiento internacional y, más tarde, un rápido desarrollo económico.' } },
        { date: '1975', name: { pl: 'Śmierć Franco i przejście do demokracji', native: 'Muerte de Franco y Transición' }, description: { pl: 'Po śmierci dyktatora Franco, król Juan Carlos I zainicjował proces pokojowego przejścia do demokracji, który zakończył się uchwaleniem nowej konstytucji w 1978 roku.', native: 'Tras la muerte del dictador Franco, el rey Juan Carlos I inició un proceso de transición pacífica a la democracia que culminó con la aprobación de una nueva constitución en 1978.' } },
        { date: '1986', name: { pl: 'Przystąpienie do EWG', native: 'Entrada en la CEE' }, description: { pl: 'Hiszpania dołączyła do Europejskiej Wspólnoty Gospodarczej (obecnie UE), co przyspieszyło jej modernizację i integrację z resztą Europy.', native: 'España se unió a la Comunidad Económica Europea (ahora UE), lo que aceleró su modernización e integración con el resto de Europa.' } },
        { date: '1992', name: { pl: 'Olimpiada w Barcelonie i Expo w Sewilli', native: 'Olimpiadas de Barcelona y Expo de Sevilla' }, description: { pl: 'Rok, który symbolicznie ukazał nowoczesną, otwartą na świat Hiszpanię. Oba wydarzenia były ogromnym sukcesem organizacyjnym i wizerunkowym.', native: 'Un año que mostró simbólicamente a una España moderna y abierta al mundo. Ambos eventos fueron un gran éxito organizativo y de imagen.' } },
        { date: '2002', name: { pl: 'Wprowadzenie euro', native: 'Adopción del Euro' }, description: { pl: 'Hiszpania zastąpiła swoją walutę, pesetę, wspólną europejską walutą euro, co było ważnym krokiem w integracji gospodarczej.', native: 'España reemplazó su moneda, la peseta, por la moneda única europea, el euro, un paso importante en la integración económica.' } }
    ],
    ui: { title: { pl: 'Historia Hiszpanii', native: 'Historia de España' }, backButton: { pl: 'Powrót do Kultury', native: 'Volver a Cultura' } }
  },
};
