
import type { Language } from './storage';

export interface HistoricalEvent {
  date: string;
  name: { pl: string; native: string; };
  description: { pl: string; native: string; };
}

export interface HistoryPageData {
  lang: Language;
  events: HistoricalEvent[];
  ui: {
    title: { pl: string; native: string; };
    backButton: { pl: string; native: string; };
  }
}

export const allHistoryData: Record<Language, HistoryPageData> = {
  en: {
    lang: 'en',
    events: [
        { date: '1066', name: { pl: 'Podbój normański', native: 'Norman Conquest' }, description: { pl: 'Bitwa pod Hastings i\u00A0koronacja Wilhelma Zdobywcy na króla Anglii. To wydarzenie zapoczątkowało głębokie zmiany w\u00A0angielskim społeczeństwie, języku i\u00A0kulturze, wprowadzając normański system feudalny i\u00A0francuskie wpływy językowe, które na zawsze zmieniły oblicze kraju.', native: 'The Battle of Hastings and the coronation of William the Conqueror as King of England. This event initiated profound changes in English society, language, and culture, introducing the Norman feudal system and French linguistic influences that forever changed the face of the country.' } },
        { date: '1215', name: { pl: 'Magna Carta', native: 'Magna Carta' }, description: { pl: 'Wielka Karta Swobód, podpisana przez króla Jana bez Ziemi pod presją zbuntowanych baronów. Ograniczyła władzę monarchy i\u00A0ustanowiła zasadę, że nikt, nawet król, nie jest ponad prawem. Jest to fundamentalny dokument dla rozwoju zachodniego konstytucjonalizmu i\u00A0praw obywatelskich.', native: 'The Great Charter of Freedoms, signed by King John under pressure from rebellious barons. It limited the monarch\'s power and established the principle that no one, not even the king, is above the law. It is a foundational document for the development of Western constitutionalism and civil rights.' } },
        { date: '1534', name: { pl: 'Akt Supremacji', native: 'Act of Supremacy' }, description: { pl: 'Król Henryk VIII, po konflikcie z\u00A0papiestwem w\u00A0sprawie rozwodu, ogłasza się głową Kościoła Anglii. Ten akt formalnie zapoczątkował reformację angielską i\u00A0powstanie anglikanizmu, uniezależniając kraj od Rzymu.', native: 'King Henry VIII, after a conflict with the papacy over his divorce, declares himself the head of the Church of England. This act formally initiated the English Reformation and the establishment of Anglicanism, making the country independent of Rome.' } },
        { date: '1588', name: { pl: 'Pokonanie Hiszpańskiej Armady', native: 'Defeat of the Spanish Armada' }, description: { pl: 'Zwycięstwo angielskiej floty nad potężną hiszpańską flotą inwazyjną, połączone z\u00A0niekorzystnymi warunkami pogodowymi, umocniło pozycję Anglii jako morskiej potęgi i\u00A0zapewniło jej niezależność oraz protestancką przyszłość pod rządami Elżbiety I.', native: 'The victory of the English fleet over the powerful Spanish invasion fleet, combined with adverse weather conditions, strengthened England\'s position as a naval power and secured its independence and Protestant future under Queen Elizabeth I.' } },
        { date: '1642-1651', name: { pl: 'Angielska wojna domowa', native: 'English Civil War' }, description: { pl: 'Konflikt między zwolennikami parlamentu ("Okrągłogłowymi") a\u00A0rojalistami ("Kawalerami"), który doprowadził do egzekucji króla Karola I, ustanowienia krótkotrwałej republiki (Commonwealth) pod wodzą Olivera Cromwella i\u00A0trwałego wzmocnienia roli parlamentu.', native: 'A conflict between Parliamentarians ("Roundheads") and Royalists ("Cavaliers") that led to the execution of King Charles I, the establishment of a short-lived republic (the Commonwealth) under Oliver Cromwell, and the permanent strengthening of Parliament\'s role.' } },
        { date: '1707', name: { pl: 'Akty Unii', native: 'Acts of Union' }, description: { pl: 'Połączenie Królestwa Anglii i\u00A0Królestwa Szkocji, które stworzyło zjednoczone Królestwo Wielkiej Brytanii. Unia ta była motywowana zarówno względami politycznymi, jak i\u00A0ekonomicznymi, tworząc jedno z\u00A0najpotężniejszych państw świata.', native: 'The union of the Kingdom of England and the Kingdom of Scotland, creating the united Kingdom of Great Britain. This union was motivated by both political and economic considerations, forming one of the most powerful states in the world.' } },
        { date: '1837-1901', name: { pl: 'Epoka wiktoriańska', native: 'Victorian Era' }, description: { pl: 'Długie panowanie królowej Wiktorii to okres szczytu potęgi Imperium Brytyjskiego ("imperium, nad którym nigdy nie zachodzi słońce"), rewolucji przemysłowej, ogromnego postępu technologicznego i\u00A0głębokich zmian społecznych, a\u00A0także surowej moralności.', native: 'The long reign of Queen Victoria was a period of peak power for the British Empire ("the empire on which the sun never sets"), industrial revolution, immense technological progress, profound social changes, and strict morality.' } },
        { date: '1914-1918', name: { pl: 'I wojna światowa', native: 'World War I' }, description: { pl: 'Globalny konflikt, w\u00A0którym Wielka Brytania i\u00A0jej sojusznicy walczyli przeciwko państwom centralnym. Wojna przyniosła ogromne straty ludzkie i\u00A0gospodarcze, zapoczątkowując proces dekolonizacji i\u00A0zmianę globalnego układu sił.', native: 'A global conflict in which Great Britain and its allies fought against the Central Powers. The war brought enormous human and economic losses, initiating the process of decolonization and a shift in the global balance of power.' } },
        { date: '1940', name: { pl: 'Bitwa o Anglię', native: 'Battle of Britain' }, description: { pl: 'Kluczowa kampania powietrzna II wojny światowej, w\u00A0której Royal Air Force (z\u00A0istotnym udziałem pilotów z\u00A0innych krajów, w\u00A0tym Polski) obroniła Wielką Brytanię przed niemiecką inwazją z\u00A0powietrza, co było punktem zwrotnym w\u00A0wojnie.', native: 'A key air campaign of World War II, in which the Royal Air Force (with significant participation from pilots of other countries, including Poland) defended Great Britain from a German air invasion, which was a turning point in the war.' } },
        { date: '1973', name: { pl: 'Przystąpienie do EWG', native: 'Accession to the EEC' }, description: { pl: 'Wielka Brytania dołącza do Europejskiej Wspólnoty Gospodarczej, poprzedniczki Unii Europejskiej. Ten krok miał głęboki wpływ na jej gospodarkę i\u00A0politykę, rozpoczynając złożoną relację z\u00A0kontynentalną Europą, która trwała aż do Brexitu.', native: 'The United Kingdom joins the European Economic Community, the forerunner of the European Union. This step had a profound impact on its economy and politics, beginning a complex relationship with continental Europe that lasted until Brexit.' } }
    ],
    ui: { title: { pl: 'Historia Anglii', native: 'History of England' }, backButton: { pl: 'Powrót do Kultury', native: 'Back to Culture' } }
  },
  de: {
    lang: 'de',
    events: [
        { date: '800', name: { pl: 'Koronacja Karola Wielkiego', native: 'Krönung Karls des Großen' }, description: { pl: 'W Boże Narodzenie 800 roku papież Leon III koronował króla Franków Karola Wielkiego na cesarza, odnawiając ideę Cesarstwa Rzymskiego na Zachodzie i\u00A0tworząc podwaliny pod przyszłe Święte Cesarstwo Rzymskie, jednocząc dużą część Europy.', native: 'An Weihnachten 800 krönte Papst Leo III. den Frankenkönig Karl den Großen zum Kaiser, erneuerte damit die Idee des Römischen Reiches im Westen und legte den Grundstein für das spätere Heilige Römische Reich, das einen Großteil Europas vereinte.' } },
        { date: '962', name: { pl: 'Powstanie Świętego Cesarstwa Rzymskiego', native: 'Gründung des Heiligen Römischen Reiches' }, description: { pl: 'Koronacja Ottona I\u00A0na cesarza w\u00A0Rzymie jest uważana za formalny początek Świętego Cesarstwa Rzymskiego Narodu Niemieckiego. Był to wielonarodowy byt polityczny, który istniał w\u00A0Europie Środkowej przez prawie tysiąc lat.', native: 'Die Krönung Ottos I. zum Kaiser in Rom gilt als formeller Beginn des Heiligen Römischen Reiches Deutscher Nation. Es war ein multinationales politisches Gebilde, das fast tausend Jahre lang in Mitteleuropa bestand.' } },
        { date: '1517', name: { pl: 'Początek Reformacji', native: 'Beginn der Reformation' }, description: { pl: 'Marcin Luter ogłasza swoje 95 tez w\u00A0Wittenberdze, krytykując praktykę sprzedaży odpustów. To wydarzenie zapoczątkowało reformację, podział zachodniego chrześcijaństwa i\u00A0długotrwałe wojny religijne w\u00A0Europie.', native: 'Martin Luther veröffentlicht seine 95 Thesen in Wittenberg und kritisiert die Praxis des Ablasshandels. Dieses Ereignis löste die Reformation, die Spaltung des westlichen Christentums und langanhaltende Religionskriege in Europa aus.' } },
        { date: '1815', name: { pl: 'Kongres Wiedeński', native: 'Wiener Kongress' }, description: { pl: 'Po klęsce Napoleona, europejskie mocarstwa na nowo zorganizowały porządek polityczny na kontynencie. Utworzono Związek Niemiecki, luźną konfederację 39 państw niemieckich pod przewodnictwem Austrii.', native: 'Nach der Niederlage Napoleons ordneten die europäischen Mächte die politische Ordnung des Kontinents neu. Der Deutsche Bund, eine lose Konföderation von 39 deutschen Staaten unter der Führung Österreichs, wurde gegründet.' } },
        { date: '1871', name: { pl: 'Zjednoczenie Niemiec', native: 'Deutsche Einigung' }, description: { pl: 'Po zwycięstwie w\u00A0wojnie francusko-pruskiej, z inicjatywy kanclerza Prus Ottona von Bismarcka, w\u00A0Sali Lustrzanej w\u00A0Wersalu proklamowano powstanie Cesarstwa Niemieckiego (II Rzeszy), z\u00A0królem Prus Wilhelmem I\u00A0jako cesarzem.', native: 'Nach dem Sieg im Deutsch-Französischen Krieg wurde auf Initiative des preußischen Kanzlers Otto von Bismarck im Spiegelsaal von Versailles das Deutsche Kaiserreich (das Zweite Reich) ausgerufen, mit dem preußischen König Wilhelm I. als Kaiser.' } },
        { date: '1914-1918', name: { pl: 'I wojna światowa', native: 'Erster Weltkrieg' }, description: { pl: 'Niemcy, jako jedno z\u00A0państw centralnych, poniosły klęskę w\u00A0wyniszczającej wojnie. Jej skutkiem były ogromne straty, abdykacja cesarza Wilhelma II, upadek monarchii i\u00A0powstanie niestabilnej Republiki Weimarskiej.', native: 'Deutschland erlitt als eine der Mittelmächte eine Niederlage in dem verheerenden Krieg. Die Folgen waren enorme Verluste, die Abdankung Kaiser Wilhelms II., der Untergang der Monarchie und die Gründung der instabilen Weimarer Republik.' } },
        { date: '1933', name: { pl: 'Przejęcie władzy przez Hitlera', native: 'Hitlers Machtergreifung' }, description: { pl: 'Adolf Hitler zostaje mianowany kanclerzem Niemiec, co zapoczątkowało błyskawiczną transformację Republiki Weimarskiej w\u00A0totalitarną III Rzeszę, opartą na ideologii nazistowskiej i\u00A0terrorze.', native: 'Adolf Hitler wird zum Reichskanzler ernannt, was den schnellen Umbau der Weimarer Republik in das totalitäre Dritte Reich einleitete, das auf nationalsozialistischer Ideologie und Terror basierte.' } },
        { date: '1949', name: { pl: 'Podział Niemiec', native: 'Teilung Deutschlands' }, description: { pl: 'Po II wojnie światowej i\u00A0w\u00A0obliczu narastającej zimnej wojny, Niemcy zostały podzielone na dwa państwa: kapitalistyczną Republikę Federalną Niemiec (RFN) na zachodzie i\u00A0komunistyczną Niemiecką Republikę Demokratyczną (NRD) na wschodzie.', native: 'Nach dem Zweiten Weltkrieg und angesichts des aufkommenden Kalten Krieges wurde Deutschland in zwei Staaten geteilt: die kapitalistische Bundesrepublik Deutschland (BRD) im Westen und die kommunistische Deutsche Demokratische Republik (DDR) im Osten.' } },
        { date: '1961', name: { pl: 'Budowa Muru Berlińskiego', native: 'Bau der Berliner Mauer' }, description: { pl: 'Władze NRD zbudowały mur fizycznie dzielący Berlin, aby powstrzymać masową ucieczkę swoich obywateli na Zachód. Stał się on najbardziej znanym symbolem zimnej wojny i\u00A0podziału Europy.', native: 'Die DDR-Regierung errichtete eine Mauer, die Berlin physisch teilte, um die Massenflucht ihrer Bürger in den Westen zu stoppen. Sie wurde zum bekanntesten Symbol des Kalten Krieges und der Teilung Europas.' } },
        { date: '1990', name: { pl: 'Zjednoczenie Niemiec', native: 'Deutsche Wiedervereinigung' }, description: { pl: 'Po upadku Muru Berlińskiego w\u00A01989 roku, Niemiecka Republika Demokratyczna została formalnie włączona do Republiki Federalnej Niemiec 3 października 1990 roku, kończąc ponad 40-letni podział kraju.', native: 'Nach dem Fall der Berliner Mauer 1989 wurde die Deutsche Demokratische Republik am 3. Oktober 1990 formell in die Bundesrepublik Deutschland eingegliedert, was die über 40-jährige Teilung des Landes beendete.' } }
    ],
    ui: { title: { pl: 'Historia Niemiec', native: 'Geschichte Deutschlands' }, backButton: { pl: 'Powrót do Kultury', native: 'Zurück zur Kultur' } }
  },
  fr: {
    lang: 'fr',
    events: [
        { date: '481', name: { pl: 'Chlodwig I zostaje królem Franków', native: 'Clovis Ier devient roi des Francs' }, description: { pl: 'Chlodwig zjednoczył większość plemion frankijskich pod jednym przywództwem, założył dynastię Merowingów i\u00A0przyjął katolicyzm, co miało kluczowe znaczenie dla przyszłości Francji i\u00A0jej sojuszu z\u00A0papiestwem.', native: 'Clovis a unifié la plupart des tribus franques sous un seul dirigeant, fondé la dynastie mérovingienne et s\'est converti au catholicisme, ce qui a été crucial pour l\'avenir de la France et son alliance avec la papauté.' } },
        { date: '800', name: { pl: 'Koronacja Karola Wielkiego', native: 'Couronnement de Charlemagne' }, description: { pl: 'Król Franków Karol Wielki został koronowany na Cesarza Rzymian przez papieża Leona III w\u00A0Rzymie, tworząc potężne Imperium Karolińskie, które obejmowało większość zachodniej i\u00A0środkowej Europy.', native: 'Le roi des Francs, Charlemagne, fut couronné Empereur des Romains par le pape Léon III à Rome, créant un puissant Empire carolingien qui englobait la majeure partie de l\'Europe occidentale et centrale.' } },
        { date: '1429', name: { pl: 'Joanna d\'Arc w Orleanie', native: 'Jeanne d\'Arc à Orléans' }, description: { pl: 'Podczas wojny stuletniej, nastoletnia Joanna d\'Arc poprowadziła wyczerpaną armię francuską do spektakularnego zwycięstwa, znosząc angielskie oblężenie Orleanu i\u00A0odwracając losy wojny na korzyść Francji.', native: 'Pendant la guerre de Cent Ans, l\'adolescente Jeanne d\'Arc mena l\'armée française épuisée à une victoire spectaculaire, levant le siège anglais d\'Orléans et renversant le cours de la guerre en faveur de la France.' } },
        { date: '1789', name: { pl: 'Początek Rewolucji Francuskiej', native: 'Début de la Révolution Française' }, description: { pl: 'Zdobycie Bastylii 14 lipca 1789 roku jest symbolicznym początkiem rewolucji, która obaliła monarchię absolutną i\u00A0ustanowiła republikę opartą na fundamentalnych zasadach "Wolności, Równości, Braterstwa".', native: 'La prise de la Bastille le 14 juillet 1789 est le début symbolique de la révolution qui a renversé la monarchie absolue et établi une république fondée sur les principes fondamentaux de "Liberté, Égalité, Fraternité".' } },
        { date: '1804', name: { pl: 'Napoleon zostaje cesarzem', native: 'Napoléon devient Empereur' }, description: { pl: 'Napoleon Bonaparte koronował się na Cesarza Francuzów w\u00A0katedrze Notre-Dame w\u00A0Paryżu. Jego rządy przyniosły rozległe reformy prawne (Kodeks Napoleona) i\u00A0serię wojen, które na zawsze zmieniły mapę Europy.', native: 'Napoléon Bonaparte se couronne Empereur des Français à la cathédrale Notre-Dame de Paris. Son règne a apporté des réformes juridiques étendues (le Code Napoléon) et une série de guerres qui ont redessiné la carte de l\'Europe à jamais.' } },
        { date: '1889', name: { pl: 'Budowa Wieży Eiffla', native: 'Construction de la Tour Eiffel' }, description: { pl: 'Zbudowana jako brama wejściowa i\u00A0główna atrakcja na Wystawę Światową w\u00A0Paryżu, wieża zaprojektowana przez Gustave\'a Eiffla, mimo początkowej krytyki, stała się trwałym symbolem Francji i\u00A0cudem inżynierii przemysłowej.', native: 'Construite comme porte d\'entrée et attraction principale de l\'Exposition universelle de Paris, la tour conçue par Gustave Eiffel, malgré les critiques initiales, est devenue un symbole durable de la France et une merveille de l\'ingénierie industrielle.' } },
        { date: '1914-1918', name: { pl: 'I wojna światowa', native: 'Première Guerre mondiale' }, description: { pl: 'Francja była jednym z\u00A0głównych teatrów działań wojennych na froncie zachodnim, ponosząc ogromne zniszczenia i\u00A0straty ludzkie. Wojna zakończyła się zwycięstwem aliantów i\u00A0odzyskaniem przez Francję Alzacji i\u00A0Lotaryngii.', native: 'La France fut l\'un des principaux théâtres d\'opérations sur le front occidental, subissant d\'énormes destructions et pertes humaines. La guerre s\'est terminée par la victoire des Alliés et la récupération de l\'Alsace et de la Lorraine par la France.' } },
        { date: '1944', name: { pl: 'Lądowanie w Normandii (D-Day)', native: 'Débarquement de Normandie (Jour J)' }, description: { pl: '6 czerwca 1944 roku siły alianckie wylądowały na plażach Normandii w\u00A0ramach operacji Overlord, otwierając drugi front w\u00A0Europie Zachodniej i\u00A0rozpoczynając proces wyzwalania Francji spod okupacji niemieckiej.', native: 'Le 6 juin 1944, les forces alliées ont débarqué sur les plages de Normandie dans le cadre de l\'opération Overlord, ouvrant un second front en Europe occidentale et commençant le processus de libération de la France de l\'occupation allemande.' } },
        { date: '1958', name: { pl: 'Ustanowienie Piątej Republiki', native: 'Instauration de la Ve République' }, description: { pl: 'W obliczu głębokiego kryzysu politycznego związanego z\u00A0wojną w\u00A0Algierii, Charles de Gaulle powrócił do władzy i\u00A0wprowadził nową konstytucję, tworząc silny system prezydencki, który obowiązuje do dziś.', native: 'Face à une profonde crise politique liée à la guerre d\'Algérie, Charles de Gaulle est revenu au pouvoir et a introduit une nouvelle constitution, créant le système présidentiel fort qui est toujours en vigueur aujourd\'hui.' } },
        { date: '1992', name: { pl: 'Traktat z Maastricht', native: 'Traité de Maastricht' }, description: { pl: 'Francja była jednym z\u00A0głównych architektów i\u00A0sygnatariuszy traktatu, który formalnie ustanowił Unię Europejską, wprowadził obywatelstwo europejskie i\u00A0stworzył podwaliny pod wspólną walutę, euro.', native: 'La France fut l\'un des principaux architectes et signataires du traité qui a formellement établi l\'Union européenne, introduit la citoyenneté européenne et jeté les bases de la monnaie unique, l\'euro.' } }
    ],
    ui: { title: { pl: 'Historia Francji', native: 'Histoire de France' }, backButton: { pl: 'Powrót do Kultury', native: 'Retour à la Culture' } }
  },
  it: {
    lang: 'it',
    events: [
        { date: '753 p.n.e.', name: { pl: 'Założenie Rzymu', native: 'Fondazione di Roma' }, description: { pl: 'Według legendy, Rzym został założony przez braci-bliźniaków Romulusa i\u00A0Remusa. To symboliczny początek historii miasta, które z\u00A0małej osady miało stać się stolicą potężnego imperium, dominującego nad basenem Morza Śródziemnego.', native: 'Secondo la leggenda, Roma fu fondata dai fratelli gemelli Romolo e Remo. È l\'inizio simbolico della storia della città che, da un piccolo insediamento, sarebbe diventata la capitale di un potente impero che dominava il bacino del Mediterraneo.' } },
        { date: '476', name: { pl: 'Upadek Cesarstwa Rzymskiego', native: 'Caduta dell\'Impero Romano' }, description: { pl: 'Obalenie ostatniego cesarza zachodniorzymskiego, Romulusa Augustulusa, przez germańskiego wodza Odoakra jest tradycyjnie uważane za koniec starożytności i\u00A0początek burzliwego okresu średniowiecza w\u00A0Europie.', native: 'La deposizione dell\'ultimo imperatore romano d\'Occidente, Romolo Augusto, da parte del capo germanico Odoacre è tradizionalmente considerata la fine dell\'antichità e l\'inizio del turbolento periodo del Medioevo in Europa.' } },
        { date: '~1300', name: { pl: 'Początek Renesansu', native: 'Inizio del Rinascimento' }, description: { pl: 'Ruch odrodzenia sztuki, nauki i\u00A0kultury, który rozpoczął się we Florencji i\u00A0rozprzestrzenił na całą Europę. Jego pionierami byli twórcy tacy jak Dante i\u00A0Giotto, a\u00A0później Leonardo da Vinci, Michał Anioł i\u00A0Rafael, którzy na zawsze zmienili oblicze sztuki.', native: 'Un movimento di rinascita delle arti, delle scienze e della cultura che iniziò a Firenze e si diffuse in tutta Europa. I suoi pionieri furono artisti come Dante e Giotto, e più tardi Leonardo da Vinci, Michelangelo e Raffaello, che cambiarono per sempre il volto dell\'arte.' } },
        { date: '1492', name: { pl: 'Odkrycie Ameryki przez Kolumba', native: 'Scoperta dell\'America' }, description: { pl: 'Genueńczyk Krzysztof Kolumb, w\u00A0służbie Hiszpanii, dopłynął do brzegów Ameryki, błędnie wierząc, że dotarł do Indii. Jego podróż zapoczątkowała epokę wielkich odkryć geograficznych i\u00A0globalnej wymiany kulturowej i\u00A0handlowej.', native: 'Il genovese Cristoforo Colombo, al servizio della Spagna, raggiunse le coste dell\'America, credendo erroneamente di aver raggiunto le Indie. Il suo viaggio diede inizio all\'era delle grandi scoperte geografiche e degli scambi culturali e commerciali globali.' } },
        { date: '1861', name: { pl: 'Zjednoczenie Włoch', native: 'Unificazione d\'Italia' }, description: { pl: 'Proces zjednoczenia licznych państw Półwyspu Apenińskiego, znany jako Risorgimento, zakończył się proklamowaniem Królestwa Włoch z\u00A0Wiktorem Emanuelem II jako pierwszym królem. Rzym stał się stolicą w\u00A01871 roku.', native: 'Il processo di unificazione dei numerosi stati della penisola italiana, noto come Risorgimento, si concluse con la proclamazione del Regno d\'Italia con Vittorio Emanuele II come primo re. Roma divenne la capitale nel 1871.' } },
        { date: '1922', name: { pl: 'Marsz na Rzym', native: 'Marcia su Roma' }, description: { pl: 'Benito Mussolini i\u00A0jego zwolennicy w\u00A0czarnych koszulach zorganizowali marsz na stolicę, co doprowadziło do przejęcia przez nich władzy i\u00A0ustanowienia faszystowskiej dyktatury, która trwała ponad dwie dekady.', native: 'Benito Mussolini e i suoi sostenitori in camicia nera organizzarono una marcia sulla capitale, che portò alla loro presa del potere e all\'instaurazione di una dittatura fascista che durò oltre due decenni.' } },
        { date: '1946', name: { pl: 'Proklamowanie Republiki', native: 'Proclamazione della Repubblica' }, description: { pl: 'Po zakończeniu II wojny światowej i\u00A0upadku faszyzmu, Włosi w\u00A0referendum instytucjonalnym opowiedzieli się za zniesieniem monarchii i\u00A0ustanowieniem republiki, która istnieje do dziś.', native: 'Dopo la fine della Seconda Guerra Mondiale e la caduta del fascismo, gli italiani votarono in un referendum istituzionale per abolire la monarchia e istituire una repubblica, che esiste ancora oggi.' } },
        { date: '1957', name: { pl: 'Traktat Rzymski', native: 'Trattato di Roma' }, description: { pl: 'Włochy były jednym z\u00A0sześciu krajów założycielskich Europejskiej Wspólnoty Gospodarczej (EWG), poprzedniczki Unii Europejskiej, podpisując kluczowy traktat w\u00A0swojej stolicy.', native: 'L\'Italia fu uno dei sei paesi fondatori della Comunità Economica Europea (CEE), precursore dell\'Unione Europea, firmando il trattato chiave nella sua capitale.' } },
        { date: '1992', name: { pl: 'Operacja Czyste Ręce', native: 'Mani pulite' }, description: { pl: 'Seria dochodzeń sądowych, które ujawniły ogromny system korupcji (tzw. Tangentopoli) w\u00A0polityce i\u00A0biznesie, prowadząc do upadku tzw. Pierwszej Republiki i\u00A0całkowitej zmiany sceny politycznej.', native: 'Una serie di indagini giudiziarie che svelarono un vasto sistema di corruzione (il cosiddetto Tangentopoli) nella politica e negli affari, portando alla caduta della Prima Repubblica e a un completo cambiamento della scena politica.' } },
        { date: '2002', name: { pl: 'Wprowadzenie euro', native: 'Adozione dell\'Euro' }, description: { pl: 'Włochy, jako jeden z\u00A0pierwszych krajów strefy euro, zastąpiły swoją historyczną walutę narodową, lira, wspólną europejską walutą euro, co było ważnym krokiem w\u00A0integracji monetarnej.', native: 'L\'Italia, come uno dei primi paesi dell\'Eurozona, sostituì la sua storica valuta nazionale, la lira, con la moneta unica europea, l\'euro, un passo importante nell\'integrazione monetaria.' } }
    ],
    ui: { title: { pl: 'Historia Włoch', native: 'Storia d\'Italia' }, backButton: { pl: 'Powrót do Kultury', native: 'Torna a Cultura' } }
  },
  es: {
    lang: 'es',
    events: [
        { date: '711', name: { pl: 'Podbój muzułmański', native: 'Conquista musulmana' }, description: { pl: 'Wojska muzułmańskie z\u00A0Afryki Północnej przekroczyły Cieśninę Gibraltarską, rozpoczynając podbój Półwyspu Iberyjskiego, co zapoczątkowało prawie 800-letni okres obecności kultury i\u00A0nauki islamu w\u00A0Hiszpanii (Al-Andalus).', native: 'Las tropas musulmanas del norte de África cruzaron el Estrecho de Gibraltar, iniciando la conquista de la Península Ibérica, lo que dio comienzo a un período de casi 800 años de presencia de la cultura y la ciencia islámica en España (Al-Andalus).' } },
        { date: '1492', name: { pl: 'Koniec Rekonkwisty i\u00A0odkrycie Ameryki', native: 'Fin de la Reconquista y\u00A0descubrimiento de América' }, description: { pl: 'Upadek Granady, ostatniego emiratu muzułmańskiego, zakończył rekonkwistę, jednocząc Hiszpanię pod rządami katolickich monarchów. W\u00A0tym samym roku Krzysztof Kolumb dotarł do Ameryki, rozpoczynając epokę hiszpańskiego imperium kolonialnego.', native: 'La caída de Granada, el último emirato musulmán, puso fin a la Reconquista, unificando España bajo los Reyes Católicos. Ese mismo año, Cristóbal Colón llegó a América, dando inicio a la era del imperio colonial español.' } },
        { date: '1588', name: { pl: 'Klęska Wielkiej Armady', native: 'Derrota de la Armada Invencible' }, description: { pl: 'Niezwyciężona Armada, potężna flota wysłana przez króla Filipa II w\u00A0celu inwazji na Anglię, została pokonana przez flotę angielską i\u00A0sztormy. Klęska ta zapoczątkowała powolny schyłek hiszpańskiej dominacji na morzach.', native: 'La Armada Invencible, una poderosa flota enviada por el rey Felipe II para invadir Inglaterra, fue derrotada por la flota inglesa y las tormentas. Esta derrota marcó el inicio del lento declive del dominio naval español.' } },
        { date: '1808-1814', name: { pl: 'Wojna na Półwyspie Iberyjskim', native: 'Guerra de la Independencia' }, description: { pl: 'Narodowe powstanie przeciwko okupacji napoleońskiej, które stało się jednym z\u00A0pierwszych przykładów wojny partyzanckiej na dużą skalę. Doprowadziło do powstania pierwszej liberalnej hiszpańskiej konstytucji w\u00A01812 roku.', native: 'Un levantamiento nacional contra la ocupación napoleónica, que se convirtió en uno de los primeros ejemplos de guerra de guerrillas a gran escala. Condujo a la creación de la primera constitución liberal española en 1812.' } },
        { date: '1936-1939', name: { pl: 'Hiszpańska wojna domowa', native: 'Guerra Civil Española' }, description: { pl: 'Krwawy i\u00A0brutalny konflikt między siłami republikańskimi a\u00A0nacjonalistami pod wodzą generała Franco. Wojna podzieliła społeczeństwo i\u00A0zakończyła się zwycięstwem Franco, ustanawiając długą dyktaturę.', native: 'Un sangriento y brutal conflicto entre las fuerzas republicanas y los nacionalistas liderados por el general Franco. La guerra dividió a la sociedad y terminó con la victoria de Franco, estableciendo una larga dictadura.' } },
        { date: '1939-1975', name: { pl: 'Hiszpania frankistowska', native: 'España franquista' }, description: { pl: 'Okres autorytarnej dyktatury generała Francisco Franco, charakteryzujący się surowymi represjami politycznymi, cenzurą i\u00A0początkową izolacją międzynarodową, a\u00A0później gwałtownym rozwojem gospodarczym w\u00A0latach 60.', native: 'El período de la dictadura autoritaria del general Francisco Franco, caracterizado por una dura represión política, censura y un aislamiento internacional inicial, seguido de un rápido desarrollo económico en los años 60.' } },
        { date: '1975', name: { pl: 'Śmierć Franco i\u00A0przejście do demokracji', native: 'Muerte de Franco y\u00A0Transición' }, description: { pl: 'Po śmierci dyktatora Franco, król Juan Carlos I\u00A0zainicjował proces pokojowego przejścia do demokracji (La Transición), który zakończył się uchwaleniem demokratycznej konstytucji w\u00A01978 roku.', native: 'Tras la muerte del dictador Franco, el rey Juan Carlos I inició un proceso de transición pacífica a la democracia (La Transición), que culminó con la aprobación de una constitución democrática en 1978.' } },
        { date: '1986', name: { pl: 'Przystąpienie do EWG', native: 'Entrada en la CEE' }, description: { pl: 'Hiszpania, wraz z\u00A0Portugalią, dołączyła do Europejskiej Wspólnoty Gospodarczej (obecnie UE). Ten krok przyspieszył jej modernizację gospodarczą i\u00A0społeczną oraz umocnił jej pozycję w\u00A0Europie.', native: 'España, junto con Portugal, se unió a la Comunidad Económica Europea (ahora UE). Este paso aceleró su modernización económica y social y consolidó su posición en Europa.' } },
        { date: '1992', name: { pl: 'Olimpiada w\u00A0Barcelonie i\u00A0Expo w\u00A0Sewilli', native: 'Olimpiadas de Barcelona y\u00A0Expo de Sevilla' }, description: { pl: 'Rok, który symbolicznie ukazał światu nowoczesną, otwartą i\u00A0dynamiczną Hiszpanię po latach dyktatury. Oba wydarzenia były ogromnym sukcesem organizacyjnym i\u00A0wizerunkowym, przyciągając międzynarodową uwagę.', native: 'Un año que mostró simbólicamente al mundo una España moderna, abierta y dinámica tras años de dictadura. Ambos eventos fueron un gran éxito organizativo y de imagen, atrayendo la atención internacional.' } },
        { date: '2002', name: { pl: 'Wprowadzenie euro', native: 'Adopción del Euro' }, description: { pl: 'Hiszpania zastąpiła swoją długowieczną walutę, pesetę, wspólną europejską walutą euro. Był to ważny krok w\u00A0pełnej integracji gospodarczej z\u00A0Unią Europejską, ułatwiając handel i\u00A0podróże.', native: 'España reemplazó su longeva moneda, la peseta, por la moneda única europea, el euro. Fue un paso importante en la plena integración económica con la Unión Europea, facilitando el comercio y los viajes.' } }
    ],
    ui: { title: { pl: 'Historia Hiszpanii', native: 'Historia de España' }, backButton: { pl: 'Powrót do Kultury', native: 'Volver a Cultura' } }
  },
};
