
import type { Language } from './storage';

export interface MonumentData {
  name: { pl: string; native: string; };
  description: { pl: string; native: string; };
  facts: {
    location: { pl: string; native: string; };
    year: { pl: string; native: string; };
    style: { pl: string; native: string; };
    annualVisitors: { pl: string; native: string; };
  };
}

export interface MonumentsPageData {
  lang: Language;
  countryName: { pl: string; native: string; };
  monuments: MonumentData[];
  ui: {
    title: { pl: string; native: string; };
    backButton: { pl: string; native: string; };
    location: { pl: string; native: string; };
    year: { pl: string; native: string; };
    style: { pl: string; native: string; };
    annualVisitors: { pl: string; native: string; };
  }
}

export const allMonumentsData: Record<Language, MonumentsPageData> = {
  en: {
    lang: 'en',
    countryName: { pl: 'Anglia', native: 'England' },
    monuments: [
      { name: { pl: 'Stonehenge', native: 'Stonehenge' }, description: { pl: 'Prehistoryczny monument w Wiltshire, jeden z najsłynniejszych i najbardziej tajemniczych zabytków na świecie. Zbudowany z ogromnych kamiennych bloków, jego prawdziwe przeznaczenie wciąż jest przedmiotem debat, choć najprawdopodobniej pełnił funkcje ceremonialne i astronomiczne, idealnie dopasowując się do przesileń.', native: 'A prehistoric monument in Wiltshire, one of the most famous and mysterious landmarks in the world. Built from enormous stone blocks, its true purpose is still debated, but it most likely served ceremonial and astronomical functions, aligning perfectly with the solstices.' }, facts: { location: { pl: 'Wiltshire, Anglia', native: 'Wiltshire, England' }, year: { pl: 'ok. 3000 p.n.e.', native: 'c. 3000 BC' }, style: { pl: 'Neolit i Epoka Brązu', native: 'Neolithic & Bronze Age' }, annualVisitors: { pl: '~1.3 mln', native: '~1.3 million' } } },
      { name: { pl: 'Tower of London', native: 'Tower of London' }, description: { pl: 'Historyczna twierdza w sercu Londynu, która przez wieki służyła jako pałac królewski, więzienie dla znanych postaci jak Anna Boleyn, i mennica. Dziś jest domem dla klejnotów koronnych i legendarnych kruków, których obecność, według legendy, chroni królestwo przed upadkiem.', native: 'A historic castle in the heart of London, which over the centuries served as a royal palace, a prison for famous figures like Anne Boleyn, and a mint. Today it is home to the Crown Jewels and the legendary ravens, whose presence, according to legend, protects the kingdom from collapse.' }, facts: { location: { pl: 'Londyn, Anglia', native: 'London, England' }, year: { pl: '1078', native: '1078' }, style: { pl: 'Normański, Średniowieczny', native: 'Norman, Medieval' }, annualVisitors: { pl: '~3 mln', native: '~3 million' } } },
      { name: { pl: 'Pałac Buckingham', native: 'Buckingham Palace' }, description: { pl: 'Oficjalna londyńska rezydencja i główne miejsce pracy brytyjskich monarchów. Jest jednym z najbardziej rozpoznawalnych budynków na świecie, słynącym z ceremonii zmiany warty. Stanowi centralny punkt uroczystości państwowych i królewskiej gościnności.', native: 'The official London residence and principal workplace of the UK\'s monarchs. It is one of the most recognizable buildings in the world, famous for the Changing of the Guard ceremony. It serves as a focal point for state occasions and royal hospitality.' }, facts: { location: { pl: 'Londyn, Anglia', native: 'London, England' }, year: { pl: '1703', native: '1703' }, style: { pl: 'Neoklasycyzm', native: 'Neoclassical' }, annualVisitors: { pl: '~0.5 mln (wewnątrz)', native: '~0.5 million (inside)' } } },
      { name: { pl: 'Rzymskie Łaźnie', native: 'Roman Baths' }, description: { pl: 'Doskonale zachowany kompleks rzymskich łaźni w mieście Bath, zbudowany wokół jedynych naturalnie gorących źródeł w Wielkiej Brytanii. Był to jeden z największych ośrodków religijnych i spa w starożytnej Brytanii, poświęcony bogini Sulis Minerva.', native: 'A perfectly preserved complex of Roman public baths in the city of Bath, built around the UK\'s only natural hot springs. It was one of the grandest religious spas of the ancient world, dedicated to the goddess Sulis Minerva.' }, facts: { location: { pl: 'Bath, Anglia', native: 'Bath, England' }, year: { pl: 'ok. 70 n.e.', native: 'c. 70 AD' }, style: { pl: 'Starożytny Rzym', native: 'Ancient Roman' }, annualVisitors: { pl: '~1.3 mln', native: '~1.3 million' } } },
      { name: { pl: 'Mur Hadriana', native: 'Hadrian\'s Wall' }, description: { pl: 'Imponujący mur obronny zbudowany przez Rzymian w północnej Anglii za czasów cesarza Hadriana. Rozciągał się na długości 117,5 km od jednego wybrzeża do drugiego, stanowiąc północną granicę Imperium Rzymskiego i świadectwo potęgi inżynieryjnej.', native: 'An impressive defensive fortification built by the Romans in northern England during the reign of Emperor Hadrian. It spanned 73 miles (117.5 km) from coast to coast, marking the northern frontier of the Roman Empire and a testament to engineering might.' }, facts: { location: { pl: 'Północna Anglia', native: 'Northern England' }, year: { pl: '122 n.e.', native: '122 AD' }, style: { pl: 'Starożytny Rzym', native: 'Ancient Roman' }, annualVisitors: { pl: '~1.2 mln (płatne sekcje)', native: '~1.2 million (paid sections)' } } },
      { name: { pl: 'Katedra w Yorku', native: 'York Minster' }, description: { pl: 'Jedna z największych gotyckich katedr w Europie Północnej, oficjalnie Katedra i Metropolitalny Kościół św. Piotra w Yorku. Słynie z olbrzymich witraży, w tym Wielkiego Okna Wschodniego, które jest największym na świecie średniowiecznym witrażem w jednym oknie.', native: 'One of the largest Gothic cathedrals in Northern Europe, officially the Cathedral and Metropolitical Church of Saint Peter in York. It is renowned for its vast stained glass windows, including the Great East Window, the largest single expanse of medieval stained glass in the world.' }, facts: { location: { pl: 'York, Anglia', native: 'York, England' }, year: { pl: '1472 (ukończona)', native: '1472 (completed)' }, style: { pl: 'Gotyk', native: 'Gothic' }, annualVisitors: { pl: '~0.7 mln', native: '~0.7 million' } } },
      { name: { pl: 'Zamek Windsor', native: 'Windsor Castle' }, description: { pl: 'Najstarszy i największy zamieszkany zamek na świecie, będący jedną z głównych rezydencji brytyjskiej rodziny królewskiej od ponad 900 lat. Zamek jest w pełni działającym pałacem, używanym do celów ceremonialnych i państwowych.', native: 'The oldest and largest inhabited castle in the world, serving as a principal residence for the British royal family for over 900 years. The castle is a fully functioning palace, used for ceremonial and state purposes.' }, facts: { location: { pl: 'Windsor, Anglia', native: 'Windsor, England' }, year: { pl: 'XI wiek', native: '11th century' }, style: { pl: 'Różne (od normańskiego)', native: 'Various (from Norman)' }, annualVisitors: { pl: '~1.5 mln', native: '~1.5 million' } } }
    ],
    ui: { title: { pl: 'Zabytki Anglii', native: 'Monuments of England' }, backButton: { pl: 'Powrót do Kultury', native: 'Back to Culture' }, location: { pl: 'Lokalizacja', native: 'Location' }, year: { pl: 'Rok budowy', native: 'Year Built' }, style: { pl: 'Styl', native: 'Style' }, annualVisitors: { pl: 'Rocznie odwiedzających', native: 'Annual Visitors' } }
  },
  de: {
    lang: 'de',
    countryName: { pl: 'Niemcy', native: 'Deutschland' },
    monuments: [
      { name: { pl: 'Brama Brandenburska', native: 'Brandenburger Tor' }, description: { pl: 'Symbol zjednoczenia Niemiec i Berlina, stojący w sercu miasta. Ta monumentalna, neoklasycystyczna brama była świadkiem wielu kluczowych wydarzeń w historii, od parad wojskowych po upadek Muru Berlińskiego. Zwieńczona jest kwadrygą, rzeźbą przedstawiającą boginię zwycięstwa.', native: 'Ein Symbol der deutschen und Berliner Wiedervereinigung, das im Herzen der Stadt steht. Dieses monumentale, neoklassizistische Tor war Zeuge vieler Schlüsselereignisse der Geschichte, von Militärparaden bis zum Fall der Berliner Mauer. Es wird von einer Quadriga gekrönt, einer Skulptur, die die Siegesgöttin darstellt.' }, facts: { location: { pl: 'Berlin, Niemcy', native: 'Berlin, Germany' }, year: { pl: '1791', native: '1791' }, style: { pl: 'Neoklasycyzm', native: 'Neoclassicism' }, annualVisitors: { pl: '~12 mln (okolice)', native: '~12 million (area)' } } },
      { name: { pl: 'Zamek Neuschwanstein', native: 'Schloss Neuschwanstein' }, description: { pl: 'Bajkowy zamek w Bawarii, zbudowany z polecenia króla Ludwika II. Jest inspiracją dla zamku w logo Disneya i jednym z najczęściej fotografowanych budynków w Niemczech. Jego romantyczna architektura i malownicza położenie w Alpach przyciągają miliony turystów rocznie.', native: 'Ein Märchenschloss in Bayern, erbaut auf Befehl von König Ludwig II. Es ist die Inspiration für das Disney-Schloss und eines der meistfotografierten Gebäude in Deutschland. Seine romantische Architektur und malerische Lage in den Alpen ziehen jährlich Millionen von Touristen an.' }, facts: { location: { pl: 'Bawaria, Niemcy', native: 'Bavaria, Germany' }, year: { pl: '1886', native: '1886' }, style: { pl: 'Neoromanizm', native: 'Romanesque Revival' }, annualVisitors: { pl: '~1.4 mln', native: '~1.4 million' } } },
      { name: { pl: 'Katedra w Kolonii', native: 'Kölner Dom' }, description: { pl: 'Majestatyczna gotycka katedra, której budowa trwała ponad 600 lat, jest wpisana na listę światowego dziedzictwa UNESCO. Jest jednym z najwspanialszych przykładów architektury gotyckiej i cudem przetrwała bombardowania II wojny światowej, dominując nad panoramą miasta.', native: 'Ein majestätischer gotischer Dom, dessen Bau über 600 Jahre dauerte und der zum UNESCO-Weltkulturerbe gehört. Er ist eines der weltweit besten Beispiele gotischer Architektur und überlebte wie durch ein Wunder die Bombenangriffe des Zweiten Weltkriegs, wobei er die Skyline der Stadt dominiert.' }, facts: { location: { pl: 'Kolonia, Niemcy', native: 'Cologne, Germany' }, year: { pl: '1880 (ukończona)', native: '1880 (completed)' }, style: { pl: 'Gotyk', native: 'Gothic' }, annualVisitors: { pl: '~6 mln', native: '~6 million' } } },
      { name: { pl: 'Budynek Reichstagu', native: 'Reichstagsgebäude' }, description: { pl: 'Historyczna siedziba niemieckiego parlamentu (Bundestagu), która łączy klasyczną architekturę z nowoczesnością. Jego szklana kopuła, zaprojektowana przez Normana Fostera, jest symbolem przejrzystości demokracji i popularną atrakcją turystyczną.', native: 'Der historische Sitz des Deutschen Bundestages, der klassische Architektur mit Moderne verbindet. Seine Glaskuppel, entworfen von Norman Foster, ist ein Symbol demokratischer Transparenz und eine beliebte Touristenattraktion.' }, facts: { location: { pl: 'Berlin, Niemcy', native: 'Berlin, Germany' }, year: { pl: '1894 (oryg.), 1999 (kopuła)', native: '1894 (orig.), 1999 (dome)' }, style: { pl: 'Neorenesans/Nowoczesny', native: 'Neo-Renaissance/Modern' }, annualVisitors: { pl: '~2.5 mln', native: '~2.5 million' } } },
      { name: { pl: 'Zamek w Heidelbergu', native: 'Heidelberger Schloss' }, description: { pl: 'Imponujące ruiny jednego z najważniejszych renesansowych zamków na północ od Alp. Zamek góruje nad starym miastem Heidelbergu, a w jego piwnicach znajduje się gigantyczna beczka na wino (Großes Fass), co dodaje mu unikalnego charakteru.', native: 'Die imposante Ruine eines der bedeutendsten Renaissancebauten nördlich der Alpen. Das Schloss thront über der Heidelberger Altstadt und beherbergt in seinen Kellern das riesige Weinfass (Großes Fass), was ihm einen einzigartigen Charakter verleiht.' }, facts: { location: { pl: 'Heidelberg, Niemcy', native: 'Heidelberg, Germany' }, year: { pl: 'XIII-XVII w.', native: '13th-17th cent.' }, style: { pl: 'Gotyk/Renesans', native: 'Gothic/Renaissance' }, annualVisitors: { pl: '~1 mln', native: '~1 million' } } },
      { name: { pl: 'Katedra w Akwizgranie', native: 'Aachener Dom' }, description: { pl: 'Jedna z najstarszych katedr w Europie, miejsce pochówku Karola Wielkiego i przez 600 lat miejsce koronacji królów niemieckich. W jej centrum znajduje się unikalna, ośmiokątna kaplica pałacowa, stanowiąca arcydzieło architektury karolińskiej.', native: 'Einer der ältesten Dome Europas, Grabstätte Karls des Großen und über 600 Jahre lang Krönungsort deutscher Könige. Im Zentrum befindet sich die einzigartige, achteckige Pfalzkapelle, ein Meisterwerk der karolingischen Architektur.' }, facts: { location: { pl: 'Akwizgran, Niemcy', native: 'Aachen, Germany' }, year: { pl: '805', native: '805' }, style: { pl: 'Karoliński/Gotyk', native: 'Carolingian/Gothic' }, annualVisitors: { pl: '~1.5 mln', native: '~1.5 million' } } },
      { name: { pl: 'Zwinger', native: 'Zwinger' }, description: { pl: 'Wspaniały barokowy kompleks pałacowy w Dreźnie, który pierwotnie służył jako oranżeria i miejsce dworskich uroczystości. Dziś mieści światowej sławy zbiory sztuki, w tym Galerię Obrazów Starych Mistrzów z "Madonną Sykstyńską" Rafaela.', native: 'Ein prächtiger barocker Schlosskomplex in Dresden, der ursprünglich als Orangerie und Ort höfischer Feste diente. Heute beherbergt er weltberühmte Kunstsammlungen, darunter die Gemäldegalerie Alte Meister mit Raffaels "Sixtinischer Madonna".' }, facts: { location: { pl: 'Drezno, Niemcy', native: 'Dresden, Germany' }, year: { pl: '1728', native: '1728' }, style: { pl: 'Barok', native: 'Baroque' }, annualVisitors: { pl: '~1.8 mln', native: '~1.8 million' } } }
    ],
    ui: { title: { pl: 'Zabytki Niemiec', native: 'Denkmäler Deutschlands' }, backButton: { pl: 'Powrót do Kultury', native: 'Zurück zur Kultur' }, location: { pl: 'Lokalizacja', native: 'Standort' }, year: { pl: 'Rok budowy', native: 'Baujahr' }, style: { pl: 'Styl', native: 'Stil' }, annualVisitors: { pl: 'Rocznie odwiedzających', native: 'Jährliche Besucher' } }
  },
  fr: {
    lang: 'fr',
    countryName: { pl: 'Francja', native: 'France' },
    monuments: [
      { name: { pl: 'Wieża Eiffla', native: 'Tour Eiffel' }, description: { pl: 'Ikona Paryża i symbol Francji o wysokości 330 metrów. Zbudowana na Wystawę Światową w 1889 roku, początkowo była krytykowana, a dziś jest jednym z najczęściej odwiedzanych płatnych zabytków na świecie.', native: 'Icône de Paris et symbole de la France, haute de 330 mètres. Construite pour l\'Exposition universelle de 1889, elle fut d\'abord critiquée, mais est aujourd\'hui l\'un des monuments payants les plus visités au monde.' }, facts: { location: { pl: 'Paryż, Francja', native: 'Paris, France' }, year: { pl: '1889', native: '1889' }, style: { pl: 'Strukturalizm', native: 'Structuralism' }, annualVisitors: { pl: '~6 mln', native: '~6 million' } } },
      { name: { pl: 'Luwr', native: 'Musée du Louvre' }, description: { pl: 'Największe muzeum sztuki na świecie i centralny punkt orientacyjny Paryża, mieszczący się w dawnym pałacu królewskim. Jest domem dla tysięcy dzieł, w tym Mona Lisy i Wenus z Milo. Jego szklana piramida, dodana w 1989 roku, stała się nowym symbolem muzeum.', native: 'Le plus grand musée d\'art du monde et un point de repère central à Paris, installé dans un ancien palais royal. Il abrite des milliers d\'œuvres, dont la Joconde et la Vénus de Milo. Sa pyramide de verre, ajoutée en 1989, est devenue un nouveau symbole du musée.' }, facts: { location: { pl: 'Paryż, Francja', native: 'Paris, France' }, year: { pl: '1793 (otwarcie)', native: '1793 (opened)' }, style: { pl: 'Renesans/Barok/Nowoczesny', native: 'Renaissance/Baroque/Modern' }, annualVisitors: { pl: '~8 mln', native: '~8 million' } } },
      { name: { pl: 'Mont Saint-Michel', native: 'Mont Saint-Michel' }, description: { pl: 'Wyspa pływowa w Normandii, zwieńczona majestatycznym opactwem benedyktyńskim. To jedno z najbardziej zapierających dech w piersiach miejsc we Francji, które w zależności od pływów, jednych z najwyższych w Europie, staje się wyspą lub jest połączone z lądem.', native: 'Une île marémotrice en Normandie, surmontée d\'une majestueuse abbaye bénédictine. C\'est l\'un des sites les plus époustouflants de France, devenant une île ou étant reliée au continent selon les marées, qui sont parmi les plus hautes d\'Europe.' }, facts: { location: { pl: 'Normandia, Francja', native: 'Normandy, France' }, year: { pl: 'VIII wiek', native: '8th century' }, style: { pl: 'Romański/Gotyk', native: 'Romanesque/Gothic' }, annualVisitors: { pl: '~2.5 mln', native: '~2.5 million' } } },
      { name: { pl: 'Pałac Wersalski', native: 'Château de Versailles' }, description: { pl: 'Dawna rezydencja królów Francji, symbol monarchii absolutnej. Słynie z Sali Lustrzanej, gdzie podpisano Traktat Wersalski, oraz ogromnych, misternie zaprojektowanych ogrodów. To jeden z największych i najwspanialszych kompleksów pałacowych na świecie.', native: 'Ancienne résidence des rois de France, symbole de la monarchie absolue. Célèbre pour sa Galerie des Glaces, où fut signé le Traité de Versailles, et ses vastes jardins méticuleusement conçus. C\'est l\'un des plus grands et des plus magnifiques complexes palatiaux au monde.' }, facts: { location: { pl: 'Wersal, Francja', native: 'Versailles, France' }, year: { pl: '1682', native: '1682' }, style: { pl: 'Barok francuski', native: 'French Baroque' }, annualVisitors: { pl: '~15 mln', native: '~15 million' } } },
      { name: { pl: 'Katedra Notre-Dame', native: 'Cathédrale Notre-Dame' }, description: { pl: 'Gotycka katedra w sercu Paryża, arcydzieło architektury średniowiecznej, uwiecznione w powieści Victora Hugo. Znana z witraży rozetowych, latających przypór i gargulców. Obecnie w odbudowie po pożarze w 2019 roku, stanowi symbol odrodzenia.', native: 'Cathédrale gothique au cœur de Paris, chef-d\'œuvre de l\'architecture médiévale, immortalisée dans le roman de Victor Hugo. Connue pour ses rosaces, ses arcs-boutants et ses gargouilles. Actuellement en reconstruction après l\'incendie de 2019, elle est un symbole de renaissance.' }, facts: { location: { pl: 'Paryż, Francja', native: 'Paris, France' }, year: { pl: '1345 (ukończona)', native: '1345 (completed)' }, style: { pl: 'Gotyk francuski', native: 'French Gothic' }, annualVisitors: { pl: '~12 mln (przed pożarem)', native: '~12 million (pre-fire)' } } },
      { name: { pl: 'Łuk Triumfalny', native: 'Arc de Triomphe' }, description: { pl: 'Monumentalny łuk w centrum Placu Charles\'a de Gaulle\'a, upamiętniający zwycięstwa Napoleona i francuskich żołnierzy. Pod nim znajduje się Grób Nieznanego Żołnierza. Z jego szczytu roztacza się panoramiczny widok na dwanaście rozchodzących się alei.', native: 'Arc monumental au centre de la Place Charles de Gaulle, commémorant les victoires de Napoléon et des soldats français. Sous celui-ci se trouve la Tombe du Soldat Inconnu. De son sommet, on a une vue panoramique sur les douze avenues qui en partent.' }, facts: { location: { pl: 'Paryż, Francja', native: 'Paris, France' }, year: { pl: '1836', native: '1836' }, style: { pl: 'Neoklasycyzm', native: 'Neoclassicism' }, annualVisitors: { pl: '~1.7 mln', native: '~1.7 million' } } },
      { name: { pl: 'Zamek Chambord', native: 'Château de Chambord' }, description: { pl: 'Największy i najbardziej rozpoznawalny z zamków w Dolinie Loary, z 440 pokojami. Słynie z charakterystycznej architektury renesansowej, w tym spektakularnych, podwójnych, spiralnych schodów, których projekt przypisuje się Leonardowi da Vinci.', native: 'Le plus grand et le plus reconnaissable des châteaux de la vallée de la Loire, avec 440 pièces. Il est célèbre pour son architecture Renaissance distinctive, notamment un spectaculaire escalier à double hélice attribué à Léonard de Vinci.' }, facts: { location: { pl: 'Dolina Loary, Francja', native: 'Loire Valley, France' }, year: { pl: '1547', native: '1547' }, style: { pl: 'Renesans francuski', native: 'French Renaissance' }, annualVisitors: { pl: '~1 mln', native: '~1 million' } } }
    ],
    ui: { title: { pl: 'Zabytki Francji', native: 'Monuments de France' }, backButton: { pl: 'Powrót do Kultury', native: 'Retour à la Culture' }, location: { pl: 'Lokalizacja', native: 'Lieu' }, year: { pl: 'Rok budowy', native: 'Année' }, style: { pl: 'Styl', native: 'Style' }, annualVisitors: { pl: 'Rocznie odwiedzających', native: 'Visiteurs annuels' } }
  },
  it: {
    lang: 'it',
    countryName: { pl: 'Włochy', native: 'Italia' },
    monuments: [
      { name: { pl: 'Koloseum', native: 'Colosseo' }, description: { pl: 'Największy starożytny amfiteatr na świecie, symbol potęgi Imperium Rzymskiego. Odbywały się tu walki gladiatorów, polowania na dzikie zwierzęta i publiczne egzekucje, które mogło oglądać nawet do 80 000 widzów.', native: 'Il più grande anfiteatro antico del mondo, simbolo della potenza dell\'Impero Romano. Ospitava combattimenti di gladiatori, cacce di animali selvatici ed esecuzioni pubbliche, che potevano essere viste da fino a 80.000 spettatori.' }, facts: { location: { pl: 'Rzym, Włochy', native: 'Rome, Italy' }, year: { pl: '80 n.e.', native: '80 AD' }, style: { pl: 'Starożytny Rzym', native: 'Ancient Roman' }, annualVisitors: { pl: '~7.6 mln', native: '~7.6 million' } } },
      { name: { pl: 'Krzywa Wieża w Pizie', native: 'Torre di Pisa' }, description: { pl: 'Słynna na całym świecie dzwonnica (campanile) katedry w Pizie, znana z niezamierzonego przechyłu. Jej budowa trwała prawie 200 lat, a problemy ze stabilnością gruntu pojawiły się już na wczesnym etapie, czyniąc ją cudem średniowiecznej inżynierii.', native: 'Un campanile di fama mondiale della cattedrale di Pisa, noto per la sua pendenza involontaria. La sua costruzione durò quasi 200 anni e i problemi di stabilità del terreno si manifestarono fin dalle prime fasi, rendendola una meraviglia dell\'ingegneria medievale.' }, facts: { location: { pl: 'Piza, Włochy', native: 'Pisa, Italy' }, year: { pl: '1372 (ukończona)', native: '1372 (completed)' }, style: { pl: 'Romański', native: 'Romanesque' }, annualVisitors: { pl: '~5 mln (plac)', native: '~5 million (square)' } } },
      { name: { pl: 'Katedra we Florencji', native: 'Duomo di Firenze' }, description: { pl: 'Gotycka katedra, oficjalnie Cattedrale di Santa Maria del Fiore, z charakterystyczną, ogromną kopułą z cegły projektu Brunelleschiego. Jest to cud inżynierii renesansowej, który dominuje nad panoramą Florencji i jest jednym z najważniejszych zabytków miasta.', native: 'Una cattedrale gotica, ufficialmente Cattedrale di Santa Maria del Fiore, con una caratteristica ed enorme cupola in mattoni progettata dal Brunelleschi. È una meraviglia dell\'ingegneria rinascimentale che domina lo skyline di Firenze ed è uno dei monumenti più importanti della città.' }, facts: { location: { pl: 'Florencja, Włochy', native: 'Florence, Italy' }, year: { pl: '1436 (kopuła)', native: '1436 (dome)' }, style: { pl: 'Gotyk/Renesans', native: 'Gothic/Renaissance' }, annualVisitors: { pl: '~5 mln', native: '~5 million' } } },
      { name: { pl: 'Kanały Wenecji', native: 'Canali di Venezia' }, description: { pl: 'Sieć ponad 150 kanałów wodnych, które służą jako ulice tego wyjątkowego miasta. Najsłynniejszy z nich, Canal Grande, jest główną arterią komunikacyjną, wzdłuż której stoją wspaniałe pałace, a transport odbywa się gondolami i vaporetto.', native: 'Una rete di oltre 150 canali che fungono da strade di questa città unica. Il più famoso, il Canal Grande, è la principale via di trasporto, fiancheggiata da magnifici palazzi e percorsa da gondole e vaporetti.' }, facts: { location: { pl: 'Wenecja, Włochy', native: 'Venice, Italy' }, year: { pl: 'V wiek', native: '5th century' }, style: { pl: 'Infrastruktura miejska', native: 'Urban infrastructure' }, annualVisitors: { pl: '~20 mln', native: '~20 million' } } },
      { name: { pl: 'Pompeje', native: 'Pompei' }, description: { pl: 'Starożytne rzymskie miasto zniszczone i doskonale zachowane pod warstwą popiołu po wybuchu Wezuwiusza w 79 r. n.e. Dziś ruiny oferują unikalny, zamrożony w czasie wgląd w codzienne życie starożytnych Rzymian, od domów po ulice i sklepy.', native: 'Un\'antica città romana distrutta e perfettamente conservata sotto uno strato di cenere dopo l\'eruzione del Vesuvio nel 79 d.C. Oggi le rovine offrono uno sguardo unico e congelato nel tempo sulla vita quotidiana degli antichi romani, dalle case alle strade e ai negozi.' }, facts: { location: { pl: 'Neapol, Włochy', native: 'Naples, Italy' }, year: { pl: '79 n.e. (zniszczone)', native: '79 AD (destroyed)' }, style: { pl: 'Starożytny Rzym', native: 'Ancient Roman' }, annualVisitors: { pl: '~2.5 mln', native: '~2.5 million' } } },
      { name: { pl: 'Panteon', native: 'Pantheon' }, description: { pl: 'Starożytna rzymska świątynia, a obecnie kościół, słynąca z gigantycznej, niezbrojonej kopuły z centralnym otworem (oculusem). Jest to jeden z najlepiej zachowanych budynków starożytnego Rzymu, używany nieprzerwanie przez całą swoją historię.', native: 'Un antico tempio romano, ora una chiesa, famoso per la sua gigantesca cupola in cemento non armato con un oculo centrale. È uno degli edifici meglio conservati dell\'antica Roma, utilizzato ininterrottamente nel corso della sua storia.' }, facts: { location: { pl: 'Rzym, Włochy', native: 'Rome, Italy' }, year: { pl: '126 n.e.', native: '126 AD' }, style: { pl: 'Starożytny Rzym', native: 'Ancient Roman' }, annualVisitors: { pl: '~9 mln', native: '~9 million' } } },
      { name: { pl: 'Fontanna di Trevi', native: 'Fontana di Trevi' }, description: { pl: 'Największa i najsłynniejsza barokowa fontanna w Rzymie, z centralną postacią Okeanosa na rydwanie z koni morskich. Legenda głosi, że wrzucenie do niej monety gwarantuje powrót do Wiecznego Miasta.', native: 'La più grande e famosa fontana barocca di Roma, con la figura centrale di Oceano su un carro trainato da cavalli marini. La leggenda narra che lanciare una moneta al suo interno assicura il ritorno nella Città Eterna.' }, facts: { location: { pl: 'Rzym, Włochy', native: 'Rome, Italy' }, year: { pl: '1762', native: '1762' }, style: { pl: 'Barok', native: 'Baroque' }, annualVisitors: { pl: '~10.5 mln', native: '~10.5 million' } } }
    ],
    ui: { title: { pl: 'Zabytki Włoch', native: 'Monumenti d\'Italia' }, backButton: { pl: 'Powrót do Kultury', native: 'Torna a Cultura' }, location: { pl: 'Lokalizacja', native: 'Luogo' }, year: { pl: 'Rok budowy', native: 'Anno' }, style: { pl: 'Styl', native: 'Stile' }, annualVisitors: { pl: 'Rocznie odwiedzających', native: 'Visitatori annuali' } }
  },
  es: {
    lang: 'es',
    countryName: { pl: 'Hiszpania', native: 'España' },
    monuments: [
      { name: { pl: 'Sagrada Família', native: 'Sagrada Família' }, description: { pl: 'Ikona Barcelony i nieukończone arcydzieło Antoniego Gaudíego, wpisane na listę światowego dziedzictwa UNESCO. Budowa tego niezwykłego kościoła trwa od 1882 roku. Łączy w sobie gotyk z secesją, tworząc unikalny, naturalistyczny styl.', native: 'Un icono de Barcelona y la obra maestra inacabada de Antoni Gaudí, declarada Patrimonio de la Humanidad por la UNESCO. La construcción de esta extraordinaria iglesia está en curso desde 1882. Combina el gótico y el modernismo para crear un estilo naturalista único.' }, facts: { location: { pl: 'Barcelona, Hiszpania', native: 'Barcelona, Spain' }, year: { pl: '1882 - obecnie', native: '1882 - present' }, style: { pl: 'Modernizm', native: 'Modernisme' }, annualVisitors: { pl: '~4.5 mln', native: '~4.5 million' } } },
      { name: { pl: 'Alhambra', native: 'Alhambra' }, description: { pl: 'Spektakularny kompleks pałacowy i forteca mauretańskich władców w Granadzie. Słynie z misternych zdobień, dziedzińców z fontannami (jak Dziedziniec Lwów) i przepięknych ogrodów Generalife, stanowiąc szczytowe osiągnięcie sztuki islamu w Europie.', native: 'Un espectacular complejo palaciego y fortaleza de los gobernantes moros en Granada. Es famoso por sus intrincadas decoraciones, patios con fuentes (como el Patio de los Leones) y los hermosos jardines del Generalife, representando el apogeo del arte islámico en Europa.' }, facts: { location: { pl: 'Granada, Hiszpania', native: 'Granada, Spain' }, year: { pl: 'ok. 889 / XIII w.', native: 'c. 889 / 13th cent.' }, style: { pl: 'Mauretański', native: 'Moorish' }, annualVisitors: { pl: '~2.7 mln', native: '~2.7 million' } } },
      { name: { pl: 'Akwedukt w Segowii', native: 'Acueducto de Segovia' }, description: { pl: 'Jeden z najlepiej zachowanych rzymskich akweduktów na świecie, o długości 15 km. Ta imponująca budowla z granitowych bloków została wzniesiona bez użycia zaprawy i przez wieki dostarczała wodę do miasta, dominując nad jego krajobrazem.', native: 'Uno de los acueductos romanos mejor conservados del mundo, con 15 km de longitud. Esta impresionante estructura de bloques de granito fue construida sin mortero y suministró agua a la ciudad durante siglos, dominando su paisaje.' }, facts: { location: { pl: 'Segowia, Hiszpania', native: 'Segovia, Spain' }, year: { pl: 'I/II w. n.e.', native: '1st/2nd cent. AD' }, style: { pl: 'Starożytny Rzym', native: 'Ancient Roman' }, annualVisitors: { pl: '~2 mln (miasto)', native: '~2 million (city)' } } },
      { name: { pl: 'Katedra-Meczet w Kordobie', native: 'Mezquita-Catedral de Córdoba' }, description: { pl: 'Unikalny zabytek UNESCO, który pierwotnie był kościołem, następnie jednym z największych meczetów świata, a dziś jest katedrą. Słynie z "lasu" ponad 850 kolumn połączonych dwukolorowymi łukami, tworząc hipnotyzujący efekt wizualny.', native: 'Un monumento único de la UNESCO que fue originalmente una iglesia, luego una de las mezquitas más grandes del mundo y ahora es una catedral. Es famoso por su "bosque" de más de 850 columnas conectadas por arcos de dos tonos, creando un efecto visual fascinante.' }, facts: { location: { pl: 'Kordoba, Hiszpania', native: 'Córdoba, Spain' }, year: { pl: '784 (meczet)', native: '784 (mosque)' }, style: { pl: 'Mauretański/Gotyk/Renesans', native: 'Moorish/Gothic/Renaissance' }, annualVisitors: { pl: '~2 mln', native: '~2 million' } } },
      { name: { pl: 'Muzeum Prado', native: 'Museo del Prado' }, description: { pl: 'Główne hiszpańskie muzeum sztuki narodowej w Madrycie, jedno z najważniejszych na świecie. Posiada niezrównaną kolekcję sztuki europejskiej, z arcydziełami takich mistrzów jak Velázquez ("Panny dworskie"), Goya ("Trzeci maja 1808") i El Greco.', native: 'El principal museo nacional de arte de España en Madrid, uno de los más importantes del mundo. Posee una colección inigualable de arte europeo, con obras maestras de maestros como Velázquez ("Las Meninas"), Goya ("El tres de mayo de 1808") y El Greco.' }, facts: { location: { pl: 'Madryt, Hiszpania', native: 'Madrid, Spain' }, year: { pl: '1819', native: '1819' }, style: { pl: 'Neoklasycyzm', native: 'Neoclassical' }, annualVisitors: { pl: '~3.2 mln', native: '~3.2 million' } } },
      { name: { pl: 'Pałac Królewski w Madrycie', native: 'Palacio Real de Madrid' }, description: { pl: 'Oficjalna rezydencja hiszpańskiej rodziny królewskiej, choć obecnie używana tylko do ceremonii państwowych. Jest to największy funkcjonujący pałac królewski w Europie pod względem powierzchni, posiadający 3418 pokoi w stylu barokowym i klasycystycznym.', native: 'La residencia oficial de la Familia Real Española, aunque ahora se usa solo para ceremonias de estado. Es el palacio real en funcionamiento más grande de Europa por superficie, con 3.418 habitaciones de estilo barroco y clasicista.' }, facts: { location: { pl: 'Madryt, Hiszpania', native: 'Madrid, Spain' }, year: { pl: '1755', native: '1755' }, style: { pl: 'Barok', native: 'Baroque' }, annualVisitors: { pl: '~1.5 mln', native: '~1.5 million' } } },
      { name: { pl: 'Park Güell', native: 'Park Güell' }, description: { pl: 'Publiczny park z ogrodami i elementami architektonicznymi w Barcelonie, zaprojektowany przez Antoniego Gaudíego. Jest częścią światowego dziedzictwa UNESCO i słynie z mozaikowych rzeźb, jak słynna salamandra "el drac", i fantazyjnych, organicznych budowli.', native: 'Un sistema de parques públicos compuesto por jardines y elementos arquitectónicos en Barcelona, diseñado por Antoni Gaudí. Es parte del Patrimonio de la Humanidad de la UNESCO y es famoso por sus esculturas de mosaico, como la famosa salamandra "el drac", y edificios caprichosos y orgánicos.' }, facts: { location: { pl: 'Barcelona, Hiszpania', native: 'Barcelona, Spain' }, year: { pl: '1914', native: '1914' }, style: { pl: 'Modernizm', native: 'Modernisme' }, annualVisitors: { pl: '~9 mln', native: '~9 million' } } }
    ],
    ui: { title: { pl: 'Zabytki Hiszpanii', native: 'Monumentos de España' }, backButton: { pl: 'Powrót do Kultury', native: 'Volver a Cultura' }, location: { pl: 'Lokalizacja', native: 'Ubicación' }, year: { pl: 'Rok budowy', native: 'Año' }, style: { pl: 'Styl', native: 'Estilo' }, annualVisitors: { pl: 'Rocznie odwiedzających', native: 'Visitantes anuales' } }
  },
};
