
import type { PhrasesContent } from './phrases';

export const restaurantPhrases: PhrasesContent = {
  en: {
    restaurant: {
      title: 'Restaurant',
      phrases: [
        { phrase: 'A table for two, please.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'I\'d like to book a table.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Can I see the menu, please?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: 'What do you recommend?', translation: 'Co pan/pani poleca?' },
        { phrase: 'I would like to order...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'What\'s the soup of the day?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'I\'m a vegetarian.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'I have an allergy to nuts.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Is this dish spicy?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Can I have some water, please?', translation: 'Czy mogę prosić o wodę?' },
        { phrase: 'Another glass of wine, please.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'How long will we have to wait?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: 'Enjoy your meal!', translation: 'Smacznego!' },
        { phrase: 'Everything was delicious!', translation: 'Wszystko było pyszne!' },
        { phrase: 'My food is cold.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'This isn\'t what I ordered.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'Could we have the bill, please?', translation: 'Czy możemy prosić o rachunek?' },
        { phrase: 'Can we pay separately?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Is service included?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Keep the change.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Where is the restroom?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'I\'ll have the same.', translation: 'Wezmę to samo.' },
        { phrase: 'Can you recommend a local dish?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: 'What are your opening hours?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: 'Do you have a high chair for a child?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Can I get this to go?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
  },
  de: {
    restaurant: {
      title: 'Im Restaurant',
      phrases: [
        { phrase: 'Einen Tisch für zwei, bitte.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Ich möchte einen Tisch reservieren.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Könnte ich bitte die Speisekarte haben?', translation: 'Czy mogę prosić o kartę dań?' },
        { phrase: 'Was empfehlen Sie?', translation: 'Co Pan/Pani poleca?' },
        { phrase: 'Ich möchte bestellen...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'Was ist die Tagessuppe?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Ich bin Vegetarier/in.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Ich habe eine Nussallergie.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Ist dieses Gericht scharf?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Ein Wasser, bitte.', translation: 'Poproszę wodę.' },
        { phrase: 'Noch ein Glas Wein, bitte.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'Wie lange müssen wir warten?', translation: 'Jak długo musimy czekać?' },
        { phrase: 'Guten Appetit!', translation: 'Smacznego!' },
        { phrase: 'Es hat alles sehr gut geschmeckt!', translation: 'Wszystko bardzo dobrze smakowało!' },
        { phrase: 'Mein Essen ist kalt.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Das habe ich nicht bestellt.', translation: 'Tego nie zamawiałem/am.' },
        { phrase: 'Die Rechnung, bitte.', translation: 'Rachunek, proszę.' },
        { phrase: 'Können wir getrennt zahlen?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Ist das Trinkgeld inbegriffen?', translation: 'Czy napiwek jest wliczony w cenę?' },
        { phrase: 'Stimmt so.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Wo ist die Toilette?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Ich nehme das Gleiche.', translation: 'Wezmę to samo.' },
        { phrase: 'Können Sie ein lokales Gericht empfehlen?', translation: 'Czy może Pan/Pani polecić lokalne danie?' },
        { phrase: 'Was sind Ihre Öffnungszeiten?', translation: 'Jakie są godziny otwarcia?' },
        { phrase: 'Haben Sie einen Kinderstuhl?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Kann ich das zum Mitnehmen haben?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
  },
  fr: {
    restaurant: {
      title: 'Au Restaurant',
      phrases: [
        { phrase: 'Une table pour deux, s\'il vous plaît.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Je voudrais réserver une table.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Je peux voir la carte, s\'il vous plaît?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: 'Qu\'est-ce que vous recommandez?', translation: 'Co pan/pani poleca?' },
        { phrase: 'Je voudrais commander...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'Quelle est la soupe du jour?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Je suis végétarien(ne).', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Je suis allergique aux noix.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Est-ce que ce plat est épicé?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Je pourrais avoir de l\'eau, s\'il vous plaît?', translation: 'Czy mogę prosić o wodę?' },
        { phrase: 'Un autre verre de vin, s\'il vous plaît.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'Combien de temps devrons-nous attendre?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: 'Bon appétit!', translation: 'Smacznego!' },
        { phrase: 'Tout était délicieux!', translation: 'Wszystko było pyszne!' },
        { phrase: 'Mon plat est froid.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Ce n\'est pas ce que j\'ai commandé.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'L\'addition, s\'il vous plaît.', translation: 'Rachunek, proszę.' },
        { phrase: 'Pouvons-nous payer séparément?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Le service est-il inclus?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Gardez la monnaie.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Où sont les toilettes?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Je prendrai la même chose.', translation: 'Wezmę to samo.' },
        { phrase: 'Pouvez-vous recommander un plat local?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: 'Quelles sont vos heures d\'ouverture?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: 'Avez-vous une chaise haute pour enfant?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Je peux l\'emporter?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
  },
  es: {
    restaurant: {
      title: 'En el Restaurante',
      phrases: [
        { phrase: 'Una mesa para dos, por favor.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Quisiera reservar una mesa.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: '¿Puedo ver el menú, por favor?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: '¿Qué me recomienda?', translation: 'Co mi pan/pani poleca?' },
        { phrase: 'Quisiera pedir...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: '¿Cuál es la sopa del día?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Soy vegetariano/a.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Soy alérgico/a a las nueces.', translation: 'Mam alergię na orzechy.' },
        { phrase: '¿Este plato es picante?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Un vaso de agua, por favor.', translation: 'Poproszę szklankę wody.' },
        { phrase: 'Otra copa de vino, por favor.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: '¿Cuánto tiempo tendremos que esperar?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: '¡Buen provecho!', translation: 'Smacznego!' },
        { phrase: '¡Todo estaba delicioso!', translation: 'Wszystko było pyszne!' },
        { phrase: 'Mi comida está fría.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Esto no es lo que pedí.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'La cuenta, por favor.', translation: 'Rachunek, proszę.' },
        { phrase: '¿Podemos pagar por separado?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: '¿El servicio está incluido?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Quédese con el cambio.', translation: 'Reszty nie trzeba.' },
        { phrase: '¿Dónde está el baño?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Tomaré lo mismo.', translation: 'Wezmę to samo.' },
        { phrase: '¿Puede recomendar un plato local?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: '¿Cuál es su horario?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: '¿Tiene una silla alta para niños?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: '¿Me lo puede poner para llevar?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
  },
  it: {
    restaurant: {
      title: 'Al Ristorante',
      phrases: [
        { phrase: 'Un tavolo per due, per favore.', translation: 'Stolik dla dwojga, proszę.' },
        { phrase: 'Vorrei prenotare un tavolo.', translation: 'Chciałbym/Chciałabym zarezerwować stolik.' },
        { phrase: 'Posso vedere il menu, per favore?', translation: 'Czy mogę zobaczyć menu?' },
        { phrase: 'Cosa ci consiglia?', translation: 'Co nam Pan/Pani poleca?' },
        { phrase: 'Vorrei ordinare...', translation: 'Chciałbym/Chciałabym zamówić...' },
        { phrase: 'Qual è la zuppa del giorno?', translation: 'Jaka jest zupa dnia?' },
        { phrase: 'Sono vegetariano/a.', translation: 'Jestem wegetarianinem/wegetarianką.' },
        { phrase: 'Sono allergico/a alle noci.', translation: 'Mam alergię na orzechy.' },
        { phrase: 'Questo piatto è piccante?', translation: 'Czy to danie jest ostre?' },
        { phrase: 'Un po\' d\'acqua, per favore.', translation: 'Poproszę trochę wody.' },
        { phrase: 'Un altro bicchiere di vino, per favore.', translation: 'Jeszcze jeden kieliszek wina, proszę.' },
        { phrase: 'Quanto dovremo aspettare?', translation: 'Jak długo będziemy musieli czekać?' },
        { phrase: 'Buon appetito!', translation: 'Smacznego!' },
        { phrase: 'Era tutto delizioso!', translation: 'Wszystko było pyszne!' },
        { phrase: 'Il mio piatto è freddo.', translation: 'Moje jedzenie jest zimne.' },
        { phrase: 'Non è quello che ho ordinato.', translation: 'To nie jest to, co zamawiałem/am.' },
        { phrase: 'Il conto, per favore.', translation: 'Rachunek, proszę.' },
        { phrase: 'Possiamo pagare separatamente?', translation: 'Czy możemy zapłacić osobno?' },
        { phrase: 'Il servizio è incluso?', translation: 'Czy obsługa jest wliczona w cenę?' },
        { phrase: 'Tenga il resto.', translation: 'Reszty nie trzeba.' },
        { phrase: 'Dov\'è il bagno?', translation: 'Gdzie jest toaleta?' },
        { phrase: 'Prendo lo stesso.', translation: 'Wezmę to samo.' },
        { phrase: 'Può consigliare un piatto locale?', translation: 'Czy może pan/pani polecić lokalne danie?' },
        { phrase: 'Qual è il vostro orario di apertura?', translation: 'W jakich godzinach jest otwarte?' },
        { phrase: 'Avete un seggiolone per bambini?', translation: 'Czy macie krzesełko dla dziecka?' },
        { phrase: 'Posso prenderlo da asporto?', translation: 'Czy mogę to wziąć na wynos?' }
      ]
    },
  },
};
