
import type { PhrasesContent } from './phrases';

export const partyPhrases: PhrasesContent = {
  en: {
    party: {
        title: 'Party',
        phrases: [
            { phrase: 'Thanks for inviting me.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Pleased to meet you.', translation: 'Miło mi cię poznać.' },
            { phrase: 'Cheers!', translation: 'Na zdrowie!' },
            { phrase: 'It\'s a great party!', translation: 'To świetna impreza!' },
            { phrase: 'Do you want to dance?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'I love this song!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'This is delicious!', translation: 'To jest pyszne!' },
            { phrase: 'I\'m having a great time.', translation: 'Świetnie się bawię.' },
            { phrase: 'Can I get you a drink?', translation: 'Mogę ci przynieść coś do picia?' },
            { phrase: 'What do you do for a living?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Congratulations!', translation: 'Gratulacje!' },
            { phrase: 'Happy birthday!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'I really like your outfit.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'The atmosphere is amazing.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Let\'s take a picture.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Could you pass me the snacks?', translation: 'Czy możesz podać mi przekąski?' },
            { phrase: 'What are you drinking?', translation: 'Co pijesz?' },
            { phrase: 'I have to go now, thanks for everything.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Let\'s keep in touch.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'See you next time!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'Shall we go outside for some fresh air?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'The music is a bit too loud.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'This place is beautiful.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Who is the DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Is it okay if I smoke here?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'I\'ll be right back.', translation: 'Zaraz wracam.' }
        ]
    },
  },
  de: {
    party: {
        title: 'Auf einer Party',
        phrases: [
            { phrase: 'Danke für die Einladung.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Freut mich, dich kennenzulernen.', translation: 'Miło mi cię poznać.' },
            { phrase: 'Prost!', translation: 'Na zdrowie!' },
            { phrase: 'Das ist eine tolle Party!', translation: 'To świetna impreza!' },
            { phrase: 'Möchtest du tanzen?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'Ich liebe dieses Lied!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'Das ist köstlich!', translation: 'To jest pyszne!' },
            { phrase: 'Ich amüsiere mich prächtig.', translation: 'Świetnie się bawię.' },
            { phrase: 'Soll ich dir etwas zu trinken holen?', translation: 'Przynieść ci coś do picia?' },
            { phrase: 'Was machst du beruflich?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Herzlichen Glückwunsch!', translation: 'Gratulacje!' },
            { phrase: 'Alles Gute zum Geburtstag!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'Dein Outfit gefällt mir sehr.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'Die Atmosphäre ist super.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Machen wir ein Foto.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Könntest du mir die Snacks reichen?', translation: 'Czy możesz podać mi przekąski?' },
            { phrase: 'Was trinkst du?', translation: 'Co pijesz?' },
            { phrase: 'Ich muss jetzt gehen, danke für alles.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Lass uns in Kontakt bleiben.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'Bis zum nächsten Mal!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'Wollen wir kurz an die frische Luft gehen?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'Die Musik ist ein bisschen zu laut.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Dieser Ort ist wunderschön.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Wer ist der DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Ist es in Ordnung, wenn ich hier rauche?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Ich bin gleich wieder da.', translation: 'Zaraz wracam.' }
        ]
    },
  },
  fr: {
    party: {
        title: 'À une Fête',
        phrases: [
            { phrase: 'Merci pour l\'invitation.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Enchanté(e).', translation: 'Miło mi cię poznać.' },
            { phrase: 'Santé!', translation: 'Na zdrowie!' },
            { phrase: 'C\'est une super soirée!', translation: 'To świetna impreza!' },
            { phrase: 'Tu veux danser?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'J\'adore cette chanson!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'C\'est délicieux!', translation: 'To jest pyszne!' },
            { phrase: 'Je m\'amuse beaucoup.', translation: 'Świetnie się bawię.' },
            { phrase: 'Je peux t\'offrir un verre?', translation: 'Mogę ci postawić drinka?' },
            { phrase: 'Qu\'est-ce que tu fais dans la vie?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Félicitations!', translation: 'Gratulacje!' },
            { phrase: 'Joyeux anniversaire!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'J\'aime beaucoup ta tenue.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'L\'ambiance est géniale.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'On fait une photo.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Tu peux me passer les chips?', translation: 'Czy możesz podać mi chipsy?' },
            { phrase: 'Qu\'est-ce que tu bois?', translation: 'Co pijesz?' },
            { phrase: 'Je dois y aller, merci pour tout.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'On reste en contact.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'À la prochaine!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'On va prendre l\'air?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'La musique est un peu trop forte.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Cet endroit est magnifique.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Qui est le DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Ça ne dérange pas si je fume ici?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Je reviens tout de suite.', translation: 'Zaraz wracam.' }
        ]
    },
  },
  es: {
    party: {
        title: 'En una Fiesta',
        phrases: [
            { phrase: 'Gracias por invitarme.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Encantado/a de conocerte.', translation: 'Miło mi cię poznać.' },
            { phrase: '¡Salud!', translation: 'Na zdrowie!' },
            { phrase: '¡Es una fiesta genial!', translation: 'To świetna impreza!' },
            { phrase: '¿Quieres bailar?', translation: 'Chcesz zatańczyć?' },
            { phrase: '¡Me encanta esta canción!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: '¡Esto está delicioso!', translation: 'To jest pyszne!' },
            { phrase: 'Me lo estoy pasando genial.', translation: 'Świetnie się bawię.' },
            { phrase: '¿Te traigo algo de beber?', translation: 'Przynieść ci coś do picia?' },
            { phrase: '¿A qué te dedicas?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: '¡Enhorabuena! / ¡Felicidades!', translation: 'Gratulacje!' },
            { phrase: '¡Feliz cumpleaños!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'Me gusta mucho tu ropa.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'El ambiente es increíble.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Vamos a hacernos una foto.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: '¿Me pasas los aperitivos?', translation: 'Czy możesz podać mi przekąski?' },
            { phrase: '¿Qué estás bebiendo?', translation: 'Co pijesz?' },
            { phrase: 'Tengo que irme ya, gracias por todo.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Seguimos en contacto.', translation: 'Bądźmy w kontakcie.' },
            { phrase: '¡Hasta la próxima!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: '¿Salimos a tomar el aire?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'La música está un poco alta.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Este lugar es precioso.', translation: 'To miejsce jest piękne.' },
            { phrase: '¿Quién es el DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: '¿Te importa si fumo aquí?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Ahora vuelvo.', translation: 'Zaraz wracam.' }
        ]
    },
  },
  it: {
    party: {
        title: 'A una Festa',
        phrases: [
            { phrase: 'Grazie per l\'invito.', translation: 'Dziękuję za zaproszenie.' },
            { phrase: 'Piacere di conoscerti.', translation: 'Miło mi cię poznać.' },
            { phrase: 'Salute! / Cin cin!', translation: 'Na zdrowie!' },
            { phrase: 'È una festa fantastica!', translation: 'To świetna impreza!' },
            { phrase: 'Vuoi ballare?', translation: 'Chcesz zatańczyć?' },
            { phrase: 'Adoro questa canzone!', translation: 'Uwielbiam tę piosenkę!' },
            { phrase: 'È delizioso!', translation: 'To jest pyszne!' },
            { phrase: 'Mi sto divertendo un mondo.', translation: 'Świetnie się bawię.' },
            { phrase: 'Posso offrirti da bere?', translation: 'Mogę ci postawić drinka?' },
            { phrase: 'Cosa fai nella vita?', translation: 'Czym się zajmujesz zawodowo?' },
            { phrase: 'Congratulazioni!', translation: 'Gratulacje!' },
            { phrase: 'Buon compleanno!', translation: 'Wszystkiego najlepszego z okazji urodzin!' },
            { phrase: 'Mi piace molto come sei vestito/a.', translation: 'Bardzo podoba mi się twój strój.' },
            { phrase: 'L\'atmosfera è fantastica.', translation: 'Atmosfera jest niesamowita.' },
            { phrase: 'Facciamoci una foto.', translation: 'Zróbmy sobie zdjęcie.' },
            { phrase: 'Mi passi le patatine?', translation: 'Czy możesz podać mi chipsy?' },
            { phrase: 'Cosa stai bevendo?', translation: 'Co pijesz?' },
            { phrase: 'Devo andare ora, grazie di tutto.', translation: 'Muszę już iść, dziękuję za wszystko.' },
            { phrase: 'Rimaniamo in contatto.', translation: 'Bądźmy w kontakcie.' },
            { phrase: 'Alla prossima!', translation: 'Do zobaczenia następnym razem!' },
            { phrase: 'Andiamo fuori a prendere una boccata d\'aria?', translation: 'Wyjdziemy na zewnątrz zaczerpnąć świeżego powietrza?' },
            { phrase: 'La musica è un po\' troppo alta.', translation: 'Muzyka jest trochę za głośna.' },
            { phrase: 'Questo posto è bellissimo.', translation: 'To miejsce jest piękne.' },
            { phrase: 'Chi è il DJ?', translation: 'Kto jest DJ-em?' },
            { phrase: 'Ti dispiace se fumo qui?', translation: 'Czy mogę tu zapalić?' },
            { phrase: 'Torno subito.', translation: 'Zaraz wracam.' }
        ]
    },
  },
};
