
export interface IrregularVerbQuestion {
  id: number;
  verb: string;
  participle: string;
  auxiliary: 'avoir' | 'être';
  translationOptions: string[];
  correctTranslation: string;
}

export const questions: IrregularVerbQuestion[] = [
  { id: 1, verb: 'être', participle: 'été', auxiliary: 'avoir', translationOptions: ['być', 'mieć', 'robić'], correctTranslation: 'być' },
  { id: 2, verb: 'avoir', participle: 'eu', auxiliary: 'avoir', translationOptions: ['dawać', 'brać', 'mieć'], correctTranslation: 'mieć' },
  { id: 3, verb: 'aller', participle: 'allé', auxiliary: 'être', translationOptions: ['iść, jechać', 'przychodzić', 'biec'], correctTranslation: 'iść, jechać' },
  { id: 4, verb: 'faire', participle: 'fait', auxiliary: 'avoir', translationOptions: ['robić', 'mówić', 'widzieć'], correctTranslation: 'robić' },
  { id: 5, verb: 'dire', participle: 'dit', auxiliary: 'avoir', translationOptions: ['słuchać', 'pisać', 'mówić'], correctTranslation: 'mówić' },
  { id: 6, verb: 'pouvoir', participle: 'pu', auxiliary: 'avoir', translationOptions: ['chcieć', 'móc', 'musieć'], correctTranslation: 'móc' },
  { id: 7, verb: 'prendre', participle: 'pris', auxiliary: 'avoir', translationOptions: ['dawać', 'brać', 'przynosić'], correctTranslation: 'brać' },
  { id: 8, verb: 'venir', participle: 'venu', auxiliary: 'être', translationOptions: ['przychodzić', 'wychodzić', 'zostawać'], correctTranslation: 'przychodzić' },
  { id: 9, verb: 'voir', participle: 'vu', auxiliary: 'avoir', translationOptions: ['słyszeć', 'patrzeć', 'widzieć'], correctTranslation: 'widzieć' },
  { id: 10, verb: 'savoir', participle: 'su', auxiliary: 'avoir', translationOptions: ['myśleć', 'wiedzieć', 'ignorować'], correctTranslation: 'wiedzieć' },
  { id: 11, verb: 'vouloir', participle: 'voulu', auxiliary: 'avoir', translationOptions: ['potrzebować', 'chcieć', 'lubić'], correctTranslation: 'chcieć' },
  { id: 12, verb: 'mettre', participle: 'mis', auxiliary: 'avoir', translationOptions: ['kłaść, wkładać', 'wyjmować', 'przesuwać'], correctTranslation: 'kłaść, wkładać' },
  { id: 13, verb: 'donner', participle: 'donné', auxiliary: 'avoir', translationOptions: ['brać', 'dawać', 'otrzymywać'], correctTranslation: 'dawać' },
  { id: 14, verb: 'tenir', participle: 'tenu', auxiliary: 'avoir', translationOptions: ['trzymać', 'puszczać', 'upuszczać'], correctTranslation: 'trzymać' },
  { id: 15, verb: 'parler', participle: 'parlé', auxiliary: 'avoir', translationOptions: ['mówić', 'milczeć', 'słuchać'], correctTranslation: 'mówić' },
  { id: 16, verb: 'trouver', participle: 'trouvé', auxiliary: 'avoir', translationOptions: ['znaleźć', 'zgubić', 'szukać'], correctTranslation: 'znaleźć' },
  { id: 17, verb: 'rendre', participle: 'rendu', auxiliary: 'avoir', translationOptions: ['oddawać', 'pożyczać', 'brać'], correctTranslation: 'oddawać' },
  { id: 18, verb: 'partir', participle: 'parti', auxiliary: 'être', translationOptions: ['wyjechać', 'przyjeżdżać', 'zostawać'], correctTranslation: 'wyjechać' },
  { id: 19, verb: 'sortir', participle: 'sorti', auxiliary: 'être', translationOptions: ['wychodzić', 'wchodzić', 'zostawać'], correctTranslation: 'wychodzić' },
  { id: 20, verb: 'arriver', participle: 'arrivé', auxiliary: 'être', translationOptions: ['wyjeżdżać', 'przybywać', 'odjeżdżać'], correctTranslation: 'przybywać' },
  { id: 21, verb: 'entrer', participle: 'entré', auxiliary: 'être', translationOptions: ['wchodzić', 'wychodzić', 'czekać'], correctTranslation: 'wchodzić' },
  { id: 22, verb: 'rester', participle: 'resté', auxiliary: 'être', translationOptions: ['odchodzić', 'zostawać', 'wracać'], correctTranslation: 'zostawać' },
  { id: 23, verb: 'tomber', participle: 'tombé', auxiliary: 'être', translationOptions: ['upaść', 'wstać', 'skakać'], correctTranslation: 'upaść' },
  { id: 24, verb: 'devenir', participle: 'devenu', auxiliary: 'être', translationOptions: ['być', 'stawać się', 'pozostawać'], correctTranslation: 'stawać się' },
  { id: 25, verb: 'revenir', participle: 'revenu', auxiliary: 'être', translationOptions: ['wrócić', 'wyjechać', 'odejść'], correctTranslation: 'wrócić' },
  { id: 26, verb: 'croire', participle: 'cru', auxiliary: 'avoir', translationOptions: ['wątpić', 'wierzyć', 'wiedzieć'], correctTranslation: 'wierzyć' },
  { id: 27, verb: 'penser', participle: 'pensé', auxiliary: 'avoir', translationOptions: ['czuć', 'wiedzieć', 'myśleć'], correctTranslation: 'myśleć' },
  { id: 28, verb: 'passer', participle: 'passé', auxiliary: 'avoir', translationOptions: ['spędzać, przechodzić', 'zatrzymać się', 'zostawać'], correctTranslation: 'spędzać, przechodzić' },
  { id: 29, verb: 'laisser', participle: 'laissé', auxiliary: 'avoir', translationOptions: ['pozwalać, zostawiać', 'brać', 'zabraniać'], correctTranslation: 'pozwalać, zostawiać' },
  { id: 30, verb: 'sembler', participle: 'semblé', auxiliary: 'avoir', translationOptions: ['być pewnym', 'wydawać się', 'wiedzieć'], correctTranslation: 'wydawać się' },
  { id: 31, verb: 'porter', participle: 'porté', auxiliary: 'avoir', translationOptions: ['nosić', 'zdejmować', 'przymierzać'], correctTranslation: 'nosić' },
  { id: 32, verb: 'suivre', participle: 'suivi', auxiliary: 'avoir', translationOptions: ['podążać', 'prowadzić', 'zatrzymywać się'], correctTranslation: 'podążać' },
  { id: 33, verb: 'connaître', participle: 'connu', auxiliary: 'avoir', translationOptions: ['znać', 'uczyć się', 'zapominać'], correctTranslation: 'znać' },
  { id: 34, verb: 'vivre', participle: 'vécu', auxiliary: 'avoir', translationOptions: ['umierać', 'żyć', 'przeżyć'], correctTranslation: 'żyć' },
  { id: 35, verb: 'sentir', participle: 'senti', auxiliary: 'avoir', translationOptions: ['dotykać', 'patrzeć', 'czuć'], correctTranslation: 'czuć' },
  { id: 36, verb: 'écouter', participle: 'écouté', auxiliary: 'avoir', translationOptions: ['mówić', 'słuchać', 'ignorować'], correctTranslation: 'słuchać' },
  { id: 37, verb: 'entendre', participle: 'entendu', auxiliary: 'avoir', translationOptions: ['słyszeć', 'widzieć', 'mówić'], correctTranslation: 'słyszeć' },
  { id: 38, verb: 'perdre', participle: 'perdu', auxiliary: 'avoir', translationOptions: ['znajdować', 'tracić', 'wygrywać'], correctTranslation: 'tracić' },
  { id: 39, verb: 'ouvrir', participle: 'ouvert', auxiliary: 'avoir', translationOptions: ['zamykać', 'otwierać', 'pukać'], correctTranslation: 'otwierać' },
  { id: 40, verb: 'fermer', participle: 'fermé', auxiliary: 'avoir', translationOptions: ['otwierać', 'zamykać', 'łamać'], correctTranslation: 'zamykać' },
  { id: 41, verb: 'apprendre', participle: 'appris', auxiliary: 'avoir', translationOptions: ['uczyć się', 'uczyć kogoś', 'zapominać'], correctTranslation: 'uczyć się' },
  { id: 42, verb: 'comprendre', participle: 'compris', auxiliary: 'avoir', translationOptions: ['rozumieć', 'mylić', 'ignorować'], correctTranslation: 'rozumieć' },
  { id: 43, verb: 'écrire', participle: 'écrit', auxiliary: 'avoir', translationOptions: ['czytać', 'pisać', 'rysować'], correctTranslation: 'pisać' },
  { id: 44, verb: 'lire', participle: 'lu', auxiliary: 'avoir', translationOptions: ['pisać', 'słuchać', 'czytać'], correctTranslation: 'czytać' },
  { id: 45, verb: 'boire', participle: 'bu', auxiliary: 'avoir', translationOptions: ['jeść', 'pić', 'spać'], correctTranslation: 'pić' },
  { id: 46, verb: 'manger', participle: 'mangé', auxiliary: 'avoir', translationOptions: ['pić', 'głodować', 'jeść'], correctTranslation: 'jeść' },
  { id: 47, verb: 'recevoir', participle: 'reçu', auxiliary: 'avoir', translationOptions: ['dawać', 'wysyłać', 'otrzymywać'], correctTranslation: 'otrzymywać' },
  { id: 48, verb: 'répondre', participle: 'répondu', auxiliary: 'avoir', translationOptions: ['pytać', 'odpowiadać', 'milczeć'], correctTranslation: 'odpowiadać' },
  { id: 49, verb: 'attendre', participle: 'attendu', auxiliary: 'avoir', translationOptions: ['iść', 'odchodzić', 'czekać'], correctTranslation: 'czekać' },
  { id: 50, verb: 'chercher', participle: 'cherché', auxiliary: 'avoir', translationOptions: ['znaleźć', 'gubić', 'szukać'], correctTranslation: 'szukać' },
  { id: 51, verb: 'exister', participle: 'existé', auxiliary: 'avoir', translationOptions: ['znikać', 'istnieć', 'tworzyć'], correctTranslation: 'istnieć' },
  { id: 52, verb: 'jouer', participle: 'joué', auxiliary: 'avoir', translationOptions: ['pracować', 'uczyć się', 'grać'], correctTranslation: 'grać' },
  { id: 53, verb: 'marcher', participle: 'marché', auxiliary: 'avoir', translationOptions: ['biegać', 'stać', 'chodzić'], correctTranslation: 'chodzić' },
  { id: 54, verb: 'travailler', participle: 'travaillé', auxiliary: 'avoir', translationOptions: ['odpoczywać', 'pracować', 'bawić się'], correctTranslation: 'pracować' },
  { id: 55, verb: 'appeler', participle: 'appelé', auxiliary: 'avoir', translationOptions: ['odbierać', 'dzwonić', 'pisać'], correctTranslation: 'dzwonić' },
  { id: 56, verb: 'changer', participle: 'changé', auxiliary: 'avoir', translationOptions: ['zmieniać', 'zostawać', 'trwać'], correctTranslation: 'zmieniać' },
  { id: 57, verb: 'utiliser', participle: 'utilisé', auxiliary: 'avoir', translationOptions: ['używać', 'marnować', 'naprawiać'], correctTranslation: 'używać' },
  { id: 58, verb: 'montrer', participle: 'montré', auxiliary: 'avoir', translationOptions: ['ukrywać', 'pokazywać', 'patrzeć'], correctTranslation: 'pokazywać' },
  { id: 59, verb: 'aimer', participle: 'aimé', auxiliary: 'avoir', translationOptions: ['nienawidzić', 'lubić, kochać', 'ignorować'], correctTranslation: 'lubić, kochać' },
  { id: 60, verb: 'détester', participle: 'détesté', auxiliary: 'avoir', translationOptions: ['uwielbiać', 'nienawidzić', 'tolerować'], correctTranslation: 'nienawidzić' },
  { id: 61, verb: 'naître', participle: 'né', auxiliary: 'être', translationOptions: ['umierać', 'żyć', 'urodzić się'], correctTranslation: 'urodzić się' },
  { id: 62, verb: 'mourir', participle: 'mort', auxiliary: 'être', translationOptions: ['żyć', 'urodzić się', 'umrzeć'], correctTranslation: 'umrzeć' },
  { id: 63, verb: 'descendre', participle: 'descendu', auxiliary: 'être', translationOptions: ['wchodzić', 'schodzić', 'wspinać się'], correctTranslation: 'schodzić' },
  { id: 64, verb: 'monter', participle: 'monté', auxiliary: 'être', translationOptions: ['schodzić', 'wchodzić', 'spadać'], correctTranslation: 'wchodzić' },
  { id: 65, verb: 'retourner', participle: 'retourné', auxiliary: 'être', translationOptions: ['odchodzić', 'wracać', 'zostawać'], correctTranslation: 'wracać' },
  { id: 66, verb: 'rentrer', participle: 'rentré', auxiliary: 'être', translationOptions: ['wyjść', 'wrócić (do domu)', 'podróżować'], correctTranslation: 'wrócić (do domu)' },
  { id: 67, verb: 'reconnaître', participle: 'reconnu', auxiliary: 'avoir', translationOptions: ['zapominać', 'rozpoznać', 'ignorować'], correctTranslation: 'rozpoznać' },
  { id: 68, verb: 'choisir', participle: 'choisi', auxiliary: 'avoir', translationOptions: ['wybierać', 'odrzucać', 'wahać się'], correctTranslation: 'wybierać' },
  { id: 69, verb: 'dormir', participle: 'dormi', auxiliary: 'avoir', translationOptions: ['budzić się', 'spać', 'odpoczywać'], correctTranslation: 'spać' },
  { id: 70, verb: 'courir', participle: 'couru', auxiliary: 'avoir', translationOptions: ['chodzić', 'stać', 'biec'], correctTranslation: 'biec' },
  { id: 71, verb: 'finir', participle: 'fini', auxiliary: 'avoir', translationOptions: ['zaczynać', 'kończyć', 'kontynuować'], correctTranslation: 'kończyć' },
  { id: 72, verb: 'gagner', participle: 'gagné', auxiliary: 'avoir', translationOptions: ['przegrywać', 'wygrywać', 'remisować'], correctTranslation: 'wygrywać' },
  { id: 73, verb: 'permettre', participle: 'permis', auxiliary: 'avoir', translationOptions: ['zabraniać', 'nakazywać', 'pozwalać'], correctTranslation: 'pozwalać' },
  { id: 74, verb: 'refuser', participle: 'refusé', auxiliary: 'avoir', translationOptions: ['zgadzać się', 'odmawiać', 'prosić'], correctTranslation: 'odmawiać' },
  { id: 75, verb: 'accepter', participle: 'accepté', auxiliary: 'avoir', translationOptions: ['odrzucać', 'akceptować', 'negocjować'], correctTranslation: 'akceptować' },
  { id: 76, verb: 'décider', participle: 'décidé', auxiliary: 'avoir', translationOptions: ['wahać się', 'zdecydować', 'myśleć'], correctTranslation: 'zdecydować' },
  { id: 77, verb: 'oublier', participle: 'oublié', auxiliary: 'avoir', translationOptions: ['pamiętać', 'zapomnieć', 'uczyć się'], correctTranslation: 'zapomnieć' },
  { id: 78, verb: 'préparer', participle: 'préparé', auxiliary: 'avoir', translationOptions: ['niszczyć', 'przygotować', 'kończyć'], correctTranslation: 'przygotować' },
  { id: 79, verb: 'payer', participle: 'payé', auxiliary: 'avoir', translationOptions: ['otrzymywać', 'płacić', 'oszczędzać'], correctTranslation: 'płacić' },
  { id: 80, verb: 'acheter', participle: 'acheté', auxiliary: 'avoir', translationOptions: ['sprzedawać', 'kupować', 'wymieniać'], correctTranslation: 'kupować' },
  { id: 81, verb: 'vendre', participle: 'vendu', auxiliary: 'avoir', translationOptions: ['kupować', 'sprzedawać', 'pożyczać'], correctTranslation: 'sprzedawać' },
  { id: 82, verb: 'couper', participle: 'coupé', auxiliary: 'avoir', translationOptions: ['kleić', 'ciąć', 'łączyć'], correctTranslation: 'ciąć' },
  { id: 83, verb: 'tirer', participle: 'tiré', auxiliary: 'avoir', translationOptions: ['pchać', 'ciągnąć', 'nosić'], correctTranslation: 'ciągnąć' },
  { id: 84, verb: 'quitter', participle: 'quitté', auxiliary: 'avoir', translationOptions: ['zostawać', 'przybywać', 'opuszczać'], correctTranslation: 'opuszczać' },
  { id: 85, verb: 'rire', participle: 'ri', auxiliary: 'avoir', translationOptions: ['płakać', 'śmiać się', 'krzyczeć'], correctTranslation: 'śmiać się' },
  { id: 86, verb: 'pleurer', participle: 'pleuré', auxiliary: 'avoir', translationOptions: ['śmiać się', 'płakać', 'cieszyć się'], correctTranslation: 'płakać' },
  { id: 87, verb: 'servir', participle: 'servi', auxiliary: 'avoir', translationOptions: ['brać', 'zamawiać', 'służyć/podawać'], correctTranslation: 'służyć/podawać' },
  { id: 88, verb: 'offrir', participle: 'offert', auxiliary: 'avoir', translationOptions: ['odbierać', 'oferować/dawać', 'prosić'], correctTranslation: 'oferować/dawać' },
  { id: 89, verb: 'couvrir', participle: 'couvert', auxiliary: 'avoir', translationOptions: ['odkrywać', 'przykrywać', 'pokazywać'], correctTranslation: 'przykrywać' },
  { id: 90, verb: 'fuir', participle: 'fui', auxiliary: 'avoir', translationOptions: ['ścigać', 'zostawać', 'uciekać'], correctTranslation: 'uciekać' },
  { id: 91, verb: 'joindre', participle: 'joint', auxiliary: 'avoir', translationOptions: ['rozdzielać', 'dołączać', 'opuszczać'], correctTranslation: 'dołączać' },
  { id: 92, verb: 'craindre', participle: 'craint', auxiliary: 'avoir', translationOptions: ['odważyć się', 'obawiać się', 'ignorować'], correctTranslation: 'obawiać się' },
  { id: 93, verb: 'peindre', participle: 'peint', auxiliary: 'avoir', translationOptions: ['rysować', 'malować', 'wymazywać'], correctTranslation: 'malować' },
  { id: 94, verb: 'vaincre', participle: 'vaincu', auxiliary: 'avoir', translationOptions: ['poddawać się', 'zwyciężać', 'walczyć'], correctTranslation: 'zwyciężać' },
  { id: 95, verb: 'résoudre', participle: 'résolu', auxiliary: 'avoir', translationOptions: ['tworzyć problem', 'rozwiązać', 'unikać'], correctTranslation: 'rozwiązać' },
  { id: 96, verb: 'conduire', participle: 'conduit', auxiliary: 'avoir', translationOptions: ['chodzić pieszo', 'prowadzić (pojazd)', 'być pasażerem'], correctTranslation: 'prowadzić (pojazd)' },
  { id: 97, verb: 'découvrir', participle: 'découvert', auxiliary: 'avoir', translationOptions: ['zakrywać', 'gubić', 'odkrywać'], correctTranslation: 'odkrywać' },
  { id: 98, verb: 'envoyer', participle: 'envoyé', auxiliary: 'avoir', translationOptions: ['odbierać', 'wysyłać', 'przynosić'], correctTranslation: 'wysyłać' },
  { id: 99, verb: 'réussir', participle: 'réussi', auxiliary: 'avoir', translationOptions: ['próbować', 'udać się', 'ponieść porażkę'], correctTranslation: 'udać się' },
  { id: 100, verb: 'battre', participle: 'battu', auxiliary: 'avoir', translationOptions: ['przegrywać', 'poddawać się', 'bić'], correctTranslation: 'bić' },
  { id: 101, verb: 'souffrir', participle: 'souffert', auxiliary: 'avoir', translationOptions: ['cieszyć się', 'cierpieć', 'unikać'], correctTranslation: 'cierpieć' }
];
