export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Polish', word: 'Cześć', options: ['Goodbye', 'Hello', 'Thank you', 'Sorry'], correctAnswer: 'Hello' },
  { id: 2, language: 'Polish', word: 'Do widzenia', options: ['Hello', 'Good morning', 'Good night', 'Goodbye'], correctAnswer: 'Goodbye' },
  { id: 3, language: 'Polish', word: 'Dziękuję', options: ['Please', 'You\'re welcome', 'Thank you', 'Sorry'], correctAnswer: 'Thank you' },
  { id: 4, language: 'Polish', word: 'Tak', options: ['Yes', 'No', 'Maybe', 'Always'], correctAnswer: 'Yes' },
  { id: 5, language: 'Polish', word: 'Nie', options: ['Good', 'Never', 'Why', 'No'], correctAnswer: 'No' },
  { id: 6, language: 'Polish', word: 'Mężczyzna', options: ['Woman', 'Man', 'Child', 'Person'], correctAnswer: 'Man' },
  { id: 7, language: 'Polish', word: 'Kobieta', options: ['Man', 'Girl', 'Woman', 'Boy'], correctAnswer: 'Woman' },
  { id: 8, language: 'Polish', word: 'Jeść', options: ['To drink', 'To sleep', 'To eat', 'To run'], correctAnswer: 'To eat' },
  { id: 9, language: 'Polish', word: 'Woda', options: ['Fire', 'Water', 'Earth', 'Air'], correctAnswer: 'Water' },
  { id: 10, language: 'Polish', word: 'Kot', options: ['Dog', 'Bird', 'Fish', 'Cat'], correctAnswer: 'Cat' },
  { id: 11, language: 'Polish', word: 'Pies', options: ['Cat', 'Dog', 'Lion', 'Tiger'], correctAnswer: 'Dog' },
  { id: 12, language: 'Polish', word: 'Dom', options: ['Car', 'School', 'House', 'Shop'], correctAnswer: 'House' },
  { id: 13, language: 'Polish', word: 'Samochód', options: ['Bicycle', 'Train', 'Bus', 'Car'], correctAnswer: 'Car' },
  { id: 14, language: 'Polish', word: 'Szkoła', options: ['Hospital', 'School', 'University', 'Library'], correctAnswer: 'School' },
  { id: 15, language: 'Polish', word: 'Książka', options: ['Movie', 'Song', 'Book', 'Painting'], correctAnswer: 'Book' },
  { id: 16, language: 'Polish', word: 'Słońce', options: ['Moon', 'Star', 'Sun', 'Cloud'], correctAnswer: 'Sun' },
  { id: 17, language: 'Polish', word: 'Miłość', options: ['Hate', 'Joy', 'Sadness', 'Love'], correctAnswer: 'Love' },
  { id: 18, language: 'Polish', word: 'Przyjaciel', options: ['Enemy', 'Neighbor', 'Friend', 'Family'], correctAnswer: 'Friend' },
  { id: 19, language: 'Polish', word: 'Rodzina', options: ['Friends', 'Family', 'Relatives', 'Neighbors'], correctAnswer: 'Family' },
  { id: 20, language: 'Polish', word: 'Rano', options: ['Evening', 'Night', 'Afternoon', 'Morning'], correctAnswer: 'Morning' },
  { id: 21, language: 'Polish', word: 'Noc', options: ['Day', 'Night', 'Dusk', 'Dawn'], correctAnswer: 'Night' },
  { id: 22, language: 'Polish', word: 'Dzień', options: ['Week', 'Month', 'Year', 'Day'], correctAnswer: 'Day' },
  { id: 23, language: 'Polish', word: 'Tydzień', options: ['Day', 'Week', 'Weekend', 'Month'], correctAnswer: 'Week' },
  { id: 24, language: 'Polish', word: 'Miesiąc', options: ['Year', 'Century', 'Decade', 'Month'], correctAnswer: 'Month' },
  { id: 25, language: 'Polish', word: 'Rok', options: ['Month', 'Year', 'Day', 'Hour'], correctAnswer: 'Year' },
  { id: 26, language: 'Polish', word: 'Dzisiaj', options: ['Yesterday', 'Tomorrow', 'Today', 'The day after tomorrow'], correctAnswer: 'Today' },
  { id: 27, language: 'Polish', word: 'Jutro', options: ['Today', 'Yesterday', 'The day before yesterday', 'Tomorrow'], correctAnswer: 'Tomorrow' },
  { id: 28, language: 'Polish', word: 'Proszę', options: ['Thank you', 'Please', 'Sorry', 'You\'re welcome'], correctAnswer: 'Please' },
  { id: 29, language: 'Polish', word: 'Jabłko', options: ['Banana', 'Orange', 'Apple', 'Pear'], correctAnswer: 'Apple' },
  { id: 30, language: 'Polish', word: 'Dzień dobry', options: ['Good evening', 'Good night', 'Good morning', 'Hello'], correctAnswer: 'Good morning' },
  { id: 31, language: 'Polish', word: 'Dobry wieczór', options: ['Good morning', 'Good night', 'Good evening', 'Good day'], correctAnswer: 'Good evening' },
  { id: 32, language: 'Polish', word: 'Dobranoc', options: ['Good morning', 'Good evening', 'Good night', 'Goodbye'], correctAnswer: 'Good night' },
  { id: 33, language: 'Polish', word: 'Przepraszam', options: ['Excuse me', 'Thank you', 'Please', 'Hello'], correctAnswer: 'Excuse me' },
  { id: 34, language: 'Polish', word: 'Praca', options: ['Holiday', 'Fun', 'Work', 'School'], correctAnswer: 'Work' },
  { id: 35, language: 'Polish', word: 'Miasto', options: ['Village', 'Country', 'City', 'Street'], correctAnswer: 'City' },
  { id: 36, language: 'Polish', word: 'Jedzenie', options: ['Drink', 'Water', 'Food', 'Bread'], correctAnswer: 'Food' },
  { id: 37, language: 'Polish', word: 'Chleb', options: ['Milk', 'Water', 'Bread', 'Cheese'], correctAnswer: 'Bread' },
  { id: 38, language: 'Polish', word: 'Mleko', options: ['Juice', 'Water', 'Milk', 'Tea'], correctAnswer: 'Milk' },
  { id: 39, language: 'Polish', word: 'Kawa', options: ['Tea', 'Water', 'Coffee', 'Juice'], correctAnswer: 'Coffee' },
  { id: 40, language: 'Polish', word: 'Herbata', options: ['Coffee', 'Milk', 'Tea', 'Water'], correctAnswer: 'Tea' },
  { id: 41, language: 'Polish', word: 'Czas', options: ['Space', 'Place', 'Time', 'Day'], correctAnswer: 'Time' },
  { id: 42, language: 'Polish', word: 'Godzina', options: ['Minute', 'Second', 'Hour', 'Day'], correctAnswer: 'Hour' },
  { id: 43, language: 'Polish', word: 'Wczoraj', options: ['Today', 'Tomorrow', 'Yesterday', 'Now'], correctAnswer: 'Yesterday' },
  { id: 44, language: 'Polish', word: 'Pieniądze', options: ['Gold', 'Silver', 'Money', 'Credit'], correctAnswer: 'Money' },
  { id: 45, language: 'Polish', word: 'Sklep', options: ['Office', 'School', 'Shop', 'House'], correctAnswer: 'Shop' },
  { id: 46, language: 'Polish', word: 'Ulica', options: ['Road', 'Avenue', 'Street', 'Path'], correctAnswer: 'Street' },
  { id: 47, language: 'Polish', word: 'Droga', options: ['Street', 'Path', 'Road', 'Highway'], correctAnswer: 'Road' },
  { id: 48, language: 'Polish', word: 'Matka', options: ['Father', 'Sister', 'Mother', 'Brother'], correctAnswer: 'Mother' },
  { id: 49, language: 'Polish', word: 'Ojciec', options: ['Mother', 'Brother', 'Father', 'Sister'], correctAnswer: 'Father' },
  { id: 50, language: 'Polish', word: 'Dziecko', options: ['Adult', 'Man', 'Woman', 'Child'], correctAnswer: 'Child' },
  { id: 51, language: 'Polish', word: 'Pytanie', options: ['Answer', 'Problem', 'Question', 'Test'], correctAnswer: 'Question' },
  { id: 52, language: 'Polish', word: 'Odpowiedź', options: ['Question', 'Answer', 'Test', 'Solution'], correctAnswer: 'Answer' },
  { id: 53, language: 'Polish', word: 'Problem', options: ['Solution', 'Question', 'Problem', 'Answer'], correctAnswer: 'Problem' },
  { id: 54, language: 'Polish', word: 'Pomoc', options: ['Trouble', 'Help', 'Work', 'Game'], correctAnswer: 'Help' },
  { id: 55, language: 'Polish', word: 'Szybko', options: ['Slowly', 'Fast', 'Quick', 'Loudly'], correctAnswer: 'Fast' },
  { id: 56, language: 'Polish', word: 'Wolno', options: ['Fast', 'Quickly', 'Slowly', 'Quietly'], correctAnswer: 'Slowly' },
  { id: 57, language: 'Polish', word: 'Duży', options: ['Small', 'Big', 'Tall', 'Short'], correctAnswer: 'Big' },
  { id: 58, language: 'Polish', word: 'Mały', options: ['Big', 'Large', 'Small', 'Huge'], correctAnswer: 'Small' },
  { id: 59, language: 'Polish', word: 'Dobry', options: ['Bad', 'Good', 'Nice', 'Great'], correctAnswer: 'Good' },
  { id: 60, language: 'Polish', word: 'Zły', options: ['Good', 'Nice', 'Bad', 'Evil'], correctAnswer: 'Bad' },
  { id: 61, language: 'Polish', word: 'Nowy', options: ['Old', 'New', 'Young', 'Ancient'], correctAnswer: 'New' },
  { id: 62, language: 'Polish', word: 'Stary', options: ['New', 'Young', 'Old', 'Modern'], correctAnswer: 'Old' },
  { id: 63, language: 'Polish', word: 'Ciepły', options: ['Cold', 'Cool', 'Warm', 'Hot'], correctAnswer: 'Warm' },
  { id: 64, language: 'Polish', word: 'Zimny', options: ['Warm', 'Hot', 'Cold', 'Cool'], correctAnswer: 'Cold' },
  { id: 65, language: 'Polish', word: 'Łatwy', options: ['Hard', 'Difficult', 'Easy', 'Simple'], correctAnswer: 'Easy' },
  { id: 66, language: 'Polish', word: 'Trudny', options: ['Easy', 'Simple', 'Hard', 'Light'], correctAnswer: 'Hard' },
  { id: 67, language: 'Polish', word: 'Otwarty', options: ['Closed', 'Shut', 'Open', 'Locked'], correctAnswer: 'Open' },
  { id: 68, language: 'Polish', word: 'Zamknięty', options: ['Open', 'Free', 'Closed', 'Unlocked'], correctAnswer: 'Closed' },
  { id: 69, language: 'Polish', word: 'Jasny', options: ['Dark', 'Black', 'Light', 'Dim'], correctAnswer: 'Light' },
  { id: 70, language: 'Polish', word: 'Ciemny', options: ['Light', 'Bright', 'Dark', 'White'], correctAnswer: 'Dark' },
  { id: 71, language: 'Polish', word: 'Film', options: ['Book', 'Song', 'Movie', 'Picture'], correctAnswer: 'Movie' },
  { id: 72, language: 'Polish', word: 'Muzyka', options: ['Art', 'Film', 'Music', 'Dance'], correctAnswer: 'Music' },
  { id: 73, language: 'Polish', word: 'Kolor', options: ['Shape', 'Size', 'Color', 'Sound'], correctAnswer: 'Color' },
  { id: 74, language: 'Polish', word: 'Czerwony', options: ['Blue', 'Green', 'Red', 'Yellow'], correctAnswer: 'Red' },
  { id: 75, language: 'Polish', word: 'Niebieski', options: ['Green', 'Red', 'Blue', 'Yellow'], correctAnswer: 'Blue' },
  { id: 76, language: 'Polish', word: 'Zielony', options: ['Red', 'Blue', 'Green', 'Yellow'], correctAnswer: 'Green' },
  { id: 77, language: 'Polish', word: 'Żółty', options: ['Red', 'Blue', 'Green', 'Yellow'], correctAnswer: 'Yellow' },
  { id: 78, language: 'Polish', word: 'Biały', options: ['Black', 'Gray', 'White', 'Brown'], correctAnswer: 'White' },
  { id: 79, language: 'Polish', word: 'Czarny', options: ['White', 'Gray', 'Black', 'Brown'], correctAnswer: 'Black' },
  { id: 80, language: 'Polish', word: 'Iść', options: ['To run', 'To go', 'To stand', 'To sit'], correctAnswer: 'To go' },
  { id: 81, language: 'Polish', word: 'Biegać', options: ['To walk', 'To run', 'To jump', 'To swim'], correctAnswer: 'To run' },
  { id: 82, language: 'Polish', word: 'Mówić', options: ['To listen', 'To speak', 'To read', 'To write'], correctAnswer: 'To speak' },
  { id: 83, language: 'Polish', word: 'Widzieć', options: ['To hear', 'To see', 'To touch', 'To smell'], correctAnswer: 'To see' },
  { id: 84, language: 'Polish', word: 'Wiedzieć', options: ['To think', 'To know', 'To learn', 'To forget'], correctAnswer: 'To know' },
  { id: 85, language: 'Polish', word: 'Chcieć', options: ['To need', 'To want', 'To have', 'To like'], correctAnswer: 'To want' },
  { id: 86, language: 'Polish', word: 'Móc', options: ['Must', 'Should', 'Can', 'Will'], correctAnswer: 'Can' },
  { id: 87, language: 'Polish', word: 'Musieć', options: ['Can', 'Should', 'Must', 'May'], correctAnswer: 'Must' },
  { id: 88, language: 'Polish', word: 'Spać', options: ['To wake up', 'To sleep', 'To eat', 'To drink'], correctAnswer: 'To sleep' },
  { id: 89, language: 'Polish', word: 'Myśleć', options: ['To know', 'To think', 'To feel', 'To believe'], correctAnswer: 'To think' },
  { id: 90, language: 'Polish', word: 'Lubić', options: ['To love', 'To hate', 'To like', 'To prefer'], correctAnswer: 'To like' },
  { id: 91, language: 'Polish', word: 'Zawsze', options: ['Never', 'Sometimes', 'Always', 'Often'], correctAnswer: 'Always' },
  { id: 92, language: 'Polish', word: 'Nigdy', options: ['Always', 'Often', 'Never', 'Sometimes'], correctAnswer: 'Never' },
  { id: 93, language: 'Polish', word: 'Często', options: ['Rarely', 'Seldom', 'Often', 'Sometimes'], correctAnswer: 'Often' },
  { id: 94, language: 'Polish', word: 'Rzadko', options: ['Often', 'Always', 'Rarely', 'Never'], correctAnswer: 'Rarely' },
  { id: 95, language: 'Polish', word: 'Tutaj', options: ['There', 'Here', 'Where', 'Everywhere'], correctAnswer: 'Here' },
  { id: 96, language: 'Polish', word: 'Tam', options: ['Here', 'There', 'Near', 'Far'], correctAnswer: 'There' },
  { id: 97, language: 'Polish', word: 'Dlaczego', options: ['What', 'When', 'Why', 'Who'], correctAnswer: 'Why' },
  { id: 98, language: 'Polish', word: 'Ponieważ', options: ['But', 'So', 'Because', 'And'], correctAnswer: 'Because' },
  { id: 99, language: 'Polish', word: 'Ale', options: ['And', 'Or', 'But', 'So'], correctAnswer: 'But' },
  { id: 100, language: 'Polish', word: 'I', options: ['Or', 'But', 'And', 'So'], correctAnswer: 'And' }
];
