export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Polish', word: 'Cześć', options: ['Arrivederci', 'Ciao', 'Grazie', 'Scusa'], correctAnswer: 'Ciao' },
  { id: 2, language: 'Polish', word: 'Do widzenia', options: ['Ciao', 'Buongiorno', 'Buonanotte', 'Arrivederci'], correctAnswer: 'Arrivederci' },
  { id: 3, language: 'Polish', word: 'Dziękuję', options: ['Prego', 'Per favore', 'Grazie', 'Scusa'], correctAnswer: 'Grazie' },
  { id: 4, language: 'Polish', word: 'Tak', options: ['Sì', 'No', 'Forse', 'Sempre'], correctAnswer: 'Sì' },
  { id: 5, language: 'Polish', word: 'Nie', options: ['Bene', 'Mai', 'Perché', 'No'], correctAnswer: 'No' },
  { id: 6, language: 'Polish', word: 'Mężczyzna', options: ['Donna', 'Uomo', 'Bambino', 'Persona'], correctAnswer: 'Uomo' },
  { id: 7, language: 'Polish', word: 'Kobieta', options: ['Uomo', 'Ragazza', 'Donna', 'Ragazzo'], correctAnswer: 'Donna' },
  { id: 8, language: 'Polish', word: 'Jeść', options: ['Bere', 'Dormire', 'Mangiare', 'Correre'], correctAnswer: 'Mangiare' },
  { id: 9, language: 'Polish', word: 'Woda', options: ['Fuoco', 'Acqua', 'Terra', 'Aria'], correctAnswer: 'Acqua' },
  { id: 10, language: 'Polish', word: 'Kot', options: ['Cane', 'Uccello', 'Pesce', 'Gatto'], correctAnswer: 'Gatto' },
  { id: 11, language: 'Polish', word: 'Pies', options: ['Gatto', 'Cane', 'Leone', 'Tigre'], correctAnswer: 'Cane' },
  { id: 12, language: 'Polish', word: 'Dom', options: ['Macchina', 'Scuola', 'Casa', 'Negozio'], correctAnswer: 'Casa' },
  { id: 13, language: 'Polish', word: 'Samochód', options: ['Bicicletta', 'Treno', 'Autobus', 'Macchina'], correctAnswer: 'Macchina' },
  { id: 14, language: 'Polish', word: 'Szkoła', options: ['Ospedale', 'Scuola', 'Università', 'Biblioteca'], correctAnswer: 'Scuola' },
  { id: 15, language: 'Polish', word: 'Książka', options: ['Film', 'Canzone', 'Libro', 'Quadro'], correctAnswer: 'Libro' },
  { id: 16, language: 'Polish', word: 'Słońce', options: ['Luna', 'Stella', 'Sole', 'Nuvola'], correctAnswer: 'Sole' },
  { id: 17, language: 'Polish', word: 'Miłość', options: ['Odio', 'Gioia', 'Tristezza', 'Amore'], correctAnswer: 'Amore' },
  { id: 18, language: 'Polish', word: 'Przyjaciel', options: ['Nemico', 'Vicino', 'Amico', 'Famiglia'], correctAnswer: 'Amico' },
  { id: 19, language: 'Polish', word: 'Rodzina', options: ['Amici', 'Famiglia', 'Parenti', 'Vicini'], correctAnswer: 'Famiglia' },
  { id: 20, language: 'Polish', word: 'Rano', options: ['Sera', 'Notte', 'Pomeriggio', 'Mattina'], correctAnswer: 'Mattina' },
  { id: 21, language: 'Polish', word: 'Noc', options: ['Giorno', 'Notte', 'Crepuscolo', 'Alba'], correctAnswer: 'Notte' },
  { id: 22, language: 'Polish', word: 'Dzień', options: ['Settimana', 'Mese', 'Anno', 'Giorno'], correctAnswer: 'Giorno' },
  { id: 23, language: 'Polish', word: 'Tydzień', options: ['Giorno', 'Settimana', 'Fine settimana', 'Mese'], correctAnswer: 'Settimana' },
  { id: 24, language: 'Polish', word: 'Miesiąc', options: ['Anno', 'Secolo', 'Decennio', 'Mese'], correctAnswer: 'Mese' },
  { id: 25, language: 'Polish', word: 'Rok', options: ['Mese', 'Anno', 'Giorno', 'Ora'], correctAnswer: 'Anno' },
  { id: 26, language: 'Polish', word: 'Dzisiaj', options: ['Ieri', 'Domani', 'Oggi', 'Dopodomani'], correctAnswer: 'Oggi' },
  { id: 27, language: 'Polish', word: 'Jutro', options: ['Oggi', 'Ieri', 'L\'altro ieri', 'Domani'], correctAnswer: 'Domani' },
  { id: 28, language: 'Polish', word: 'Proszę', options: ['Grazie', 'Per favore', 'Scusa', 'Prego'], correctAnswer: 'Per favore' },
  { id: 29, language: 'Polish', word: 'Jabłko', options: ['Banana', 'Arancia', 'Mela', 'Pera'], correctAnswer: 'Mela' },
  { id: 30, language: 'Polish', word: 'Dzień dobry', options: ['Buonasera', 'Buonanotte', 'Buongiorno', 'Ciao'], correctAnswer: 'Buongiorno' },
  { id: 31, language: 'Polish', word: 'Dobry wieczór', options: ['Buongiorno', 'Buonanotte', 'Buonasera', 'Buon pomeriggio'], correctAnswer: 'Buonasera' },
  { id: 32, language: 'Polish', word: 'Dobranoc', options: ['Buongiorno', 'Buonasera', 'Buonanotte', 'Arrivederci'], correctAnswer: 'Buonanotte' },
  { id: 33, language: 'Polish', word: 'Przepraszam', options: ['Grazie', 'Per favore', 'Scusa', 'Ciao'], correctAnswer: 'Scusa' },
  { id: 34, language: 'Polish', word: 'Praca', options: ['Vacanza', 'Divertimento', 'Lavoro', 'Scuola'], correctAnswer: 'Lavoro' },
  { id: 35, language: 'Polish', word: 'Miasto', options: ['Paese', 'Nazione', 'Città', 'Strada'], correctAnswer: 'Città' },
  { id: 36, language: 'Polish', word: 'Jedzenie', options: ['Bevanda', 'Acqua', 'Cibo', 'Pane'], correctAnswer: 'Cibo' },
  { id: 37, language: 'Polish', word: 'Chleb', options: ['Latte', 'Acqua', 'Pane', 'Formaggio'], correctAnswer: 'Pane' },
  { id: 38, language: 'Polish', word: 'Mleko', options: ['Succo', 'Acqua', 'Latte', 'Tè'], correctAnswer: 'Latte' },
  { id: 39, language: 'Polish', word: 'Kawa', options: ['Tè', 'Acqua', 'Caffè', 'Succo'], correctAnswer: 'Caffè' },
  { id: 40, language: 'Polish', word: 'Herbata', options: ['Caffè', 'Latte', 'Tè', 'Acqua'], correctAnswer: 'Tè' },
  { id: 41, language: 'Polish', word: 'Czas', options: ['Spazio', 'Luogo', 'Tempo', 'Giorno'], correctAnswer: 'Tempo' },
  { id: 42, language: 'Polish', word: 'Godzina', options: ['Minuto', 'Secondo', 'Ora', 'Giorno'], correctAnswer: 'Ora' },
  { id: 43, language: 'Polish', word: 'Wczoraj', options: ['Oggi', 'Domani', 'Ieri', 'Adesso'], correctAnswer: 'Ieri' },
  { id: 44, language: 'Polish', word: 'Pieniądze', options: ['Oro', 'Argento', 'Soldi', 'Credito'], correctAnswer: 'Soldi' },
  { id: 45, language: 'Polish', word: 'Sklep', options: ['Ufficio', 'Scuola', 'Negozio', 'Casa'], correctAnswer: 'Negozio' },
  { id: 46, language: 'Polish', word: 'Ulica', options: ['Strada', 'Viale', 'Via', 'Sentiero'], correctAnswer: 'Via' },
  { id: 47, language: 'Polish', word: 'Droga', options: ['Via', 'Sentiero', 'Strada', 'Autostrada'], correctAnswer: 'Strada' },
  { id: 48, language: 'Polish', word: 'Matka', options: ['Padre', 'Sorella', 'Madre', 'Fratello'], correctAnswer: 'Madre' },
  { id: 49, language: 'Polish', word: 'Ojciec', options: ['Madre', 'Fratello', 'Padre', 'Sorella'], correctAnswer: 'Padre' },
  { id: 50, language: 'Polish', word: 'Dziecko', options: ['Adulto', 'Uomo', 'Donna', 'Bambino'], correctAnswer: 'Bambino' },
  { id: 51, language: 'Polish', word: 'Pytanie', options: ['Risposta', 'Problema', 'Domanda', 'Test'], correctAnswer: 'Domanda' },
  { id: 52, language: 'Polish', word: 'Odpowiedź', options: ['Domanda', 'Risposta', 'Test', 'Soluzione'], correctAnswer: 'Risposta' },
  { id: 53, language: 'Polish', word: 'Problem', options: ['Soluzione', 'Domanda', 'Problema', 'Risposta'], correctAnswer: 'Problema' },
  { id: 54, language: 'Polish', word: 'Pomoc', options: ['Guai', 'Aiuto', 'Lavoro', 'Gioco'], correctAnswer: 'Aiuto' },
  { id: 55, language: 'Polish', word: 'Szybko', options: ['Lentamente', 'Veloce', 'Rapido', 'Forte'], correctAnswer: 'Veloce' },
  { id: 56, language: 'Polish', word: 'Wolno', options: ['Veloce', 'Rapido', 'Lento', 'Silenzioso'], correctAnswer: 'Lento' },
  { id: 57, language: 'Polish', word: 'Duży', options: ['Piccolo', 'Grande', 'Alto', 'Basso'], correctAnswer: 'Grande' },
  { id: 58, language: 'Polish', word: 'Mały', options: ['Grande', 'Enorme', 'Piccolo', 'Gigante'], correctAnswer: 'Piccolo' },
  { id: 59, language: 'Polish', word: 'Dobry', options: ['Cattivo', 'Buono', 'Gentile', 'Ottimo'], correctAnswer: 'Buono' },
  { id: 60, language: 'Polish', word: 'Zły', options: ['Buono', 'Gentile', 'Cattivo', 'Male'], correctAnswer: 'Cattivo' },
  { id: 61, language: 'Polish', word: 'Nowy', options: ['Vecchio', 'Nuovo', 'Giovane', 'Antico'], correctAnswer: 'Nuovo' },
  { id: 62, language: 'Polish', word: 'Stary', options: ['Nuovo', 'Giovane', 'Vecchio', 'Moderno'], correctAnswer: 'Vecchio' },
  { id: 63, language: 'Polish', word: 'Ciepły', options: ['Freddo', 'Fresco', 'Caldo', 'Bollente'], correctAnswer: 'Caldo' },
  { id: 64, language: 'Polish', word: 'Zimny', options: ['Caldo', 'Bollente', 'Freddo', 'Fresco'], correctAnswer: 'Freddo' },
  { id: 65, language: 'Polish', word: 'Łatwy', options: ['Duro', 'Difficile', 'Facile', 'Semplice'], correctAnswer: 'Facile' },
  { id: 66, language: 'Polish', word: 'Trudny', options: ['Facile', 'Semplice', 'Difficile', 'Leggero'], correctAnswer: 'Difficile' },
  { id: 67, language: 'Polish', word: 'Otwarty', options: ['Chiuso', 'Serrato', 'Aperto', 'Bloccato'], correctAnswer: 'Aperto' },
  { id: 68, language: 'Polish', word: 'Zamknięty', options: ['Aperto', 'Libero', 'Chiuso', 'Sbloccato'], correctAnswer: 'Chiuso' },
  { id: 69, language: 'Polish', word: 'Jasny', options: ['Scuro', 'Nero', 'Chiaro', 'Tenue'], correctAnswer: 'Chiaro' },
  { id: 70, language: 'Polish', word: 'Ciemny', options: ['Chiaro', 'Luminoso', 'Scuro', 'Bianco'], correctAnswer: 'Scuro' },
  { id: 71, language: 'Polish', word: 'Film', options: ['Libro', 'Canzone', 'Film', 'Quadro'], correctAnswer: 'Film' },
  { id: 72, language: 'Polish', word: 'Muzyka', options: ['Arte', 'Film', 'Musica', 'Danza'], correctAnswer: 'Musica' },
  { id: 73, language: 'Polish', word: 'Kolor', options: ['Forma', 'Dimensione', 'Colore', 'Suono'], correctAnswer: 'Colore' },
  { id: 74, language: 'Polish', word: 'Czerwony', options: ['Blu', 'Verde', 'Rosso', 'Giallo'], correctAnswer: 'Rosso' },
  { id: 75, language: 'Polish', word: 'Niebieski', options: ['Verde', 'Rosso', 'Blu', 'Giallo'], correctAnswer: 'Blu' },
  { id: 76, language: 'Polish', word: 'Zielony', options: ['Rosso', 'Blu', 'Verde', 'Giallo'], correctAnswer: 'Verde' },
  { id: 77, language: 'Polish', word: 'Żółty', options: ['Rosso', 'Blu', 'Verde', 'Giallo'], correctAnswer: 'Giallo' },
  { id: 78, language: 'Polish', word: 'Biały', options: ['Nero', 'Grigio', 'Bianco', 'Marrone'], correctAnswer: 'Bianco' },
  { id: 79, language: 'Polish', word: 'Czarny', options: ['Bianco', 'Grigio', 'Nero', 'Marrone'], correctAnswer: 'Nero' },
  { id: 80, language: 'Polish', word: 'Iść', options: ['Correre', 'Andare', 'Stare', 'Sedere'], correctAnswer: 'Andare' },
  { id: 81, language: 'Polish', word: 'Biegać', options: ['Camminare', 'Correre', 'Saltare', 'Nuotare'], correctAnswer: 'Correre' },
  { id: 82, language: 'Polish', word: 'Mówić', options: ['Ascoltare', 'Parlare', 'Leggere', 'Scrivere'], correctAnswer: 'Parlare' },
  { id: 83, language: 'Polish', word: 'Widzieć', options: ['Sentire', 'Vedere', 'Toccare', 'Odorare'], correctAnswer: 'Vedere' },
  { id: 84, language: 'Polish', word: 'Wiedzieć', options: ['Pensare', 'Sapere', 'Imparare', 'Dimenticare'], correctAnswer: 'Sapere' },
  { id: 85, language: 'Polish', word: 'Chcieć', options: ['Aver bisogno', 'Volere', 'Avere', 'Piacere'], correctAnswer: 'Volere' },
  { id: 86, language: 'Polish', word: 'Móc', options: ['Dovere', 'Bisognare', 'Potere', 'Volere'], correctAnswer: 'Potere' },
  { id: 87, language: 'Polish', word: 'Musieć', options: ['Potere', 'Dovere', 'Bisognare', 'Volere'], correctAnswer: 'Dovere' },
  { id: 88, language: 'Polish', word: 'Spać', options: ['Svegliarsi', 'Dormire', 'Mangiare', 'Bere'], correctAnswer: 'Dormire' },
  { id: 89, language: 'Polish', word: 'Myśleć', options: ['Sapere', 'Pensare', 'Sentire', 'Credere'], correctAnswer: 'Pensare' },
  { id: 90, language: 'Polish', word: 'Lubić', options: ['Amare', 'Odiare', 'Piacere', 'Preferire'], correctAnswer: 'Piacere' },
  { id: 91, language: 'Polish', word: 'Zawsze', options: ['Mai', 'A volte', 'Sempre', 'Spesso'], correctAnswer: 'Sempre' },
  { id: 92, language: 'Polish', word: 'Nigdy', options: ['Sempre', 'Spesso', 'Mai', 'A volte'], correctAnswer: 'Mai' },
  { id: 93, language: 'Polish', word: 'Często', options: ['Raramente', 'A volte', 'Spesso', 'Sempre'], correctAnswer: 'Spesso' },
  { id: 94, language: 'Polish', word: 'Rzadko', options: ['Spesso', 'Sempre', 'Raramente', 'Mai'], correctAnswer: 'Raramente' },
  { id: 95, language: 'Polish', word: 'Tutaj', options: ['Lì', 'Qui', 'Dove', 'Ovunque'], correctAnswer: 'Qui' },
  { id: 96, language: 'Polish', word: 'Tam', options: ['Qui', 'Lì', 'Vicino', 'Lontano'], correctAnswer: 'Lì' },
  { id: 97, language: 'Polish', word: 'Dlaczego', options: ['Cosa', 'Quando', 'Perché', 'Chi'], correctAnswer: 'Perché' },
  { id: 98, language: 'Polish', word: 'Ponieważ', options: ['Ma', 'Quindi', 'Perché', 'E'], correctAnswer: 'Perché' },
  { id: 99, language: 'Polish', word: 'Ale', options: ['E', 'O', 'Ma', 'Quindi'], correctAnswer: 'Ma' },
  { id: 100, language: 'Polish', word: 'I', options: ['O', 'Ma', 'E', 'Quindi'], correctAnswer: 'E' }
];
