export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Polish', word: 'Cześć', options: ['Adiós', 'Hola', 'Gracias', 'Perdón'], correctAnswer: 'Hola' },
  { id: 2, language: 'Polish', word: 'Do widzenia', options: ['Hola', 'Buenos días', 'Buenas noches', 'Adiós'], correctAnswer: 'Adiós' },
  { id: 3, language: 'Polish', word: 'Dziękuję', options: ['De nada', 'Por favor', 'Gracias', 'Perdón'], correctAnswer: 'Gracias' },
  { id: 4, language: 'Polish', word: 'Tak', options: ['Sí', 'No', 'Quizás', 'Siempre'], correctAnswer: 'Sí' },
  { id: 5, language: 'Polish', word: 'Nie', options: ['Bien', 'Nunca', 'Por qué', 'No'], correctAnswer: 'No' },
  { id: 6, language: 'Polish', word: 'Mężczyzna', options: ['Mujer', 'Hombre', 'Niño', 'Persona'], correctAnswer: 'Hombre' },
  { id: 7, language: 'Polish', word: 'Kobieta', options: ['Hombre', 'Chica', 'Mujer', 'Chico'], correctAnswer: 'Mujer' },
  { id: 8, language: 'Polish', word: 'Jeść', options: ['Beber', 'Dormir', 'Comer', 'Correr'], correctAnswer: 'Comer' },
  { id: 9, language: 'Polish', word: 'Woda', options: ['Fuego', 'Agua', 'Tierra', 'Aire'], correctAnswer: 'Agua' },
  { id: 10, language: 'Polish', word: 'Kot', options: ['Perro', 'Pájaro', 'Pez', 'Gato'], correctAnswer: 'Gato' },
  { id: 11, language: 'Polish', word: 'Pies', options: ['Gato', 'Perro', 'León', 'Tigre'], correctAnswer: 'Perro' },
  { id: 12, language: 'Polish', word: 'Dom', options: ['Coche', 'Escuela', 'Casa', 'Tienda'], correctAnswer: 'Casa' },
  { id: 13, language: 'Polish', word: 'Samochód', options: ['Bicicleta', 'Tren', 'Autobús', 'Coche'], correctAnswer: 'Coche' },
  { id: 14, language: 'Polish', word: 'Szkoła', options: ['Hospital', 'Escuela', 'Universidad', 'Biblioteca'], correctAnswer: 'Escuela' },
  { id: 15, language: 'Polish', word: 'Książka', options: ['Película', 'Canción', 'Libro', 'Pintura'], correctAnswer: 'Libro' },
  { id: 16, language: 'Polish', word: 'Słońce', options: ['Luna', 'Estrella', 'Sol', 'Nube'], correctAnswer: 'Sol' },
  { id: 17, language: 'Polish', word: 'Miłość', options: ['Odio', 'Alegría', 'Tristeza', 'Amor'], correctAnswer: 'Amor' },
  { id: 18, language: 'Polish', word: 'Przyjaciel', options: ['Enemigo', 'Vecino', 'Amigo', 'Familia'], correctAnswer: 'Amigo' },
  { id: 19, language: 'Polish', word: 'Rodzina', options: ['Amigos', 'Familia', 'Parientes', 'Vecinos'], correctAnswer: 'Familia' },
  { id: 20, language: 'Polish', word: 'Rano', options: ['Tarde', 'Noche', 'Mediodía', 'Mañana'], correctAnswer: 'Mañana' },
  { id: 21, language: 'Polish', word: 'Noc', options: ['Día', 'Noche', 'Atardecer', 'Amanecer'], correctAnswer: 'Noche' },
  { id: 22, language: 'Polish', word: 'Dzień', options: ['Semana', 'Mes', 'Año', 'Día'], correctAnswer: 'Día' },
  { id: 23, language: 'Polish', word: 'Tydzień', options: ['Día', 'Semana', 'Fin de semana', 'Mes'], correctAnswer: 'Semana' },
  { id: 24, language: 'Polish', word: 'Miesiąc', options: ['Año', 'Siglo', 'Década', 'Mes'], correctAnswer: 'Mes' },
  { id: 25, language: 'Polish', word: 'Rok', options: ['Mes', 'Año', 'Día', 'Hora'], correctAnswer: 'Año' },
  { id: 26, language: 'Polish', word: 'Dzisiaj', options: ['Ayer', 'Mañana', 'Hoy', 'Pasado mañana'], correctAnswer: 'Hoy' },
  { id: 27, language: 'Polish', word: 'Jutro', options: ['Hoy', 'Ayer', 'Anteayer', 'Mañana'], correctAnswer: 'Mañana' },
  { id: 28, language: 'Polish', word: 'Proszę', options: ['Gracias', 'Por favor', 'Perdón', 'De nada'], correctAnswer: 'Por favor' },
  { id: 29, language: 'Polish', word: 'Jabłko', options: ['Plátano', 'Naranja', 'Manzana', 'Pera'], correctAnswer: 'Manzana' },
  { id: 30, language: 'Polish', word: 'Dzień dobry', options: ['Buenas tardes', 'Buenas noches', 'Buenos días', 'Hola'], correctAnswer: 'Buenos días' },
  { id: 31, language: 'Polish', word: 'Dobry wieczór', options: ['Buenos días', 'Buenas noches', 'Buenas tardes', 'Hola'], correctAnswer: 'Buenas tardes' },
  { id: 32, language: 'Polish', word: 'Dobranoc', options: ['Buenos días', 'Buenas tardes', 'Buenas noches', 'Adiós'], correctAnswer: 'Buenas noches' },
  { id: 33, language: 'Polish', word: 'Przepraszam', options: ['Gracias', 'Por favor', 'Perdón', 'Hola'], correctAnswer: 'Perdón' },
  { id: 34, language: 'Polish', word: 'Praca', options: ['Vacaciones', 'Diversión', 'Trabajo', 'Escuela'], correctAnswer: 'Trabajo' },
  { id: 35, language: 'Polish', word: 'Miasto', options: ['Pueblo', 'País', 'Ciudad', 'Calle'], correctAnswer: 'Ciudad' },
  { id: 36, language: 'Polish', word: 'Jedzenie', options: ['Bebida', 'Agua', 'Comida', 'Pan'], correctAnswer: 'Comida' },
  { id: 37, language: 'Polish', word: 'Chleb', options: ['Leche', 'Agua', 'Pan', 'Queso'], correctAnswer: 'Pan' },
  { id: 38, language: 'Polish', word: 'Mleko', options: ['Jugo', 'Agua', 'Leche', 'Té'], correctAnswer: 'Leche' },
  { id: 39, language: 'Polish', word: 'Kawa', options: ['Té', 'Agua', 'Café', 'Jugo'], correctAnswer: 'Café' },
  { id: 40, language: 'Polish', word: 'Herbata', options: ['Café', 'Leche', 'Té', 'Agua'], correctAnswer: 'Té' },
  { id: 41, language: 'Polish', word: 'Czas', options: ['Espacio', 'Lugar', 'Tiempo', 'Día'], correctAnswer: 'Tiempo' },
  { id: 42, language: 'Polish', word: 'Godzina', options: ['Minuto', 'Segundo', 'Hora', 'Día'], correctAnswer: 'Hora' },
  { id: 43, language: 'Polish', word: 'Wczoraj', options: ['Hoy', 'Mañana', 'Ayer', 'Ahora'], correctAnswer: 'Ayer' },
  { id: 44, language: 'Polish', word: 'Pieniądze', options: ['Oro', 'Plata', 'Dinero', 'Crédito'], correctAnswer: 'Dinero' },
  { id: 45, language: 'Polish', word: 'Sklep', options: ['Oficina', 'Escuela', 'Tienda', 'Casa'], correctAnswer: 'Tienda' },
  { id: 46, language: 'Polish', word: 'Ulica', options: ['Camino', 'Avenida', 'Calle', 'Sendero'], correctAnswer: 'Calle' },
  { id: 47, language: 'Polish', word: 'Droga', options: ['Calle', 'Sendero', 'Carretera', 'Autopista'], correctAnswer: 'Carretera' },
  { id: 48, language: 'Polish', word: 'Matka', options: ['Padre', 'Hermana', 'Madre', 'Hermano'], correctAnswer: 'Madre' },
  { id: 49, language: 'Polish', word: 'Ojciec', options: ['Madre', 'Hermano', 'Padre', 'Hermana'], correctAnswer: 'Padre' },
  { id: 50, language: 'Polish', word: 'Dziecko', options: ['Adulto', 'Hombre', 'Mujer', 'Niño'], correctAnswer: 'Niño' },
  { id: 51, language: 'Polish', word: 'Pytanie', options: ['Respuesta', 'Problema', 'Pregunta', 'Prueba'], correctAnswer: 'Pregunta' },
  { id: 52, language: 'Polish', word: 'Odpowiedź', options: ['Pregunta', 'Respuesta', 'Prueba', 'Solución'], correctAnswer: 'Respuesta' },
  { id: 53, language: 'Polish', word: 'Problem', options: ['Solución', 'Pregunta', 'Problema', 'Respuesta'], correctAnswer: 'Problema' },
  { id: 54, language: 'Polish', word: 'Pomoc', options: ['Problema', 'Ayuda', 'Trabajo', 'Juego'], correctAnswer: 'Ayuda' },
  { id: 55, language: 'Polish', word: 'Szybko', options: ['Lento', 'Rápido', 'Veloz', 'Fuerte'], correctAnswer: 'Rápido' },
  { id: 56, language: 'Polish', word: 'Wolno', options: ['Rápido', 'Veloz', 'Lento', 'Silencioso'], correctAnswer: 'Lento' },
  { id: 57, language: 'Polish', word: 'Duży', options: ['Pequeño', 'Grande', 'Alto', 'Bajo'], correctAnswer: 'Grande' },
  { id: 58, language: 'Polish', word: 'Mały', options: ['Grande', 'Enorme', 'Pequeño', 'Gigante'], correctAnswer: 'Pequeño' },
  { id: 59, language: 'Polish', word: 'Dobry', options: ['Malo', 'Bueno', 'Agradable', 'Genial'], correctAnswer: 'Bueno' },
  { id: 60, language: 'Polish', word: 'Zły', options: ['Bueno', 'Agradable', 'Malo', 'Malvado'], correctAnswer: 'Malo' },
  { id: 61, language: 'Polish', word: 'Nowy', options: ['Viejo', 'Nuevo', 'Joven', 'Antiguo'], correctAnswer: 'Nuevo' },
  { id: 62, language: 'Polish', word: 'Stary', options: ['Nuevo', 'Joven', 'Viejo', 'Moderno'], correctAnswer: 'Viejo' },
  { id: 63, language: 'Polish', word: 'Ciepły', options: ['Frío', 'Fresco', 'Caliente', 'Caluroso'], correctAnswer: 'Caliente' },
  { id: 64, language: 'Polish', word: 'Zimny', options: ['Caliente', 'Caluroso', 'Frío', 'Fresco'], correctAnswer: 'Frío' },
  { id: 65, language: 'Polish', word: 'Łatwy', options: ['Duro', 'Difícil', 'Fácil', 'Simple'], correctAnswer: 'Fácil' },
  { id: 66, language: 'Polish', word: 'Trudny', options: ['Fácil', 'Simple', 'Difícil', 'Ligero'], correctAnswer: 'Difícil' },
  { id: 67, language: 'Polish', word: 'Otwarty', options: ['Cerrado', 'Sellado', 'Abierto', 'Bloqueado'], correctAnswer: 'Abierto' },
  { id: 68, language: 'Polish', word: 'Zamknięty', options: ['Abierto', 'Libre', 'Cerrado', 'Desbloqueado'], correctAnswer: 'Cerrado' },
  { id: 69, language: 'Polish', word: 'Jasny', options: ['Oscuro', 'Negro', 'Claro', 'Tenue'], correctAnswer: 'Claro' },
  { id: 70, language: 'Polish', word: 'Ciemny', options: ['Claro', 'Brillante', 'Oscuro', 'Blanco'], correctAnswer: 'Oscuro' },
  { id: 71, language: 'Polish', word: 'Film', options: ['Libro', 'Canción', 'Película', 'Cuadro'], correctAnswer: 'Película' },
  { id: 72, language: 'Polish', word: 'Muzyka', options: ['Arte', 'Película', 'Música', 'Baile'], correctAnswer: 'Música' },
  { id: 73, language: 'Polish', word: 'Kolor', options: ['Forma', 'Tamaño', 'Color', 'Sonido'], correctAnswer: 'Color' },
  { id: 74, language: 'Polish', word: 'Czerwony', options: ['Azul', 'Verde', 'Rojo', 'Amarillo'], correctAnswer: 'Rojo' },
  { id: 75, language: 'Polish', word: 'Niebieski', options: ['Verde', 'Rojo', 'Azul', 'Amarillo'], correctAnswer: 'Azul' },
  { id: 76, language: 'Polish', word: 'Zielony', options: ['Rojo', 'Azul', 'Verde', 'Amarillo'], correctAnswer: 'Verde' },
  { id: 77, language: 'Polish', word: 'Żółty', options: ['Rojo', 'Azul', 'Verde', 'Amarillo'], correctAnswer: 'Amarillo' },
  { id: 78, language: 'Polish', word: 'Biały', options: ['Negro', 'Gris', 'Blanco', 'Marrón'], correctAnswer: 'Blanco' },
  { id: 79, language: 'Polish', word: 'Czarny', options: ['Blanco', 'Gris', 'Negro', 'Marrón'], correctAnswer: 'Negro' },
  { id: 80, language: 'Polish', word: 'Iść', options: ['Correr', 'Ir', 'Estar', 'Sentarse'], correctAnswer: 'Ir' },
  { id: 81, language: 'Polish', word: 'Biegać', options: ['Caminar', 'Correr', 'Saltar', 'Nadar'], correctAnswer: 'Correr' },
  { id: 82, language: 'Polish', word: 'Mówić', options: ['Escuchar', 'Hablar', 'Leer', 'Escribir'], correctAnswer: 'Hablar' },
  { id: 83, language: 'Polish', word: 'Widzieć', options: ['Oír', 'Ver', 'Tocar', 'Oler'], correctAnswer: 'Ver' },
  { id: 84, language: 'Polish', word: 'Wiedzieć', options: ['Pensar', 'Saber', 'Aprender', 'Olvidar'], correctAnswer: 'Saber' },
  { id: 85, language: 'Polish', word: 'Chcieć', options: ['Necesitar', 'Querer', 'Tener', 'Gustar'], correctAnswer: 'Querer' },
  { id: 86, language: 'Polish', word: 'Móc', options: ['Deber', 'Tener que', 'Poder', 'Querer'], correctAnswer: 'Poder' },
  { id: 87, language: 'Polish', word: 'Musieć', options: ['Poder', 'Deber', 'Tener que', 'Querer'], correctAnswer: 'Tener que' },
  { id: 88, language: 'Polish', word: 'Spać', options: ['Despertar', 'Dormir', 'Comer', 'Beber'], correctAnswer: 'Dormir' },
  { id: 89, language: 'Polish', word: 'Myśleć', options: ['Saber', 'Pensar', 'Sentir', 'Creer'], correctAnswer: 'Pensar' },
  { id: 90, language: 'Polish', word: 'Lubić', options: ['Amar', 'Odiar', 'Gustar', 'Preferir'], correctAnswer: 'Gustar' },
  { id: 91, language: 'Polish', word: 'Zawsze', options: ['Nunca', 'A veces', 'Siempre', 'A menudo'], correctAnswer: 'Siempre' },
  { id: 92, language: 'Polish', word: 'Nigdy', options: ['Siempre', 'A menudo', 'Nunca', 'A veces'], correctAnswer: 'Nunca' },
  { id: 93, language: 'Polish', word: 'Często', options: ['Raramente', 'A veces', 'A menudo', 'Siempre'], correctAnswer: 'A menudo' },
  { id: 94, language: 'Polish', word: 'Rzadko', options: ['A menudo', 'Siempre', 'Raramente', 'Nunca'], correctAnswer: 'Raramente' },
  { id: 95, language: 'Polish', word: 'Tutaj', options: ['Allí', 'Aquí', 'Dónde', 'En todas partes'], correctAnswer: 'Aquí' },
  { id: 96, language: 'Polish', word: 'Tam', options: ['Aquí', 'Allí', 'Cerca', 'Lejos'], correctAnswer: 'Allí' },
  { id: 97, language: 'Polish', word: 'Dlaczego', options: ['Qué', 'Cuándo', 'Por qué', 'Quién'], correctAnswer: 'Por qué' },
  { id: 98, language: 'Polish', word: 'Ponieważ', options: ['Pero', 'Así que', 'Porque', 'Y'], correctAnswer: 'Porque' },
  { id: 99, language: 'Polish', word: 'Ale', options: ['Y', 'O', 'Pero', 'Así que'], correctAnswer: 'Pero' },
  { id: 100, language: 'Polish', word: 'I', options: ['O', 'Pero', 'Y', 'Así que'], correctAnswer: 'Y' }
];
