
export interface Question {
  id: number;
  language: 'English';
  word: string;
  options?: string[]; // Options are now generated dynamically
  correctAnswers: string[];
}

export const questions: Question[] = [
  // PODSTAWOWE, ABSOLUTNY MUST-HAVE
  { id: 1, language: 'English', word: 'ask out', correctAnswers: ['zaprosić kogoś na randkę'] },
  { id: 2, language: 'English', word: 'back up', correctAnswers: ['poprzeć', 'zrobić kopię zapasową'] },
  { id: 3, language: 'English', word: 'blow up', correctAnswers: ['wybuchnąć', 'zdenerwować się'] },
  { id: 4, language: 'English', word: 'break down', correctAnswers: ['zepsuć się', 'załamać się'] },
  { id: 5, language: 'English', word: 'break up', correctAnswers: ['rozstać się'] },
  { id: 6, language: 'English', word: 'bring up', correctAnswers: ['poruszyć temat', 'wychować'] },
  { id: 7, language: 'English', word: 'call back', correctAnswers: ['oddzwonić'] },
  { id: 8, language: 'English', word: 'call off', correctAnswers: ['odwołać'] },
  { id: 9, language: 'English', word: 'carry on', correctAnswers: ['kontynuować'] },
  { id: 10, language: 'English', word: 'catch up', correctAnswers: ['nadrobić zaległości'] },
  { id: 11, language: 'English', word: 'check in', correctAnswers: ['zameldować się', 'dać znać'] },
  { id: 12, language: 'English', word: 'check out', correctAnswers: ['wymeldować się', 'sprawdzić'] },
  { id: 13, language: 'English', word: 'come across', correctAnswers: ['natknąć się'] },
  { id: 14, language: 'English', word: 'come back', correctAnswers: ['wrócić'] },
  { id: 15, language: 'English', word: 'come in', correctAnswers: ['wejść'] },
  { id: 16, language: 'English', word: 'come out', correctAnswers: ['wyjść', 'ukazać się'] },
  { id: 17, language: 'English', word: 'come over', correctAnswers: ['wpaść z wizytą'] },
  { id: 18, language: 'English', word: 'cut down', correctAnswers: ['ograniczyć'] },
  { id: 19, language: 'English', word: 'cut off', correctAnswers: ['odciąć', 'przerwać'] },

  // PRACA, ŻYCIE CODZIENNE, KONTAKTY
  { id: 20, language: 'English', word: 'deal with', correctAnswers: ['radzić sobie z czymś'] },
  { id: 21, language: 'English', word: 'drop by', correctAnswers: ['wpaść na chwilę'] },
  { id: 22, language: 'English', word: 'drop off', correctAnswers: ['podrzucić', 'zasnąć'] },
  { id: 23, language: 'English', word: 'figure out', correctAnswers: ['zrozumieć', 'rozgryźć'] },
  { id: 24, language: 'English', word: 'fill in', correctAnswers: ['wypełnić', 'zastąpić'] },
  { id: 25, language: 'English', word: 'find out', correctAnswers: ['dowiedzieć się'] },
  { id: 26, language: 'English', word: 'get along', correctAnswers: ['dogadywać się'] },
  { id: 27, language: 'English', word: 'get back', correctAnswers: ['wrócić'] },
  { id: 28, language: 'English', word: 'get in', correctAnswers: ['wejść', 'dostać się'] },
  { id: 29, language: 'English', word: 'get off', correctAnswers: ['wysiąść', 'zejść z pracy'] },
  { id: 30, language: 'English', word: 'get on', correctAnswers: ['wsiąść', 'radzić sobie'] },
  { id: 31, language: 'English', word: 'get over', correctAnswers: ['dojść do siebie'] },
  { id: 32, language: 'English', word: 'get through', correctAnswers: ['przebrnąć', 'dodzwonić się'] },
  { id: 33, language: 'English', word: 'give back', correctAnswers: ['oddać'] },
  { id: 34, language: 'English', word: 'give up', correctAnswers: ['poddać się', 'rzucić coś'] },
  { id: 35, language: 'English', word: 'go ahead', correctAnswers: ['kontynuować', 'zgodzić się'] },
  { id: 36, language: 'English', word: 'go back', correctAnswers: ['wrócić'] },
  { id: 37, language: 'English', word: 'go on', correctAnswers: ['dziać się', 'kontynuować'] },
  { id: 38, language: 'English', word: 'go out', correctAnswers: ['wyjść'] },
  { id: 39, language: 'English', word: 'go through', correctAnswers: ['przejść przez coś'] },

  // ROZMOWY, RELACJE, EMOCJE
  { id: 40, language: 'English', word: 'hang out', correctAnswers: ['spędzać czas'] },
  { id: 41, language: 'English', word: 'hold on', correctAnswers: ['poczekać'] },
  { id: 42, language: 'English', word: 'keep on', correctAnswers: ['kontynuować'] },
  { id: 43, language: 'English', word: 'let down', correctAnswers: ['zawieść'] },
  { id: 44, language: 'English', word: 'look after', correctAnswers: ['opiekować się'] },
  { id: 45, language: 'English', word: 'look for', correctAnswers: ['szukać'] },
  { id: 46, language: 'English', word: 'look forward to', correctAnswers: ['nie móc się doczekać'] },
  { id: 47, language: 'English', word: 'look into', correctAnswers: ['sprawdzić', 'zbadać'] },
  { id: 48, language: 'English', word: 'look out', correctAnswers: ['uważać'] },
  { id: 49, language: 'English', word: 'make up', correctAnswers: ['pogodzić się', 'wymyślić'] },
  { id: 50, language: 'English', word: 'move on', correctAnswers: ['iść dalej'] },
  { id: 51, language: 'English', word: 'open up', correctAnswers: ['otworzyć się'] },
  { id: 52, language: 'English', word: 'pick up', correctAnswers: ['odebrać', 'podnieść', 'nauczyć się'] },
  { id: 53, language: 'English', word: 'put off', correctAnswers: ['odkładać'] },
  { id: 54, language: 'English', word: 'run into', correctAnswers: ['wpaść na kogoś'] },
  { id: 55, language: 'English', word: 'settle down', correctAnswers: ['ustatkowac się'] },
  { id: 56, language: 'English', word: 'show up', correctAnswers: ['pojawić się'] },
  { id: 57, language: 'English', word: 'shut up', correctAnswers: ['zamknąć się'] },
  { id: 58, language: 'English', word: 'sort out', correctAnswers: ['ogarnąć', 'rozwiązać'] },

  // PRACA, OBOWIĄZKI, ORGANIZACJA
  { id: 59, language: 'English', word: 'take over', correctAnswers: ['przejąć'] },
  { id: 60, language: 'English', word: 'take up', correctAnswers: ['zacząć (hobby)'] },
  { id: 61, language: 'English', word: 'think over', correctAnswers: ['przemyśleć'] },
  { id: 62, language: 'English', word: 'throw away', correctAnswers: ['wyrzucić'] },
  { id: 63, language: 'English', word: 'turn down', correctAnswers: ['odrzucić', 'ściszyć'] },
  { id: 64, language: 'English', word: 'turn up', correctAnswers: ['pojawić się', 'podgłośnić'] },
  { id: 65, language: 'English', word: 'work out', correctAnswers: ['rozwiązać', 'ćwiczyć'] },
  { id: 66, language: 'English', word: 'write down', correctAnswers: ['zapisać'] },
  { id: 67, language: 'English', word: 'set up', correctAnswers: ['założyć', 'zorganizować'] },
  { id: 68, language: 'English', word: 'slow down', correctAnswers: ['zwolnić'] },
  { id: 69, language: 'English', word: 'speed up', correctAnswers: ['przyspieszyć'] },
  { id: 70, language: 'English', word: 'step down', correctAnswers: ['ustąpić'] },
  { id: 71, language: 'English', word: 'step up', correctAnswers: ['zwiększyć zaangażowanie'] },

  // BARDZO CZĘSTE W MOWIE POTOCZNEJ
  { id: 72, language: 'English', word: 'break out', correctAnswers: ['wybuchnąć', 'uciec'] },
  { id: 73, language: 'English', word: 'bring back', correctAnswers: ['przywrócić'] },
  { id: 74, language: 'English', word: 'calm down', correctAnswers: ['uspokoić się'] },
  { id: 75, language: 'English', word: 'check over', correctAnswers: ['sprawdzić dokładnie'] },
  { id: 76, language: 'English', word: 'clear up', correctAnswers: ['wyjaśnić', 'posprzątać'] },
  { id: 77, language: 'English', word: 'come along', correctAnswers: ['przyjść', 'robić postępy'] },
  { id: 78, language: 'English', word: 'cut back', correctAnswers: ['ograniczyć wydatki'] },
  { id: 79, language: 'English', word: 'fall apart', correctAnswers: ['rozpaść się'] },
  { id: 80, language: 'English', word: 'fall behind', correctAnswers: ['zostać w tyle'] },
  { id: 81, language: 'English', word: 'fill out', correctAnswers: ['wypełnić formularz'] },
  { id: 82, language: 'English', word: 'get away', correctAnswers: ['wyjechać', 'uciec'] },
  { id: 83, language: 'English', word: 'get by', correctAnswers: ['radzić sobie'] },
  { id: 84, language: 'English', word: 'get together', correctAnswers: ['spotkać się'] },
  { id: 85, language: 'English', word: 'give in', correctAnswers: ['ulec'] },
  { id: 86, language: 'English', word: 'go wrong', correctAnswers: ['pójść nie tak'] },
  { id: 87, language: 'English', word: 'hang on', correctAnswers: ['poczekać'] },
  { id: 88, language: 'English', word: 'keep up', correctAnswers: ['nadążać'] },

  // PRACA + TECHNOLOGIA + ŻYCIE NOWOCZESNE
  { id: 89, language: 'English', word: 'log in', correctAnswers: ['zalogować się'] },
  { id: 90, language: 'English', word: 'log out', correctAnswers: ['wylogować się'] },
  { id: 91, language: 'English', word: 'sign in', correctAnswers: ['podpisać się', 'zalogować'] },
  { id: 92, language: 'English', word: 'sign out', correctAnswers: ['wylogować się'] },
  { id: 93, language: 'English', word: 'turn on', correctAnswers: ['włączyć'] },
  { id: 94, language: 'English', word: 'turn off', correctAnswers: ['wyłączyć'] },
  { id: 95, language: 'English', word: 'plug in', correctAnswers: ['podłączyć'] },
  { id: 96, language: 'English', word: 'back out', correctAnswers: ['wycofać się'] },
  { id: 97, language: 'English', word: 'boot up', correctAnswers: ['uruchomić system'] },
  { id: 98, language: 'English', word: 'shut down', correctAnswers: ['zamknąć', 'wyłączyć'] },

  // EMOCJE, PROBLEMY, REAKCJE
  { id: 99, language: 'English', word: 'freak out', correctAnswers: ['spanikować'] },
  { id: 100, language: 'English', word: 'lash out', correctAnswers: ['wybuchnąć gniewem'] },
  { id: 101, language: 'English', word: 'mess up', correctAnswers: ['schrzanić coś'] },
  { id: 102, language: 'English', word: 'pass out', correctAnswers: ['zemdleć'] },
  { id: 103, language: 'English', word: 'snap out of', correctAnswers: ['otrząsnąć się'] },
  { id: 104, language: 'English', word: 'wear out', correctAnswers: ['zmęczyć', 'zużyć'] },
  { id: 105, language: 'English', word: 'blow off', correctAnswers: ['zlekceważyć'] },
  { id: 106, language: 'English', word: 'bottle up', correctAnswers: ['tłumić emocje'] },

  // KOŃCÓWKA – BARDZO NATURALNE, CZĘSTE
  { id: 107, language: 'English', word: 'bring along', correctAnswers: ['zabrać ze sobą'] },
  { id: 108, language: 'English', word: 'call up', correctAnswers: ['zadzwonić'] },
  { id: 109, language: 'English', word: 'come around', correctAnswers: ['zmienić zdanie'] },
  { id: 110, language: 'English', word: 'cut out', correctAnswers: ['przestać', 'wyciąć'] },
  { id: 111, language: 'English', word: 'get ahead', correctAnswers: ['wysunąć się na prowadzenie'] },
  { id: 112, language: 'English', word: 'give away', correctAnswers: ['zdradzić', 'oddać'] },
  { id: 113, language: 'English', word: 'hold back', correctAnswers: ['powstrzymać'] },
  { id: 114, language: 'English', word: 'keep away', correctAnswers: ['trzymać z daleka'] },
  { id: 115, language: 'English', word: 'lay off', correctAnswers: ['zwolnić z pracy'] },
  { id: 116, language: 'English', word: 'live up to', correctAnswers: ['spełnić oczekiwania'] },
  { id: 117, language: 'English', word: 'pass away', correctAnswers: ['umrzeć'] },
  { id: 118, language: 'English', word: 'pull over', correctAnswers: ['zjechać na bok'] },
  { id: 119, language: 'English', word: 'run out', correctAnswers: ['skończyć się'] },
  { id: 120, language: 'English', word: 'stand by', correctAnswers: ['czekać', 'wspierać'] },
  { id: 121, language: 'English', word: 'stick to', correctAnswers: ['trzymać się'] },
  { id: 122, language: 'English', word: 'take off', correctAnswers: ['wystartować', 'zdjąć'] },
  { id: 123, language: 'English', word: 'turn around', correctAnswers: ['odwrócić sytuację'] },
  { id: 124, language: 'English', word: 'warm up', correctAnswers: ['rozgrzać się'] },
  { id: 125, language: 'English', word: 'wrap up', correctAnswers: ['zakończyć'] },
];

