export interface Question {
  id: number;
  language: 'English';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'English', word: 'A blessing in disguise', options: ['Szczęście w nieszczęściu', 'Błogosławieństwo w przebraniu', 'Dar od losu', 'Pechowa sytuacja'], correctAnswer: 'Szczęście w nieszczęściu' },
  { id: 2, language: 'English', word: 'A dime a dozen', options: ['Na pęczki', 'Tuzin za grosze', 'Tania rzecz', 'Rzadkie znalezisko'], correctAnswer: 'Na pęczki' },
  { id: 3, language: 'English', word: 'A drop in the ocean', options: ['Kropla w morzu potrzeb', 'Kropla w oceanie', 'Mała część całości', 'Ogromna większość'], correctAnswer: 'Kropla w morzu potrzeb' },
  { id: 4, language: 'English', word: 'A piece of cake', options: ['Bułka z masłem', 'Kawałek ciasta', 'Słodka nagroda', 'Trudne zadanie'], correctAnswer: 'Bułka z masłem' },
  { id: 5, language: 'English', word: 'A slap on the wrist', options: ['Upomnienie / Lekka kara', 'Klapnięcie w nadgarstek', 'Publiczna nagana', 'Surowa kara'], correctAnswer: 'Upomnienie / Lekka kara' },
  { id: 6, language: 'English', word: 'A storm in a teacup', options: ['Burza w szklance wody', 'Sztorm w filiżance', 'Poważny problem', 'Spokojna dyskusja'], correctAnswer: 'Burza w szklance wody' },
  { id: 7, language: 'English', word: 'Achilles’ heel', options: ['Pięta Achillesa', 'Obcas Achillesa', 'Najmocniejsza strona', 'Ukryty talent'], correctAnswer: 'Pięta Achillesa' },
  { id: 8, language: 'English', word: 'Add fuel to the fire', options: ['Dolewać oliwy do ognia', 'Dodawać paliwa do ognia', 'Gasić pożar', 'Rozpalać ognisko'], correctAnswer: 'Dolewać oliwy do ognia' },
  { id: 9, language: 'English', word: 'All ears', options: ['Zamieniać się w słuch', 'Same uszy', 'Puszczać mimo uszu', 'Słuchać jednym uchem'], correctAnswer: 'Zamieniać się w słuch' },
  { id: 10, language: 'English', word: 'All in the same boat', options: ['Jechać na tym samym wózku', 'Wszyscy w tej samej łodzi', 'Być w różnych sytuacjach', 'Płynąć pod prąd'], correctAnswer: 'Jechać na tym samym wózku' },
  { id: 11, language: 'English', word: 'Apple of my eye', options: ['Oczko w głowie', 'Jabłko mojego oka', 'Ulubiony owoc', 'Źrenica oka'], correctAnswer: 'Oczko w głowie' },
  { id: 12, language: 'English', word: 'At the drop of a hat', options: ['Od ręki / Natychmiast', 'Po zrzuceniu kapelusza', 'Po długim namyśle', 'Z opóźnieniem'], correctAnswer: 'Od ręki / Natychmiast' },
  { id: 13, language: 'English', word: 'Back to the drawing board', options: ['Zacząć od nowa', 'Wrócić do deski kreślarskiej', 'Skończyć projekt', 'Rysować plany'], correctAnswer: 'Zacząć od nowa' },
  { id: 14, language: 'English', word: 'Barking up the wrong tree', options: ['Szczekać pod niewłaściwym drzewem', 'Mylić się co do kogoś/czegoś', 'Szukać pod właściwym adresem', 'Gonić w piętkę'], correctAnswer: 'Mylić się co do kogoś/czegoś' },
  { id: 15, language: 'English', word: 'Beat around the bush', options: ['Owijać w bawełnę', 'Bić wokół krzaka', 'Mówić prosto z mostu', 'Chodzić po lesie'], correctAnswer: 'Owijać w bawełnę' },
  { id: 16, language: 'English', word: 'Better late than never', options: ['Lepiej późno niż wcale', 'Zawsze na czas', 'Spóźnić się', 'Być pierwszym'], correctAnswer: 'Lepiej późno niż wcale' },
  { id: 17, language: 'English', word: 'Bite off more than you can chew', options: ['Porywać się z motyką na słońce', 'Odgryźć więcej niż można przeżuć', 'Być bardzo głodnym', 'Zachować umiar'], correctAnswer: 'Porywać się z motyką na słońce' },
  { id: 18, language: 'English', word: 'Bite the bullet', options: ['Zacisnąć zęby i coś zrobić', 'Ugryźć nabój', 'Unikać problemu', 'Poddać się'], correctAnswer: 'Zacisnąć zęby i coś zrobić' },
  { id: 19, language: 'English', word: 'Break the ice', options: ['Przełamać pierwsze lody', 'Łamać lód', 'Tworzyć niezręczną ciszę', 'Rozpocząć kłótnię'], correctAnswer: 'Przełamać pierwsze lody' },
  { id: 20, language: 'English', word: 'Bring home the bacon', options: ['Przynieść do domu boczek', 'Zarabiać na życie', 'Być bezrobotnym', 'Gotować obiad'], correctAnswer: 'Zarabiać na życie' },
  { id: 21, language: 'English', word: 'Burn the midnight oil', options: ['Palić nocną lampkę', 'Pracować do późna w nocy', 'Wcześnie chodzić spać', 'Oszczędzać energię'], correctAnswer: 'Pracować do późna w nocy' },
  { id: 22, language: 'English', word: 'Call it a day', options: ['Nazwać to dniem', 'Zakończyć pracę na dziś', 'Zacząć pracę', 'Pracować cały dzień'], correctAnswer: 'Zakończyć pracę na dziś' },
  { id: 23, language: 'English', word: 'Calm before the storm', options: ['Cisza przed burzą', 'Spokój po burzy', 'Cicha pogoda', 'Nerwowa atmosfera'], correctAnswer: 'Cisza przed burzą' },
  { id: 24, language: 'English', word: 'Catch someone red-handed', options: ['Złapać kogoś na gorącym uczynku', 'Złapać kogoś z czerwoną ręką', 'Pomóc komuś w potrzebie', 'Puścić kogoś wolno'], correctAnswer: 'Złapać kogoś na gorącym uczynku' },
  { id: 25, language: 'English', word: 'Costs an arm and a leg', options: ['Kosztować fortunę', 'Kosztować rękę i nogę', 'Być tanim jak barszcz', 'Być za darmo'], correctAnswer: 'Kosztować fortunę' },
  { id: 26, language: 'English', word: 'Cross that bridge when you come to it', options: ['Będziemy się martwić, jak przyjdzie czas', 'Przejść przez most, gdy do niego dojdziesz', 'Martwić się na zapas', 'Budować mosty'], correctAnswer: 'Będziemy się martwić, jak przyjdzie czas' },
  { id: 27, language: 'English', word: 'Cry over spilled milk', options: ['Płakać nad rozlanym mlekiem', 'Rozpaczać nad czymś, czego nie można zmienić', 'Martwić się o przyszłość', 'Sprzątać bałagan'], correctAnswer: 'Rozpaczać nad czymś, czego nie można zmienić' },
  { id: 28, language: 'English', word: 'Cut corners', options: ['Iść na skróty', 'Obcinać rogi', 'Być dokładnym', 'Pracować ciężko'], correctAnswer: 'Iść na skróty' },
  { id: 29, language: 'English', word: 'Devil’s advocate', options: ['Adwokat diabła', 'Zgadzać się ze wszystkimi', 'Prowokować dyskusję', 'Bronić złej sprawy'], correctAnswer: 'Prowokować dyskusję' },
  { id: 30, language: 'English', word: 'Don’t count your chickens before they hatch', options: ['Nie dzielić skóry na niedźwiedziu', 'Nie liczyć kurczaków przed wykluciem', 'Być optymistą', 'Planować z wyprzedzeniem'], correctAnswer: 'Nie dzielić skóry na niedźwiedziu' },
  { id: 31, language: 'English', word: 'Don’t put all your eggs in one basket', options: ['Nie stawiać wszystkiego na jedną kartę', 'Nie wkładać wszystkich jajek do jednego koszyka', 'Ryzykować wszystko', 'Robić omlet'], correctAnswer: 'Nie stawiać wszystkiego na jedną kartę' },
  { id: 32, language: 'English', word: 'Down to the wire', options: ['Na ostatnią chwilę', 'Do samego drutu', 'Z dużym zapasem czasu', 'W połowie drogi'], correctAnswer: 'Na ostatnią chwilę' },
  { id: 33, language: 'English', word: 'Draw the line', options: ['Postawić granicę', 'Narysować linię', 'Przekraczać granice', 'Zacząć od nowa'], correctAnswer: 'Postawić granicę' },
  { id: 34, language: 'English', word: 'Drive someone up the wall', options: ['Doprowadzać kogoś do szału', 'Wjechać w ścianę', 'Uspokajać kogoś', 'Podwozić kogoś'], correctAnswer: 'Doprowadzać kogoś do szału' },
  { id: 35, language: 'English', word: 'Drop a bombshell', options: ['Ogłosić coś szokującego', 'Zrzucić bombę', 'Zrobić niespodziankę', 'Powiedzieć coś nieistotnego'], correctAnswer: 'Ogłosić coś szokującego' },
  { id: 36, language: 'English', word: 'Easier said than done', options: ['Łatwiej powiedzieć, niż zrobić', 'Trudne do powiedzenia', 'Bardzo proste zadanie', 'Niemożliwe do wykonania'], correctAnswer: 'Łatwiej powiedzieć, niż zrobić' },
  { id: 37, language: 'English', word: 'Every cloud has a silver lining', options: ['Nie ma tego złego, co by na dobre nie wyszło', 'Każda chmura ma srebrną podszewkę', 'Zawsze jest nadzieja', 'Po deszczu zawsze jest tęcza'], correctAnswer: 'Nie ma tego złego, co by na dobre nie wyszło' },
  { id: 38, language: 'English', word: 'Face the music', options: ['Stawić czoła konsekwencjom', 'Zmierz się z muzyką', 'Iść na koncert', 'Unikać problemów'], correctAnswer: 'Stawić czoła konsekwencjom' },
  { id: 39, language: 'English', word: 'Fair and square', options: ['Uczciwie', 'Sprawiedliwie i kwadratowo', 'Oszukiwać', 'Wygrać nieuczciwie'], correctAnswer: 'Uczciwie' },
  { id: 40, language: 'English', word: 'Far cry from', options: ['Dalekie od ideału/prawdy', 'Daleki krzyk od', 'Bardzo podobne', 'Dokładnie to samo'], correctAnswer: 'Dalekie od ideału/prawdy' },
  { id: 41, language: 'English', word: 'Feel under the weather', options: ['Źle się czuć', 'Czuć się pod pogodą', 'Być na zewnątrz w deszczu', 'Cieszyć się pogodą'], correctAnswer: 'Źle się czuć' },
  { id: 42, language: 'English', word: 'Fingers crossed', options: ['Trzymać kciuki', 'Skrzyżowane palce', 'Modlić się o szczęście', 'Mieć pecha'], correctAnswer: 'Trzymać kciuki' },
  { id: 43, language: 'English', word: 'Fish out of water', options: ['Czuć się nieswojo', 'Ryba bez wody', 'Być w swoim żywiole', 'Pływać w oceanie'], correctAnswer: 'Czuć się nieswojo' },
  { id: 44, language: 'English', word: 'Fly off the handle', options: ['Wpaść w furię', 'Oderwać się od klamki', 'Zachować spokój', 'Latać helikopterem'], correctAnswer: 'Wpaść w furię' },
  { id: 45, language: 'English', word: 'For the time being', options: ['Na razie', 'W międzyczasie', 'Na zawsze', 'W przyszłości'], correctAnswer: 'Na razie' },
  { id: 46, language: 'English', word: 'From the horse’s mouth', options: ['Z pierwszej ręki', 'Z końskich ust', 'Z wiarygodnego źródła', 'Z plotek'], correctAnswer: 'Z pierwszej ręki' },
  { id: 47, language: 'English', word: 'Get a taste of your own medicine', options: ['Dostać swoją własną medycynę', 'Odpłacić pięknym za nadobne', 'Próbować lekarstwa', 'Zachorować'], correctAnswer: 'Odpłacić pięknym za nadobne' },
  { id: 48, language: 'English', word: 'Get cold feet', options: ['Stchórzyć w ostatniej chwili', 'Dostać zimnych stóp', 'Zmarznąć', 'Być odważnym'], correctAnswer: 'Stchórzyć w ostatniej chwili' },
  { id: 49, language: 'English', word: 'Get something off your chest', options: ['Wygadać się', 'Zrzucić coś z klatki piersiowej', 'Ukrywać sekret', 'Ćwiczyć na siłowni'], correctAnswer: 'Wygadać się' },
  { id: 50, language: 'English', word: 'Get your act together', options: ['Wziąć się w garść', 'Zebrać swoje akta', 'Zorganizować przedstawienie', 'Robić bałagan'], correctAnswer: 'Wziąć się w garść' },
  { id: 51, language: 'English', word: 'Go back to square one', options: ['Wrócić na pole numer jeden', 'Zacząć od początku', 'Skończyć grę', 'Cofnąć się o krok'], correctAnswer: 'Zacząć od początku' },
  { id: 52, language: 'English', word: 'Go the extra mile', options: ['Zrobić więcej niż to konieczne', 'Przejść dodatkową milę', 'Skończyć maraton', 'Iść na długi spacer'], correctAnswer: 'Zrobić więcej niż to konieczne' },
  { id: 53, language: 'English', word: 'Hit the books', options: ['Uderzyć w książki', 'Uczyć się pilnie', 'Czytać dużo książek', 'Rzucać książkami'], correctAnswer: 'Uczyć się pilnie' },
  { id: 54, language: 'English', word: 'Hit the nail on the head', options: ['Trafić w sedno', 'Uderzyć gwoździem w głowę', 'Pomylić się', 'Pracować jako stolarz'], correctAnswer: 'Trafić w sedno' },
  { id: 55, language: 'English', word: 'Hit the sack', options: ['Uderzyć w worek', 'Iść spać', 'Być bardzo zmęczonym', 'Zacząć trening'], correctAnswer: 'Iść spać' },
  { id: 56, language: 'English', word: 'Hold your horses', options: ['Trzymaj swoje konie', 'Wstrzymaj się', 'Uspokój się', 'Iść do stajni'], correctAnswer: 'Wstrzymaj się' },
  { id: 57, language: 'English', word: 'In a nutshell', options: ['W łupinie orzecha', 'Krótko mówiąc', 'W skrócie', 'W szczegółach'], correctAnswer: 'Krótko mówiąc' },
  { id: 58, language: 'English', word: 'In hot water', options: ['W gorącej wodzie', 'Mieć kłopoty', 'Być w saunie', 'Kąpać się w wannie'], correctAnswer: 'Mieć kłopoty' },
  { id: 59, language: 'English', word: 'In the nick of time', options: ['W ostatniej chwili', 'W samą porę', 'Za wcześnie', 'Za późno'], correctAnswer: 'W ostatniej chwili' },
  { id: 60, language: 'English', word: 'It takes two to tango', options: ['Do tanga trzeba dwojga', 'Obie strony są winne', 'Tańczyć w parze', 'Pracować w zespole'], correctAnswer: 'Do tanga trzeba dwojga' },
  { id: 61, language: 'English', word: 'Jump on the bandwagon', options: ['Wskoczyć do wagonu z orkiestrą', 'Dołączyć do popularnego trendu', 'Iść na paradę', 'Być oryginalnym'], correctAnswer: 'Dołączyć do popularnego trendu' },
  { id: 62, language: 'English', word: 'Keep an eye on', options: ['Trzymać na czymś oko', 'Pilnować czegoś', 'Obserwować z daleka', 'Ignorować coś'], correctAnswer: 'Pilnować czegoś' },
  { id: 63, language: 'English', word: 'Keep your chin up', options: ['Głowa do góry', 'Nie poddawaj się', 'Patrzeć w górę', 'Być dumnym'], correctAnswer: 'Głowa do góry' },
  { id: 64, language: 'English', word: 'Kill two birds with one stone', options: ['Upiec dwie pieczenie na jednym ogniu', 'Zabić dwa ptaki jednym kamieniem', 'Polować na ptaki', 'Robić dwie rzeczy naraz'], correctAnswer: 'Upiec dwie pieczenie na jednym ogniu' },
  { id: 65, language: 'English', word: 'Knock on wood', options: ['Pukać w drewno', 'Odpukać w niemalowane', 'Na szczęście', 'Przynieść pecha'], correctAnswer: 'Odpukać w niemalowane' },
  { id: 66, language: 'English', word: 'Know the ropes', options: ['Znać liny', 'Znać się na rzeczy', 'Uczyć się żeglarstwa', 'Być nowicjuszem'], correctAnswer: 'Znać się na rzeczy' },
  { id: 67, language: 'English', word: 'Last straw', options: ['Ostatnia słomka', 'Miarka się przebrała', 'Ostatnia szansa', 'Koniec napoju'], correctAnswer: 'Miarka się przebrała' },
  { id: 68, language: 'English', word: 'Let sleeping dogs lie', options: ['Nie wywołuj wilka z lasu', 'Zostaw śpiące psy w spokoju', 'Nie rozdrapuj starych ran', 'Obudzić psa'], correctAnswer: 'Nie wywołuj wilka z lasu' },
  { id: 69, language: 'English', word: 'Let the cat out of the bag', options: ['Wypuścić kota z worka', 'Wygadać sekret', 'Kupić kota w worku', 'Zrobić niespodziankę'], correctAnswer: 'Wygadać sekret' },
  { id: 70, language: 'English', word: 'Make a long story short', options: ['Uczynić długą historię krótką', 'Krótko mówiąc', 'Opowiadać długo', 'Pisać streszczenie'], correctAnswer: 'Krótko mówiąc' },
  { id: 71, language: 'English', word: 'Make ends meet', options: ['Wiązać koniec z końcem', 'Oszczędzać pieniądze', 'Być bogatym', 'Wydawać pieniądze'], correctAnswer: 'Wiązać koniec z końcem' },
  { id: 72, language: 'English', word: 'Method to the madness', options: ['Jest w tym metoda', 'Metoda w szaleństwie', 'Być szalonym', 'Działać chaotycznie'], correctAnswer: 'Jest w tym metoda' },
  { id: 73, language: 'English', word: 'Miss the boat', options: ['Przegapić okazję', 'Spóźnić się na statek', 'Być na czas', 'Płynąć łodzią'], correctAnswer: 'Przegapić okazję' },
  { id: 74, language: 'English', word: 'Mum’s the word', options: ['Mama jest słowem', 'Ani mru-mru', 'Zachowaj to w tajemnicy', 'Mówić głośno'], correctAnswer: 'Ani mru-mru' },
  { id: 75, language: 'English', word: 'Neck of the woods', options: ['Szyja lasu', 'W tych stronach', 'Daleko stąd', 'Głęboko w lesie'], correctAnswer: 'W tych stronach' },
  { id: 76, language: 'English', word: 'No pain, no gain', options: ['Bez pracy nie ma kołaczy', 'Nie ma bólu, nie ma zysku', 'Cierpieć w milczeniu', 'Unikać wysiłku'], correctAnswer: 'Bez pracy nie ma kołaczy' },
  { id: 77, language: 'English', word: 'Not a chance', options: ['Nie ma mowy', 'Nie szansa', 'Może później', 'Na pewno'], correctAnswer: 'Nie ma mowy' },
  { id: 78, language: 'English', word: 'Off the hook', options: ['Zdjęty z haka', 'Uwolniony od kłopotów', 'Mieć problem', 'Łowić ryby'], correctAnswer: 'Uwolniony od kłopotów' },
  { id: 79, language: 'English', word: 'On cloud nine', options: ['Na chmurze dziewiątej', 'Być w siódmym niebie', 'Być smutnym', 'Marzyć'], correctAnswer: 'Być w siódmym niebie' },
  { id: 80, language: 'English', word: 'On the ball', options: ['Być czujnym i szybkim w reakcji', 'Na piłce', 'Grać w piłkę', 'Być rozkojarzonym'], correctAnswer: 'Być czujnym i szybkim w reakcji' },
  { id: 81, language: 'English', word: 'On thin ice', options: ['Na cienkim lodzie', 'Być w ryzykownej sytuacji', 'Jeździć na łyżwach', 'Być bezpiecznym'], correctAnswer: 'Być w ryzykownej sytuacji' },
  { id: 82, language: 'English', word: 'Once in a blue moon', options: ['Bardzo rzadko', 'Raz na niebieski księżyc', 'Często', 'Nigdy'], correctAnswer: 'Bardzo rzadko' },
  { id: 83, language: 'English', word: 'Out of the blue', options: ['Nagle, z nienacka', 'Z niebieskiego', 'Spodziewanie', 'Zgodnie z planem'], correctAnswer: 'Nagle, z nienacka' },
  { id: 84, language: 'English', word: 'Out of the frying pan into the fire', options: ['Z deszczu pod rynnę', 'Z patelni do ognia', 'Unikać problemów', 'Rozwiązać problem'], correctAnswer: 'Z deszczu pod rynnę' },
  { id: 85, language: 'English', word: 'Pass the buck', options: ['Przerzucić odpowiedzialność', 'Podać dolara', 'Przyjąć odpowiedzialność', 'Pożyczyć pieniądze'], correctAnswer: 'Przerzucić odpowiedzialność' },
  { id: 86, language: 'English', word: 'Penny for your thoughts', options: ['Grosz za twoje myśli', 'O czym myślisz?', 'Cisza przed burzą', 'Płacić za pomysły'], correctAnswer: 'O czym myślisz?' },
  { id: 87, language: 'English', word: 'Play it by ear', options: ['Grać na ucho', 'Improwizować', 'Trzymać się planu', 'Słuchać muzyki'], correctAnswer: 'Improwizować' },
  { id: 88, language: 'English', word: 'Pull someone’s leg', options: ['Ciągnąć kogoś za nogę', 'Nabierać kogoś', 'Mówić prawdę', 'Pomagać komuś'], correctAnswer: 'Nabierać kogoś' },
  { id: 89, language: 'English', word: 'Put your foot in your mouth', options: ['Włożyć stopę do ust', 'Palnąć gafę', 'Powiedzieć coś mądrego', 'Być cicho'], correctAnswer: 'Palnąć gafę' },
  { id: 90, language: 'English', word: 'Rain on someone’s parade', options: ['Psuć komuś plany/radość', 'Padać na czyjejś paradzie', 'Organizować paradę', 'Cieszyć się z deszczu'], correctAnswer: 'Psuć komuś plany/radość' },
  { id: 91, language: 'English', word: 'Read between the lines', options: ['Czytać między wierszami', 'Domyślać się ukrytego znaczenia', 'Czytać dosłownie', 'Czytać szybko'], correctAnswer: 'Domyślać się ukrytego znaczenia' },
  { id: 92, language: 'English', word: 'Rome wasn’t built in a day', options: ['Nie od razu Rzym zbudowano', 'Wszystko wymaga czasu', 'Budować miasto', 'Szybka praca'], correctAnswer: 'Nie od razu Rzym zbudowano' },
  { id: 93, language: 'English', word: 'Run like the wind', options: ['Biec jak wiatr', 'Biec bardzo szybko', 'Biec wolno', 'Stać w miejscu'], correctAnswer: 'Biec bardzo szybko' },
  { id: 94, language: 'English', word: 'See eye to eye', options: ['Zgadzać się w pełni', 'Patrzeć sobie w oczy', 'Mieć inne zdanie', 'Kłócić się'], correctAnswer: 'Zgadzać się w pełni' },
  { id: 95, language: 'English', word: 'Shoot yourself in the foot', options: ['Strzelić sobie w stopę', 'Zaszkodzić samemu sobie', 'Odnieść sukces', 'Być ostrożnym'], correctAnswer: 'Zaszkodzić samemu sobie' },
  { id: 96, language: 'English', word: 'Sit on the fence', options: ['Siedzieć na płocie', 'Być niezdecydowanym', 'Podjąć decyzję', 'Odpoczywać w ogrodzie'], correctAnswer: 'Być niezdecydowanym' },
  { id: 97, language: 'English', word: 'Sleep on it', options: ['Przespać się z tym', 'Przemyśleć coś przez noc', 'Pójść spać', 'Podjąć szybką decyzję'], correctAnswer: 'Przemyśleć coś przez noc' },
  { id: 98, language: 'English', word: 'Smell a rat', options: ['Czuć szczura', 'Podejrzewać podstęp', 'Węszyć kłopoty', 'Mieć zwierzaka'], correctAnswer: 'Węszyć kłopoty' },
  { id: 99, language: 'English', word: 'Spill the beans', options: ['Wysypać fasolę', 'Wygadać sekret', 'Gotować obiad', 'Trzymać język za zębami'], correctAnswer: 'Wygadać sekret' },
  { id: 100, language: 'English', word: 'Steal someone’s thunder', options: ['Ukraść komuś piorun', 'Ukraść komuś show / zasługi', 'Być głośnym', 'Pomagać komuś'], correctAnswer: 'Ukraść komuś show / zasługi' },
  { id: 101, language: 'English', word: 'Stick to your guns', options: ['Trzymać się swoich pistoletów', 'Trzymać się swojego zdania', 'Zmienić zdanie', 'Poddać się'], correctAnswer: 'Trzymać się swojego zdania' },
  { id: 102, language: 'English', word: 'Take it with a grain of salt', options: ['Brać to z ziarnem soli', 'Traktować coś z przymrużeniem oka', 'Wierzyć we wszystko', 'Być sceptycznym'], correctAnswer: 'Traktować coś z przymrużeniem oka' },
  { id: 103, language: 'English', word: 'Take the bull by the horns', options: ['Wziąć byka za rogi', 'Stawić czoła problemowi', 'Unikać problemów', 'Iść na corridę'], correctAnswer: 'Wziąć byka za rogi' },
  { id: 104, language: 'English', word: 'The ball is in your court', options: ['Piłka jest na twoim korcie', 'Teraz twoja kolej na ruch', 'Grać w tenisa', 'Unikać odpowiedzialności'], correctAnswer: 'Teraz twoja kolej na ruch' },
  { id: 105, language: 'English', word: 'The best of both worlds', options: ['Połączenie najlepszych cech', 'Najlepsze z obu światów', 'Wybór jednej opcji', 'Kompromis'], correctAnswer: 'Połączenie najlepszych cech' },
  { id: 106, language: 'English', word: 'The early bird catches the worm', options: ['Kto rano wstaje, temu Pan Bóg daje', 'Wczesny ptak łapie robaka', 'Późno chodzić spać', 'Być leniwym'], correctAnswer: 'Kto rano wstaje, temu Pan Bóg daje' },
  { id: 107, language: 'English', word: 'The tip of the iceberg', options: ['Wierzchołek góry lodowej', 'Tylko mała część problemu', 'Cały problem', 'Rozwiązanie problemu'], correctAnswer: 'Wierzchołek góry lodowej' },
  { id: 108, language: 'English', word: 'Through thick and thin', options: ['Na dobre i na złe', 'Przez grube i cienkie', 'W każdych warunkach', 'Tylko w dobrych chwilach'], correctAnswer: 'Na dobre i na złe' },
  { id: 109, language: 'English', word: 'Time flies', options: ['Czas leci', 'Czas mija bardzo szybko', 'Czas się dłuży', 'Zegarek lata'], correctAnswer: 'Czas leci' },
  { id: 110, language: 'English', word: 'To be on the same page', options: ['Być na tej samej stronie', 'Zgadzać się / Myśleć tak samo', 'Czytać tę samą książkę', 'Mieć inne zdanie'], correctAnswer: 'Zgadzać się / Myśleć tak samo' },
  { id: 111, language: 'English', word: 'To cost an arm and a leg', options: ['Być bardzo drogim', 'Kosztować rękę i nogę', 'Być tanim', 'Zapłacić częściami ciała'], correctAnswer: 'Być bardzo drogim' },
  { id: 112, language: 'English', word: 'To cut corners', options: ['Obcinać rogi', 'Robić coś po skrócie', 'Iść na skróty', 'Być dokładnym'], correctAnswer: 'Robić coś po skrócie' },
  { id: 113, language: 'English', word: 'To get out of hand', options: ['Wyjść z rąk', 'Wymknąć się spod kontroli', 'Trzymać coś w ręku', 'Uspokoić sytuację'], correctAnswer: 'Wymknąć się spod kontroli' },
  { id: 114, language: 'English', word: 'To go the extra mile', options: ['Zrobić dodatkowy wysiłek', 'Przejść dodatkową milę', 'Robić minimum', 'Iść na długi spacer'], correctAnswer: 'Zrobić dodatkowy wysiłek' },
  { id: 115, language: 'English', word: 'To hit the nail on the head', options: ['Uderzyć gwoździem w głowę', 'Trafić w sedno', 'Pomylić się', 'Uderzyć młotkiem'], correctAnswer: 'Trafić w sedno' },
  { id: 116, language: 'English', word: 'To keep someone posted', options: ['Trzymać kogoś na poczcie', 'Informować regularnie', 'Wysyłać listy', 'Ukrywać informacje'], correctAnswer: 'Informować regularnie' },
  { id: 117, language: 'English', word: 'To let someone off the hook', options: ['Zdjąć kogoś z haka', 'Uwolnić od odpowiedzialności', 'Złapać rybę', 'Oskarżyć kogoś'], correctAnswer: 'Uwolnić od odpowiedzialności' },
  { id: 118, language: 'English', word: 'To miss the boat', options: ['Spóźnić się na łódkę', 'Przegapić okazję', 'Płynąć statkiem', 'Wykorzystać szansę'], correctAnswer: 'Przegapić okazję' },
  { id: 119, language: 'English', word: 'To play devil’s advocate', options: ['Grać adwokata diabła', 'Prowokować do dyskusji', 'Zgadzać się ze wszystkimi', 'Bronić zła'], correctAnswer: 'Prowokować do dyskusji' },
  { id: 120, language: 'English', word: 'To pull yourself together', options: ['Pociągnąć się razem', 'Wziąć się w garść', 'Rozpaść się', 'Odpocząć'], correctAnswer: 'Wziąć się w garść' },
  { id: 121, language: 'English', word: 'To put two and two together', options: ['Dodać dwa do dwóch', 'Skojarzyć fakty', 'Mylić się w obliczeniach', 'Robić coś prostego'], correctAnswer: 'Skojarzyć fakty' },
  { id: 122, language: 'English', word: 'To rock the boat', options: ['Kołysać łodzią', 'Zaburzać spokój', 'Płynąć spokojnie', 'Naprawiać łódź'], correctAnswer: 'Zaburzać spokój' },
  { id: 123, language: 'English', word: 'To see eye to eye', options: ['Patrzeć oko w oko', 'Zgadzać się całkowicie', 'Kłócić się', 'Patrzeć w różnych kierunkach'], correctAnswer: 'Zgadzać się całkowicie' },
  { id: 124, language: 'English', word: 'To sit tight', options: ['Siedzieć ciasno', 'Czekać cierpliwie', 'Wiercić się', 'Wstać i iść'], correctAnswer: 'Czekać cierpliwie' },
  { id: 125, language: 'English', word: 'To spill the beans', options: ['Wysypać fasolę', 'Wygadać sekret', 'Gotować obiad', 'Trzymać język za zębami'], correctAnswer: 'Wygadać sekret' },
  { id: 126, language: 'English', word: 'To take a rain check', options: ['Wziąć czek na deszcz', 'Przełożyć coś na później', 'Zgodzić się od razu', 'Iść w deszczu'], correctAnswer: 'Przełożyć coś na później' },
  { id: 127, language: 'English', word: 'To throw in the towel', options: ['Rzucić ręcznik', 'Poddawać się', 'Kontynuować walkę', 'Wziąć prysznic'], correctAnswer: 'Poddawać się' },
  { id: 128, language: 'English', word: 'To twist someone’s arm', options: ['Wykręcić komuś rękę', 'Przekonać kogoś do czegoś', 'Zrobić komuś krzywdę', 'Masować ramię'], correctAnswer: 'Przekonać kogoś do czegoś' },
  { id: 129, language: 'English', word: 'Up in the air', options: ['W powietrzu', 'Sytuacja niepewna', 'Latać samolotem', 'Wszystko jasne'], correctAnswer: 'Sytuacja niepewna' },
  { id: 130, language: 'English', word: 'Watch your back', options: ['Uważaj na siebie', 'Patrz na swoje plecy', 'Oglądać się za siebie', 'Być ostrożnym'], correctAnswer: 'Uważaj na siebie' },
  { id: 131, language: 'English', word: 'Walking on air', options: ['Chodzić po powietrzu', 'Być bardzo szczęśliwym', 'Być lekkim jak piórko', 'Skakać z radości'], correctAnswer: 'Być bardzo szczęśliwym' },
  { id: 132, language: 'English', word: 'When pigs fly', options: ['Kiedy świnie latają', 'Coś niemożliwego', 'Na święty nigdy', 'W dalekiej przyszłości'], correctAnswer: 'Na święty nigdy' },
  { id: 133, language: 'English', word: 'You can say that again', options: ['Możesz to powtórzyć', 'Zgadzam się w pełni', 'Nie rozumiem', 'Mów głośniej'], correctAnswer: 'Zgadzam się w pełni' },
  { id: 134, language: 'English', word: 'Your guess is as good as mine', options: ['Twój domysł jest tak dobry jak mój', 'Nie wiem', 'Zgadnij jeszcze raz', 'Masz rację'], correctAnswer: 'Nie wiem' },
];
