export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Polish', word: 'Cześć', options: ['Au revoir', 'Bonjour', 'Merci', 'Pardon'], correctAnswer: 'Bonjour' },
  { id: 2, language: 'Polish', word: 'Do widzenia', options: ['Bonjour', 'Bon matin', 'Bonne nuit', 'Au revoir'], correctAnswer: 'Au revoir' },
  { id: 3, language: 'Polish', word: 'Dziękuję', options: ['S\'il vous plaît', 'De rien', 'Merci', 'Pardon'], correctAnswer: 'Merci' },
  { id: 4, language: 'Polish', word: 'Tak', options: ['Oui', 'Non', 'Peut-être', 'Toujours'], correctAnswer: 'Oui' },
  { id: 5, language: 'Polish', word: 'Nie', options: ['Bien', 'Jamais', 'Pourquoi', 'Non'], correctAnswer: 'Non' },
  { id: 6, language: 'Polish', word: 'Mężczyzna', options: ['Femme', 'Homme', 'Enfant', 'Personne'], correctAnswer: 'Homme' },
  { id: 7, language: 'Polish', word: 'Kobieta', options: ['Homme', 'Fille', 'Femme', 'Garçon'], correctAnswer: 'Femme' },
  { id: 8, language: 'Polish', word: 'Jeść', options: ['Boire', 'Dormir', 'Manger', 'Courir'], correctAnswer: 'Manger' },
  { id: 9, language: 'Polish', word: 'Woda', options: ['Feu', 'Eau', 'Terre', 'Air'], correctAnswer: 'Eau' },
  { id: 10, language: 'Polish', word: 'Kot', options: ['Chien', 'Oiseau', 'Poisson', 'Chat'], correctAnswer: 'Chat' },
  { id: 11, language: 'Polish', word: 'Pies', options: ['Chat', 'Chien', 'Lion', 'Tigre'], correctAnswer: 'Chien' },
  { id: 12, language: 'Polish', word: 'Dom', options: ['Voiture', 'École', 'Maison', 'Magasin'], correctAnswer: 'Maison' },
  { id: 13, language: 'Polish', word: 'Samochód', options: ['Vélo', 'Train', 'Bus', 'Voiture'], correctAnswer: 'Voiture' },
  { id: 14, language: 'Polish', word: 'Szkoła', options: ['Hôpital', 'École', 'Université', 'Bibliothèque'], correctAnswer: 'École' },
  { id: 15, language: 'Polish', word: 'Książka', options: ['Film', 'Chanson', 'Livre', 'Tableau'], correctAnswer: 'Livre' },
  { id: 16, language: 'Polish', word: 'Słońce', options: ['Lune', 'Étoile', 'Soleil', 'Nuage'], correctAnswer: 'Soleil' },
  { id: 17, language: 'Polish', word: 'Miłość', options: ['Haine', 'Joie', 'Tristesse', 'Amour'], correctAnswer: 'Amour' },
  { id: 18, language: 'Polish', word: 'Przyjaciel', options: ['Ennemi', 'Voisin', 'Ami', 'Famille'], correctAnswer: 'Ami' },
  { id: 19, language: 'Polish', word: 'Rodzina', options: ['Amis', 'Famille', 'Parents', 'Voisins'], correctAnswer: 'Famille' },
  { id: 20, language: 'Polish', word: 'Rano', options: ['Soir', 'Nuit', 'Après-midi', 'Matin'], correctAnswer: 'Matin' },
  { id: 21, language: 'Polish', word: 'Noc', options: ['Jour', 'Nuit', 'Soir', 'Matin'], correctAnswer: 'Nuit' },
  { id: 22, language: 'Polish', word: 'Dzień', options: ['Semaine', 'Mois', 'An', 'Jour'], correctAnswer: 'Jour' },
  { id: 23, language: 'Polish', word: 'Tydzień', options: ['Jour', 'Semaine', 'Weekend', 'Mois'], correctAnswer: 'Semaine' },
  { id: 24, language: 'Polish', word: 'Miesiąc', options: ['An', 'Siècle', 'Décennie', 'Mois'], correctAnswer: 'Mois' },
  { id: 25, language: 'Polish', word: 'Rok', options: ['Mois', 'An', 'Jour', 'Heure'], correctAnswer: 'An' },
  { id: 26, language: 'Polish', word: 'Dzisiaj', options: ['Hier', 'Demain', 'Aujourd\'hui', 'Après-demain'], correctAnswer: 'Aujourd\'hui' },
  { id: 27, language: 'Polish', word: 'Jutro', options: ['Aujourd\'hui', 'Hier', 'Avant-hier', 'Demain'], correctAnswer: 'Demain' },
  { id: 28, language: 'Polish', word: 'Proszę', options: ['Merci', 'S\'il vous plaît', 'Pardon', 'De rien'], correctAnswer: 'S\'il vous plaît' },
  { id: 29, language: 'Polish', word: 'Jabłko', options: ['Banane', 'Orange', 'Pomme', 'Poire'], correctAnswer: 'Pomme' },
  { id: 30, language: 'Polish', word: 'Dzień dobry', options: ['Bonsoir', 'Bonne nuit', 'Bonjour', 'Salut'], correctAnswer: 'Bonjour' },
  { id: 31, language: 'Polish', word: 'Dobry wieczór', options: ['Bonjour', 'Bonne nuit', 'Bonsoir', 'Bonne journée'], correctAnswer: 'Bonsoir' },
  { id: 32, language: 'Polish', word: 'Dobranoc', options: ['Bonjour', 'Bonsoir', 'Bonne nuit', 'Au revoir'], correctAnswer: 'Bonne nuit' },
  { id: 33, language: 'Polish', word: 'Przepraszam', options: ['Merci', 'S\'il vous plaît', 'Pardon', 'Salut'], correctAnswer: 'Pardon' },
  { id: 34, language: 'Polish', word: 'Praca', options: ['Vacances', 'Plaisir', 'Travail', 'École'], correctAnswer: 'Travail' },
  { id: 35, language: 'Polish', word: 'Miasto', options: ['Village', 'Pays', 'Ville', 'Rue'], correctAnswer: 'Ville' },
  { id: 36, language: 'Polish', word: 'Jedzenie', options: ['Boisson', 'Eau', 'Nourriture', 'Pain'], correctAnswer: 'Nourriture' },
  { id: 37, language: 'Polish', word: 'Chleb', options: ['Lait', 'Eau', 'Pain', 'Fromage'], correctAnswer: 'Pain' },
  { id: 38, language: 'Polish', word: 'Mleko', options: ['Jus', 'Eau', 'Lait', 'Thé'], correctAnswer: 'Lait' },
  { id: 39, language: 'Polish', word: 'Kawa', options: ['Thé', 'Eau', 'Café', 'Jus'], correctAnswer: 'Café' },
  { id: 40, language: 'Polish', word: 'Herbata', options: ['Café', 'Lait', 'Thé', 'Eau'], correctAnswer: 'Thé' },
  { id: 41, language: 'Polish', word: 'Czas', options: ['Espace', 'Lieu', 'Temps', 'Jour'], correctAnswer: 'Temps' },
  { id: 42, language: 'Polish', word: 'Godzina', options: ['Minute', 'Seconde', 'Heure', 'Jour'], correctAnswer: 'Heure' },
  { id: 43, language: 'Polish', word: 'Wczoraj', options: ['Aujourd\'hui', 'Demain', 'Hier', 'Maintenant'], correctAnswer: 'Hier' },
  { id: 44, language: 'Polish', word: 'Pieniądze', options: ['Or', 'Argent (métal)', 'Argent', 'Crédit'], correctAnswer: 'Argent' },
  { id: 45, language: 'Polish', word: 'Sklep', options: ['Bureau', 'École', 'Magasin', 'Maison'], correctAnswer: 'Magasin' },
  { id: 46, language: 'Polish', word: 'Ulica', options: ['Route', 'Avenue', 'Rue', 'Chemin'], correctAnswer: 'Rue' },
  { id: 47, language: 'Polish', word: 'Droga', options: ['Rue', 'Chemin', 'Route', 'Autoroute'], correctAnswer: 'Route' },
  { id: 48, language: 'Polish', word: 'Matka', options: ['Père', 'Sœur', 'Mère', 'Frère'], correctAnswer: 'Mère' },
  { id: 49, language: 'Polish', word: 'Ojciec', options: ['Mère', 'Frère', 'Père', 'Sœur'], correctAnswer: 'Père' },
  { id: 50, language: 'Polish', word: 'Dziecko', options: ['Adulte', 'Homme', 'Femme', 'Enfant'], correctAnswer: 'Enfant' },
  { id: 51, language: 'Polish', word: 'Pytanie', options: ['Réponse', 'Problème', 'Question', 'Test'], correctAnswer: 'Question' },
  { id: 52, language: 'Polish', word: 'Odpowiedź', options: ['Question', 'Réponse', 'Test', 'Solution'], correctAnswer: 'Réponse' },
  { id: 53, language: 'Polish', word: 'Problem', options: ['Solution', 'Question', 'Problème', 'Réponse'], correctAnswer: 'Problème' },
  { id: 54, language: 'Polish', word: 'Pomoc', options: ['Difficulté', 'Aide', 'Travail', 'Jeu'], correctAnswer: 'Aide' },
  { id: 55, language: 'Polish', word: 'Szybko', options: ['Lentement', 'Vite', 'Rapidement', 'Fort'], correctAnswer: 'Vite' },
  { id: 56, language: 'Polish', word: 'Wolno', options: ['Vite', 'Rapidement', 'Lentement', 'Doucement'], correctAnswer: 'Lentement' },
  { id: 57, language: 'Polish', word: 'Duży', options: ['Petit', 'Grand', 'Haut', 'Court'], correctAnswer: 'Grand' },
  { id: 58, language: 'Polish', word: 'Mały', options: ['Grand', 'Large', 'Petit', 'Énorme'], correctAnswer: 'Petit' },
  { id: 59, language: 'Polish', word: 'Dobry', options: ['Mauvais', 'Bon', 'Gentil', 'Génial'], correctAnswer: 'Bon' },
  { id: 60, language: 'Polish', word: 'Zły', options: ['Bon', 'Gentil', 'Mauvais', 'Méchant'], correctAnswer: 'Mauvais' },
  { id: 61, language: 'Polish', word: 'Nowy', options: ['Vieux', 'Nouveau', 'Jeune', 'Ancien'], correctAnswer: 'Nouveau' },
  { id: 62, language: 'Polish', word: 'Stary', options: ['Nouveau', 'Jeune', 'Vieux', 'Moderne'], correctAnswer: 'Vieux' },
  { id: 63, language: 'Polish', word: 'Ciepły', options: ['Froid', 'Frais', 'Chaud', 'Brûlant'], correctAnswer: 'Chaud' },
  { id: 64, language: 'Polish', word: 'Zimny', options: ['Chaud', 'Brûlant', 'Froid', 'Frais'], correctAnswer: 'Froid' },
  { id: 65, language: 'Polish', word: 'Łatwy', options: ['Dur', 'Difficile', 'Facile', 'Simple'], correctAnswer: 'Facile' },
  { id: 66, language: 'Polish', word: 'Trudny', options: ['Facile', 'Simple', 'Difficile', 'Léger'], correctAnswer: 'Difficile' },
  { id: 67, language: 'Polish', word: 'Otwarty', options: ['Fermé', 'Clos', 'Ouvert', 'Verrouillé'], correctAnswer: 'Ouvert' },
  { id: 68, language: 'Polish', word: 'Zamknięty', options: ['Ouvert', 'Libre', 'Fermé', 'Déverrouillé'], correctAnswer: 'Fermé' },
  { id: 69, language: 'Polish', word: 'Jasny', options: ['Sombre', 'Noir', 'Clair', 'Obscur'], correctAnswer: 'Clair' },
  { id: 70, language: 'Polish', word: 'Ciemny', options: ['Clair', 'Brillant', 'Sombre', 'Blanc'], correctAnswer: 'Sombre' },
  { id: 71, language: 'Polish', word: 'Film', options: ['Livre', 'Chanson', 'Film', 'Tableau'], correctAnswer: 'Film' },
  { id: 72, language: 'Polish', word: 'Muzyka', options: ['Art', 'Film', 'Musique', 'Danse'], correctAnswer: 'Musique' },
  { id: 73, language: 'Polish', word: 'Kolor', options: ['Forme', 'Taille', 'Couleur', 'Son'], correctAnswer: 'Couleur' },
  { id: 74, language: 'Polish', word: 'Czerwony', options: ['Bleu', 'Vert', 'Rouge', 'Jaune'], correctAnswer: 'Rouge' },
  { id: 75, language: 'Polish', word: 'Niebieski', options: ['Vert', 'Rouge', 'Bleu', 'Jaune'], correctAnswer: 'Bleu' },
  { id: 76, language: 'Polish', word: 'Zielony', options: ['Rouge', 'Bleu', 'Vert', 'Jaune'], correctAnswer: 'Vert' },
  { id: 77, language: 'Polish', word: 'Żółty', options: ['Rouge', 'Bleu', 'Vert', 'Jaune'], correctAnswer: 'Jaune' },
  { id: 78, language: 'Polish', word: 'Biały', options: ['Noir', 'Gris', 'Blanc', 'Marron'], correctAnswer: 'Blanc' },
  { id: 79, language: 'Polish', word: 'Czarny', options: ['Blanc', 'Gris', 'Noir', 'Marron'], correctAnswer: 'Noir' },
  { id: 80, language: 'Polish', word: 'Iść', options: ['Courir', 'Aller', 'Rester', 'S\'asseoir'], correctAnswer: 'Aller' },
  { id: 81, language: 'Polish', word: 'Biegać', options: ['Marcher', 'Courir', 'Sauter', 'Nager'], correctAnswer: 'Courir' },
  { id: 82, language: 'Polish', word: 'Mówić', options: ['Écouter', 'Parler', 'Lire', 'Écrire'], correctAnswer: 'Parler' },
  { id: 83, language: 'Polish', word: 'Widzieć', options: ['Entendre', 'Voir', 'Toucher', 'Sentir'], correctAnswer: 'Voir' },
  { id: 84, language: 'Polish', word: 'Wiedzieć', options: ['Penser', 'Savoir', 'Apprendre', 'Oublier'], correctAnswer: 'Savoir' },
  { id: 85, language: 'Polish', word: 'Chcieć', options: ['Avoir besoin', 'Vouloir', 'Avoir', 'Aimer'], correctAnswer: 'Vouloir' },
  { id: 86, language: 'Polish', word: 'Móc', options: ['Devoir', 'Falloir', 'Pouvoir', 'Vouloir'], correctAnswer: 'Pouvoir' },
  { id: 87, language: 'Polish', word: 'Musieć', options: ['Pouvoir', 'Falloir', 'Devoir', 'Vouloir'], correctAnswer: 'Devoir' },
  { id: 88, language: 'Polish', word: 'Spać', options: ['Se réveiller', 'Dormir', 'Manger', 'Boire'], correctAnswer: 'Dormir' },
  { id: 89, language: 'Polish', word: 'Myśleć', options: ['Savoir', 'Penser', 'Sentir', 'Croire'], correctAnswer: 'Penser' },
  { id: 90, language: 'Polish', word: 'Lubić', options: ['Adorer', 'Détester', 'Aimer', 'Préférer'], correctAnswer: 'Aimer' },
  { id: 91, language: 'Polish', word: 'Zawsze', options: ['Jamais', 'Parfois', 'Toujours', 'Souvent'], correctAnswer: 'Toujours' },
  { id: 92, language: 'Polish', word: 'Nigdy', options: ['Toujours', 'Souvent', 'Jamais', 'Parfois'], correctAnswer: 'Jamais' },
  { id: 93, language: 'Polish', word: 'Często', options: ['Rarement', 'Parfois', 'Souvent', 'Toujours'], correctAnswer: 'Souvent' },
  { id: 94, language: 'Polish', word: 'Rzadko', options: ['Souvent', 'Toujours', 'Rarement', 'Jamais'], correctAnswer: 'Rarement' },
  { id: 95, language: 'Polish', word: 'Tutaj', options: ['Là-bas', 'Ici', 'Où', 'Partout'], correctAnswer: 'Ici' },
  { id: 96, language: 'Polish', word: 'Tam', options: ['Ici', 'Là-bas', 'Près', 'Loin'], correctAnswer: 'Là-bas' },
  { id: 97, language: 'Polish', word: 'Dlaczego', options: ['Quoi', 'Quand', 'Pourquoi', 'Qui'], correctAnswer: 'Pourquoi' },
  { id: 98, language: 'Polish', word: 'Ponieważ', options: ['Mais', 'Donc', 'Parce que', 'Et'], correctAnswer: 'Parce que' },
  { id: 99, language: 'Polish', word: 'Ale', options: ['Et', 'Ou', 'Mais', 'Donc'], correctAnswer: 'Mais' },
  { id: 100, language: 'Polish', word: 'I', options: ['Ou', 'Mais', 'Et', 'Donc'], correctAnswer: 'Et' }
];
