export interface IrregularVerbQuestion {
  id: number;
  verb: string; // Base form
  form2: string; // Past simple
  form3: string; // Past participle
  translationOptions: string[];
  correctTranslation: string;
}

export const questions: IrregularVerbQuestion[] = [
  {
    id: 1,
    verb: 'be',
    form2: 'was/were',
    form3: 'been',
    translationOptions: ['być', 'mieć', 'robić'],
    correctTranslation: 'być',
  },
  {
    id: 2,
    verb: 'go',
    form2: 'went',
    form3: 'gone',
    translationOptions: ['przychodzić', 'iść', 'biec'],
    correctTranslation: 'iść',
  },
  {
    id: 3,
    verb: 'do',
    form2: 'did',
    form3: 'done',
    translationOptions: ['robić', 'mówić', 'widzieć'],
    correctTranslation: 'robić',
  },
  {
    id: 4,
    verb: 'have',
    form2: 'had',
    form3: 'had',
    translationOptions: ['dawać', 'brać', 'mieć'],
    correctTranslation: 'mieć',
  },
  {
    id: 5,
    verb: 'make',
    form2: 'made',
    form3: 'made',
    translationOptions: ['tworzyć', 'niszczyć', 'kupować'],
    correctTranslation: 'tworzyć',
  },
  {
    id: 6,
    verb: 'see',
    form2: 'saw',
    form3: 'seen',
    translationOptions: ['słyszeć', 'patrzeć', 'widzieć'],
    correctTranslation: 'widzieć',
  },
  {
    id: 7,
    verb: 'say',
    form2: 'said',
    form3: 'said',
    translationOptions: ['mówić', 'pytać', 'odpowiadać'],
    correctTranslation: 'mówić',
  },
  {
    id: 8,
    verb: 'get',
    form2: 'got',
    form3: 'got/gotten',
    translationOptions: ['dostawać', 'tracić', 'wysyłać'],
    correctTranslation: 'dostawać',
  },
  {
    id: 9,
    verb: 'eat',
    form2: 'ate',
    form3: 'eaten',
    translationOptions: ['pić', 'jeść', 'spać'],
    correctTranslation: 'jeść',
  },
  {
    id: 10,
    verb: 'take',
    form2: 'took',
    form3: 'taken',
    translationOptions: ['dawać', 'brać', 'przynosić'],
    correctTranslation: 'brać',
  },
  {
    id: 11,
    verb: 'begin',
    form2: 'began',
    form3: 'begun',
    translationOptions: ['kończyć', 'zaczynać', 'kontynuować'],
    correctTranslation: 'zaczynać',
  },
  {
    id: 12,
    verb: 'break',
    form2: 'broke',
    form3: 'broken',
    translationOptions: ['naprawiać', 'budować', 'łamać'],
    correctTranslation: 'łamać',
  },
  {
    id: 13,
    verb: 'choose',
    form2: 'chose',
    form3: 'chosen',
    translationOptions: ['odrzucać', 'ignorować', 'wybierać'],
    correctTranslation: 'wybierać',
  },
  {
    id: 14,
    verb: 'come',
    form2: 'came',
    form3: 'come',
    translationOptions: ['przychodzić', 'wychodzić', 'zostawać'],
    correctTranslation: 'przychodzić',
  },
  {
    id: 15,
    verb: 'drink',
    form2: 'drank',
    form3: 'drunk',
    translationOptions: ['jeść', 'pić', 'gotować'],
    correctTranslation: 'pić',
  },
  {
    id: 16,
    verb: 'drive',
    form2: 'drove',
    form3: 'driven',
    translationOptions: ['prowadzić (pojazd)', 'chodzić', 'latać'],
    correctTranslation: 'prowadzić (pojazd)',
  },
  {
    id: 17,
    verb: 'fall',
    form2: 'fell',
    form3: 'fallen',
    translationOptions: ['wstawać', 'upadać', 'skakać'],
    correctTranslation: 'upadać',
  },
  {
    id: 18,
    verb: 'find',
    form2: 'found',
    form3: 'found',
    translationOptions: ['gubić', 'szukać', 'znajdować'],
    correctTranslation: 'znajdować',
  },
  {
    id: 19,
    verb: 'fly',
    form2: 'flew',
    form3: 'flown',
    translationOptions: ['pływać', 'latać', 'biegać'],
    correctTranslation: 'latać',
  },
  {
    id: 20,
    verb: 'forget',
    form2: 'forgot',
    form3: 'forgotten',
    translationOptions: ['pamiętać', 'uczyć się', 'zapominać'],
    correctTranslation: 'zapominać',
  },
  {
    id: 21,
    verb: 'give',
    form2: 'gave',
    form3: 'given',
    translationOptions: ['brać', 'dawać', 'otrzymywać'],
    correctTranslation: 'dawać',
  },
  {
    id: 22,
    verb: 'know',
    form2: 'knew',
    form3: 'known',
    translationOptions: ['myśleć', 'wiedzieć/znać', 'ignorować'],
    correctTranslation: 'wiedzieć/znać',
  },
  {
    id: 23,
    verb: 'leave',
    form2: 'left',
    form3: 'left',
    translationOptions: ['przybywać', 'zostawać', 'opuszczać/zostawiać'],
    correctTranslation: 'opuszczać/zostawiać',
  },
  {
    id: 24,
    verb: 'lose',
    form2: 'lost',
    form3: 'lost',
    translationOptions: ['znajdować', 'wygrywać', 'gubić/tracić'],
    correctTranslation: 'gubić/tracić',
  },
  {
    id: 25,
    verb: 'run',
    form2: 'ran',
    form3: 'run',
    translationOptions: ['chodzić', 'biec', 'stać'],
    correctTranslation: 'biec',
  },
  {
    id: 26,
    verb: 'sing',
    form2: 'sang',
    form3: 'sung',
    translationOptions: ['tańczyć', 'śpiewać', 'mówić'],
    correctTranslation: 'śpiewać',
  },
  {
    id: 27,
    verb: 'speak',
    form2: 'spoke',
    form3: 'spoken',
    translationOptions: ['słuchać', 'pisać', 'mówić'],
    correctTranslation: 'mówić',
  },
  {
    id: 28,
    verb: 'swim',
    form2: 'swam',
    form3: 'swum',
    translationOptions: ['pływać', 'nurkować', 'biegać'],
    correctTranslation: 'pływać',
  },
  {
    id: 29,
    verb: 'write',
    form2: 'wrote',
    form3: 'written',
    translationOptions: ['czytać', 'pisać', 'rysować'],
    correctTranslation: 'pisać',
  },
  {
    id: 30,
    verb: 'win',
    form2: 'won',
    form3: 'won',
    translationOptions: ['przegrywać', 'remisować', 'wygrywać'],
    correctTranslation: 'wygrywać',
  },
];
