export interface Question {
  id: number;
  language: 'English';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'English', word: 'ask out', options: ['zapytać o drogę', 'poprosić o wyjście', 'zaprośić kogoś na randkę', 'wypytać kogoś'], correctAnswer: 'zaprośić kogoś na randkę' },
  { id: 2, language: 'English', word: 'back up', options: ['cofnąć się', 'wrócić', 'poprzeć / zrobić kopię zapasową', 'zrezygnować'], correctAnswer: 'poprzeć / zrobić kopię zapasową' },
  { id: 3, language: 'English', word: 'blow up', options: ['nadmuchać', 'powiększyć', 'zdmuchnąć', 'wybuchnąć / zdenerwować się'], correctAnswer: 'wybuchnąć / zdenerwować się' },
  { id: 4, language: 'English', word: 'break down', options: ['przełamać', 'zniszczyć', 'zepsuć się / załamać się', 'rozbić'], correctAnswer: 'zepsuć się / załamać się' },
  { id: 5, language: 'English', word: 'break up', options: ['zepsuć się', 'przerwać', 'złamać', 'rozstać się'], correctAnswer: 'rozstać się' },
  { id: 6, language: 'English', word: 'bring up', options: ['przynieść na górę', 'podnieść', 'poruszyć temat / wychować', 'zwrócić'], correctAnswer: 'poruszyć temat / wychować' },
  { id: 7, language: 'English', word: 'call back', options: ['odwołać', 'zadzwonić później', 'przedzwonić', 'oddzwonić'], correctAnswer: 'oddzwonić' },
  { id: 8, language: 'English', word: 'call off', options: ['zadzwonić', 'odwołać', 'wyłączyć', 'przełożyć'], correctAnswer: 'odwołać' },
  { id: 9, language: 'English', word: 'carry on', options: ['nieść dalej', 'kontynuować', 'przewozić', 'zachowywać się'], correctAnswer: 'kontynuować' },
  { id: 10, language: 'English', word: 'catch up', options: ['złapać', 'dogonić', 'nadrobić zaległości', 'spotkać się'], correctAnswer: 'nadrobić zaległości' },
  { id: 11, language: 'English', word: 'check in', options: ['sprawdzić', 'zameldować się / dać znać', 'zapłacić', 'wypisać się'], correctAnswer: 'zameldować się / dać znać' },
  { id: 12, language: 'English', word: 'check out', options: ['sprawdzić', 'przejrzeć', 'opłacić rachunek', 'wymeldować się / sprawdzić'], correctAnswer: 'wymeldować się / sprawdzić' },
  { id: 13, language: 'English', word: 'come across', options: ['przejść przez', 'natknąć się', 'spotkać', 'znaleźć'], correctAnswer: 'natknąć się' },
  { id: 14, language: 'English', word: 'come back', options: ['odejść', 'wrócić', 'przyjść', 'odwiedzić'], correctAnswer: 'wrócić' },
  { id: 15, language: 'English', word: 'come in', options: ['wyjść', 'wejść', 'wrócić', 'odejść'], correctAnswer: 'wejść' },
  { id: 16, language: 'English', word: 'come out', options: ['wejść', 'wrócić', 'wyjść / ukazać się', 'zostać'], correctAnswer: 'wyjść / ukazać się' },
  { id: 17, language: 'English', word: 'come over', options: ['przejść przez', 'przejechać', 'odwiedzić', 'wpaść z wizytą'], correctAnswer: 'wpaść z wizytą' },
  { id: 18, language: 'English', word: 'cut down', options: ['ściąć', 'przeciąć', 'ograniczyć', 'zmniejszyć'], correctAnswer: 'ograniczyć' },
  { id: 19, language: 'English', word: 'cut off', options: ['odciąć / przerwać', 'wyciąć', 'obciąć', 'skrócić'], correctAnswer: 'odciąć / przerwać' },
  { id: 20, language: 'English', word: 'deal with', options: ['handlować czymś', 'radzić sobie z czymś', 'unikać czegoś', 'zajmować się'], correctAnswer: 'radzić sobie z czymś' },
  { id: 21, language: 'English', word: 'drop by', options: ['upuścić coś', 'wpaść na chwilę', 'zrezygnować', 'przejść obok'], correctAnswer: 'wpaść na chwilę' },
  { id: 22, language: 'English', word: 'drop off', options: ['odpaść', 'podrzucić / zasnąć', 'upuścić', 'wysiąść'], correctAnswer: 'podrzucić / zasnąć' },
  { id: 23, language: 'English', word: 'figure out', options: ['rysować postać', 'liczyć', 'zrozumieć / rozgryźć', 'wyobrazić sobie'], correctAnswer: 'zrozumieć / rozgryźć' },
  { id: 24, language: 'English', word: 'fill in', options: ['wypełnić / zastąpić', 'napełnić', 'uzupełnić', 'wlać'], correctAnswer: 'wypełnić / zastąpić' },
  { id: 25, language: 'English', word: 'find out', options: ['znaleźć na zewnątrz', 'dowiedzieć się', 'szukać', 'odkryć'], correctAnswer: 'dowiedzieć się' },
  { id: 26, language: 'English', word: 'get along', options: ['iść wzdłuż', 'dogadywać się', 'radzić sobie', 'oddalić się'], correctAnswer: 'dogadywać się' },
  { id: 27, language: 'English', word: 'get back', options: ['dostać z powrotem', 'cofnąć się', 'zemścić się', 'wrócić'], correctAnswer: 'wrócić' },
  { id: 28, language: 'English', word: 'get in', options: ['wyjść', 'dostać się do środka', 'wejść / dostać się', 'wsiąść'], correctAnswer: 'wejść / dostać się' },
  { id: 29, language: 'English', word: 'get off', options: ['zejść', 'wysiąść / zejść z pracy', 'wstać', 'uciec'], correctAnswer: 'wysiąść / zejść z pracy' },
  { id: 30, language: 'English', word: 'get on', options: ['zejść', 'wsiąść / radzić sobie', 'dogadywać się', 'kontynuować'], correctAnswer: 'wsiąść / radzić sobie' },
  { id: 31, language: 'English', word: 'get over', options: ['przejść nad', 'przeskoczyć', 'dojść do siebie', 'zapomnieć'], correctAnswer: 'dojść do siebie' },
  { id: 32, language: 'English', word: 'get through', options: ['przejść przez', 'przebrnąć / dodzwonić się', 'zdać egzamin', 'zakończyć'], correctAnswer: 'przebrnąć / dodzwonić się' },
  { id: 33, language: 'English', word: 'give back', options: ['oddać', 'podarować', 'zwrócić', 'cofnąć'], correctAnswer: 'oddać' },
  { id: 34, language: 'English', word: 'give up', options: ['oddać', 'poddawać się / rzucić coś', 'zrezygnować', 'porzucić'], correctAnswer: 'poddawać się / rzucić coś' },
  { id: 35, language: 'English', word: 'go ahead', options: ['iść prosto', 'zacząć', 'kontynuować / zgodzić się', 'proszę bardzo'], correctAnswer: 'kontynuować / zgodzić się' },
  { id: 36, language: 'English', word: 'go back', options: ['cofać się', 'wrócić', 'pójść z tyłu', 'zrezygnować'], correctAnswer: 'wrócić' },
  { id: 37, language: 'English', word: 'go on', options: ['iść dalej', 'kontynuować', 'dziać się / kontynuować', 'włączać'], correctAnswer: 'dziać się / kontynuować' },
  { id: 38, language: 'English', word: 'go out', options: ['wyjść', 'wychodzić z domu', 'randkować', 'zgasnąć'], correctAnswer: 'wyjść' },
  { id: 39, language: 'English', word: 'go through', options: ['przejść przez coś', 'przejrzeć', 'doświadczyć', 'przeanalizować'], correctAnswer: 'przejść przez coś' },
  { id: 40, language: 'English', word: 'hang out', options: ['wieszać na zewnątrz', 'spędzać czas', 'czekać', 'relaksować się'], correctAnswer: 'spędzać czas' },
  { id: 41, language: 'English', word: 'hold on', options: ['trzymać się', 'poczekać', 'zawiesić', 'czekać na linii'], correctAnswer: 'poczekać' },
  { id: 42, language: 'English', word: 'keep on', options: ['trzymać na', 'zachować', 'kontynuować', 'robić dalej'], correctAnswer: 'kontynuować' },
  { id: 43, language: 'English', word: 'let down', options: ['opuścić', 'rozczarować', 'zawieść', 'obniżyć'], correctAnswer: 'zawieść' },
  { id: 44, language: 'English', word: 'look after', options: ['patrzeć za', 'szukać', 'opiekować się', 'doglądać'], correctAnswer: 'opiekować się' },
  { id: 45, language: 'English', word: 'look for', options: ['szukać', 'patrzeć na', 'znaleźć', 'oczekiwać'], correctAnswer: 'szukać' },
  { id: 46, language: 'English', word: 'look forward to', options: ['patrzeć w przód', 'oczekiwać z niecierpliwością', 'planować', 'nie móc się doczekać'], correctAnswer: 'nie móc się doczekać' },
  { id: 47, language: 'English', word: 'look into', options: ['patrzeć w', 'zbadać', 'sprawdzić / zbadać', 'przejrzeć'], correctAnswer: 'sprawdzić / zbadać' },
  { id: 48, language: 'English', word: 'look out', options: ['patrzeć na zewnątrz', 'uważać', 'wypatrywać', 'strzec się'], correctAnswer: 'uważać' },
  { id: 49, language: 'English', word: 'make up', options: ['robić makijaż', 'pogodzić się / wymyślić', 'zmyślić historię', 'nadrobić'], correctAnswer: 'pogodzić się / wymyślić' },
  { id: 50, language: 'English', word: 'move on', options: ['przesunąć się', 'iść dalej', 'zapomnieć o czymś', 'zacząć od nowa'], correctAnswer: 'iść dalej' },
  { id: 51, language: 'English', word: 'open up', options: ['otworzyć', 'otworzyć się', 'rozpocząć', 'udostępnić'], correctAnswer: 'otworzyć się' },
  { id: 52, language: 'English', word: 'pick up', options: ['podnieść', 'odebrać / podnieść / nauczyć się', 'zebrać', 'podwieźć'], correctAnswer: 'odebrać / podnieść / nauczyć się' },
  { id: 53, language: 'English', word: 'put off', options: ['odłożyć ubranie', 'odkładać', 'zniechęcać', 'przesunąć'], correctAnswer: 'odkładać' },
  { id: 54, language: 'English', word: 'run into', options: ['wbiec do', 'spotkać przypadkiem', 'zderzyć się z', 'wpaść na kogoś'], correctAnswer: 'wpaść na kogoś' },
  { id: 55, language: 'English', word: 'settle down', options: ['usiąść', 'uspokoić się', 'ustatkowac się', 'zamieszkać'], correctAnswer: 'ustatkowac się' },
  { id: 56, language: 'English', word: 'show up', options: ['pokazać', 'zjawić się', 'pojawić się', 'zdemaskować'], correctAnswer: 'pojawić się' },
  { id: 57, language: 'English', word: 'shut up', options: ['zamknąć', 'uciszyć', 'zamknąć się', 'milczeć'], correctAnswer: 'zamknąć się' },
  { id: 58, language: 'English', word: 'sort out', options: ['sortować', 'uporządkować', 'rozwiązać', 'ogarnąć / rozwiązać'], correctAnswer: 'ogarnąć / rozwiązać' },
  { id: 59, language: 'English', word: 'take over', options: ['przejąć', 'przejąć kontrolę', 'zastąpić', 'zająć'], correctAnswer: 'przejąć' },
  { id: 60, language: 'English', word: 'take up', options: ['podnieść', 'zająć', 'zacząć (hobby)', 'skrócić'], correctAnswer: 'zacząć (hobby)' },
  { id: 61, language: 'English', word: 'think over', options: ['przemyśleć', 'rozważyć', 'zastanowić się', 'myśleć o'], correctAnswer: 'przemyśleć' },
  { id: 62, language: 'English', word: 'throw away', options: ['odrzucić', 'wyrzucić', 'zmarnować', 'pozbyć się'], correctAnswer: 'wyrzucić' },
  { id: 63, language: 'English', word: 'turn down', options: ['odrzucić / ściszyć', 'skręcić w dół', 'zmniejszyć', 'odmówić'], correctAnswer: 'odrzucić / ściszyć' },
  { id: 64, language: 'English', word: 'turn up', options: ['pojawić się / podgłośnić', 'podkręcić', 'znaleźć się', 'zwiększyć'], correctAnswer: 'pojawić się / podgłośnić' },
  { id: 65, language: 'English', word: 'work out', options: ['rozwiązać / ćwiczyć', 'trenować', 'obliczyć', 'udać się'], correctAnswer: 'rozwiązać / ćwiczyć' },
  { id: 66, language: 'English', word: 'write down', options: ['zapisać', 'notować', 'spisać', 'opisać'], correctAnswer: 'zapisać' },
  { id: 67, language: 'English', word: 'set up', options: ['ustawić', 'założyć / zorganizować', 'przygotować', 'zainstalować'], correctAnswer: 'założyć / zorganizować' },
  { id: 68, language: 'English', word: 'slow down', options: ['zwolnić', 'spowolnić', 'hamować', 'zmniejszyć tempo'], correctAnswer: 'zwolnić' },
  { id: 69, language: 'English', word: 'speed up', options: ['przyspieszyć', 'zwiększyć prędkość', 'przyśpieszać', 'przyśpieszyć'], correctAnswer: 'przyspieszyć' },
  { id: 70, language: 'English', word: 'step down', options: ['zejść', 'ustąpić', 'zrezygnować', 'zmniejszyć'], correctAnswer: 'ustąpić' },
  { id: 71, language: 'English', word: 'step up', options: ['podejść', 'zwiększyć zaangażowanie', 'wzmocnić', 'przyspieszyć'], correctAnswer: 'zwiększyć zaangażowanie' },
  { id: 72, language: 'English', word: 'break out', options: ['wydostać się', 'uciec', 'wybuchnąć / uciec', 'wyłamać się'], correctAnswer: 'wybuchnąć / uciec' },
  { id: 73, language: 'English', word: 'bring back', options: ['przywrócić', 'przynieść z powrotem', 'oddać', 'przypomnieć'], correctAnswer: 'przywrócić' },
  { id: 74, language: 'English', word: 'calm down', options: ['uspokoić się', 'ochłonąć', 'zrelaksować się', 'opanować się'], correctAnswer: 'uspokoić się' },
  { id: 75, language: 'English', word: 'check over', options: ['sprawdzić pobieżnie', 'przejrzeć', 'skontrolować', 'sprawdzić dokładnie'], correctAnswer: 'sprawdzić dokładnie' },
  { id: 76, language: 'English', word: 'clear up', options: ['wyjaśnić / posprzątać', 'oczyścić', 'rozjaśnić się (o pogodzie)', 'uporządkować'], correctAnswer: 'wyjaśnić / posprzątać' },
  { id: 77, language: 'English', word: 'come along', options: ['iść wzdłuż', 'dołączyć', 'robić postępy', 'przyjść / robić postępy'], correctAnswer: 'przyjść / robić postępy' },
  { id: 78, language: 'English', word: 'cut back', options: ['przyciąć', 'ograniczyć wydatki', 'zredukować', 'obciąć'], correctAnswer: 'ograniczyć wydatki' },
  { id: 79, language: 'English', word: 'fall apart', options: ['rozpaść się', 'rozlecieć się', 'załamać się', 'zniszczyć'], correctAnswer: 'rozpaść się' },
  { id: 80, language: 'English', word: 'fall behind', options: ['odpaść', 'zostać w tyle', 'mieć zaległości', 'spóźniać się'], correctAnswer: 'zostać w tyle' },
  { id: 81, language: 'English', word: 'fill out', options: ['wypełnić formularz', 'napełnić', 'uzupełnić', 'wypełnić'], correctAnswer: 'wypełnić formularz' },
  { id: 82, language: 'English', word: 'get away', options: ['uciec', 'wyjechać / uciec', 'wydostać się', 'oddalić się'], correctAnswer: 'wyjechać / uciec' },
  { id: 83, language: 'English', word: 'get by', options: ['przejść obok', 'radzić sobie', 'przetrwać', 'utrzymać się'], correctAnswer: 'radzić sobie' },
  { id: 84, language: 'English', word: 'get together', options: ['zebrać razem', 'spotkać się', 'zgromadzić się', 'umówić się'], correctAnswer: 'spotkać się' },
  { id: 85, language: 'English', word: 'give in', options: ['oddać', 'ulec', 'poddawać się', 'ustąpić'], correctAnswer: 'ulec' },
  { id: 86, language: 'English', word: 'go wrong', options: ['pójść źle', 'pójść nie tak', 'pomylić się', 'zepsuć się'], correctAnswer: 'pójść nie tak' },
  { id: 87, language: 'English', word: 'hang on', options: ['zawiesić na', 'poczekać', 'trzymać się', 'czekać'], correctAnswer: 'poczekać' },
  { id: 88, language: 'English', word: 'keep up', options: ['trzymać w górze', 'nadążać', 'utrzymywać', 'kontynuować'], correctAnswer: 'nadążać' },
  { id: 89, language: 'English', word: 'log in', options: ['zapisać się', 'wejść', 'zalogować się', 'zarejestrować'], correctAnswer: 'zalogować się' },
  { id: 90, language: 'English', word: 'log out', options: ['wyjść', 'wylogować się', 'opuścić', 'zakończyć'], correctAnswer: 'wylogować się' },
  { id: 91, language: 'English', word: 'sign in', options: ['podpisać się / zalogować', 'wpisać się', 'zameldować się', 'zarejestrować'], correctAnswer: 'podpisać się / zalogować' },
  { id: 92, language: 'English', word: 'sign out', options: ['wypisać się', 'wymeldować się', 'zrezygnować', 'wylogować się'], correctAnswer: 'wylogować się' },
  { id: 93, language: 'English', word: 'turn on', options: ['włączyć', 'uruchomić', 'odpalić', 'nakręcić'], correctAnswer: 'włączyć' },
  { id: 94, language: 'English', word: 'turn off', options: ['skręcić', 'wyłączyć', 'zgasić', 'zniechęcić'], correctAnswer: 'wyłączyć' },
  { id: 95, language: 'English', word: 'plug in', options: ['podłączyć', 'włączyć do prądu', 'zatkać', 'wepchnąć'], correctAnswer: 'podłączyć' },
  { id: 96, language: 'English', word: 'back out', options: ['cofnąć się', 'wycofać się', 'zrezygnować', 'odstąpić'], correctAnswer: 'wycofać się' },
  { id: 97, language: 'English', word: 'boot up', options: ['założyć buty', 'uruchomić system', 'włączyć komputer', 'wystartować'], correctAnswer: 'uruchomić system' },
  { id: 98, language: 'English', word: 'shut down', options: ['zamknąć', 'wyłączyć', 'zakończyć działanie', 'zamknąć / wyłączyć'], correctAnswer: 'zamknąć / wyłączyć' },
  { id: 99, language: 'English', word: 'freak out', options: ['spanikować', 'oszaleć', 'zdenerwować się', 'wystraszyć się'], correctAnswer: 'spanikować' },
  { id: 100, language: 'English', word: 'lash out', options: ['uderzyć', 'skrytykować', 'wybuchnąć gniewem', 'zaatakować'], correctAnswer: 'wybuchnąć gniewem' },
  { id: 101, language: 'English', word: 'mess up', options: ['zrobić bałagan', 'schrzanić coś', 'pomylić się', 'zepsuć'], correctAnswer: 'schrzanić coś' },
  { id: 102, language: 'English', word: 'pass out', options: ['rozdawać', 'zemdleć', 'stracić przytomność', 'zasnąć'], correctAnswer: 'zemdleć' },
  { id: 103, language: 'English', word: 'snap out of', options: ['wyjść z czegoś', 'otrząsnąć się', 'obudzić się', 'przestać'], correctAnswer: 'otrząsnąć się' },
  { id: 104, language: 'English', word: 'wear out', options: ['nosić na zewnątrz', 'zmęczyć / zużyć', 'znosić', 'wyczerpać'], correctAnswer: 'zmęczyć / zużyć' },
  { id: 105, language: 'English', word: 'blow off', options: ['zdmuchnąć', 'zlekceważyć', 'olać', 'zignorować'], correctAnswer: 'zlekceważyć' },
  { id: 106, language: 'English', word: 'bottle up', options: ['butelkować', 'tłumić emocje', 'ukrywać uczucia', 'zamykać w sobie'], correctAnswer: 'tłumić emocje' },
  { id: 107, language: 'English', word: 'bring along', options: ['przynieść', 'przyprowadzić', 'wziąć ze sobą', 'zabrać ze sobą'], correctAnswer: 'zabrać ze sobą' },
  { id: 108, language: 'English', word: 'call up', options: ['zadzwonić', 'wezwać', 'skontaktować się', 'powołać do wojska'], correctAnswer: 'zadzwonić' },
  { id: 109, language: 'English', word: 'come around', options: ['wpaść z wizytą', 'dojść do siebie', 'zmienić zdanie', 'odwiedzić'], correctAnswer: 'zmienić zdanie' },
  { id: 110, language: 'English', word: 'cut out', options: ['wyciąć', 'przestać', 'wyeliminować', 'wyłączyć'], correctAnswer: 'przestać / wyciąć' },
  { id: 111, language: 'English', word: 'get ahead', options: ['iść naprzód', 'wyprzedzić', 'wysunąć się na prowadzenie', 'osiągnąć sukces'], correctAnswer: 'wysunąć się na prowadzenie' },
  { id: 112, language: 'English', word: 'give away', options: ['oddać', 'rozdać', 'zdradzić / oddać', 'wyjawić'], correctAnswer: 'zdradzić / oddać' },
  { id: 113, language: 'English', word: 'hold back', options: ['powstrzymać', 'zatrzymać', 'ukrywać', 'wahać się'], correctAnswer: 'powstrzymać' },
  { id: 114, language: 'English', word: 'keep away', options: ['trzymać z daleka', 'unikać', 'nie zbliżać się', 'trzymać się z dala'], correctAnswer: 'trzymać z daleka' },
  { id: 115, language: 'English', word: 'lay off', options: ['odłożyć', 'przestać', 'zwolnić z pracy', 'dać spokój'], correctAnswer: 'zwolnić z pracy' },
  { id: 116, language: 'English', word: 'live up to', options: ['żyć do', 'sprostać', 'spełnić oczekiwania', 'żyć zgodnie z'], correctAnswer: 'spełnić oczekiwania' },
  { id: 117, language: 'English', word: 'pass away', options: ['przejść obok', 'minąć', 'umrzeć', 'odejść'], correctAnswer: 'umrzeć' },
  { id: 118, language: 'English', word: 'pull over', options: ['pociągnąć', 'zatrzymać się na poboczu', 'zjechać na bok', 'zatrzymać pojazd'], correctAnswer: 'zjechać na bok' },
  { id: 119, language: 'English', word: 'run out', options: ['wybiec', 'skończyć się', 'wyczerpać się', 'uciekać'], correctAnswer: 'skończyć się' },
  { id: 120, language: 'English', word: 'stand by', options: ['stać obok', 'wspierać', 'czekać / wspierać', 'być w gotowości'], correctAnswer: 'czekać / wspierać' },
  { id: 121, language: 'English', word: 'stick to', options: ['przykleić się do', 'trzymać się', 'przestrzegać', 'obstawać przy'], correctAnswer: 'trzymać się' },
  { id: 122, language: 'English', word: 'take off', options: ['zdjąć', 'wystartować / zdjąć', 'odlecieć', 'odnieść sukces'], correctAnswer: 'wystartować / zdjąć' },
  { id: 123, language: 'English', word: 'turn around', options: ['odwrócić się', 'zawracać', 'odwrócić sytuację', 'poprawić'], correctAnswer: 'odwrócić sytuację' },
  { id: 124, language: 'English', word: 'warm up', options: ['podgrzać', 'rozgrzać się', 'rozgrzewka', 'ocieplić'], correctAnswer: 'rozgrzać się' },
  { id: 125, language: 'English', word: 'wrap up', options: ['zawinąć', 'zakończyć', 'podsumować', 'ubrać się ciepło'], correctAnswer: 'zakończyć' },
];
