
export interface Question {
  id: number;
  language: 'German';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'German', word: 'Alles in Butter', options: ['wszystko w porządku', 'jeść śniadanie', 'coś jest nie tak', 'wszystko w maśle'], correctAnswer: 'wszystko w porządku' },
  { id: 2, language: 'German', word: 'Alle Viere von sich strecken', options: ['rozciągać wszystkie kończyny', 'być bardzo zmęczonym', 'rozluźnić się całkowicie', 'wstać energicznie'], correctAnswer: 'rozluźnić się całkowicie' },
  { id: 3, language: 'German', word: 'Auf Wolke sieben sein', options: ['być na siódmej chmurze', 'być w siódmym niebie', 'być bardzo smutnym', 'latać samolotem'], correctAnswer: 'być w siódmym niebie' },
  { id: 4, language: 'German', word: 'Auf dem Holzweg sein', options: ['spacerować po lesie', 'być w błędzie', 'iść drewnianą ścieżką', 'mieć rację'], correctAnswer: 'być w błędzie' },
  { id: 5, language: 'German', word: 'Auf die Palme bringen', options: ['wspinać się na palmę', 'uspokajać kogoś', 'doprowadzić do wściekłości', 'jechać na wakacje'], correctAnswer: 'doprowadzić do wściekłości' },
  { id: 6, language: 'German', word: 'Auf die Tube drücken', options: ['naciskać na tubkę', 'przyspieszyć coś', 'zwolnić tempo', 'malować obraz'], correctAnswer: 'przyspieszyć coś' },
  { id: 7, language: 'German', word: 'Auf Herz und Nieren prüfen', options: ['badać serce i nerki', 'dokładnie sprawdzić', 'zrobić badania lekarskie', 'sprawdzać powierzchownie'], correctAnswer: 'dokładnie sprawdzić' },
  { id: 8, language: 'German', word: 'Aus allen Wolken fallen', options: ['spadać ze wszystkich chmur', 'być bardzo zaskoczonym', 'spodziewać się czegoś', 'skakać ze spadochronem'], correctAnswer: 'być bardzo zaskoczonym' },
  { id: 9, language: 'German', word: 'Aus dem Nähkästchen plaudern', options: ['plotkować o szyciu', 'wyjawić sekret', 'rozmawiać o modzie', 'szyć ubrania'], correctAnswer: 'wyjawić sekret' },
  { id: 10, language: 'German', word: 'Aus dem Häuschen sein', options: ['wyjść z domku', 'być bardzo podekscytowanym', 'być smutnym', 'remontować dom'], correctAnswer: 'być bardzo podekscytowanym' },
  { id: 11, language: 'German', word: 'Bärenhunger haben', options: ['mieć głód niedźwiedzia', 'być bardzo głodnym', 'być najedzonym', 'polować na niedźwiedzie'], correctAnswer: 'być bardzo głodnym' },
  { id: 12, language: 'German', word: 'Das A und O sein', options: ['być alfabetem', 'być początkiem i końcem', 'być najważniejszym', 'być nieistotnym'], correctAnswer: 'być najważniejszym' },
  { id: 13, language: 'German', word: 'Das Kind beim Schopfe packen', options: ['łapać dziecko za włosy', 'skorzystać z okazji', 'wychowywać dziecko', 'czekać na odpowiedni moment'], correctAnswer: 'skorzystać z okazji' },
  { id: 14, language: 'German', word: 'Das ist Jacke wie Hose', options: ['to kurtka jak spodnie', 'to obojętne', 'pasować idealnie', 'ubierać się modnie'], correctAnswer: 'to obojętne' },
  { id: 15, language: 'German', word: 'Den Nagel auf den Kopf treffen', options: ['uderzyć w gwóźdź', 'trafić w sedno', 'popełnić błąd', 'budować coś'], correctAnswer: 'trafić w sedno' },
  { id: 16, language: 'German', word: 'Den Teufel an die Wand malen', options: ['malować diabła na ścianie', 'wywoływać wilka z lasu', 'wyolbrzymiać problem', 'być optymistą'], correctAnswer: 'wyolbrzymiać problem' },
  { id: 17, language: 'German', word: 'Den Wald vor lauter Bäumen nicht sehen', options: ['nie widzieć lasu z powodu drzew', 'nie dostrzegać oczywistości', 'gubić się w lesie', 'być spostrzegawczym'], correctAnswer: 'nie dostrzegać oczywistości' },
  { id: 18, language: 'German', word: 'Die Daumen drücken', options: ['ściskać kciuki', 'trzymać kciuki', 'mieć bolące palce', 'grozić komuś'], correctAnswer: 'trzymać kciuki' },
  { id: 19, language: 'German', word: 'Die Kirche im Dorf lassen', options: ['zostawić kościół we wsi', 'nie przesadzać', 'iść na mszę', 'budować kościół'], correctAnswer: 'nie przesadzać' },
  { id: 20, language: 'German', word: 'Die Katze aus dem Sack lassen', options: ['wypuścić kota z worka', 'wyjawić sekret', 'bawić się z kotem', 'trzymać coś w tajemnicy'], correctAnswer: 'wyjawić sekret' },
  { id: 21, language: 'German', word: 'Die Nase voll haben', options: ['mieć pełny nos', 'mieć katar', 'mieć czegoś dość', 'węszyć'], correctAnswer: 'mieć czegoś dość' },
  { id: 22, language: 'German', word: 'Die Spreu vom Weizen trennen', options: ['oddzielić plewy od pszenicy', 'odróżnić ważne od nieistotnego', 'pracować na roli', 'robić mąkę'], correctAnswer: 'odróżnić ważne od nieistotnego' },
  { id: 23, language: 'German', word: 'Ein Auge zudrücken', options: ['zamknąć jedno oko', 'przymknąć na coś oko', 'mieć problemy ze wzrokiem', 'obserwować uważnie'], correctAnswer: 'przymknąć na coś oko' },
  { id: 24, language: 'German', word: 'Ein Brett vor dem Kopf haben', options: ['mieć deskę przed głową', 'być twardogłowym', 'nie rozumieć czegoś oczywistego', 'być mądrym'], correctAnswer: 'nie rozumieć czegoś oczywistego' },
  { id: 25, language: 'German', word: 'Ein Herz und eine Seele sein', options: ['być sercem i duszą', 'być bardzo blisko z kimś', 'być zakochanym', 'mieć dobre serce'], correctAnswer: 'być bardzo blisko z kimś' },
  { id: 26, language: 'German', word: 'Ein Schlag in die Magengrube', options: ['uderzenie w żołądek', 'szokujące doświadczenie', 'ból brzucha', 'przyjemna niespodzianka'], correctAnswer: 'szokujące doświadczenie' },
  { id: 27, language: 'German', word: 'Ein Tropfen auf den heißen Stein', options: ['kropla na gorącym kamieniu', 'mały, nieznaczący efekt', 'kropla w morzu potrzeb', 'coś bardzo cennego'], correctAnswer: 'kropla w morzu potrzeb' },
  { id: 28, language: 'German', word: 'Eine Extrawurst bekommen', options: ['dostać dodatkową kiełbasę', 'otrzymać specjalne traktowanie', 'być głodnym', 'lubić kiełbasę'], correctAnswer: 'otrzymać specjalne traktowanie' },
  { id: 29, language: 'German', word: 'Eine Schraube locker haben', options: ['mieć luźną śrubę', 'być trochę szalonym', 'naprawiać coś', 'być poważnym'], correctAnswer: 'być trochę szalonym' },
  { id: 30, language: 'German', word: 'Etwas auf die lange Bank schieben', options: ['przesuwać coś na długą ławkę', 'odkładać coś na później', 'załatwić coś od razu', 'siedzieć na ławce'], correctAnswer: 'odkładać coś na później' },
  { id: 31, language: 'German', word: 'Etwas durch die Blume sagen', options: ['powiedzieć coś przez kwiaty', 'powiedzieć coś delikatnie', 'mówić wprost', 'dawać komuś kwiaty'], correctAnswer: 'powiedzieć coś delikatnie' },
  { id: 32, language: 'German', word: 'Etwas unter den Tisch fallen lassen', options: ['upuścić coś pod stół', 'zignorować coś celowo', 'ukrywać coś', 'robić bałagan'], correctAnswer: 'zignorować coś celowo' },
  { id: 33, language: 'German', word: 'Feuer und Flamme sein', options: ['być ogniem i płomieniem', 'być bardzo podekscytowanym', 'gasić pożar', 'być złym'], correctAnswer: 'być bardzo podekscytowanym' },
  { id: 34, language: 'German', word: 'Fünf gerade sein lassen', options: ['pozwolić piątce być prostą', 'przymknąć na coś oko', 'być dokładnym', 'liczyć do pięciu'], correctAnswer: 'przymknąć na coś oko' },
  { id: 35, language: 'German', word: 'Für jemanden die Hand ins Feuer legen', options: ['włożyć za kogoś rękę do ognia', 'dać za kogoś gwarancję', 'narazić kogoś na niebezpieczeństwo', 'rozpalać ognisko'], correctAnswer: 'dać za kogoś gwarancję' },
  { id: 36, language: 'German', word: 'Für etwas gerade stehen', options: ['stać prosto za coś', 'ponosić odpowiedzialność', 'bronić czegoś', 'unikać konsekwencji'], correctAnswer: 'ponosić odpowiedzialność' },
  { id: 37, language: 'German', word: 'Hals- und Beinbruch', options: ['złamania szyi i nogi', 'powodzenia!', 'życzyć komuś źle', 'iść do szpitala'], correctAnswer: 'powodzenia!' },
  { id: 38, language: 'German', word: 'Hand in Hand gehen', options: ['iść ręka w rękę', 'iść ramię w ramię', 'współpracować', 'spacerować'], correctAnswer: 'iść ramię w ramię' },
  { id: 39, language: 'German', word: 'Ins Gras beißen', options: ['gryźć trawę', 'umrzeć', 'jeść sałatkę', 'leżeć na trawie'], correctAnswer: 'umrzeć' },
  { id: 40, language: 'German', word: 'Ins kalte Wasser springen', options: ['skakać do zimnej wody', 'zostać rzuconym na głęboką wodę', 'pływać w jeziorze', 'unikać wyzwań'], correctAnswer: 'zostać rzuconym na głęboką wodę' },
  { id: 41, language: 'German', word: 'Jemandem den Rücken stärken', options: ['wzmacniać komuś plecy', 'masować plecy', 'wspierać kogoś', 'atakować od tyłu'], correctAnswer: 'wspierać kogoś' },
  { id: 42, language: 'German', word: 'Jemandem Honig ums Maul schmieren', options: ['smarować komuś usta miodem', 'pochlebiać komuś', 'karmić miodem', 'mówić prawdę'], correctAnswer: 'pochlebiać komuś' },
  { id: 43, language: 'German', word: 'Jemandem auf den Keks gehen', options: ['iść komuś na ciastko', 'denerwować kogoś', 'częstować ciastkami', 'lubić kogoś'], correctAnswer: 'denerwować kogoś' },
  { id: 44, language: 'German', word: 'Jemandem einen Bären aufbinden', options: ['przywiązać komuś niedźwiedzia', 'oszukać kogoś', 'opowiadać bajki', 'iść do zoo'], correctAnswer: 'oszukać kogoś' },
  { id: 45, language: 'German', word: 'Jemandem die Daumen drücken', options: ['wyciskać komuś kciuki', 'trzymać za kogoś kciuki', 'grozić komuś', 'bić kogoś'], correctAnswer: 'trzymać za kogoś kciuki' },
  { id: 46, language: 'German', word: 'Jemandem die Suppe versalzen', options: ['przesolić komuś zupę', 'psuć komuś przyjemność', 'gotować zupę', 'dzielić się jedzeniem'], correctAnswer: 'psuć komuś przyjemność' },
  { id: 47, language: 'German', word: 'Jemandem unter die Arme greifen', options: ['chwycić kogoś pod ramię', 'pomóc komuś', 'prowadzić kogoś', 'atakować kogoś'], correctAnswer: 'pomóc komuś' },
  { id: 48, language: 'German', word: 'Jemanden auf die Palme bringen', options: ['wprowadzić kogoś na palmę', 'doprowadzić kogoś do wściekłości', 'pomóc się wspinać', 'wysłać na wakacje'], correctAnswer: 'doprowadzić kogoś do wściekłości' },
  { id: 49, language: 'German', word: 'Jemanden durch den Kakao ziehen', options: ['przeciągnąć kogoś przez kakao', 'wyśmiewać kogoś', 'robić gorącą czekoladę', 'brudzić kogoś'], correctAnswer: 'wyśmiewać kogoś' },
  { id: 50, language: 'German', word: 'Jemanden ins kalte Wasser werfen', options: ['wrzucić kogoś do zimnej wody', 'wystawić kogoś na próbę', 'uczyć pływać', 'żartować z kogoś'], correctAnswer: 'wystawić kogoś na próbę' },
  { id: 51, language: 'German', word: 'Jemanden mit offenen Armen empfangen', options: ['przyjąć kogoś z otwartymi ramionami', 'przyjąć kogoś serdecznie', 'przytulić kogoś', 'odrzucić kogoś'], correctAnswer: 'przyjąć kogoś serdecznie' },
  { id: 52, language: 'German', word: 'Jemanden auf die Schippe nehmen', options: ['wziąć kogoś na łopatę', 'nabierać kogoś', 'pracować z kimś', 'przenosić kogoś'], correctAnswer: 'nabierać kogoś' },
  { id: 53, language: 'German', word: 'Jemanden auf die Finger schauen', options: ['patrzeć komuś na palce', 'pilnować kogoś', 'podziwiać czyjeś dłonie', 'grać na pianinie'], correctAnswer: 'pilnować kogoś' },
  { id: 54, language: 'German', word: 'Jemanden ins Herz schließen', options: ['zamknąć kogoś w sercu', 'polubić kogoś bardzo', 'zakochać się', 'mieć problemy z sercem'], correctAnswer: 'polubić kogoś bardzo' },
  { id: 55, language: 'German', word: 'Jemanden über den Tisch ziehen', options: ['przeciągnąć kogoś przez stół', 'oszukać kogoś', 'pokonać w siłowaniu na rękę', 'przesunąć stół'], correctAnswer: 'oszukać kogoś' },
  { id: 56, language: 'German', word: 'Jemanden vom Hocker reißen', options: ['zerwać kogoś ze stołka', 'zadziwić kogoś', 'przewrócić kogoś', 'pomóc wstać'], correctAnswer: 'zadziwić kogoś' },
  { id: 57, language: 'German', word: 'Jemanden vor den Kopf stoßen', options: ['uderzyć kogoś w głowę', 'urazić kogoś', 'zaskoczyć kogoś', 'zgodzić się z kimś'], correctAnswer: 'urazić kogoś' },
  { id: 58, language: 'German', word: 'Jemanden zur Schnecke machen', options: ['zrobić z kogoś ślimaka', 'zbesztać kogoś', 'spowolnić kogoś', 'bawić się ze ślimakami'], correctAnswer: 'zbesztać kogoś' },
  { id: 59, language: 'German', word: 'Jemandem einen Strich durch die Rechnung machen', options: ['zrobić komuś kreskę w rachunku', 'pokrzyżować komuś plany', 'pomóc w liczeniu', 'popełnić błąd w obliczeniach'], correctAnswer: 'pokrzyżować komuś plany' },
  { id: 60, language: 'German', word: 'Jemandem den Wind aus den Segeln nehmen', options: ['zabrać komuś wiatr z żagli', 'odebrać komuś inicjatywę', 'pomóc żeglować', 'uszkodzić żagiel'], correctAnswer: 'odebrać komuś inicjatywę' },
  { id: 61, language: 'German', word: 'Kein Blatt vor den Mund nehmen', options: ['nie brać liścia przed usta', 'mówić wprost', 'jeść sałatę', 'być nieśmiałym'], correctAnswer: 'mówić wprost' },
  { id: 62, language: 'German', word: 'Geld wie Heu haben', options: ['mieć pieniądze jak siano', 'mieć dużo pieniędzy', 'być biednym', 'pracować na farmie'], correctAnswer: 'mieć dużo pieniędzy' },
  { id: 63, language: 'German', word: 'Kein Licht am Ende des Tunnels sehen', options: ['nie widzieć światła na końcu tunelu', 'nie widzieć rozwiązania', 'być w ciemnym tunelu', 'być optymistą'], correctAnswer: 'nie widzieć rozwiązania' },
  { id: 64, language: 'German', word: 'Kein Ohr für etwas haben', options: ['nie mieć ucha do czegoś', 'nie chcieć czegoś słuchać', 'być głuchym', 'słuchać uważnie'], correctAnswer: 'nie chcieć czegoś słuchać' },
  { id: 65, language: 'German', word: 'Klar wie Kloßbrühe', options: ['jasne jak bulion kluskowy', 'bardzo jasne', 'coś niezrozumiałego', 'gotować zupę'], correctAnswer: 'bardzo jasne' },
  { id: 66, language: 'German', word: 'Krokodilstränen weinen', options: ['płakać krokodylimi łzami', 'fałszywie płakać', 'bać się krokodyli', 'płakać ze szczęścia'], correctAnswer: 'fałszywie płakać' },
  { id: 67, language: 'German', word: 'Kurz und bündig', options: ['krótko i zwięźle', 'długo i rozwlekle', 'pisać list', 'mówić szybko'], correctAnswer: 'krótko i zwięźle' },
  { id: 68, language: 'German', word: 'Mit dem Kopf durch die Wand', options: ['iść z głową przez ścianę', 'być upartym', 'rozbijać ścianę', 'podejmować ryzyko'], correctAnswer: 'być upartym' },
  { id: 69, language: 'German', word: 'Mit allen Wassern gewaschen sein', options: ['być umytym wszystkimi wodami', 'być doświadczonym i sprytnym', 'być mokrym', 'pływać w morzu'], correctAnswer: 'być doświadczonym i sprytnym' },
  { id: 70, language: 'German', word: 'Mit jemandem durch dick und dünn gehen', options: ['iść z kimś przez grube i cienkie', 'być razem na dobre i na złe', 'chodzić na spacery', 'tylko w dobrych chwilach'], correctAnswer: 'być razem na dobre i na złe' },
  { id: 71, language: 'German', word: 'Mit Kanonen auf Spatzen schießen', options: ['strzelać z armat do wróbli', 'przesadzać', 'używać zbyt silnych środków', 'polować na ptaki'], correctAnswer: 'używać zbyt silnych środków' },
  { id: 72, language: 'German', word: 'Mit einem blauen Auge davonkommen', options: ['uciec z podbitym okiem', 'wyjść z czegoś z niewielkimi stratami', 'mieć siniaka', 'uniknąć kary'], correctAnswer: 'wyjść z czegoś z niewielkimi stratami' },
  { id: 73, language: 'German', word: 'Nach dem Rechten sehen', options: ['patrzeć na prawo', 'sprawdzić, czy wszystko w porządku', 'szukać czegoś', 'być sędzią'], correctAnswer: 'sprawdzić, czy wszystko w porządku' },
  { id: 74, language: 'German', word: 'Nach dem Mund reden', options: ['mówić według ust', 'pochlebiać komuś', 'mówić niewyraźnie', 'powtarzać po kimś'], correctAnswer: 'pochlebiać komuś' },
  { id: 75, language: 'German', word: 'Nicht alle Tassen im Schrank haben', options: ['nie mieć wszystkich filiżanek w szafie', 'być trochę szalonym', 'robić porządki', 'pić herbatę'], correctAnswer: 'być trochę szalonym' },
  { id: 76, language: 'German', word: 'Nicht das Gelbe vom Ei sein', options: ['nie być żółtkiem z jajka', 'nie być idealnym', 'być zepsutym', 'gotować jajka'], correctAnswer: 'nie być idealnym' },
  { id: 77, language: 'German', word: 'Nicht auf den Kopf gefallen sein', options: ['nie upaść na głowę', 'być bystrym', 'być niezdarnym', 'mieć zawroty głowy'], correctAnswer: 'być bystrym' },
  { id: 78, language: 'German', word: 'Nicht den Kopf in den Sand stecken', options: ['nie wkładać głowy w piasek', 'nie poddawać się', 'chować się przed problemem', 'iść na plażę'], correctAnswer: 'nie poddawać się' },
  { id: 79, language: 'German', word: 'Nicht über alle Berge sein', options: ['nie być za wszystkimi górami', 'nie zniknąć całkowicie', 'być bezpiecznym', 'wspinać się po górach'], correctAnswer: 'nie zniknąć całkowicie' },
  { id: 80, language: 'German', word: 'Nur Bahnhof verstehen', options: ['rozumieć tylko dworzec', 'nie rozumieć nic', 'czekać na pociąg', 'podróżować koleją'], correctAnswer: 'nie rozumieć nic' },
  { id: 81, language: 'German', word: 'Perlen vor die Säue werfen', options: ['rzucać perły przed świnie', 'marnować coś wartościowego', 'karmić świnie', 'być hojnym'], correctAnswer: 'marnować coś wartościowego' },
  { id: 82, language: 'German', word: 'Quark mit Soße', options: ['twaróg z sosem', 'coś bez sensu', 'jeść deser', 'przepis kulinarny'], correctAnswer: 'coś bez sensu' },
  { id: 83, language: 'German', word: 'Schwein haben', options: ['mieć świnię', 'mieć szczęście', 'być brudnym', 'hodować zwierzęta'], correctAnswer: 'mieć szczęście' },
  { id: 84, language: 'German', word: 'Sich die Haare raufen', options: ['wyrywać sobie włosy', 'frustrować się', 'czesać się', 'iść do fryzjera'], correctAnswer: 'frustrować się' },
  { id: 85, language: 'German', word: 'Sich ins Zeug legen', options: ['położyć się w rzeczach', 'bardzo się starać', 'odpoczywać', 'robić bałagan'], correctAnswer: 'bardzo się starać' },
  { id: 86, language: 'German', word: 'Sich nicht in die Karten schauen lassen', options: ['nie pozwalać patrzeć w swoje karty', 'nie zdradzać swoich planów', 'grać w karty', 'być szczerym'], correctAnswer: 'nie zdradzać swoich planów' },
  { id: 87, language: 'German', word: 'Sich zum Affen machen', options: ['robić z siebie małpę', 'ośmieszyć się', 'iść do zoo', 'bawić się'], correctAnswer: 'ośmieszyć się' },
  { id: 88, language: 'German', word: 'Sich wie ein Fisch im Wasser fühlen', options: ['czuć się jak ryba w wodzie', 'czuć się komfortowo', 'pływać', 'być mokrym'], correctAnswer: 'czuć się komfortowo' },
  { id: 89, language: 'German', word: 'Sich auf die faule Haut legen', options: ['kłaść się na leniwą skórę', 'leniuchować', 'opalać się', 'ciężko pracować'], correctAnswer: 'leniuchować' },
  { id: 90, language: 'German', word: 'Sich etwas hinter die Ohren schreiben', options: ['zapisać coś sobie za uszami', 'zapamiętać coś dobrze', 'robić notatki', 'słuchać uważnie'], correctAnswer: 'zapamiętać coś dobrze' },
  { id: 91, language: 'German', word: 'Sich etwas nicht nehmen lassen', options: ['nie dać sobie czegoś zabrać', 'nie pozwolić sobie odebrać', 'być upartym', 'bronić swoich rzeczy'], correctAnswer: 'nie pozwolić sobie odebrać' },
  { id: 92, language: 'German', word: 'Sich etwas durch den Kopf gehen lassen', options: ['pozwolić czemuś przejść przez głowę', 'przemyśleć coś', 'mieć ból głowy', 'zapomnieć o czymś'], correctAnswer: 'przemyśleć coś' },
  { id: 93, language: 'German', word: 'Sich etwas vom Munde absparen', options: ['oszczędzać coś z ust', 'odmawiać sobie jedzenia by oszczędzać', 'być na diecie', 'mówić mało'], correctAnswer: 'odmawiać sobie jedzenia by oszczędzać' },
  { id: 94, language: 'German', word: 'Sich die Zähne ausbeißen', options: ['wybić sobie zęby', 'męczyć się z czymś bezskutecznie', 'jeść twarde rzeczy', 'iść do dentysty'], correctAnswer: 'męczyć się z czymś bezskutecznie' },
  { id: 95, language: 'German', word: 'Sich keinen Kopf machen', options: ['nie robić sobie głowy', 'nie martwić się', 'być beztroskim', 'myśleć intensywnie'], correctAnswer: 'nie martwić się' },
  { id: 96, language: 'German', word: 'Sich nicht lumpen lassen', options: ['nie dać się oszukać', 'nie oszczędzać na wysiłku/pieniądzach', 'być hojnym', 'być skąpym'], correctAnswer: 'być hojnym' },
  { id: 97, language: 'German', word: 'Sich um Kopf und Kragen reden', options: ['mówić o głowie i kołnierzu', 'narazić się przez gadanie', 'plotkować', 'dużo mówić'], correctAnswer: 'narazić się przez gadanie' },
  { id: 98, language: 'German', word: 'Sich von der Leber wegreden', options: ['mówić od wątroby', 'mówić szczerze', 'mówić co ślina na język przyniesie', 'być chorym na wątrobę'], correctAnswer: 'mówić co ślina na język przyniesie' },
  { id: 99, language: 'German', word: 'Sich etwas auf die Fahne schreiben', options: ['zapisać coś sobie na fladze', 'być z czegoś dumnym', 'postawić sobie za cel', 'rysować flagę'], correctAnswer: 'postawić sobie za cel' },
  { id: 100, language: 'German', word: 'Stehaufmännchen sein', options: ['być wańką-wstańką', 'być odpornym na porażki', 'zawsze wstawać', 'bawić się zabawką'], correctAnswer: 'być odpornym na porażki' },
  { id: 101, language: 'German', word: 'Sturm im Wasserglas', options: ['burza w szklance wody', 'problem wyolbrzymiony', 'pić wodę', 'robić eksperyment'], correctAnswer: 'problem wyolbrzymiony' },
  { id: 102, language: 'German', word: 'Tausend Meilen entfernt sein', options: ['być oddalonym o tysiąc mil', 'być bardzo daleko', 'myśleć o czymś innym', 'podróżować'], correctAnswer: 'być bardzo daleko' },
  { id: 103, language: 'German', word: 'Tomaten auf den Augen haben', options: ['mieć pomidory na oczach', 'nie zauważać czegoś oczywistego', 'mieć czerwone oczy', 'robić sałatkę'], correctAnswer: 'nie zauważać czegoś oczywistego' },
  { id: 104, language: 'German', word: 'Über den eigenen Schatten springen', options: ['przeskoczyć własny cień', 'przełamać własne ograniczenia', 'skakać w dal', 'bawić się cieniem'], correctAnswer: 'przełamać własne ograniczenia' },
  { id: 105, language: 'German', word: 'Über die Stränge schlagen', options: ['uderzyć w pasy', 'przesadzić', 'przekroczyć granice', 'karać konia'], correctAnswer: 'przekroczyć granice' },
  { id: 106, language: 'German', word: 'Unter vier Augen sprechen', options: ['rozmawiać pod czterema oczami', 'rozmawiać prywatnie', 'nosić okulary', 'rozmawiać w cztery oczy'], correctAnswer: 'rozmawiać w cztery oczy' },
  { id: 107, language: 'German', word: 'Unter die Haube kommen', options: ['wejść pod czepek', 'wyjść za mąż/ożenić się', 'nosić nakrycie głowy', 'ukrywać się'], correctAnswer: 'wyjść za mąż/ożenić się' },
  { id: 108, language: 'German', word: 'Unter den Tisch fallen lassen', options: ['upuścić pod stół', 'zignorować coś celowo', 'schować pod stołem', 'uniknąć tematu'], correctAnswer: 'zignorować coś celowo' },
  { id: 109, language: 'German', word: 'Von der Hand in den Mund leben', options: ['żyć z ręki do ust', 'żyć z dnia na dzień', 'jeść rękami', 'być biednym'], correctAnswer: 'żyć z dnia na dzień' },
  { id: 110, language: 'German', word: 'Von allen guten Geistern verlassen sein', options: ['być opuszczonym przez wszystkie dobre duchy', 'być kompletnie szalonym', 'bać się duchów', 'być samotnym'], correctAnswer: 'być kompletnie szalonym' },
  { id: 111, language: 'German', word: 'Vor der eigenen Tür kehren', options: ['zamiatać przed własnymi drzwiami', 'zająć się swoimi sprawami', 'robić porządki', 'krytykować innych'], correctAnswer: 'zająć się swoimi sprawami' },
  { id: 112, language: 'German', word: 'Vor die Hunde gehen', options: ['iść przed psy', 'upadać/degenerować się', 'iść na spacer z psem', 'być w złej sytuacji'], correctAnswer: 'upadać/degenerować się' },
  { id: 113, language: 'German', word: 'Vor die Wand fahren', options: ['wjechać w ścianę', 'zawalić coś całkowicie', 'mieć wypadek', 'ponieść porażkę'], correctAnswer: 'zawalić coś całkowicie' },
  { id: 114, language: 'German', word: 'Vor Freude strahlen', options: ['promienieć z radości', 'być bardzo szczęśliwym', 'uśmiechać się szeroko', 'opalać się'], correctAnswer: 'być bardzo szczęśliwym' },
  { id: 115, language: 'German', word: 'Vor sich hin dämmern', options: ['drzemać przed sobą', 'być w lekkim letargu', 'śnić na jawie', 'odpoczywać'], correctAnswer: 'być w lekkim letargu' },
  { id: 116, language: 'German', word: 'Vor etwas die Augen verschließen', options: ['zamykać oczy przed czymś', 'ignorować coś', 'nie chcieć czegoś widzieć', 'udawać ślepego'], correctAnswer: 'nie chcieć czegoś widzieć' },
  { id: 117, language: 'German', word: 'Wasser auf die Mühlen gießen', options: ['lać wodę na młyny', 'wzmacniać czyjeś argumenty', 'pomagać komuś nieświadomie', 'pracować w młynie'], correctAnswer: 'wzmacniać czyjeś argumenty' },
  { id: 118, language: 'German', word: 'Wie aus dem Ei gepellt sein', options: ['być jak z jajka obrany', 'być perfekcyjnie ubranym', 'wyglądać świeżo', 'jeść jajka'], correctAnswer: 'być perfekcyjnie ubranym' },
  { id: 119, language: 'German', word: 'Wie ein Stein im Brett haben', options: ['mieć kamień w desce', 'mieć u kogoś fory', 'mieć przewagę', 'grać w planszówki'], correctAnswer: 'mieć u kogoś fory' },
  { id: 120, language: 'German', word: 'Wie ein Lauffeuer verbreiten', options: ['rozprzestrzeniać się jak ogień', 'rozprzestrzeniać się szybko', 'palić las', 'gasić pożar'], correctAnswer: 'rozprzestrzeniać się szybko' },
  { id: 121, language: 'German', word: 'Wie man in den Wald hineinruft, so schallt es heraus', options: ['jak się w lesie woła, tak się odbija', 'reakcje odpowiadają zachowaniom', 'jak Kuba Bogu, tak Bóg Kubie', 'krzyczeć w lesie'], correctAnswer: 'jak Kuba Bogu, tak Bóg Kubie' },
  { id: 122, language: 'German', word: 'Wie ein Elefant im Porzellanladen', options: ['jak słoń w składzie porcelany', 'być niezręcznym', 'niszczyć wszystko', 'odwiedzać sklep'], correctAnswer: 'być niezręcznym' },
  { id: 123, language: 'German', word: 'Wie die Katze um den heißen Brei schleichen', options: ['chodzić jak kot koło gorącej kaszy', 'owijać w bawełnę', 'unikać tematu', 'być ostrożnym'], correctAnswer: 'owijać w bawełnę' },
  { id: 124, language: 'German', word: 'Wie auf heißen Kohlen sitzen', options: ['siedzieć jak na gorących węglach', 'być bardzo niespokojnym', 'grillować', 'opalać się'], correctAnswer: 'być bardzo niespokojnym' },
  { id: 125, language: 'German', word: 'Wie ein rotes Tuch wirken', options: ['działać jak czerwona płachta', 'prowokować kogoś', 'być zły jak byk', 'oglądać corridę'], correctAnswer: 'prowokować kogoś' },
  { id: 126, language: 'German', word: 'Willst du mit mir gehen?', options: ['Chcesz ze mną iść?', 'zaproszenie na randkę', 'propozycja chodzenia ze sobą', 'iść na spacer'], correctAnswer: 'propozycja chodzenia ze sobą' },
  { id: 127, language: 'German', word: 'Wo sich Fuchs und Hase gute Nacht sagen', options: ['gdzie lis i zając mówią sobie dobranoc', 'bardzo odległe miejsce', 'na odludziu', 'w głębokim lesie'], correctAnswer: 'na odludziu' },
  { id: 128, language: 'German', word: 'Wo gehobelt wird, da fallen Späne', options: ['gdzie się struga, tam lecą wióry', 'przy pracy są straty', 'gdzie drwa rąbią, tam wióry lecą', 'pracować w stolarni'], correctAnswer: 'gdzie drwa rąbią, tam wióry lecą' },
  { id: 129, language: 'German', word: 'Wo Rauch ist, da ist auch Feuer', options: ['gdzie dym, tam i ogień', 'nie ma dymu bez ognia', 'palić ognisko', 'widzieć dym'], correctAnswer: 'nie ma dymu bez ognia' },
  { id: 130, language: 'German', word: 'Zu Befehl sein', options: ['być na rozkaz', 'być do dyspozycji', 'słuchać rozkazów', 'być w wojsku'], correctAnswer: 'być do dyspozycji' },
  { id: 131, language: 'German', word: 'Zu tief ins Glas schauen', options: ['patrzeć zbyt głęboko w szklankę', 'za dużo pić', 'być pijanym', 'lubić alkohol'], correctAnswer: 'za dużo pić' },
  { id: 132, language: 'German', word: 'Zwei Fliegen mit einer Klappe schlagen', options: ['uderzyć dwie muchy jedną packą', 'załatwić dwie rzeczy naraz', 'upiec dwie pieczenie na jednym ogniu', 'być skutecznym'], correctAnswer: 'upiec dwie pieczenie na jednym ogniu' },
  { id: 133, language: 'German', word: 'Zwischen Baum und Borke stehen', options: ['stać między drzewem a korą', 'być w trudnej sytuacji', 'być między młotem a kowadłem', 'być w lesie'], correctAnswer: 'być między młotem a kowadłem' },
  { id: 134, language: 'German', word: 'Auf eigenen Füßen stehen', options: ['stać na własnych nogach', 'być samodzielnym', 'mieć silne nogi', 'być dorosłym'], correctAnswer: 'być samodzielnym' },
  { id: 135, language: 'German', word: 'Alles auf eine Karte setzen', options: ['położyć wszystko na jedną kartę', 'zaryzykować wszystko', 'grać w karty', 'mieć tylko jedną opcję'], correctAnswer: 'zaryzykować wszystko' },
  { id: 136, language: 'German', word: 'Den Kopf in den Sand stecken', options: ['wkładać głowę w piasek', 'unikać problemów', 'chować się', 'być na plaży'], correctAnswer: 'unikać problemów' },
  { id: 137, language: 'German', word: 'Die Zähne zusammenbeißen', options: ['zaciskać zęby', 'wytrzymać trudności', 'być złym', 'iść do dentysty'], correctAnswer: 'wytrzymać trudności' },
  { id: 138, language: 'German', word: 'Ein Haar in der Suppe finden', options: ['znaleźć włos w zupie', 'szukać problemu', 'narzekać na drobnostki', 'być wybrednym'], correctAnswer: 'szukać problemu' },
  { id: 139, language: 'German', word: 'Etwas aus dem Effeff beherrschen', options: ['opanować coś z FF', 'znać coś perfekcyjnie', 'uczyć się czegoś', 'być ekspertem'], correctAnswer: 'znać coś perfekcyjnie' },
  { id: 140, language: 'German', word: 'Jemandem auf den Zahn fühlen', options: ['czuć komuś na zębie', 'dokładnie kogoś przepytać', 'badać zęby', 'iść do dentysty'], correctAnswer: 'dokładnie kogoś przepytać' },
  { id: 141, language: 'German', word: 'Kein Wort über etwas verlieren', options: ['nie stracić słowa o czymś', 'nie wspominać o czymś', 'milczeć', 'trzymać w tajemnicy'], correctAnswer: 'nie wspominać o czymś' },
  { id: 142, language: 'German', word: 'Mit der Tür ins Haus fallen', options: ['wpaść z drzwiami do domu', 'mówić bez ogródek', 'być bezpośrednim', 'być niegrzecznym'], correctAnswer: 'mówić bez ogródek' },
];

