
export interface Question {
  id: number;
  language: 'English';
  word: string;
  options?: string[]; // Options are now generated dynamically
  correctAnswers: string[];
}

export const questions: Question[] = [
  // PODSTAWOWE, ABSOLUTNY MUST-HAVE
  { id: 1, language: 'English', word: 'Ask out', correctAnswers: ['Zaprosić kogoś na randkę'] },
  { id: 2, language: 'English', word: 'Back up', correctAnswers: ['Poprzeć', 'Zrobić kopię zapasową'] },
  { id: 3, language: 'English', word: 'Blow up', correctAnswers: ['Wybuchnąć', 'Zdenerwować się'] },
  { id: 4, language: 'English', word: 'Break down', correctAnswers: ['Zepsuć się', 'Załamać się'] },
  { id: 5, language: 'English', word: 'Break up', correctAnswers: ['Rozstać się'] },
  { id: 6, language: 'English', word: 'Bring up', correctAnswers: ['Poruszyć temat', 'Wychować'] },
  { id: 7, language: 'English', word: 'Call back', correctAnswers: ['Oddzwonić'] },
  { id: 8, language: 'English', word: 'Call off', correctAnswers: ['Odwołać'] },
  { id: 9, language: 'English', word: 'Carry on', correctAnswers: ['Kontynuować'] },
  { id: 10, language: 'English', word: 'Catch up', correctAnswers: ['Nadrobić zaległości'] },
  { id: 11, language: 'English', word: 'Check in', correctAnswers: ['Zameldować się', 'Dać znać'] },
  { id: 12, language: 'English', word: 'Check out', correctAnswers: ['Wymeldować się', 'Sprawdzić'] },
  { id: 13, language: 'English', word: 'Come across', correctAnswers: ['Natknąć się'] },
  { id: 14, language: 'English', word: 'Come back', correctAnswers: ['Wrócić'] },
  { id: 15, language: 'English', word: 'Come in', correctAnswers: ['Wejść'] },
  { id: 16, language: 'English', word: 'Come out', correctAnswers: ['Wyjść', 'Ukazać się'] },
  { id: 17, language: 'English', word: 'Come over', correctAnswers: ['Wpaść z wizytą'] },
  { id: 18, language: 'English', word: 'Cut down', correctAnswers: ['Ograniczyć'] },
  { id: 19, language: 'English', word: 'Cut off', correctAnswers: ['Odciąć', 'Przerwać'] },

  // PRACA, ŻYCIE CODZIENNE, KONTAKTY
  { id: 20, language: 'English', word: 'Deal with', correctAnswers: ['Radzić sobie z czymś'] },
  { id: 21, language: 'English', word: 'Drop by', correctAnswers: ['Wpaść na chwilę'] },
  { id: 22, language: 'English', word: 'Drop off', correctAnswers: ['Podrzucić', 'Zasnąć'] },
  { id: 23, language: 'English', word: 'Figure out', correctAnswers: ['Zrozumieć', 'Rozgryźć'] },
  { id: 24, language: 'English', word: 'Fill in', correctAnswers: ['Wypełnić', 'Zastąpić'] },
  { id: 25, language: 'English', word: 'Find out', correctAnswers: ['Dowiedzieć się'] },
  { id: 26, language: 'English', word: 'Get along', correctAnswers: ['Dogadywać się'] },
  { id: 27, language: 'English', word: 'Get back', correctAnswers: ['Wrócić'] },
  { id: 28, language: 'English', word: 'Get in', correctAnswers: ['Wejść', 'Dostać się'] },
  { id: 29, language: 'English', word: 'Get off', correctAnswers: ['Wysiąść', 'Zejść z pracy'] },
  { id: 30, language: 'English', word: 'Get on', correctAnswers: ['Wsiąść', 'Radzić sobie'] },
  { id: 31, language: 'English', word: 'Get over', correctAnswers: ['Dojść do siebie'] },
  { id: 32, language: 'English', word: 'Get through', correctAnswers: ['Przebrnąć', 'Dodzwonić się'] },
  { id: 33, language: 'English', word: 'Give back', correctAnswers: ['Oddać'] },
  { id: 34, language: 'English', word: 'Give up', correctAnswers: ['Poddać się', 'Rzucić coś'] },
  { id: 35, language: 'English', word: 'Go ahead', correctAnswers: ['Kontynuować', 'Zgodzić się'] },
  { id: 36, language: 'English', word: 'Go back', correctAnswers: ['Wrócić'] },
  { id: 37, language: 'English', word: 'Go on', correctAnswers: ['Dziać się', 'Kontynuować'] },
  { id: 38, language: 'English', word: 'Go out', correctAnswers: ['Wyjść'] },
  { id: 39, language: 'English', word: 'Go through', correctAnswers: ['Przejść przez coś'] },

  // ROZMOWY, RELACJE, EMOCJE
  { id: 40, language: 'English', word: 'Hang out', correctAnswers: ['Spędzać czas'] },
  { id: 41, language: 'English', word: 'Hold on', correctAnswers: ['Poczekać'] },
  { id: 42, language: 'English', word: 'Keep on', correctAnswers: ['Kontynuować'] },
  { id: 43, language: 'English', word: 'Let down', correctAnswers: ['Zawieść'] },
  { id: 44, language: 'English', word: 'Look after', correctAnswers: ['Opiekować się'] },
  { id: 45, language: 'English', word: 'Look for', correctAnswers: ['Szukać'] },
  { id: 46, language: 'English', word: 'Look forward to', correctAnswers: ['Nie móc się doczekać'] },
  { id: 47, language: 'English', word: 'Look into', correctAnswers: ['Sprawdzić', 'Zbadać'] },
  { id: 48, language: 'English', word: 'Look out', correctAnswers: ['Uważać'] },
  { id: 49, language: 'English', word: 'Make up', correctAnswers: ['Pogodzić się', 'Wymyślić'] },
  { id: 50, language: 'English', word: 'Move on', correctAnswers: ['Iść dalej'] },
  { id: 51, language: 'English', word: 'Open up', correctAnswers: ['Otworzyć się'] },
  { id: 52, language: 'English', word: 'Pick up', correctAnswers: ['Odebrać', 'Podnieść', 'Nauczyć się'] },
  { id: 53, language: 'English', word: 'Put off', correctAnswers: ['Odkładać'] },
  { id: 54, language: 'English', word: 'Run into', correctAnswers: ['Wpaść na kogoś'] },
  { id: 55, language: 'English', word: 'Settle down', correctAnswers: ['Ustatkowac się'] },
  { id: 56, language: 'English', word: 'Show up', correctAnswers: ['Pojawić się'] },
  { id: 57, language: 'English', word: 'Shut up', correctAnswers: ['Zamknąć się'] },
  { id: 58, language: 'English', word: 'Sort out', correctAnswers: ['Ogarnąć', 'Rozwiązać'] },

  // PRACA, OBOWIĄZKI, ORGANIZACJA
  { id: 59, language: 'English', word: 'Take over', correctAnswers: ['Przejąć'] },
  { id: 60, language: 'English', word: 'Take up', correctAnswers: ['Zacząć (hobby)'] },
  { id: 61, language: 'English', word: 'Think over', correctAnswers: ['Przemyśleć'] },
  { id: 62, language: 'English', word: 'Throw away', correctAnswers: ['Wyrzucić'] },
  { id: 63, language: 'English', word: 'Turn down', correctAnswers: ['Odrzucić', 'Ściszyć'] },
  { id: 64, language: 'English', word: 'Turn up', correctAnswers: ['Pojawić się', 'Podgłośnić'] },
  { id: 65, language: 'English', word: 'Work out', correctAnswers: ['Rozwiązać', 'Ćwiczyć'] },
  { id: 66, language: 'English', word: 'Write down', correctAnswers: ['Zapisać'] },
  { id: 67, language: 'English', word: 'Set up', correctAnswers: ['Założyć', 'Zorganizować'] },
  { id: 68, language: 'English', word: 'Slow down', correctAnswers: ['Zwolnić'] },
  { id: 69, language: 'English', word: 'Speed up', correctAnswers: ['Przyspieszyć'] },
  { id: 70, language: 'English', word: 'Step down', correctAnswers: ['Ustąpić'] },
  { id: 71, language: 'English', word: 'Step up', correctAnswers: ['Zwiększyć zaangażowanie'] },

  // BARDZO CZĘSTE W MOWIE POTOCZNEJ
  { id: 72, language: 'English', word: 'Break out', correctAnswers: ['Wybuchnąć', 'Uciec'] },
  { id: 73, language: 'English', word: 'Bring back', correctAnswers: ['Przywrócić'] },
  { id: 74, language: 'English', word: 'Calm down', correctAnswers: ['Uspokoić się'] },
  { id: 75, language: 'English', word: 'Check over', correctAnswers: ['Sprawdzić dokładnie'] },
  { id: 76, language: 'English', word: 'Clear up', correctAnswers: ['Wyjaśnić', 'Posprzątać'] },
  { id: 77, language: 'English', word: 'Come along', correctAnswers: ['Przyjść', 'Robić postępy'] },
  { id: 78, language: 'English', word: 'Cut back', correctAnswers: ['Ograniczyć wydatki'] },
  { id: 79, language: 'English', word: 'Fall apart', correctAnswers: ['Rozpaść się'] },
  { id: 80, language: 'English', word: 'Fall behind', correctAnswers: ['Zostać w tyle'] },
  { id: 81, language: 'English', word: 'Fill out', correctAnswers: ['Wypełnić formularz'] },
  { id: 82, language: 'English', word: 'Get away', correctAnswers: ['Wyjechać', 'Uciec'] },
  { id: 83, language: 'English', word: 'Get by', correctAnswers: ['Radzić sobie'] },
  { id: 84, language: 'English', word: 'Get together', correctAnswers: ['Spotkać się'] },
  { id: 85, language: 'English', word: 'Give in', correctAnswers: ['Ulec'] },
  { id: 86, language: 'English', word: 'Go wrong', correctAnswers: ['Pójść nie tak'] },
  { id: 87, language: 'English', word: 'Hang on', correctAnswers: ['Poczekać'] },
  { id: 88, language: 'English', word: 'Keep up', correctAnswers: ['Nadążać'] },

  // PRACA + TECHNOLOGIA + ŻYCIE NOWOCZESNE
  { id: 89, language: 'English', word: 'Log in', correctAnswers: ['Zalogować się'] },
  { id: 90, language: 'English', word: 'Log out', correctAnswers: ['Wylogować się'] },
  { id: 91, language: 'English', word: 'Sign in', correctAnswers: ['Podpisać się', 'Zalogować'] },
  { id: 92, language: 'English', word: 'Sign out', correctAnswers: ['Wylogować się'] },
  { id: 93, language: 'English', word: 'Turn on', correctAnswers: ['Włączyć'] },
  { id: 94, language: 'English', word: 'Turn off', correctAnswers: ['Wyłączyć'] },
  { id: 95, language: 'English', word: 'Plug in', correctAnswers: ['Podłączyć'] },
  { id: 96, language: 'English', word: 'Back out', correctAnswers: ['Wycofać się'] },
  { id: 97, language: 'English', word: 'Boot up', correctAnswers: ['Uruchomić system'] },
  { id: 98, language: 'English', word: 'Shut down', correctAnswers: ['Zamknąć', 'Wyłączyć'] },

  // EMOCJE, PROBLEMY, REAKCJE
  { id: 99, language: 'English', word: 'Freak out', correctAnswers: ['Spanikować'] },
  { id: 100, language: 'English', word: 'Lash out', correctAnswers: ['Wybuchnąć gniewem'] },
  { id: 101, language: 'English', word: 'Mess up', correctAnswers: ['Schrzanić coś'] },
  { id: 102, language: 'English', word: 'Pass out', correctAnswers: ['Zemdlać'] },
  { id: 103, language: 'English', word: 'Snap out of', correctAnswers: ['Otrząsnąć się'] },
  { id: 104, language: 'English', word: 'Wear out', correctAnswers: ['Zmęczyć', 'Zużyć'] },
  { id: 105, language: 'English', word: 'Blow off', correctAnswers: ['Zlekceważyć'] },
  { id: 106, language: 'English', word: 'Bottle up', correctAnswers: ['Tłumić emocje'] },

  // KOŃCÓWKA – BARDZO NATURALNE, CZĘSTE
  { id: 107, language: 'English', word: 'Bring along', correctAnswers: ['Zabrać ze sobą'] },
  { id: 108, language: 'English', word: 'Call up', correctAnswers: ['Zadzwonić'] },
  { id: 109, language: 'English', word: 'Come around', correctAnswers: ['Zmienić zdanie'] },
  { id: 110, language: 'English', word: 'Cut out', correctAnswers: ['Przestać', 'Wyciąć'] },
  { id: 111, language: 'English', word: 'Get ahead', correctAnswers: ['Wysunąć się na prowadzenie'] },
  { id: 112, language: 'English', word: 'Give away', correctAnswers: ['Zdradzić', 'Oddać'] },
  { id: 113, language: 'English', word: 'Hold back', correctAnswers: ['Powstrzymać'] },
  { id: 114, language: 'English', word: 'Keep away', correctAnswers: ['Trzymać z daleka'] },
  { id: 115, language: 'English', word: 'Lay off', correctAnswers: ['Zwolnić z pracy'] },
  { id: 116, language: 'English', word: 'Live up to', correctAnswers: ['Spełnić oczekiwania'] },
  { id: 117, language: 'English', word: 'Pass away', correctAnswers: ['Umrzeć'] },
  { id: 118, language: 'English', word: 'Pull over', correctAnswers: ['Zjechać na bok'] },
  { id: 119, language: 'English', word: 'Run out', correctAnswers: ['Skończyć się'] },
  { id: 120, language: 'English', word: 'Stand by', correctAnswers: ['Czekać', 'Wspierać'] },
  { id: 121, language: 'English', word: 'Stick to', correctAnswers: ['Trzymać się'] },
  { id: 122, language: 'English', word: 'Take off', correctAnswers: ['Wystartować', 'Zdjąć'] },
  { id: 123, language: 'English', word: 'Turn around', correctAnswers: ['Odwrócić sytuację'] },
  { id: 124, language: 'English', word: 'Warm up', correctAnswers: ['Rozgrzać się'] },
  { id: 125, language: 'English', word: 'Wrap up', correctAnswers: ['Zakończyć'] },
];
