export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  { id: 1, language: 'Polish', word: 'Cześć', options: ['Auf Wiedersehen', 'Hallo', 'Danke', 'Entschuldigung'], correctAnswer: 'Hallo' },
  { id: 2, language: 'Polish', word: 'Do widzenia', options: ['Hallo', 'Guten Morgen', 'Gute Nacht', 'Auf Wiedersehen'], correctAnswer: 'Auf Wiedersehen' },
  { id: 3, language: 'Polish', word: 'Dziękuję', options: ['Bitte', 'Gern geschehen', 'Danke', 'Entschuldigung'], correctAnswer: 'Danke' },
  { id: 4, language: 'Polish', word: 'Tak', options: ['Ja', 'Nein', 'Vielleicht', 'Immer'], correctAnswer: 'Ja' },
  { id: 5, language: 'Polish', word: 'Nie', options: ['Gut', 'Niemals', 'Warum', 'Nein'], correctAnswer: 'Nein' },
  { id: 6, language: 'Polish', word: 'Mężczyzna', options: ['die Frau', 'der Mann', 'das Kind', 'die Person'], correctAnswer: 'der Mann' },
  { id: 7, language: 'Polish', word: 'Kobieta', options: ['der Mann', 'das Mädchen', 'die Frau', 'der Junge'], correctAnswer: 'die Frau' },
  { id: 8, language: 'Polish', word: 'Jeść', options: ['trinken', 'schlafen', 'essen', 'laufen'], correctAnswer: 'essen' },
  { id: 9, language: 'Polish', word: 'Woda', options: ['das Feuer', 'das Wasser', 'die Erde', 'die Luft'], correctAnswer: 'das Wasser' },
  { id: 10, language: 'Polish', word: 'Kot', options: ['der Hund', 'der Vogel', 'der Fisch', 'die Katze'], correctAnswer: 'die Katze' },
  { id: 11, language: 'Polish', word: 'Pies', options: ['die Katze', 'der Hund', 'der Löwe', 'der Tiger'], correctAnswer: 'der Hund' },
  { id: 12, language: 'Polish', word: 'Dom', options: ['das Auto', 'die Schule', 'das Haus', 'das Geschäft'], correctAnswer: 'das Haus' },
  { id: 13, language: 'Polish', word: 'Samochód', options: ['das Fahrrad', 'der Zug', 'der Bus', 'das Auto'], correctAnswer: 'das Auto' },
  { id: 14, language: 'Polish', word: 'Szkoła', options: ['das Krankenhaus', 'die Schule', 'die Universität', 'die Bibliothek'], correctAnswer: 'die Schule' },
  { id: 15, language: 'Polish', word: 'Książka', options: ['der Film', 'das Lied', 'das Buch', 'das Bild'], correctAnswer: 'das Buch' },
  { id: 16, language: 'Polish', word: 'Słońce', options: ['der Mond', 'der Stern', 'die Sonne', 'die Wolke'], correctAnswer: 'die Sonne' },
  { id: 17, language: 'Polish', word: 'Miłość', options: ['der Hass', 'die Freude', 'die Traurigkeit', 'die Liebe'], correctAnswer: 'die Liebe' },
  { id: 18, language: 'Polish', word: 'Przyjaciel', options: ['der Feind', 'der Nachbar', 'der Freund', 'die Familie'], correctAnswer: 'der Freund' },
  { id: 19, language: 'Polish', word: 'Rodzina', options: ['die Freunde', 'die Familie', 'die Verwandten', 'die Nachbarn'], correctAnswer: 'die Familie' },
  { id: 20, language: 'Polish', word: 'Rano', options: ['der Abend', 'die Nacht', 'der Nachmittag', 'der Morgen'], correctAnswer: 'der Morgen' },
  { id: 21, language: 'Polish', word: 'Noc', options: ['der Tag', 'die Nacht', 'die Dämmerung', 'die Morgendämmerung'], correctAnswer: 'die Nacht' },
  { id: 22, language: 'Polish', word: 'Dzień', options: ['die Woche', 'der Monat', 'das Jahr', 'der Tag'], correctAnswer: 'der Tag' },
  { id: 23, language: 'Polish', word: 'Tydzień', options: ['der Tag', 'die Woche', 'das Wochenende', 'der Monat'], correctAnswer: 'die Woche' },
  { id: 24, language: 'Polish', word: 'Miesiąc', options: ['das Jahr', 'das Jahrhundert', 'das Jahrzehnt', 'der Monat'], correctAnswer: 'der Monat' },
  { id: 25, language: 'Polish', word: 'Rok', options: ['der Monat', 'das Jahr', 'der Tag', 'die Stunde'], correctAnswer: 'das Jahr' },
  { id: 26, language: 'Polish', word: 'Dzisiaj', options: ['gestern', 'morgen', 'heute', 'übermorgen'], correctAnswer: 'heute' },
  { id: 27, language: 'Polish', word: 'Jutro', options: ['heute', 'gestern', 'vorgestern', 'morgen'], correctAnswer: 'morgen' },
  { id: 28, language: 'Polish', word: 'Proszę', options: ['Danke', 'Bitte', 'Entschuldigung', 'Gern geschehen'], correctAnswer: 'Bitte' },
  { id: 29, language: 'Polish', word: 'Jabłko', options: ['die Banane', 'die Orange', 'der Apfel', 'die Birne'], correctAnswer: 'der Apfel' },
  { id: 30, language: 'Polish', word: 'Dzień dobry', options: ['Guten Abend', 'Gute Nacht', 'Guten Morgen', 'Hallo'], correctAnswer: 'Guten Morgen' },
  { id: 31, language: 'Polish', word: 'Dobry wieczór', options: ['Guten Morgen', 'Gute Nacht', 'Guten Abend', 'Guten Tag'], correctAnswer: 'Guten Abend' },
  { id: 32, language: 'Polish', word: 'Dobranoc', options: ['Guten Morgen', 'Guten Abend', 'Gute Nacht', 'Auf Wiedersehen'], correctAnswer: 'Gute Nacht' },
  { id: 33, language: 'Polish', word: 'Przepraszam', options: ['Danke', 'Bitte', 'Entschuldigung', 'Hallo'], correctAnswer: 'Entschuldigung' },
  { id: 34, language: 'Polish', word: 'Praca', options: ['der Urlaub', 'der Spaß', 'die Arbeit', 'die Schule'], correctAnswer: 'die Arbeit' },
  { id: 35, language: 'Polish', word: 'Miasto', options: ['das Dorf', 'das Land', 'die Stadt', 'die Straße'], correctAnswer: 'die Stadt' },
  { id: 36, language: 'Polish', word: 'Jedzenie', options: ['das Getränk', 'das Wasser', 'das Essen', 'das Brot'], correctAnswer: 'das Essen' },
  { id: 37, language: 'Polish', word: 'Chleb', options: ['die Milch', 'das Wasser', 'das Brot', 'der Käse'], correctAnswer: 'das Brot' },
  { id: 38, language: 'Polish', word: 'Mleko', options: ['der Saft', 'das Wasser', 'die Milch', 'der Tee'], correctAnswer: 'die Milch' },
  { id: 39, language: 'Polish', word: 'Kawa', options: ['der Tee', 'das Wasser', 'der Kaffee', 'der Saft'], correctAnswer: 'der Kaffee' },
  { id: 40, language: 'Polish', word: 'Herbata', options: ['der Kaffee', 'die Milch', 'der Tee', 'das Wasser'], correctAnswer: 'der Tee' },
  { id: 41, language: 'Polish', word: 'Czas', options: ['der Raum', 'der Ort', 'die Zeit', 'der Tag'], correctAnswer: 'die Zeit' },
  { id: 42, language: 'Polish', word: 'Godzina', options: ['die Minute', 'die Sekunde', 'die Stunde', 'der Tag'], correctAnswer: 'die Stunde' },
  { id: 43, language: 'Polish', word: 'Wczoraj', options: ['heute', 'morgen', 'gestern', 'jetzt'], correctAnswer: 'gestern' },
  { id: 44, language: 'Polish', word: 'Pieniądze', options: ['das Gold', 'das Silber', 'das Geld', 'der Kredit'], correctAnswer: 'das Geld' },
  { id: 45, language: 'Polish', word: 'Sklep', options: ['das Büro', 'die Schule', 'das Geschäft', 'das Haus'], correctAnswer: 'das Geschäft' },
  { id: 46, language: 'Polish', word: 'Ulica', options: ['der Weg', 'die Allee', 'die Straße', 'der Pfad'], correctAnswer: 'die Straße' },
  { id: 47, language: 'Polish', word: 'Droga', options: ['die Straße', 'der Pfad', 'der Weg', 'die Autobahn'], correctAnswer: 'der Weg' },
  { id: 48, language: 'Polish', word: 'Matka', options: ['der Vater', 'die Schwester', 'die Mutter', 'der Bruder'], correctAnswer: 'die Mutter' },
  { id: 49, language: 'Polish', word: 'Ojciec', options: ['die Mutter', 'der Bruder', 'der Vater', 'die Schwester'], correctAnswer: 'der Vater' },
  { id: 50, language: 'Polish', word: 'Dziecko', options: ['der Erwachsene', 'der Mann', 'die Frau', 'das Kind'], correctAnswer: 'das Kind' },
  { id: 51, language: 'Polish', word: 'Pytanie', options: ['die Antwort', 'das Problem', 'die Frage', 'der Test'], correctAnswer: 'die Frage' },
  { id: 52, language: 'Polish', word: 'Odpowiedź', options: ['die Frage', 'die Antwort', 'der Test', 'die Lösung'], correctAnswer: 'die Antwort' },
  { id: 53, language: 'Polish', word: 'Problem', options: ['die Lösung', 'die Frage', 'das Problem', 'die Antwort'], correctAnswer: 'das Problem' },
  { id: 54, language: 'Polish', word: 'Pomoc', options: ['der Ärger', 'die Hilfe', 'die Arbeit', 'das Spiel'], correctAnswer: 'die Hilfe' },
  { id: 55, language: 'Polish', word: 'Szybko', options: ['langsam', 'schnell', 'rasch', 'laut'], correctAnswer: 'schnell' },
  { id: 56, language: 'Polish', word: 'Wolno', options: ['schnell', 'rasch', 'langsam', 'leise'], correctAnswer: 'langsam' },
  { id: 57, language: 'Polish', word: 'Duży', options: ['klein', 'groß', 'hoch', 'kurz'], correctAnswer: 'groß' },
  { id: 58, language: 'Polish', word: 'Mały', options: ['groß', 'riesig', 'klein', 'winzig'], correctAnswer: 'klein' },
  { id: 59, language: 'Polish', word: 'Dobry', options: ['schlecht', 'gut', 'nett', 'großartig'], correctAnswer: 'gut' },
  { id: 60, language: 'Polish', word: 'Zły', options: ['gut', 'nett', 'schlecht', 'böse'], correctAnswer: 'schlecht' },
  { id: 61, language: 'Polish', word: 'Nowy', options: ['alt', 'neu', 'jung', 'antik'], correctAnswer: 'neu' },
  { id: 62, language: 'Polish', word: 'Stary', options: ['neu', 'jung', 'alt', 'modern'], correctAnswer: 'alt' },
  { id: 63, language: 'Polish', word: 'Ciepły', options: ['kalt', 'kühl', 'warm', 'heiß'], correctAnswer: 'warm' },
  { id: 64, language: 'Polish', word: 'Zimny', options: ['warm', 'heiß', 'kalt', 'kühl'], correctAnswer: 'kalt' },
  { id: 65, language: 'Polish', word: 'Łatwy', options: ['schwer', 'schwierig', 'einfach', 'leicht'], correctAnswer: 'einfach' },
  { id: 66, language: 'Polish', word: 'Trudny', options: ['einfach', 'leicht', 'schwer', 'hell'], correctAnswer: 'schwer' },
  { id: 67, language: 'Polish', word: 'Otwarty', options: ['geschlossen', 'zu', 'offen', 'gesperrt'], correctAnswer: 'offen' },
  { id: 68, language: 'Polish', word: 'Zamknięty', options: ['offen', 'frei', 'geschlossen', 'entsperrt'], correctAnswer: 'geschlossen' },
  { id: 69, language: 'Polish', word: 'Jasny', options: ['dunkel', 'schwarz', 'hell', 'matt'], correctAnswer: 'hell' },
  { id: 70, language: 'Polish', word: 'Ciemny', options: ['hell', 'leuchtend', 'dunkel', 'weiß'], correctAnswer: 'dunkel' },
  { id: 71, language: 'Polish', word: 'Film', options: ['das Buch', 'das Lied', 'der Film', 'das Bild'], correctAnswer: 'der Film' },
  { id: 72, language: 'Polish', word: 'Muzyka', options: ['die Kunst', 'der Film', 'die Musik', 'der Tanz'], correctAnswer: 'die Musik' },
  { id: 73, language: 'Polish', word: 'Kolor', options: ['die Form', 'die Größe', 'die Farbe', 'der Klang'], correctAnswer: 'die Farbe' },
  { id: 74, language: 'Polish', word: 'Czerwony', options: ['blau', 'grün', 'rot', 'gelb'], correctAnswer: 'rot' },
  { id: 75, language: 'Polish', word: 'Niebieski', options: ['grün', 'rot', 'blau', 'gelb'], correctAnswer: 'blau' },
  { id: 76, language: 'Polish', word: 'Zielony', options: ['rot', 'blau', 'grün', 'gelb'], correctAnswer: 'grün' },
  { id: 77, language: 'Polish', word: 'Żółty', options: ['rot', 'blau', 'grün', 'gelb'], correctAnswer: 'gelb' },
  { id: 78, language: 'Polish', word: 'Biały', options: ['schwarz', 'grau', 'weiß', 'braun'], correctAnswer: 'weiß' },
  { id: 79, language: 'Polish', word: 'Czarny', options: ['weiß', 'grau', 'schwarz', 'braun'], correctAnswer: 'schwarz' },
  { id: 80, language: 'Polish', word: 'Iść', options: ['laufen', 'gehen', 'stehen', 'sitzen'], correctAnswer: 'gehen' },
  { id: 81, language: 'Polish', word: 'Biegać', options: ['gehen', 'laufen', 'springen', 'schwimmen'], correctAnswer: 'laufen' },
  { id: 82, language: 'Polish', word: 'Mówić', options: ['hören', 'sprechen', 'lesen', 'schreiben'], correctAnswer: 'sprechen' },
  { id: 83, language: 'Polish', word: 'Widzieć', options: ['hören', 'sehen', 'fühlen', 'riechen'], correctAnswer: 'sehen' },
  { id: 84, language: 'Polish', word: 'Wiedzieć', options: ['denken', 'wissen', 'lernen', 'vergessen'], correctAnswer: 'wissen' },
  { id: 85, language: 'Polish', word: 'Chcieć', options: ['brauchen', 'wollen', 'haben', 'mögen'], correctAnswer: 'wollen' },
  { id: 86, language: 'Polish', word: 'Móc', options: ['müssen', 'sollen', 'können', 'werden'], correctAnswer: 'können' },
  { id: 87, language: 'Polish', word: 'Musieć', options: ['können', 'sollen', 'müssen', 'dürfen'], correctAnswer: 'müssen' },
  { id: 88, language: 'Polish', word: 'Spać', options: ['aufwachen', 'schlafen', 'essen', 'trinken'], correctAnswer: 'schlafen' },
  { id: 89, language: 'Polish', word: 'Myśleć', options: ['wissen', 'denken', 'fühlen', 'glauben'], correctAnswer: 'denken' },
  { id: 90, language: 'Polish', word: 'Lubić', options: ['lieben', 'hassen', 'mögen', 'bevorzugen'], correctAnswer: 'mögen' },
  { id: 91, language: 'Polish', word: 'Zawsze', options: ['nie', 'manchmal', 'immer', 'oft'], correctAnswer: 'immer' },
  { id: 92, language: 'Polish', word: 'Nigdy', options: ['immer', 'oft', 'nie', 'manchmal'], correctAnswer: 'nie' },
  { id: 93, language: 'Polish', word: 'Często', options: ['selten', 'manchmal', 'oft', 'immer'], correctAnswer: 'oft' },
  { id: 94, language: 'Polish', word: 'Rzadko', options: ['oft', 'immer', 'selten', 'nie'], correctAnswer: 'selten' },
  { id: 95, language: 'Polish', word: 'Tutaj', options: ['dort', 'hier', 'wo', 'überall'], correctAnswer: 'hier' },
  { id: 96, language: 'Polish', word: 'Tam', options: ['hier', 'dort', 'nah', 'fern'], correctAnswer: 'dort' },
  { id: 97, language: 'Polish', word: 'Dlaczego', options: ['was', 'wann', 'warum', 'wer'], correctAnswer: 'warum' },
  { id: 98, language: 'Polish', word: 'Ponieważ', options: ['aber', 'also', 'weil', 'und'], correctAnswer: 'weil' },
  { id: 99, language: 'Polish', word: 'Ale', options: ['und', 'oder', 'aber', 'also'], correctAnswer: 'aber' },
  { id: 100, language: 'Polish', word: 'I', options: ['oder', 'aber', 'und', 'also'], correctAnswer: 'und' }
];
