
export interface IrregularVerbQuestion {
  id: number;
  verb: string; // Base form
  form2: string; // Past simple
  form3: string; // Past participle
  translationOptions: string[];
  correctTranslation: string;
}

export const questions: IrregularVerbQuestion[] = [
  { id: 1, verb: 'be', form2: 'was/were', form3: 'been', translationOptions: ['być', 'mieć', 'robić'], correctAnswer: 'być' },
  { id: 2, verb: 'beat', form2: 'beat', form3: 'beaten', translationOptions: ['bić', 'wygrywać', 'przegrywać'], correctAnswer: 'bić' },
  { id: 3, verb: 'become', form2: 'became', form3: 'become', translationOptions: ['stawać się', 'być', 'pozostawać'], correctAnswer: 'stawać się' },
  { id: 4, verb: 'begin', form2: 'began', form3: 'begun', translationOptions: ['zaczynać', 'kończyć', 'kontynuować'], correctAnswer: 'zaczynać' },
  { id: 5, verb: 'bend', form2: 'bent', form3: 'bent', translationOptions: ['zginać', 'prostować', 'łamać'], correctAnswer: 'zginać' },
  { id: 6, verb: 'bet', form2: 'bet', form3: 'bet', translationOptions: ['zakładać się', 'przegrywać', 'wygrywać'], correctAnswer: 'zakładać się' },
  { id: 7, verb: 'bite', form2: 'bit', form3: 'bitten', translationOptions: ['gryźć', 'żuć', 'połykać'], correctAnswer: 'gryźć' },
  { id: 8, verb: 'blow', form2: 'blew', form3: 'blown', translationOptions: ['dmuchać', 'ciągnąć', 'pchać'], correctAnswer: 'dmuchać' },
  { id: 9, verb: 'break', form2: 'broke', form3: 'broken', translationOptions: ['łamać', 'naprawiać', 'budować'], correctAnswer: 'łamać' },
  { id: 10, verb: 'bring', form2: 'brought', form3: 'brought', translationOptions: ['przynosić', 'zabierać', 'wysyłać'], correctAnswer: 'przynosić' },
  { id: 11, verb: 'build', form2: 'built', form3: 'built', translationOptions: ['budować', 'niszczyć', 'projektować'], correctAnswer: 'budować' },
  { id: 12, verb: 'burn', form2: 'burnt/burned', form3: 'burnt/burned', translationOptions: ['palić/płonąć', 'gasić', 'zalewać'], correctAnswer: 'palić/płonąć' },
  { id: 13, verb: 'buy', form2: 'bought', form3: 'bought', translationOptions: ['kupować', 'sprzedawać', 'wymieniać'], correctAnswer: 'kupować' },
  { id: 14, verb: 'catch', form2: 'caught', form3: 'caught', translationOptions: ['łapać', 'puszczać', 'rzucać'], correctAnswer: 'łapać' },
  { id: 15, verb: 'choose', form2: 'chose', form3: 'chosen', translationOptions: ['wybierać', 'odrzucać', 'ignorować'], correctAnswer: 'wybierać' },
  { id: 16, verb: 'come', form2: 'came', form3: 'come', translationOptions: ['przychodzić', 'wychodzić', 'zostawać'], correctAnswer: 'przychodzić' },
  { id: 17, verb: 'cost', form2: 'cost', form3: 'cost', translationOptions: ['kosztować', 'płacić', 'zarabiać'], correctAnswer: 'kosztować' },
  { id: 18, verb: 'cut', form2: 'cut', form3: 'cut', translationOptions: ['ciąć', 'kleić', 'szyć'], correctAnswer: 'ciąć' },
  { id: 19, verb: 'deal', form2: 'dealt', form3: 'dealt', translationOptions: ['radzić sobie/rozdawać', 'unikać', 'zbierać'], correctAnswer: 'radzić sobie/rozdawać' },
  { id: 20, verb: 'dig', form2: 'dug', form3: 'dug', translationOptions: ['kopać', 'zasypywać', 'sadzić'], correctAnswer: 'kopać' },
  { id: 21, verb: 'do', form2: 'did', form3: 'done', translationOptions: ['robić', 'niszczyć', 'tworzyć'], correctAnswer: 'robić' },
  { id: 22, verb: 'draw', form2: 'drew', form3: 'drawn', translationOptions: ['rysować', 'pisać', 'malować'], correctAnswer: 'rysować' },
  { id: 23, verb: 'dream', form2: 'dreamt/dreamed', form3: 'dreamt/dreamed', translationOptions: ['marzyć/śnić', 'budzić się', 'planować'], correctAnswer: 'marzyć/śnić' },
  { id: 24, verb: 'drink', form2: 'drank', form3: 'drunk', translationOptions: ['pić', 'jeść', 'spać'], correctAnswer: 'pić' },
  { id: 25, verb: 'drive', form2: 'drove', form3: 'driven', translationOptions: ['prowadzić (pojazd)', 'chodzić', 'biegać'], correctAnswer: 'prowadzić (pojazd)' },
  { id: 26, verb: 'eat', form2: 'ate', form3: 'eaten', translationOptions: ['jeść', 'pić', 'głodować'], correctAnswer: 'jeść' },
  { id: 27, verb: 'fall', form2: 'fell', form3: 'fallen', translationOptions: ['upadać', 'wstawać', 'skakać'], correctAnswer: 'upadać' },
  { id: 28, verb: 'feel', form2: 'felt', form3: 'felt', translationOptions: ['czuć', 'dotykać', 'widzieć'], correctAnswer: 'czuć' },
  { id: 29, verb: 'fight', form2: 'fought', form3: 'fought', translationOptions: ['walczyć', 'poddawać się', 'uciekać'], correctAnswer: 'walczyć' },
  { id: 30, verb: 'find', form2: 'found', form3: 'found', translationOptions: ['znajdować', 'gubić', 'szukać'], correctAnswer: 'znajdować' },
  { id: 31, verb: 'fly', form2: 'flew', form3: 'flown', translationOptions: ['latać', 'pływać', 'biegać'], correctAnswer: 'latać' },
  { id: 32, verb: 'forget', form2: 'forgot', form3: 'forgotten', translationOptions: ['zapominać', 'pamiętać', 'uczyć się'], correctAnswer: 'zapominać' },
  { id: 33, verb: 'forgive', form2: 'forgave', form3: 'forgiven', translationOptions: ['wybaczać', 'oskarżać', 'karać'], correctAnswer: 'wybaczać' },
  { id: 34, verb: 'freeze', form2: 'froze', form3: 'frozen', translationOptions: ['zamarzać', 'topnieć', 'gotować'], correctAnswer: 'zamarzać' },
  { id: 35, verb: 'get', form2: 'got', form3: 'got/gotten', translationOptions: ['dostawać', 'dawać', 'tracić'], correctAnswer: 'dostawać' },
  { id: 36, verb: 'give', form2: 'gave', form3: 'given', translationOptions: ['dawać', 'brać', 'otrzymywać'], correctAnswer: 'dawać' },
  { id: 37, verb: 'go', form2: 'went', form3: 'gone', translationOptions: ['iść', 'stać', 'przychodzić'], correctAnswer: 'iść' },
  { id: 38, verb: 'grow', form2: 'grew', form3: 'grown', translationOptions: ['rosnąć', 'maleć', 'kurczyć się'], correctAnswer: 'rosnąć' },
  { id: 39, verb: 'hang', form2: 'hung', form3: 'hung', translationOptions: ['wieszać', 'kłaść', 'zdejmować'], correctAnswer: 'wieszać' },
  { id: 40, verb: 'have', form2: 'had', form3: 'had', translationOptions: ['mieć', 'potrzebować', 'być'], correctAnswer: 'mieć' },
  { id: 41, verb: 'hear', form2: 'heard', form3: 'heard', translationOptions: ['słyszeć', 'widzieć', 'mówić'], correctAnswer: 'słyszeć' },
  { id: 42, verb: 'hide', form2: 'hid', form3: 'hidden', translationOptions: ['chować się', 'pokazywać', 'szukać'], correctAnswer: 'chować się' },
  { id: 43, verb: 'hit', form2: 'hit', form3: 'hit', translationOptions: ['uderzać', 'głaskać', 'unikać'], correctAnswer: 'uderzać' },
  { id: 44, verb: 'hold', form2: 'held', form3: 'held', translationOptions: ['trzymać', 'puszczać', 'upuszczać'], correctAnswer: 'trzymać' },
  { id: 45, verb: 'hurt', form2: 'hurt', form3: 'hurt', translationOptions: ['ranić/boleć', 'leczyć', 'pomagać'], correctAnswer: 'ranić/boleć' },
  { id: 46, verb: 'keep', form2: 'kept', form3: 'kept', translationOptions: ['trzymać/zachowywać', 'oddawać', 'wyrzucać'], correctAnswer: 'trzymać/zachowywać' },
  { id: 47, verb: 'know', form2: 'knew', form3: 'known', translationOptions: ['wiedzieć/znać', 'nie wiedzieć', 'uczyć się'], correctAnswer: 'wiedzieć/znać' },
  { id: 48, verb: 'lay', form2: 'laid', form3: 'laid', translationOptions: ['kłaść', 'podnosić', 'stawiać'], correctAnswer: 'kłaść' },
  { id: 49, verb: 'lead', form2: 'led', form3: 'led', translationOptions: ['prowadzić', 'podążać', 'stać'], correctAnswer: 'prowadzić' },
  { id: 50, verb: 'leave', form2: 'left', form3: 'left', translationOptions: ['opuszczać/zostawiać', 'przybywać', 'wracać'], correctAnswer: 'opuszczać/zostawiać' },
  { id: 51, verb: 'lend', form2: 'lent', form3: 'lent', translationOptions: ['pożyczać (komuś)', 'pożyczać (od kogoś)', 'dawać'], correctAnswer: 'pożyczać (komuś)' },
  { id: 52, verb: 'let', form2: 'let', form3: 'let', translationOptions: ['pozwalać', 'zabraniać', 'kazać'], correctAnswer: 'pozwalać' },
  { id: 53, verb: 'lie', form2: 'lay', form3: 'lain', translationOptions: ['leżeć', 'stać', 'siedzieć'], correctAnswer: 'leżeć' },
  { id: 54, verb: 'lose', form2: 'lost', form3: 'lost', translationOptions: ['gubić/przegrywać', 'znajdować', 'wygrywać'], correctAnswer: 'gubić/przegrywać' },
  { id: 55, verb: 'make', form2: 'made', form3: 'made', translationOptions: ['robić/tworzyć', 'niszczyć', 'psuć'], correctAnswer: 'robić/tworzyć' },
  { id: 56, verb: 'mean', form2: 'meant', form3: 'meant', translationOptions: ['znaczyć/mieć na myśli', 'domyślać się', 'ignorować'], correctAnswer: 'znaczyć/mieć na myśli' },
  { id: 57, verb: 'meet', form2: 'met', form3: 'met', translationOptions: ['spotykać', 'omijać', 'rozstawać się'], correctAnswer: 'spotykać' },
  { id: 58, verb: 'pay', form2: 'paid', form3: 'paid', translationOptions: ['płacić', 'otrzymywać', 'oszczędzać'], correctAnswer: 'płacić' },
  { id: 59, verb: 'put', form2: 'put', form3: 'put', translationOptions: ['kłaść', 'brać', 'podnosić'], correctAnswer: 'kłaść' },
  { id: 60, verb: 'read', form2: 'read', form3: 'read', translationOptions: ['czytać', 'pisać', 'oglądać'], correctAnswer: 'czytać' },
  { id: 61, verb: 'ride', form2: 'rode', form3: 'ridden', translationOptions: ['jeździć (na czymś)', 'chodzić', 'stać'], correctAnswer: 'jeździć (na czymś)' },
  { id: 62, verb: 'ring', form2: 'rang', form3: 'rung', translationOptions: ['dzwonić', 'milczeć', 'pisać'], correctAnswer: 'dzwonić' },
  { id: 63, verb: 'rise', form2: 'rose', form3: 'risen', translationOptions: ['wznosić się/wstawać', 'opadać', 'siadać'], correctAnswer: 'wznosić się/wstawać' },
  { id: 64, verb: 'run', form2: 'ran', form3: 'run', translationOptions: ['biec', 'chodzić', 'stać'], correctAnswer: 'biec' },
  { id: 65, verb: 'say', form2: 'said', form3: 'said', translationOptions: ['mówić/powiedzieć', 'pytać', 'milczeć'], correctAnswer: 'mówić/powiedzieć' },
  { id: 66, verb: 'see', form2: 'saw', form3: 'seen', translationOptions: ['widzieć', 'słyszeć', 'czuć'], correctAnswer: 'widzieć' },
  { id: 67, verb: 'sell', form2: 'sold', form3: 'sold', translationOptions: ['sprzedawać', 'kupować', 'dawać'], correctAnswer: 'sprzedawać' },
  { id: 68, verb: 'send', form2: 'sent', form3: 'sent', translationOptions: ['wysyłać', 'otrzymywać', 'przynosić'], correctAnswer: 'wysyłać' },
  { id: 69, verb: 'set', form2: 'set', form3: 'set', translationOptions: ['ustawiać', 'przesuwać', 'burzyć'], correctAnswer: 'ustawiać' },
  { id: 70, verb: 'shake', form2: 'shook', form3: 'shaken', translationOptions: ['trząść', 'uspokajać', 'trzymać'], correctAnswer: 'trząść' },
  { id: 71, verb: 'shine', form2: 'shone', form3: 'shone', translationOptions: ['świecić', 'gasnąć', 'ciemnieć'], correctAnswer: 'świecić' },
  { id: 72, verb: 'shoot', form2: 'shot', form3: 'shot', translationOptions: ['strzelać', 'celować', 'rzucać'], correctAnswer: 'strzelać' },
  { id: 73, verb: 'show', form2: 'showed', form3: 'shown', translationOptions: ['pokazywać', 'ukrywać', 'zasłaniać'], correctAnswer: 'pokazywać' },
  { id: 74, verb: 'shut', form2: 'shut', form3: 'shut', translationOptions: ['zamykać', 'otwierać', 'uchylać'], correctAnswer: 'zamykać' },
  { id: 75, verb: 'sing', form2: 'sang', form3: 'sung', translationOptions: ['śpiewać', 'mówić', 'krzyczeć'], correctAnswer: 'śpiewać' },
  { id: 76, verb: 'sink', form2: 'sank', form3: 'sunk', translationOptions: ['tonąć', 'pływać', 'unosić się'], correctAnswer: 'tonąć' },
  { id: 77, verb: 'sit', form2: 'sat', form3: 'sat', translationOptions: ['siedzieć', 'stać', 'leżeć'], correctAnswer: 'siedzieć' },
  { id: 78, verb: 'sleep', form2: 'slept', form3: 'slept', translationOptions: ['spać', 'budzić się', 'pracować'], correctAnswer: 'spać' },
  { id: 79, verb: 'speak', form2: 'spoke', form3: 'spoken', translationOptions: ['mówić', 'milczeć', 'słuchać'], correctAnswer: 'mówić' },
  { id: 80, verb: 'spend', form2: 'spent', form3: 'spent', translationOptions: ['spędzać/wydawać', 'oszczędzać', 'zarabiać'], correctAnswer: 'spędzać/wydawać' },
  { id: 81, verb: 'stand', form2: 'stood', form3: 'stood', translationOptions: ['stać', 'siedzieć', 'leżeć'], correctAnswer: 'stać' },
  { id: 82, verb: 'steal', form2: 'stole', form3: 'stolen', translationOptions: ['kraść', 'dawać', 'oddawać'], correctAnswer: 'kraść' },
  { id: 83, verb: 'stick', form2: 'stuck', form3: 'stuck', translationOptions: ['przyklejać/trzymać się', 'odklejać', 'puszczać'], correctAnswer: 'przyklejać/trzymać się' },
  { id: 84, verb: 'strike', form2: 'struck', form3: 'struck', translationOptions: ['uderzać', 'głaskać', 'unikać'], correctAnswer: 'uderzać' },
  { id: 85, verb: 'swear', form2: 'swore', form3: 'sworn', translationOptions: ['przysięgać', 'kłamać', 'wątpić'], correctAnswer: 'przysięgać' },
  { id: 86, verb: 'swim', form2: 'swam', form3: 'swum', translationOptions: ['pływać', 'tonąć', 'biegać'], correctAnswer: 'pływać' },
  { id: 87, verb: 'take', form2: 'took', form3: 'taken', translationOptions: ['brać', 'dawać', 'rzucać'], correctAnswer: 'brać' },
  { id: 88, verb: 'teach', form2: 'taught', form3: 'taught', translationOptions: ['uczyć (kogoś)', 'uczyć się', 'zapominać'], correctAnswer: 'uczyć (kogoś)' },
  { id: 89, verb: 'tell', form2: 'told', form3: 'told', translationOptions: ['mówić/opowiadać', 'pytać', 'słuchać'], correctAnswer: 'mówić/opowiadać' },
  { id: 90, verb: 'think', form2: 'thought', form3: 'thought', translationOptions: ['myśleć', 'wiedzieć', 'czuć'], correctAnswer: 'myśleć' },
  { id: 91, verb: 'throw', form2: 'threw', form3: 'thrown', translationOptions: ['rzucać', 'łapać', 'trzymać'], correctAnswer: 'rzucać' },
  { id: 92, verb: 'understand', form2: 'understood', form3: 'understood', translationOptions: ['rozumieć', 'ignorować', 'mylić'], correctAnswer: 'rozumieć' },
  { id: 93, verb: 'wake', form2: 'woke', form3: 'woken', translationOptions: ['budzić się', 'zasypiać', 'spać'], correctAnswer: 'budzić się' },
  { id: 94, verb: 'wear', form2: 'wore', form3: 'worn', translationOptions: ['nosić (ubranie)', 'zdejmować', 'kupować'], correctAnswer: 'nosić (ubranie)' },
  { id: 95, verb: 'win', form2: 'won', form3: 'won', translationOptions: ['wygrywać', 'przegrywać', 'remisować'], correctAnswer: 'wygrywać' },
  { id: 96, verb: 'write', form2: 'wrote', form3: 'written', translationOptions: ['pisać', 'czytać', 'rysować'], correctAnswer: 'pisać' },
  { id: 97, verb: 'bleed', form2: 'bled', form3: 'bled', translationOptions: ['krwawić', 'leczyć', 'bandażować'], correctAnswer: 'krwawić' },
  { id: 98, verb: 'breed', form2: 'bred', form3: 'bred', translationOptions: ['hodować', 'niszczyć', 'polować'], correctAnswer: 'hodować' },
  { id: 99, verb: 'cling', form2: 'clung', form3: 'clung', translationOptions: ['uczepić się/przylgnąć', 'puścić', 'odepchnąć'], correctAnswer: 'uczepić się/przylgnąć' },
  { id: 100, verb: 'creep', form2: 'crept', form3: 'crept', translationOptions: ['skradać się', 'biec', 'krzyczeć'], correctAnswer: 'skradać się' },
  { id: 101, verb: 'dive', form2: 'dived/dove', form3: 'dived', translationOptions: ['nurkować', 'pływać', 'wynurzać się'], correctAnswer: 'nurkować' },
  { id: 102, verb: 'feed', form2: 'fed', form3: 'fed', translationOptions: ['karmić', 'głodzić', 'jeść'], correctAnswer: 'karmić' },
  { id: 103, verb: 'flee', form2: 'fled', form3: 'fled', translationOptions: ['uciekać', 'zostawać', 'walczyć'], correctAnswer: 'uciekać' },
  { id: 104, verb: 'forbid', form2: 'forbade', form3: 'forbidden', translationOptions: ['zabraniać', 'pozwalać', 'prosić'], correctAnswer: 'zabraniać' },
  { id: 105, verb: 'grind', form2: 'ground', form3: 'ground', translationOptions: ['mielić', 'mieszać', 'gotować'], correctAnswer: 'mielić' },
  { id: 106, verb: 'kneel', form2: 'knelt', form3: 'knelt', translationOptions: ['klęczeć', 'stać', 'siedzieć'], correctAnswer: 'klęczeć' },
  { id: 107, verb: 'light', form2: 'lit', form3: 'lit', translationOptions: ['zapalać/oświetlać', 'gasić', 'zaciemniać'], correctAnswer: 'zapalać/oświetlać' },
  { id: 108, verb: 'prove', form2: 'proved', form3: 'proven/proved', translationOptions: ['udowadniać', 'zaprzeczać', 'wątpić'], correctAnswer: 'udowadniać' },
  { id: 109, verb: 'quit', form2: 'quit', form3: 'quit', translationOptions: ['rzucać/rezygnować', 'zaczynać', 'kontynuować'], correctAnswer: 'rzucać/rezygnować' },
  { id: 110, verb: 'seek', form2: 'sought', form3: 'sought', translationOptions: ['szukać', 'znajdować', 'unikać'], correctAnswer: 'szukać' },
  { id: 111, verb: 'shed', form2: 'shed', form3: 'shed', translationOptions: ['zrzucać/gubić', 'zakładać', 'zbierać'], correctAnswer: 'zrzucać/gubić' },
  { id: 112, verb: 'smell', form2: 'smelt/smelled', form3: 'smelt/smelled', translationOptions: ['pachnieć/wąchać', 'patrzeć', 'dotykać'], correctAnswer: 'pachnieć/wąchać' },
  { id: 113, verb: 'speed', form2: 'sped', form3: 'sped', translationOptions: ['pędzić/przyspieszać', 'zwalniać', 'zatrzymywać się'], correctAnswer: 'pędzić/przyspieszać' },
  { id: 114, verb: 'spoil', form2: 'spoilt/spoiled', form3: 'spoilt/spoiled', translationOptions: ['psuć/rozpieszczać', 'naprawiać', 'karcić'], correctAnswer: 'psuć/rozpieszczać' },
  { id: 115, verb: 'spread', form2: 'spread', form3: 'spread', translationOptions: ['rozprzestrzeniać (się)', 'zbierać', 'ograniczać'], correctAnswer: 'rozprzestrzeniać (się)' },
  { id: 116, verb: 'spring', form2: 'sprang', form3: 'sprung', translationOptions: ['skakać/wytrysnąć', 'opadać', 'stać'], correctAnswer: 'skakać/wytrysnąć' },
  { id: 117, verb: 'sting', form2: 'stung', form3: 'stung', translationOptions: ['żądlić/kłuć', 'głaskać', 'leczyć'], correctAnswer: 'żądlić/kłuć' },
  { id: 118, verb: 'sweep', form2: 'swept', form3: 'swept', translationOptions: ['zamiatać', 'brudzić', 'myć'], correctAnswer: 'zamiatać' },
  { id: 119, verb: 'swing', form2: 'swung', form3: 'swung', translationOptions: ['huśtać się', 'stać', 'zatrzymywać'], correctAnswer: 'huśtać się' },
  { id: 120, verb: 'tear', form2: 'tore', form3: 'torn', translationOptions: ['drzeć/rozdzierać', 'kleić', 'szyć'], correctAnswer: 'drzeć/rozdzierać' },
  { id: 121, verb: 'tread', form2: 'trod', form3: 'trodden', translationOptions: ['stąpać/deptać', 'unosić się', 'skakać'], correctAnswer: 'stąpać/deptać' },
  { id: 122, verb: 'weep', form2: 'wept', form3: 'wept', translationOptions: ['płakać', 'śmiać się', 'milczeć'], correctAnswer: 'płakać' },
  { id: 123, verb: 'wind', form2: 'wound', form3: 'wound', translationOptions: ['nakręcać/owijać', 'rozwijać', 'prostować'], correctAnswer: 'nakręcać/owijać' },
  { id: 124, verb: 'withdraw', form2: 'withdrew', form3: 'withdrawn', translationOptions: ['wycofywać (się)', 'wpłacać', 'dołączać'], correctAnswer: 'wycofywać (się)' },
  { id: 125, verb: 'withstand', form2: 'withstood', form3: 'withstood', translationOptions: ['wytrzymywać', 'poddawać się', 'łamać się'], correctAnswer: 'wytrzymywać' },
  { id: 126, verb: 'bind', form2: 'bound', form3: 'bound', translationOptions: ['wiązać', 'rozwiązywać', 'uwalniać'], correctAnswer: 'wiązać' },
  { id: 127, verb: 'cast', form2: 'cast', form3: 'cast', translationOptions: ['rzucać', 'łapać', 'trzymać'], correctAnswer: 'rzucać' },
  { id: 128, verb: 'forecast', form2: 'forecast', form3: 'forecast', translationOptions: ['prognozować', 'zgadywać', 'relacjonować'], correctAnswer: 'prognozować' },
  { id: 129, verb: 'knit', form2: 'knit/knitted', form3: 'knit/knitted', translationOptions: ['robić na drutach', 'szyć', 'pruć'], correctAnswer: 'robić na drutach' },
  { id: 130, verb: 'lean', form2: 'leant/leaned', form3: 'leant/leaned', translationOptions: ['opierać się', 'prostować się', 'odsuwać się'], correctAnswer: 'opierać się' },
  { id: 131, verb: 'leap', form2: 'leapt/leaped', form3: 'leapt/leaped', translationOptions: ['skakać', 'stać', 'pełzać'], correctAnswer: 'skakać' },
  { id: 132, verb: 'rid', form2: 'rid', form3: 'rid', translationOptions: ['pozbywać się', 'zdobywać', 'trzymać'], correctAnswer: 'pozbywać się' },
  { id: 133, verb: 'slide', form2: 'slid', form3: 'slid', translationOptions: ['ślizgać się', 'stać', 'zatrzymywać'], correctAnswer: 'ślizgać się' },
  { id: 134, verb: 'split', form2: 'split', form3: 'split', translationOptions: ['dzielić/rozdzielać', 'łączyć', 'scalać'], correctAnswer: 'dzielić/rozdzielać' },
  { id: 135, verb: 'wed', form2: 'wed', form3: 'wed', translationOptions: ['brać ślub', 'rozwodzić się', 'rozstawać się'], correctAnswer: 'brać ślub' },
  { id: 136, verb: 'arise', form2: 'arose', form3: 'arisen', translationOptions: ['powstawać/pojawiać się', 'znikać', 'opadać'], correctAnswer: 'powstawać/pojawiać się' },
  { id: 137, verb: 'burst', form2: 'burst', form3: 'burst', translationOptions: ['pękać', 'kurczyć się', 'naprawiać'], correctAnswer: 'pękać' },
  { id: 138, verb: 'slit', form2: 'slit', form3: 'slit', translationOptions: ['rozcinać', 'zszywać', 'kleić'], correctAnswer: 'rozcinać' },
  { id: 139, verb: 'spin', form2: 'spun', form3: 'spun', translationOptions: ['kręcić (się)', 'zatrzymywać', 'prostować'], correctAnswer: 'kręcić (się)' },
  { id: 140, verb: 'spit', form2: 'spat', form3: 'spat', translationOptions: ['pluć', 'połykać', 'pić'], correctAnswer: 'pluć' },
  { id: 141, verb: 'stride', form2: 'strode', form3: 'stridden', translationOptions: ['kroczyć', 'czołgać się', 'stać'], correctAnswer: 'kroczyć' },
  { id: 142, verb: 'strive', form2: 'strove', form3: 'striven', translationOptions: ['dążyć/usiłować', 'poddawać się', 'rezygnować'], correctAnswer: 'dążyć/usiłować' },
  { id: 143, verb: 'thrust', form2: 'thrust', form3: 'thrust', translationOptions: ['pchać/wpychać', 'ciągnąć', 'wycofywać'], correctAnswer: 'pchać/wpychać' },
  { id: 144, verb: 'wet', form2: 'wet/wetted', form3: 'wet/wetted', translationOptions: ['moczyć', 'suszyć', 'wycierać'], correctAnswer: 'moczyć' },
  { id: 145, verb: 'wring', form2: 'wrung', form3: 'wrung', translationOptions: ['wyżymać/wykręcać', 'moczyć', 'gładzić'], correctAnswer: 'wyżymać/wykręcać' }
];

