export interface Question {
  id: number;
  language: 'Polish';
  word: string;
  options: string[];
  correctAnswer: string;
}

export const questions: Question[] = [
  {
    id: 1,
    language: 'Polish',
    word: 'Hello',
    options: ['Do widzenia', 'Cześć', 'Dziękuję', 'Przepraszam'],
    correctAnswer: 'Cześć',
  },
  {
    id: 2,
    language: 'Polish',
    word: 'Goodbye',
    options: ['Cześć', 'Dzień dobry', 'Dobranoc', 'Do widzenia'],
    correctAnswer: 'Do widzenia',
  },
  {
    id: 3,
    language: 'Polish',
    word: 'Thank you',
    options: ['Proszę', 'Nie ma za co', 'Dziękuję', 'Przepraszam'],
    correctAnswer: 'Dziękuję',
  },
  {
    id: 4,
    language: 'Polish',
    word: 'Yes',
    options: ['Tak', 'Nie', 'Może', 'Zawsze'],
    correctAnswer: 'Tak',
  },
  {
    id: 5,
    language: 'Polish',
    word: 'No',
    options: ['W porządku', 'Nigdy', 'Dlaczego', 'Nie'],
    correctAnswer: 'Nie',
  },
  {
    id: 6,
    language: 'Polish',
    word: 'Man',
    options: ['Kobieta', 'Mężczyzna', 'Dziecko', 'Osoba'],
    correctAnswer: 'Mężczyzna',
  },
  {
    id: 7,
    language: 'Polish',
    word: 'Woman',
    options: ['Mężczyzna', 'Dziewczyna', 'Kobieta', 'Chłopiec'],
    correctAnswer: 'Kobieta',
  },
  {
    id: 8,
    language: 'Polish',
    word: 'To eat',
    options: ['Pić', 'Spać', 'Jeść', 'Biegać'],
    correctAnswer: 'Jeść',
  },
  {
    id: 9,
    language: 'Polish',
    word: 'Water',
    options: ['Ogień', 'Woda', 'Ziemia', 'Powietrze'],
    correctAnswer: 'Woda',
  },
  {
    id: 10,
    language: 'Polish',
    word: 'Cat',
    options: ['Pies', 'Ptak', 'Ryba', 'Kot'],
    correctAnswer: 'Kot',
  },
  {
    id: 11,
    language: 'Polish',
    word: 'Dog',
    options: ['Kot', 'Pies', 'Lew', 'Tygrys'],
    correctAnswer: 'Pies',
  },
  {
    id: 12,
    language: 'Polish',
    word: 'House',
    options: ['Samochód', 'Szkoła', 'Dom', 'Sklep'],
    correctAnswer: 'Dom',
  },
  {
    id: 13,
    language: 'Polish',
    word: 'Car',
    options: ['Rower', 'Pociąg', 'Autobus', 'Samochód'],
    correctAnswer: 'Samochód',
  },
  {
    id: 14,
    language: 'Polish',
    word: 'School',
    options: ['Szpital', 'Szkoła', 'Uniwersytet', 'Biblioteka'],
    correctAnswer: 'Szkoła',
  },
  {
    id: 15,
    language: 'Polish',
    word: 'Book',
    options: ['Film', 'Piosenka', 'Książka', 'Obraz'],
    correctAnswer: 'Książka',
  },
  {
    id: 16,
    language: 'Polish',
    word: 'Sun',
    options: ['Księżyc', 'Gwiazda', 'Słońce', 'Chmura'],
    correctAnswer: 'Słońce',
  },
  {
    id: 17,
    language: 'Polish',
    word: 'Moon',
    options: ['Słońce', 'Planeta', 'Księżyc', 'Kometa'],
    correctAnswer: 'Księżyc',
  },
  {
    id: 18,
    language: 'Polish',
    word: 'Love',
    options: ['Nienawiść', 'Radość', 'Smutek', 'Miłość'],
    correctAnswer: 'Miłość',
  },
  {
    id: 19,
    language: 'Polish',
    word: 'Friend',
    options: ['Wróg', 'Sąsiad', 'Przyjaciel', 'Rodzina'],
    correctAnswer: 'Przyjaciel',
  },
  {
    id: 20,
    language: 'Polish',
    word: 'Family',
    options: ['Znajomi', 'Rodzina', 'Krewni', 'Sąsiedzi'],
    correctAnswer: 'Rodzina',
  },
  {
    id: 21,
    language: 'Polish',
    word: 'Morning',
    options: ['Wieczór', 'Noc', 'Popołudnie', 'Rano'],
    correctAnswer: 'Rano',
  },
  {
    id: 22,
    language: 'Polish',
    word: 'Night',
    options: ['Dzień', 'Noc', 'Zmierzch', 'Świt'],
    correctAnswer: 'Noc',
  },
  {
    id: 23,
    language: 'Polish',
    word: 'Day',
    options: ['Tydzień', 'Miesiąc', 'Rok', 'Dzień'],
    correctAnswer: 'Dzień',
  },
  {
    id: 24,
    language: 'Polish',
    word: 'Week',
    options: ['Dzień', 'Tydzień', 'Weekend', 'Miesiąc'],
    correctAnswer: 'Tydzień',
  },
  {
    id: 25,
    language: 'Polish',
    word: 'Month',
    options: ['Rok', 'Wiek', 'Dekada', 'Miesiąc'],
    correctAnswer: 'Miesiąc',
  },
  {
    id: 26,
    language: 'Polish',
    word: 'Year',
    options: ['Miesiąc', 'Rok', 'Dzień', 'Godzina'],
    correctAnswer: 'Rok',
  },
  {
    id: 27,
    language: 'Polish',
    word: 'Today',
    options: ['Wczoraj', 'Jutro', 'Dzisiaj', 'Pojutrze'],
    correctAnswer: 'Dzisiaj',
  },
  {
    id: 28,
    language: 'Polish',
    word: 'Tomorrow',
    options: ['Dzisiaj', 'Wczoraj', 'Przedwczoraj', 'Jutro'],
    correctAnswer: 'Jutro',
  },
  {
    id: 29,
    language: 'Polish',
    word: 'Please',
    options: ['Dziękuję', 'Proszę', 'Przepraszam', 'Nie ma za co'],
    correctAnswer: 'Proszę',
  },
  {
    id: 30,
    language: 'Polish',
    word: 'Apple',
    options: ['Banan', 'Pomarańcza', 'Jabłko', 'Gruszka'],
    correctAnswer: 'Jabłko',
  },
];
