import type { Language } from './storage';

export interface Tense {
  language: Language;
  name: string;
  usage: string;
  examples: {
    original: string;
    translation: string;
  }[];
}

export const allTenses: Tense[] = [
  // English
  { language: 'en', name: 'Present Simple', usage: 'Używany do opisywania nawyków, faktów i regularnych czynności.', examples: [{original: 'She works in a hospital.', translation: 'Ona pracuje w szpitalu.'}, {original: 'The Earth revolves around the Sun.', translation: 'Ziemia krąży wokół Słońca.'}] },
  { language: 'en', name: 'Present Continuous', usage: 'Używany do czynności dziejących się w momencie mówienia lub tymczasowych sytuacji.', examples: [{original: 'I am reading a book right now.', translation: 'Czytam teraz książkę.'}, {original: 'They are building a new bridge in the city center.', translation: 'Oni budują nowy most w centrum miasta.'}] },
  { language: 'en', name: 'Present Perfect', usage: 'Używany do czynności, które miały miejsce w nieokreślonej przeszłości lub mają związek z teraźniejszością.', examples: [{original: 'He has lost his keys.', translation: 'On zgubił klucze.'}, {original: 'We have seen that movie twice.', translation: 'Widzieliśmy ten film dwa razy.'}] },
  { language: 'en', name: 'Present Perfect Continuous', usage: 'Podkreśla ciągłość czynności, która zaczęła się w przeszłości i trwa do teraz.', examples: [{original: 'They have been talking for an hour.', translation: 'Oni rozmawiają od godziny.'}, {original: 'She has been learning Spanish since December.', translation: 'Ona uczy się hiszpańskiego od grudnia.'}] },
  { language: 'en', name: 'Past Simple', usage: 'Używany do opisywania zakończonych czynności w przeszłości.', examples: [{original: 'They visited Paris last year.', translation: 'Oni odwiedzili Paryż w zeszłym roku.'}, {original: 'He bought a new car yesterday.', translation: 'On wczoraj kupił nowy samochód.'}] },
  { language: 'en', name: 'Past Continuous', usage: 'Opisuje czynność trwającą w określonym momencie w przeszłości, często jako tło dla innego wydarzenia.', examples: [{original: 'I was watching TV when you called.', translation: 'Oglądałem telewizję, kiedy zadzwoniłeś.'}, {original: 'The sun was shining and the birds were singing.', translation: 'Słońce świeciło, a ptaki śpiewały.'}] },
  { language: 'en', name: 'Past Perfect', usage: 'Używany do opisu czynności, która zakończyła się przed inną czynnością w przeszłości (czas "zaprzzeszły").', examples: [{original: 'The train had left when I arrived at the station.', translation: 'Pociąg już odjechał, kiedy dotarłem na stację.'}, {original: 'She had already cooked dinner before he came home.', translation: 'Ona ugotowała już obiad, zanim on wrócił do domu.'}] },
  { language: 'en', name: 'Past Perfect Continuous', usage: 'Podkreśla ciągłość czynności, która trwała przez pewien czas przed innym wydarzeniem w przeszłości.', examples: [{original: 'He had been working there for five years before he quit.', translation: 'Pracował tam przez pięć lat, zanim zrezygnował.'}, {original: 'They had been waiting for 30 minutes when the bus finally arrived.', translation: 'Czekali 30 minut, kiedy autobus w końcu przyjechał.'}] },
  { language: 'en', name: 'Future Simple', usage: 'Używany do spontanicznych decyzji, obietnic i przewidywań opartych na opinii.', examples: [{original: 'I will help you with your homework.', translation: 'Pomogę ci z zadaniem domowym.'}, {original: 'I think it will rain tomorrow.', translation: 'Myślę, że jutro będzie padać.'}] },
  { language: 'en', name: 'Future Continuous', usage: 'Opisuje czynność, która będzie trwała w określonym momencie w przyszłości.', examples: [{original: 'This time tomorrow, I will be flying to Spain.', translation: 'Jutro o tej porze będę lecieć do Hiszpanii.'}, {original: 'Don\'t call at 8 PM, I will be having dinner.', translation: 'Nie dzwoń o 20:00, będę jadł kolację.'}] },
  { language: 'en', name: 'Future Perfect', usage: 'Wyraża czynność, która zostanie zakończona przed określonym momentem w przyszłości.', examples: [{original: 'By 2025, they will have finished the project.', translation: 'Do 2025 roku skończą ten projekt.'}, {original: 'She will have graduated by next summer.', translation: 'Ona ukończy studia do przyszłego lata.'}] },
  { language: 'en', name: 'Future Perfect Continuous', usage: 'Podkreśla, jak długo będzie trwała czynność do określonego momentu w przyszłości.', examples: [{original: 'By next year, I will have been living here for ten years.', translation: 'W przyszłym roku minie dziesięć lat, odkąd tu mieszkam.'}, {original: 'When he retires, he will have been working for 40 years.', translation: 'Kiedy przejdzie na emeryturę, będzie pracował już 40 lat.'}] },
  { language: 'en', name: 'Zero Conditional', usage: 'Używany do opisywania faktów, ogólnych prawd i sytuacji, które zawsze są prawdziwe.', examples: [{original: 'If you heat water to 100 degrees, it boils.', translation: 'Jeśli podgrzejesz wodę do 100 stopni, zagotuje się.'}, {original: 'Plants die if they don\'t get enough water.', translation: 'Rośliny umierają, jeśli nie dostają wystarczająco wody.'}] },
  { language: 'en', name: 'First Conditional', usage: 'Okres warunkowy I: Opisuje realne, prawdopodobne sytuacje w przyszłości.', examples: [{original: 'If it rains tomorrow, we will stay at home.', translation: 'Jeśli jutro będzie padać, zostaniemy w domu.'}, {original: 'If you study hard, you will pass the exam.', translation: 'Jeśli będziesz się pilnie uczyć, zdasz egzamin.'}] },
  { language: 'en', name: 'Second Conditional', usage: 'Okres warunkowy II: Używany do opisywania hipotetycznych, mało prawdopodobnych sytuacji w teraźniejszości lub przyszłości (tzw. "gdybanie").', examples: [{original: 'If I won the lottery, I would buy a big house.', translation: 'Gdybym wygrał na loterii, kupiłbym duży dom.'}, {original: 'If I were you, I would take that job.', translation: 'Na twoim miejscu przyjąłbym tę pracę.'}] },
  { language: 'en', name: 'Third Conditional', usage: 'Okres warunkowy III: Opisuje hipotetyczne sytuacje z przeszłości, które się nie wydarzyły i ich hipotetyczne skutki.', examples: [{original: 'If you had studied harder, you would have passed the exam.', translation: 'Gdybyś uczył się pilniej, zdałbyś egzamin.'}, {original: 'If she had taken the earlier train, she wouldn\'t have been late.', translation: 'Gdyby pojechała wcześniejszym pociągiem, nie spóźniłaby się.'}] },

  // French
  { language: 'fr', name: 'Présent (Indicatif)', usage: 'Opisuje czynności teraźniejsze, nawyki i ogólne prawdy.', examples: [{original: 'Il parle français.', translation: 'On mówi po francusku.'}, {original: 'Nous mangeons une pizza.', translation: 'Jemy pizzę.'}] },
  { language: 'fr', name: 'Présent (Subjonctif)', usage: 'Wyraża subiektywne odczucia, wątpliwości, życzenia, konieczność po określonych spójnikach i zwrotach.', examples: [{original: 'Il faut que tu viennes.', translation: 'Trzeba, żebyś przyszedł.'}, {original: 'Je veux qu\'elle soit heureuse.', translation: 'Chcę, żeby ona była szczęśliwa.'}] },
  { language: 'fr', name: 'Passé composé (Indicatif)', usage: 'Główny czas przeszły dokonany, używany do opisywania jednorazowych, zakończonych czynności w przeszłości.', examples: [{original: 'J\'ai mangé une pomme.', translation: 'Zjadłem/am jabłko.'}, {original: 'Elle est allée au cinéma hier soir.', translation: 'Ona poszła wczoraj wieczorem do kina.'}] },
  { language: 'fr', name: 'Imparfait (Indicatif)', usage: 'Czas przeszły niedokonany, używany do opisywania tła, nawyków, stanów i czynności trwających w przeszłości.', examples: [{original: 'Quand j\'étais petit, je jouais au football.', translation: 'Kiedy byłem mały, grałem w piłkę nożną.'}, {original: 'Il pleuvait et le vent soufflait fort.', translation: 'Padało i wiatr mocno wiał.'}] },
  { language: 'fr', name: 'Passé simple (Indicatif)', usage: 'Czas przeszły prosty, używany głównie w języku pisanym (literatura) do opisywania zakończonych, historycznych wydarzeń.', examples: [{original: 'Le roi mourut en 1715.', translation: 'Król umarł w 1715 roku.'}, {original: 'Il prit son épée et partit au combat.', translation: 'On chwycił swój miecz i ruszył do walki.'}] },
  { language: 'fr', name: 'Plus-que-parfait (Indicatif)', usage: 'Czas zaprzeszły, opisuje czynność, która wydarzyła się przed inną czynnością w przeszłości.', examples: [{original: 'Il avait déjà fini quand je suis arrivé.', translation: 'On już skończył, kiedy przybyłem.'}, {original: 'Elle avait lu le livre avant de voir le film.', translation: 'Ona przeczytała książkę, zanim zobaczyła film.'}] },
  { language: 'fr', name: 'Passé (Subjonctif)', usage: 'Wyraża subiektywne odczucia dotyczące czynności przeszłej, która wydarzyła się przed momentem mówienia.', examples: [{original: 'Je suis content que tu aies réussi.', translation: 'Cieszę się, że ci się udało.'}, {original: 'Il est dommage qu\'il soit parti si tôt.', translation: 'Szkoda, że on tak wcześnie wyjechał.'}] },
  { language: 'fr', name: 'Plus-que-parfait (Subjonctif)', usage: 'Bardzo formalny i rzadki, używany w literaturze do wyrażania nierealnej przeszłości w zdaniach podrzędnych.', examples: [{original: 'S\'il l\'eût su, il serait venu.', translation: 'Gdyby był to wiedział, byłby przyszedł.'}, {original: 'J\'aurais aimé qu\'il m\'eût dit la vérité.', translation: 'Chciałbym, żeby był mi powiedział prawdę.'}] },
  { language: 'fr', name: 'Futur simple (Indicatif)', usage: 'Używany do opisywania czynności, które odbędą się w przyszłości.', examples: [{original: 'Nous voyagerons en Italie.', translation: 'Pojedziemy do Włoch.'}, {original: 'Tu finiras tes devoirs plus tard.', translation: 'Skończysz swoje zadania później.'}] },
  { language: 'fr', name: 'Futur antérieur (Indicatif)', usage: 'Wyraża czynność przyszłą, która zakończy się przed inną czynnością przyszłą.', examples: [{original: 'Quand tu arriveras, j\'aurai déjà fini.', translation: 'Kiedy przyjedziesz, ja już skończę.'}, {original: 'Il aura appris la nouvelle avant nous.', translation: 'On dowie się o tym przed nami.'}] },
  { language: 'fr', name: 'Conditionnel présent', usage: 'Tryb przypuszczający, używany do wyrażania życzeń, rad, uprzejmych próśb i hipotetycznych sytuacji.', examples: [{original: 'Je voudrais un café, s\'il vous plaît.', translation: 'Chciałbym kawę, proszę.'}, {original: 'Si j\'avais le temps, je lirais ce livre.', translation: 'Gdybym miał czas, przeczytałbym tę książkę.'}] },
  { language: 'fr', name: 'Conditionnel passé', usage: 'Wyraża czynność, która mogłaby się wydarzyć w przeszłości (ale się nie wydarzyła), często wyrażając żal lub wyrzut.', examples: [{original: 'J\'aurais dû étudier plus.', translation: 'Powinienem był więcej się uczyć.'}, {original: 'Tu aurais pu me le dire plus tôt.', translation: 'Mogłeś mi to powiedzieć wcześniej.'}] },

  // German
  { language: 'de', name: 'Präsens', usage: 'Używany do czynności teraźniejszych, nawyków, ogólnych prawd i zaplanowanej przyszłości.', examples: [{original: 'Er lernt Deutsch.', translation: 'On uczy się niemieckiego.'}, {original: 'Wir gehen heute Abend ins Kino.', translation: 'Idziemy dziś wieczorem do kina.'}] },
  { language: 'de', name: 'Perfekt', usage: 'Najczęściej używany czas przeszły w mowie potocznej do opisywania zakończonych czynności.', examples: [{original: 'Ich habe ein Buch gelesen.', translation: 'Przeczytałem/am książkę.'}, {original: 'Sie ist nach Berlin gefahren.', translation: 'Ona pojechała do Berlina.'}] },
  { language: 'de', name: 'Präteritum', usage: 'Czas przeszły prosty, używany głównie w języku pisanym (książki, gazety) oraz z czasownikami modalnymi i "sein", "haben".', examples: [{original: 'Er war gestern im Kino.', translation: 'On był wczoraj w kinie.'}, {original: 'Die Kinder spielten im Garten.', translation: 'Dzieci bawiły się w ogrodzie.'}] },
  { language: 'de', name: 'Plusquamperfekt', usage: 'Czas zaprzeszły, opisuje czynność, która zakończyła się przed inną czynnością w przeszłości.', examples: [{original: 'Nachdem er gegessen hatte, ging er spazieren.', translation: 'Po tym, jak zjadł, poszedł na spacer.'}, {original: 'Ich hatte den Film schon gesehen, bevor er im Kino lief.', translation: 'Widziałem już ten film, zanim wszedł do kin.'}] },
  { language: 'de', name: 'Futur I', usage: 'Używany do wyrażania przyszłych zamiarów, obietnic i prognoz.', examples: [{original: 'Wir werden morgen ankommen.', translation: 'Przyjedziemy jutro.'}, {original: 'Ich werde dich am Bahnhof abholen.', translation: 'Odbiorę cię z dworca.'}] },
  { language: 'de', name: 'Futur II', usage: 'Wyraża czynność, która zostanie zakończona w przyszłości lub przypuszczenie dotyczące przeszłości.', examples: [{original: 'Bis morgen wird er die Arbeit beendet haben.', translation: 'Do jutra on skończy pracę.'}, {original: 'Er wird den Brief wohl schon abgeschickt haben.', translation: 'On prawdopodobnie wysłał już list.'}] },
  { language: 'de', name: 'Konjunktiv I', usage: 'Tryb łączący I, używany głównie w mowie zależnej (np. w wiadomościach), do wyrażania czyjejś wypowiedzi.', examples: [{original: 'Der Politiker sagte, er werde zurücktreten.', translation: 'Polityk powiedział, że ustąpi.'}, {original: 'Sie sagt, sie habe keine Zeit.', translation: 'Ona mówi, że nie ma czasu.'}] },
  { language: 'de', name: 'Konjunktiv II', usage: 'Tryb łączący II, używany do wyrażania życzeń, nierealnych warunków i uprzejmych próśb (odpowiednik polskiego trybu przypuszczającego).', examples: [{original: 'Wenn ich reich wäre, würde ich ein Haus kaufen.', translation: 'Gdybym był bogaty, kupiłbym dom.'}, {original: 'Könntest du mir bitte helfen?', translation: 'Czy mógłbyś mi proszę pomóc?'}] },

  // Spanish
  { language: 'es', name: 'Presente (Indicativo)', usage: 'Opisuje czynności teraźniejsze, nawyki i prawdy ogólne.', examples: [{original: 'Ella habla español.', translation: 'Ona mówi po hiszpańsku.'}, {original: 'Nosotros vivimos en Polonia.', translation: 'Mieszkamy w Polsce.'}] },
  { language: 'es', name: 'Presente de subjuntivo', usage: 'Wyraża życzenia, wątpliwości, emocje, nierealne sytuacje w teraźniejszości.', examples: [{original: 'Quiero que vengas a la fiesta.', translation: 'Chcę, żebyś przyszedł na imprezę.'}, {original: 'Es importante que estudies.', translation: 'Jest ważne, żebyś się uczył.'}] },
  { language: 'es', name: 'Pretérito perfecto (Indicativo)', usage: 'Używany do opisywania czynności, które wydarzyły się niedawno i mają związek z teraźniejszością.', examples: [{original: 'Esta mañana he bebido café.', translation: 'Dziś rano piłem/am kawę.'}, {original: 'Todavía no hemos visto esa película.', translation: 'Jeszcze nie widzieliśmy tego filmu.'}] },
  { language: 'es', name: 'Pretérito imperfecto (Indicativo)', usage: 'Używany do opisywania tła, zwyczajów, czynności powtarzających się i stanów w przeszłości.', examples: [{original: 'Cuando era niño, jugaba mucho.', translation: 'Kiedy byłem dzieckiem, dużo się bawiłem.'}, {original: 'Hacía sol y los pájaros cantaban.', translation: 'Było słonecznie i ptaki śpiewały.'}] },
  { language: 'es', name: 'Pretérito indefinido', usage: 'Używany do opisywania zakończonych, jednorazowych czynności w przeszłości.', examples: [{original: 'Ayer comimos paella.', translation: 'Wczoraj zjedliśmy paellę.'}, {original: 'El año pasado viajé a España.', translation: 'W zeszłym roku pojechałem do Hiszpanii.'}] },
  { language: 'es', name: 'Pretérito pluscuamperfecto (Indicativo)', usage: 'Czas zaprzeszły, opisuje czynność zakończoną przed inną czynnością w przeszłości.', examples: [{original: 'Cuando llegué, la película ya había empezado.', translation: 'Kiedy przyszedłem, film już się zaczął.'}, {original: 'Él ya se había ido cuando llamaste.', translation: 'On już wyszedł, kiedy zadzwoniłaś.'}] },
  { language: 'es', name: 'Pretérito perfecto de subjuntivo', usage: 'Wyraża życzenie lub wątpliwość odnośnie zakończonej czynności w niedalekiej przeszłości.', examples: [{original: 'Espero que hayas dormido bien.', translation: 'Mam nadzieję, że dobrze spałeś.'}, {original: 'Me alegro de que hayas venido.', translation: 'Cieszę się, że przyszedłeś.'}] },
  { language: 'es', name: 'Pretérito pluscuamperfecto de subjuntivo', usage: 'Wyraża hipotetyczne sytuacje w przeszłości, które się nie wydarzyły (gdybanie o przeszłości).', examples: [{original: 'Si hubiera sabido, te habría llamado.', translation: 'Gdybym wiedział, zadzwoniłbym do ciebie.'}, {original: 'Si hubieras estudiado más, habrías aprobado.', translation: 'Gdybyś uczył się więcej, zdałbyś.'}] },
  { language: 'es', name: 'Futuro simple (Indicativo)', usage: 'Używany do wyrażania przyszłych czynności, przypuszczeń i obietnic.', examples: [{original: 'Mañana te llamaré.', translation: 'Zadzwonię do ciebie jutro.'}, {original: 'Creo que lloverá.', translation: 'Myślę, że będzie padać.'}] },
  { language: 'es', name: 'Futuro compuesto', usage: 'Wyraża czynność, która zostanie zakończona przed określonym momentem w przyszłości.', examples: [{original: 'Para las cinco, habré terminado todo.', translation: 'Do piątej wszystko skończę.'}, {original: 'Dentro de un año, ya nos habremos mudado.', translation: 'Za rok już się przeprowadzimy.'}] },
  { language: 'es', name: 'Condicional simple', usage: 'Tryb przypuszczający, używany do wyrażania życzeń, rad, próśb i hipotetycznych sytuacji.', examples: [{original: 'Me gustaría viajar más.', translation: 'Chciałbym więcej podróżować.'}, {original: '¿Podrías ayudarme, por favor?', translation: 'Czy mógłbyś mi pomóc, proszę?'}] },
  { language: 'es', name: 'Condicional compuesto', usage: 'Wyraża czynność, która mogłaby się wydarzyć w przeszłości, ale się nie wydarzyła.', examples: [{original: 'Habría ido, pero estaba enfermo.', translation: 'Poszedłbym, ale byłem chory.'}, {original: 'Yo en tu lugar, no lo habría hecho.', translation: 'Ja na twoim miejscu bym tego nie zrobił.'}] },

  // Italian
  { language: 'it', name: 'Presente (Indicativo)', usage: 'Opisuje czynności teraźniejsze, nawyki i prawdy ogólne.', examples: [{original: 'Lui legge un libro.', translation: 'On czyta książkę.'}, {original: 'Noi andiamo al mercato ogni sabato.', translation: 'Chodzimy na targ w każdą sobotę.'}] },
  { language: 'it', name: 'Presente (Congiuntivo)', usage: 'Wyraża wątpliwość, życzenie, opinię, możliwość w teraźniejszości.', examples: [{original: 'Penso che lui legga molto.', translation: 'Myślę, że on dużo czyta.'}, {original: 'È necessario che tu parta subito.', translation: 'Jest konieczne, żebyś natychmiast wyjechał.'}] },
  { language: 'it', name: 'Passato prossimo (Indicativo)', usage: 'Najczęściej używany czas przeszły dokonany, opisuje czynności zakończone w przeszłości.', examples: [{original: 'Ieri ho mangiato una pizza.', translation: 'Wczoraj zjadłem/am pizzę.'}, {original: 'Siamo andati al cinema la settimana scorsa.', translation: 'Poszliśmy do kina w zeszłym tygodniu.'}] },
  { language: 'it', name: 'Imperfetto (Indicativo)', usage: 'Używany do opisywania tła, zwyczajów i czynności powtarzających się w przeszłości.', examples: [{original: 'Da bambino, giocavo sempre fuori.', translation: 'Jako dziecko, zawsze bawiłem się na zewnątrz.'}, {original: 'Mentre studiavo, ascoltavo la musica.', translation: 'Podczas gdy się uczyłem, słuchałem muzyki.'}] },
  { language: 'it', name: 'Passato remoto (Indicativo)', usage: 'Czas przeszły prosty, używany głównie w literaturze do opisu odległych wydarzeń historycznych.', examples: [{original: 'Dante scrisse la Divina Commedia.', translation: 'Dante napisał Boską Komedię.'}, {original: 'Colombo scoprì l\'America nel 1492.', translation: 'Kolumb odkrył Amerykę w 1492 roku.'}] },
  { language: 'it', name: 'Trapassato prossimo (Indicativo)', usage: 'Czas zaprzeszły, opisuje czynność zakończoną przed inną czynnością w przeszłości.', examples: [{original: 'Quando sono arrivato, il film era già iniziato.', translation: 'Kiedy przybyłem, film już się zaczął.'}, {original: 'Avevo già mangiato quando mi hai chiamato.', translation: 'Już zjadłem, kiedy do mnie zadzwoniłeś.'}] },
  { language: 'it', name: 'Passato (Congiuntivo)', usage: 'Wyraża wątpliwość lub opinię o czynności, która miała miejsce w przeszłości.', examples: [{original: 'Sono felice che tu sia venuto.', translation: 'Cieszę się, że przyszedłeś.'}, {original: 'Nonostante abbia studiato, non ha superato l\'esame.', translation: 'Mimo że się uczył, nie zdał egzaminu.'}] },
  { language: 'it', name: 'Imperfetto (Congiuntivo)', usage: 'Wyraża życzenie, hipotezę lub warunek, który jest mało prawdopodobny.', examples: [{original: 'Se avessi più tempo, viaggerei di più.', translation: 'Gdybym miał więcej czasu, więcej bym podróżował.'}, {original: 'Vorrei che tu fossi qui con me.', translation: 'Chciałbym, żebyś tu ze mną był.'}] },
  { language: 'it', name: 'Trapassato (Congiuntivo)', usage: 'Wyraża nierealną hipotezę dotyczącą przeszłości.', examples: [{original: 'Se lo avessi saputo, ti avrei aiutato.', translation: 'Gdybym o tym wiedział, pomógłbym ci.'}, {original: 'Se non avesse piovuto, saremmo usciti.', translation: 'Gdyby nie padało, wyszlibyśmy.'}] },
  { language: 'it', name: 'Futuro semplice (Indicativo)', usage: 'Używany do wyrażania przyszłych czynności, obietnic i przypuszczeń.', examples: [{original: 'Domani andrò al cinema.', translation: 'Jutro pójdę do kina.'}, {original: 'Penso che vinceremo la partita.', translation: 'Myślę, że wygramy mecz.'}] },
  { language: 'it', name: 'Futuro anteriore (Indicativo)', usage: 'Wyraża czynność przyszłą, która zakończy się przed inną czynnością przyszłą.', examples: [{original: 'Dopo che avrò finito i compiti, uscirò.', translation: 'Gdy skończę zadania domowe, wyjdę.'}, {original: 'Appena sarai arrivato, chiamami.', translation: 'Jak tylko przyjedziesz, zadzwoń do mnie.'}] },
  { language: 'it', name: 'Condizionale presente / passato', usage: 'Tryb przypuszczający. \'Presente\' wyraża życzenia i prośby (chciałbym). \'Passato\' wyraża nierealne czynności z przeszłości (zrobiłbym był), często wyrażając żal.', examples: [{original: 'Vorrei un caffè.', translation: 'Chciałbym kawę.'}, {original: 'Avrei comprato quella macchina, se avessi avuto i soldi.', translation: 'Kupiłbym ten samochód, gdybym miał pieniądze.'}] },
];
