
import type { PhrasesContent } from './phrases';

export const tongueTwistersContent: PhrasesContent = {
  en: {
    'tongue-twisters': {
      title: 'Tongue Twisters',
      phrases: [
        { phrase: 'Peter Piper picked a peck of pickled peppers.', translation: '' },
        { phrase: 'She sells seashells by the seashore.', translation: '' },
        { phrase: 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?', translation: '' },
        { phrase: 'Betty Botter bought some butter, but she said the butter’s bitter.', translation: '' },
        { phrase: 'A proper copper coffee pot.', translation: '' },
        { phrase: 'Red lorry, yellow lorry.', translation: '' },
        { phrase: 'I scream, you scream, we all scream for ice cream.', translation: '' },
        { phrase: 'Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair.', translation: '' },
        { phrase: 'I saw Susie sitting in a shoeshine shop.', translation: '' },
        { phrase: 'Four furious friends fought for the phone.', translation: '' },
        { phrase: 'A big black bug bit a big black dog on his big black nose.', translation: '' },
        { phrase: 'I wish to wish the wish you wish to wish.', translation: '' },
        { phrase: 'If a dog chews shoes, whose shoes does he choose?', translation: '' },
        { phrase: 'How can a clam cram in a clean cream can?', translation: '' },
        { phrase: 'Six slippery snails, slid slowly seaward.', translation: '' },
        { phrase: 'The thirty-three thieves thought that they thrilled the throne throughout Thursday.', translation: '' },
        { phrase: 'I have got a date at a quarter to eight; I’ll see you at the gate, so don’t be late.', translation: '' },
        { phrase: 'Any noise annoys an oyster, but a noisy noise annoys an oyster more.', translation: '' },
        { phrase: 'Which witch is which?', translation: '' },
        { phrase: 'A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.', translation: '' },
        { phrase: 'Unique New York, New York unique.', translation: '' },
        { phrase: 'Round the rugged rock the ragged rascal ran.', translation: '' },
        { phrase: 'He threw three free throws.', translation: '' },
        { phrase: 'We surely shall see the sun shine soon.', translation: '' },
        { phrase: 'Fresh fried fish, fish fresh fried, fried fish fresh, fish fried fresh.', translation: '' },
        { phrase: 'If you understand, say "understand". If you don\'t understand, say "don\'t understand".', translation: '' },
        { phrase: 'A loyal warrior will rarely worry why we rule.', translation: '' },
        { phrase: 'Fred fed Ted bread, and Ted fed Fred bread.', translation: '' },
        { phrase: 'I slit the sheet, the sheet I slit, and on the slitted sheet I sit.', translation: '' },
        { phrase: 'To begin to toboggan first buy a toboggan, but don\'t buy too big a toboggan.', translation: '' }
      ]
    }
  },
  de: {
    'tongue-twisters': {
      title: 'Zungenbrecher',
      phrases: [
        { phrase: 'Fischers Fritz fischt frische Fische, frische Fische fischt Fischers Fritz.', translation: '' },
        { phrase: 'Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid.', translation: '' },
        { phrase: 'Zwischen zwei Zwetschgenzweigen zwitschern zwei Schwalben.', translation: '' },
        { phrase: 'Der dicke Dachdecker deckt das dicke Dach.', translation: '' },
        { phrase: 'Im dichten Fichtendickicht picken die Finken tüchtig.', translation: '' },
        { phrase: 'Wenn Fliegen hinter Fliegen fliegen, fliegen Fliegen hinter Fliegen her.', translation: '' },
        { phrase: 'Der Metzger wetzt das Metzgermesser.', translation: '' },
        { phrase: 'Schnecken erschrecken, wenn sie an Schnecken schlecken.', translation: '' },
        { phrase: 'Am zehnten Zehnten um zehn Uhr zehn zogen zehn zahme Ziegen zehn Zentner Zucker zum Zoo.', translation: '' },
        { phrase: 'Esel essen Nesseln nicht, Nesseln essen Esel nicht.', translation: '' },
        { phrase: 'Es klapperten die Klapperschlangen, bis ihre Klappern schlapper klangen.', translation: '' },
        { phrase: 'Der Cottbuser Postkutscher putzt den Cottbuser Postkutschkasten.', translation: '' },
        { phrase: 'Bierbrauer Bauer braut braunes Bier.', translation: '' },
        { phrase: 'Wenn hinter Robben Robben robben, robben Robben Robben hinterher.', translation: '' },
        { phrase: 'Es essen 11 Esel nasse Nesseln.', translation: '' },
        { phrase: 'Fromme Frösche fressen frische Früchte.', translation: '' },
        { phrase: 'Gibst du Opi Opium, bringt Opium Opi um.', translation: '' },
        { phrase: 'Der Gockel ga-ga-gackelt im Gras.', translation: '' },
        { phrase: 'Hans hackt Holz hinterm Hühnerhaus.', translation: '' },
        { phrase: 'In Ulm, um Ulm und um Ulm herum.', translation: '' },
        { phrase: 'Kleine Kinder können keine Kirschkerne knacken.', translation: '' },
        { phrase: 'Mäh’n Äbte Heu? Nie mäh’n Äbte Heu. Äbte beten.', translation: '' },
        { phrase: 'Russen reisen rasend schnell.', translation: '' },
        { phrase: 'Sieben Schneeschipper schippen sieben Schippen Schnee.', translation: '' },
        { phrase: 'Teste Theos Tee.', translation: '' },
        { phrase: 'Wer will, kann kommen.', translation: '' },
        { phrase: 'Zehn Ziegen zogen zehn Zentner Zucker zum Zoo.', translation: '' },
        { phrase: 'Der Zahnarzt zieht Zähne mit der Zange.', translation: '' },
        { phrase: 'Ein sehr schwer sehr schnell zu sprechender Spruch.', translation: '' },
        { phrase: 'Wir Wiener Waschweiber würden weiße Wäsche waschen, wenn wir wüssten, wo warmes Wasser wäre.', translation: '' }
      ]
    }
  },
  es: {
    'tongue-twisters': {
      title: 'Trabalenguas',
      phrases: [
        { phrase: 'Tres tristes tigres tragaban trigo en un trigal.', translation: '' },
        { phrase: 'Pablito clavó un clavito, ¿qué clavito clavó Pablito?', translation: '' },
        { phrase: 'El perro de San Roque no tiene rabo porque Ramón Ramírez se lo ha cortado.', translation: '' },
        { phrase: 'Erre con erre guitarra, erre con erre carril, rápido ruedan los carros, rápido el ferrocarril.', translation: '' },
        { phrase: 'Me han dicho que has dicho un dicho, un dicho que he dicho yo.', translation: '' },
        { phrase: 'Cuando cuentes cuentos, cuenta cuántos cuentos cuentas.', translation: '' },
        { phrase: 'El cielo está enladrillado, ¿quién lo desenladrillará?', translation: '' },
        { phrase: 'Poquito a poquito, Paquito empaca poquitas copitas en pocos paquetes.', translation: '' },
        { phrase: 'La pícara pájara pica en la típica jícara.', translation: '' },
        { phrase: 'El que poco coco come, poco coco compra.', translation: '' },
        { phrase: 'Si la sierva que te sirve, no te sirve como sierva, de qué sirve que te sirvas de una sierva que no sirve.', translation: '' },
        { phrase: 'Pepe pecas pica papas con un pico.', translation: '' },
        { phrase: 'Compadre, cómpreme un coco.', translation: '' },
        { phrase: 'El obispo de Constantinopla se quiere desconstantinopolizar.', translation: '' },
        { phrase: 'Un burro comía berros y el perro se los robó.', translation: '' },
        { phrase: 'Ñoño Yáñez come ñame en las mañanas con el niño.', translation: '' },
        { phrase: 'Pancha plancha con cuatro planchas. ¿Con cuántas planchas Pancha plancha?', translation: '' },
        { phrase: 'El ajo picó a la col, la col picó al ajo.', translation: '' },
        { phrase: 'Camarón, caramelo, caramelo, camarón.', translation: '' },
        { phrase: 'El que compra pocas capas, pocas capas paga.', translation: '' },
        { phrase: 'La bruja piruja prepara un brebaje con cera de abeja.', translation: '' },
        { phrase: 'El hipopótamo Hipo está con hipo.', translation: '' },
        { phrase: 'Si Sansón no sazona su salsa con sal, le sale sosa.', translation: '' },
        { phrase: 'Un dragón tragón tragó carbón y quedó panzón.', translation: '' },
        { phrase: 'Zorro, zorro, pide socorro con un gorro.', translation: '' },
        { phrase: 'Tengo una gallina pinta, piririnca, piriranca, con sus pollitos pintos, piririncos, pirirancos.', translation: '' },
        { phrase: 'El rey de Constantinopla está constantinoplizado.', translation: '' },
        { phrase: 'Pedro Pérez Pereira, pobre pintor portugués, pinta preciosos paisajes.', translation: '' },
        { phrase: 'Busco al vasco bizco que se fue brusco.', translation: '' },
        { phrase: '¿Cómo quieres que te quiera si el que quiero que me quiera no me quiere como quiero que me quiera?', translation: '' }
      ]
    }
  },
  fr: {
    'tongue-twisters': {
      title: 'Virelangues',
      phrases: [
        { phrase: 'Les chaussettes de l\'archiduchesse sont-elles sèches, archi-sèches ?', translation: '' },
        { phrase: 'Un chasseur sachant chasser doit savoir chasser sans son chien.', translation: '' },
        { phrase: 'Si six scies scient six cyprès, six cent six scies scient six cent six cyprès.', translation: '' },
        { phrase: 'Je veux et j\'exige d\'exquises excuses.', translation: '' },
        { phrase: 'Cinq chiens chassent six chats.', translation: '' },
        { phrase: 'Ton thé t\'a-t-il ôté ta toux ?', translation: '' },
        { phrase: 'Trois tortues trottaient sur un trottoir très étroit.', translation: '' },
        { phrase: 'Ces cerises sont si sûres qu\'on ne sait si c\'en sont.', translation: '' },
        { phrase: 'Un pâtissier qui pâtissait chez un tapissier qui tapissait.', translation: '' },
        { phrase: 'As-tu vu le ver vert allant vers le verre en verre vert?', translation: '' },
        { phrase: 'Piano, panier, panier, piano.', translation: '' },
        { phrase: 'Natacha n\'attacha pas son chat Pacha qui s\'échappa.', translation: '' },
        { phrase: 'Poisson sans boisson est poison.', translation: '' },
        { phrase: 'Le fisc fixe exprès chaque taxe fixe excessive exclusivement au luxe et à l\'exquis.', translation: '' },
        { phrase: 'Il était une fois, un homme de foi qui vendait du foie dans la ville de Foix.', translation: '' },
        { phrase: 'Je suis ce que je suis, et si je suis ce que je suis, qu\'est-ce que je suis?', translation: '' },
        { phrase: 'La pie niche haut, l\'oie niche bas. Où niche l\'hibou? L\'hibou niche ni haut ni bas.', translation: '' },
        { phrase: 'Son chat chante sa chanson.', translation: '' },
        { phrase: 'Cinq gros rats grillent dans la grosse graisse grasse.', translation: '' },
        { phrase: 'Petit pot de beurre, quand te dépetitpodebeurreriseras-tu?', translation: '' },
        { phrase: 'Le ver vert va vers le verre vert.', translation: '' },
        { phrase: 'Suis-je bien chez ce cher Serge?', translation: '' },
        { phrase: 'Un dragon gradé dégrade un gradé dragon.', translation: '' },
        { phrase: 'Ciel, si ceci se sait, ces soins sont sans succès.', translation: '' },
        { phrase: 'L\'abeille coule.', translation: '' },
        { phrase: 'Fruits frais, fruits frits, fruits cuits, fruits crus.', translation: '' },
        { phrase: 'La roue sur la rue roule; la rue sous la roue reste.', translation: '' },
        { phrase: 'Un plein plat de blé pilé.', translation: '' },
        { phrase: 'Ta tante t\'attend.', translation: '' },
        { phrase: 'Kiki était cocotte, et Koko concasseur de cacao.', translation: '' }
      ]
    }
  },
  it: {
    'tongue-twisters': {
      title: 'Scioglilingua',
      phrases: [
        { phrase: 'Trentatré trentini entrarono a Trento, tutti e trentatré trotterellando.', translation: '' },
        { phrase: 'Sopra la panca la capra campa, sotto la panca la capra crepa.', translation: '' },
        { phrase: 'Tre tigri contro tre tigri.', translation: '' },
        { phrase: 'Se l\'arcivescovo di Costantinopoli si disarcivescoviscostantinopolizzasse, vi disarcivescoviscostantinopolizzereste voi?', translation: '' },
        { phrase: 'Apelle, figlio di Apollo, fece una palla di pelle di pollo.', translation: '' },
        { phrase: 'A quest\'ora il questore in questura non c\'è.', translation: '' },
        { phrase: 'Li vuoi quei kiwi? E se non vuoi quei kiwi che kiwi vuoi?', translation: '' },
        { phrase: 'Chi ama chiama chi ama, chiamami tu che chi ami chiamo.', translation: '' },
        { phrase: 'Sette zucche secche e storte stanno strette in un sacco.', translation: '' },
        { phrase: 'Filo fine dentro il foro, più è fine meno è il foro.', translation: '' },
        { phrase: 'Se la serva non ti serve, a che serve che ti serva di una serva che non serve?', translation: '' },
        { phrase: 'Sa chi sa se sa chi sa che se sa non sa se sa, sa sol chi sa che nulla sa.', translation: '' },
        { phrase: 'Guglielmo coglie ghiaia dagli scogli.', translation: '' },
        { phrase: 'Chi porta in porto le porte, le riporta in porto o le porta altrove?', translation: '' },
        { phrase: 'Nel pozzo di San Patrizio c\'è una pazza che lava una pezza.', translation: '' },
        { phrase: 'Caro conte, chi ti canta tanto canta che t\'incanta.', translation: '' },
        { phrase: 'Scopo la casa, la scopa si sciupa.', translation: '' },
        { phrase: 'Sul tagliere gli agli taglia, non tagliare la tovaglia.', translation: '' },
        { phrase: 'Il Papa pesa e pesta il pepe a Pisa.', translation: '' },
        { phrase: 'Una platessa lessa lesse la stessa stressa.', translation: '' },
        { phrase: 'Stanno stretti sotto i letti sette spettri a denti stretti.', translation: '' },
        { phrase: 'Ho in tasca l\'esca ed esco per la pesca.', translation: '' },
        { phrase: 'Figlia, sfoglia la foglia, sfoglia la foglia, figlia.', translation: '' },
        { phrase: 'Sotto un cespo di rose paonazze c\'è un gran pozzo di pece.', translation: '' },
        { phrase: 'Un pezzo di pizza che puzza nel pozzo.', translation: '' },
        { phrase: 'Avevo un cavolo, l\'incavolai, ora non ho più il cavolo incavolato.', translation: '' },
        { phrase: 'Sereno è, sereno sarà; se non sarà sereno si rasserenerà.', translation: '' },
        { phrase: 'Dietro quel palazzo c\'è un povero cane pazzo.', translation: '' },
        { phrase: 'C\'è il questore in questura a quest\'ora?', translation: '' },
        { phrase: 'Vada, vadi, vado, vada dal podologo a podologarsi il dito.', translation: '' }
      ]
    }
  }
};
