
import type { PhrasesContent } from './phrases';

export const tongueTwistersContent: PhrasesContent = {
  en: {
    'tongue-twisters': {
      title: 'Tongue Twisters',
      phrases: [
        { phrase: 'Peter Piper picked a peck of pickled peppers.', translation: 'Piotr Piper zebrał miarkę marynowanej papryki.' },
        { phrase: 'She sells seashells by the seashore.', translation: 'Ona sprzedaje muszelki nad brzegiem morza.' },
        { phrase: 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?', translation: 'Ile drewna rzuciłby świstak, gdyby świstak potrafił rzucać drewnem?' },
        { phrase: 'Betty Botter bought some butter, but she said the butter’s bitter.', translation: 'Betty Botter kupiła trochę masła, ale powiedziała, że masło jest gorzkie.' },
        { phrase: 'A proper copper coffee pot.', translation: 'Prawidłowy miedziany dzbanek do kawy.' },
        { phrase: 'Red lorry, yellow lorry.', translation: 'Czerwona ciężarówka, żółta ciężarówka.' },
        { phrase: 'I scream, you scream, we all scream for ice cream.', translation: 'Ja krzyczę, ty krzyczysz, wszyscy krzyczymy za lodami.' },
        { phrase: 'Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair.', translation: 'Puszysty Wuzzy był niedźwiedziem. Puszysty Wuzzy nie miał włosów.' },
        { phrase: 'I saw Susie sitting in a shoeshine shop.', translation: 'Zobaczyłem Susie siedzącą w zakładzie czyszczenia butów.' },
        { phrase: 'Four furious friends fought for the phone.', translation: 'Czterech wściekłych przyjaciół walczyło o telefon.' },
        { phrase: 'A big black bug bit a big black dog on his big black nose.', translation: 'Duży czarny robak ugryzł dużego czarnego psa w jego duży czarny nos.' },
        { phrase: 'I wish to wish the wish you wish to wish.', translation: 'Chcę życzyć życzenia, które ty chcesz życzyć.' },
        { phrase: 'If a dog chews shoes, whose shoes does he choose?', translation: 'Jeśli pies żuje buty, czyje buty wybiera?' },
        { phrase: 'How can a clam cram in a clean cream can?', translation: 'Jak małż może wcisnąć się do czystej puszki ze śmietaną?' },
        { phrase: 'Six slippery snails, slid slowly seaward.', translation: 'Sześć śliskich ślimaków, ślizgało się powoli w kierunku morza.' },
        { phrase: 'The thirty-three thieves thought that they thrilled the throne throughout Thursday.', translation: 'Trzydziestu trzech złodziei myślało, że zachwycali tron przez cały czwartek.' },
        { phrase: 'I have got a date at a quarter to eight; I’ll see you at the gate, so don’t be late.', translation: 'Mam randkę za kwadrans ósma; zobaczymy się przy bramie, więc się nie spóźnij.' },
        { phrase: 'Any noise annoys an oyster, but a noisy noise annoys an oyster more.', translation: 'Każdy hałas denerwuje ostrygę, ale hałaśliwy hałas denerwuje ostrygę bardziej.' },
        { phrase: 'Which witch is which?', translation: 'Która wiedźma jest którą?' },
        { phrase: 'A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.', translation: 'Skunks usiadł na pniu i pomyślał, że pień śmierdzi, ale pień pomyślał, że skunks śmierdzi.' },
        { phrase: 'Unique New York, New York unique.', translation: 'Wyjątkowy Nowy Jork, Nowy Jork wyjątkowy.' },
        { phrase: 'Round the rugged rock the ragged rascal ran.', translation: 'Wokół chropowatej skały biegł obdarty łobuz.' },
        { phrase: 'He threw three free throws.', translation: 'Rzucił trzy rzuty wolne.' },
        { phrase: 'We surely shall see the sun shine soon.', translation: 'Z pewnością wkrótce zobaczymy słońce świecące.' },
        { phrase: 'Fresh fried fish, fish fresh fried, fried fish fresh, fish fried fresh.', translation: 'Świeżo smażona ryba, ryba świeżo smażona, smażona ryba świeża, ryba smażona świeża.' },
        { phrase: 'If you understand, say "understand". If you don\'t understand, say "don\'t understand".', translation: 'Jeśli rozumiesz, powiedz "rozumiem". Jeśli nie rozumiesz, powiedz "nie rozumiem".' },
        { phrase: 'A loyal warrior will rarely worry why we rule.', translation: 'Lojalny wojownik rzadko będzie się martwił, dlaczego rządzimy.' },
        { phrase: 'Fred fed Ted bread, and Ted fed Fred bread.', translation: 'Fred nakarmił Teda chlebem, a Ted nakarmił Freda chlebem.' },
        { phrase: 'I slit the sheet, the sheet I slit, and on the slitted sheet I sit.', translation: 'Rozciąłem prześcieradło, prześcieradło, które rozciąłem, i na rozciętym prześcieradle siedzę.' },
        { phrase: 'To begin to toboggan first buy a toboggan, but don\'t buy too big a toboggan.', translation: 'Aby zacząć jeździć na sankach, najpierw kup sanki, ale nie kupuj zbyt dużych sanek.' }
      ]
    }
  },
  de: {
    'tongue-twisters': {
      title: 'Zungenbrecher',
      phrases: [
        { phrase: 'Fischers Fritz fischt frische Fische, frische Fische fischt Fischers Fritz.', translation: 'Fritz rybaka łowi świeże ryby, świeże ryby łowi Fritz rybaka.' },
        { phrase: 'Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid.', translation: 'Czerwona kapusta pozostaje czerwoną kapustą, a suknia ślubna pozostaje suknią ślubną.' },
        { phrase: 'Zwischen zwei Zwetschgenzweigen zwitschern zwei Schwalben.', translation: 'Między dwiema gałązkami śliwy ćwierkają dwie jaskółki.' },
        { phrase: 'Der dicke Dachdecker deckt das dicke Dach.', translation: 'Gruby dekarz kryje gruby dach.' },
        { phrase: 'Im dichten Fichtendickicht picken die Finken tüchtig.', translation: 'W gęstym świerkowym gąszczu zięby dzielnie dziobią.' },
        { phrase: 'Wenn Fliegen hinter Fliegen fliegen, fliegen Fliegen hinter Fliegen her.', translation: 'Gdy muchy za muchami lecą, lecą muchy za muchami.' },
        { phrase: 'Der Metzger wetzt das Metzgermesser.', translation: 'Rzeźnik ostrzy nóż rzeźniczy.' },
        { phrase: 'Schnecken erschrecken, wenn sie an Schnecken schlecken.', translation: 'Ślimaki się przerażają, gdy liżą inne ślimaki.' },
        { phrase: 'Am zehnten Zehnten um zehn Uhr zehn zogen zehn zahme Ziegen zehn Zentner Zucker zum Zoo.', translation: 'Dziesiątego dziesiątego o dziesiątej dziesięć dziesięć oswojonych kóz ciągnęło dziesięć cetnarów cukru do zoo.' },
        { phrase: 'Esel essen Nesseln nicht, Nesseln essen Esel nicht.', translation: 'Osły nie jedzą pokrzyw, pokrzywy nie jedzą osłów.' },
        { phrase: 'Es klapperten die Klapperschlangen, bis ihre Klappern schlapper klangen.', translation: 'Grzechotniki grzechotały, aż ich grzechotki słabiej brzmiały.' },
        { phrase: 'Der Cottbuser Postkutscher putzt den Cottbuser Postkutschkasten.', translation: 'Woźnica pocztowy z Chociebuża czyści skrzynię pocztową z Chociebuża.' },
        { phrase: 'Bierbrauer Bauer braut braunes Bier.', translation: 'Piwowar Bauer warzy brązowe piwo.' },
        { phrase: 'Wenn hinter Robben Robben robben, robben Robben Robben hinterher.', translation: 'Gdy za fokami foki się czołgają, czołgają się foki za fokami.' },
        { phrase: 'Es essen 11 Esel nasse Nesseln.', translation: 'Jedenaście osłów je mokre pokrzywy.' },
        { phrase: 'Fromme Frösche fressen frische Früchte.', translation: 'Pobożne żaby jedzą świeże owoce.' },
        { phrase: 'Gibst du Opi Opium, bringt Opium Opi um.', translation: 'Jeśli dasz dziadkowi opium, opium zabije dziadka.' },
        { phrase: 'Der Gockel ga-ga-gackelt im Gras.', translation: 'Kogut gdacze w trawie.' },
        { phrase: 'Hans hackt Holz hinterm Hühnerhaus.', translation: 'Hans rąbie drewno za kurnikiem.' },
        { phrase: 'In Ulm, um Ulm und um Ulm herum.', translation: 'W Ulm, wokół Ulm i dookoła Ulm.' },
        { phrase: 'Kleine Kinder können keine Kirschkerne knacken.', translation: 'Małe dzieci nie potrafią rozgryzać pestek wiśni.' },
        { phrase: 'Mäh’n Äbte Heu? Nie mäh’n Äbte Heu. Äbte beten.', translation: 'Czy opaci koszą siano? Nigdy opaci nie koszą siana. Opaci się modlą.' },
        { phrase: 'Russen reisen rasend schnell.', translation: 'Rosjanie podróżują szaleńczo szybko.' },
        { phrase: 'Sieben Schneeschipper schippen sieben Schippen Schnee.', translation: 'Siedmiu odśnieżaczy odgarnia siedem łopat śniegu.' },
        { phrase: 'Teste Theos Tee.', translation: 'Spróbuj herbaty Theo.' },
        { phrase: 'Wer will, kann kommen.', translation: 'Kto chce, może przyjść.' },
        { phrase: 'Zehn Ziegen zogen zehn Zentner Zucker zum Zoo.', translation: 'Dziesięć kóz ciągnęło dziesięć cetnarów cukru do zoo.' },
        { phrase: 'Der Zahnarzt zieht Zähne mit der Zange.', translation: 'Dentysta wyrywa zęby cęgami.' },
        { phrase: 'Ein sehr schwer sehr schnell zu sprechender Spruch.', translation: 'Bardzo trudne do szybkiego wymówienia powiedzenie.' },
        { phrase: 'Wir Wiener Waschweiber würden weiße Wäsche waschen, wenn wir wüssten, wo warmes Wasser wäre.', translation: 'My, wiedeńskie praczki, prałybyśmy białe pranie, gdybyśmy wiedziały, gdzie jest ciepła woda.' }
      ]
    }
  },
  es: {
    'tongue-twisters': {
      title: 'Trabalenguas',
      phrases: [
        { phrase: 'Tres tristes tigres tragaban trigo en un trigal.', translation: 'Trzy smutne tygrysy połykały pszenicę na polu pszenicy.' },
        { phrase: 'Pablito clavó un clavito, ¿qué clavito clavó Pablito?', translation: 'Pablito wbił gwoździk, jaki gwoździk wbił Pablito?' },
        { phrase: 'El perro de San Roque no tiene rabo porque Ramón Ramírez se lo ha cortado.', translation: 'Pies świętego Rocha nie ma ogona, bo Ramón Ramírez go obciął.' },
        { phrase: 'Erre con erre guitarra, erre con erre carril, rápido ruedan los carros, rápido el ferrocarril.', translation: 'R z r gitara, r z r tor, szybko toczą się wozy, szybko kolej.' },
        { phrase: 'Me han dicho que has dicho un dicho, un dicho que he dicho yo.', translation: 'Powiedziano mi, że powiedziałeś powiedzenie, powiedzenie, które ja powiedziałem.' },
        { phrase: 'Cuando cuentes cuentos, cuenta cuántos cuentos cuentas.', translation: 'Kiedy opowiadasz opowieści, licz, ile opowieści opowiadasz.' },
        { phrase: 'El cielo está enladrillado, ¿quién lo desenladrillará?', translation: 'Niebo jest wybrukowane cegłami, kto je rozbrukuje?' },
        { phrase: 'Poquito a poquito, Paquito empaca poquitas copitas en pocos paquetes.', translation: 'Powolutku, Paquito pakuje mało kieliszków w mało paczek.' },
        { phrase: 'La pícara pájara pica en la típica jícara.', translation: 'Sprytny ptak dziobie w typowej tykwie.' },
        { phrase: 'El que poco coco come, poco coco compra.', translation: 'Kto je mało kokosa, mało kokosa kupuje.' },
        { phrase: 'Si la sierva que te sirve, no te sirve como sierva, de qué sirve que te sirvas de una sierva que no sirve.', translation: 'Jeśli służąca, która ci służy, nie służy ci jako służąca, na co ci służąca, która nie służy.' },
        { phrase: 'Pepe pecas pica papas con un pico.', translation: 'Pepe Pecas sieka ziemniaki kilofem.' },
        { phrase: 'Compadre, cómpreme un coco.', translation: 'Kumie, kup mi kokosa.' },
        { phrase: 'El obispo de Constantinopla se quiere desconstantinopolizar.', translation: 'Biskup Konstantynopola chce się zdekonstantynopolizować.' },
        { phrase: 'Un burro comía berros y el perro se los robó.', translation: 'Osioł jadł rzeżuchę, a pies mu ją ukradł.' },
        { phrase: 'Ñoño Yáñez come ñame en las mañanas con el niño.', translation: 'Ñoño Yáñez je pochrzyn rano z dzieckiem.' },
        { phrase: 'Pancha plancha con cuatro planchas. ¿Con cuántas planchas Pancha plancha?', translation: 'Pancha prasuje czterema żelazkami. Iloma żelazkami Pancha prasuje?' },
        { phrase: 'El ajo picó a la col, la col picó al ajo.', translation: 'Czosnek ugryzł kapustę, kapusta ugryzła czosnek.' },
        { phrase: 'Camarón, caramelo, caramelo, camarón.', translation: 'Krewetka, karmel, karmel, krewetka.' },
        { phrase: 'El que compra pocas capas, pocas capas paga.', translation: 'Kto kupuje mało peleryn, mało peleryn płaci.' },
        { phrase: 'La bruja piruja prepara un brebaje con cera de abeja.', translation: 'Czarownica Piruja przygotowuje miksturę z wosku pszczelego.' },
        { phrase: 'El hipopótamo Hipo está con hipo.', translation: 'Hipopotam Hipo ma czkawkę.' },
        { phrase: 'Si Sansón no sazona su salsa con sal, le sale sosa.', translation: 'Jeśli Samson nie doprawi swojego sosu solą, wyjdzie mu mdły.' },
        { phrase: 'Un dragón tragón tragó carbón y quedó panzón.', translation: 'Żarłoczny smok połknął węgiel i dostał brzuszka.' },
        { phrase: 'Zorro, zorro, pide socorro con un gorro.', translation: 'Lis, lisie, proś o pomoc w czapce.' },
        { phrase: 'Tengo una gallina pinta, piririnca, piriranca, con sus pollitos pintos, piririncos, pirirancos.', translation: 'Mam kurę łaciatą, piririnca, piriranca, z jej łaciatymi, piririncos, pirirancos kurczaczkami.' },
        { phrase: 'El rey de Constantinopla está constantinoplizado.', translation: 'Król Konstantynopola jest skonstantynopolizowany.' },
        { phrase: 'Pedro Pérez Pereira, pobre pintor portugués, pinta preciosos paisajes.', translation: 'Pedro Pérez Pereira, biedny portugalski malarz, maluje piękne krajobrazy.' },
        { phrase: 'Busco al vasco bizco que se fue brusco.', translation: 'Szukam zezowatego Baska, który odszedł gwałtownie.' },
        { phrase: '¿Cómo quieres que te quiera si el que quiero que me quiera no me quiere como quiero que me quiera?', translation: 'Jak chcesz, żebym cię kochał, skoro ten, którego chcę, by mnie kochał, nie kocha mnie tak, jak chcę, by mnie kochał?' }
      ]
    }
  },
  fr: {
    'tongue-twisters': {
      title: 'Virelangues',
      phrases: [
        { phrase: 'Les chaussettes de l\'archiduchesse sont-elles sèches, archi-sèches ?', translation: 'Czy skarpety arcyksiężnej są suche, arcy-suche?' },
        { phrase: 'Un chasseur sachant chasser doit savoir chasser sans son chien.', translation: 'Myśliwy umiejący polować musi umieć polować bez swojego psa.' },
        { phrase: 'Si six scies scient six cyprès, six cent six scies scient six cent six cyprès.', translation: 'Jeśli sześć pił tnie sześć cyprysów, sześćset sześć pił tnie sześćset sześć cyprysów.' },
        { phrase: 'Je veux et j\'exige d\'exquises excuses.', translation: 'Chcę i wymagam wyśmienitych przeprosin.' },
        { phrase: 'Cinq chiens chassent six chats.', translation: 'Pięć psów poluje na sześć kotów.' },
        { phrase: 'Ton thé t\'a-t-il ôté ta toux ?', translation: 'Czy twoja herbata usunęła twój kaszel?' },
        { phrase: 'Trois tortues trottaient sur un trottoir très étroit.', translation: 'Trzy żółwie człapały po bardzo wąskim chodniku.' },
        { phrase: 'Ces cerises sont si sûres qu\'on ne sait si c\'en sont.', translation: 'Te wiśnie są tak kwaśne, że nie wiadomo, czy to one.' },
        { phrase: 'Un pâtissier qui pâtissait chez un tapissier qui tapissait.', translation: 'Cukiernik, który piekł ciasta u tapicera, który tapetował.' },
        { phrase: 'As-tu vu le ver vert allant vers le verre en verre vert?', translation: 'Czy widziałeś zielonego robaka idącego w kierunku zielonego szklanego kieliszka?' },
        { phrase: 'Piano, panier, panier, piano.', translation: 'Fortepian, koszyk, koszyk, fortepian.' },
        { phrase: 'Natacha n\'attacha pas son chat Pacha qui s\'échappa.', translation: 'Natasza nie przywiązała swojego kota Paszy, który uciekł.' },
        { phrase: 'Poisson sans boisson est poison.', translation: 'Ryba bez napoju to trucizna.' },
        { phrase: 'Le fisc fixe exprès chaque taxe fixe excessive exclusivement au luxe et à l\'exquis.', translation: 'Urząd skarbowy celowo ustala każdy stały nadmierny podatek wyłącznie na luksus i wykwintność.' },
        { phrase: 'Il était une fois, un homme de foi qui vendait du foie dans la ville de Foix.', translation: 'Był sobie raz człowiek wiary, który sprzedawał wątrobę w mieście Foix.' },
        { phrase: 'Je suis ce que je suis, et si je suis ce que je suis, qu\'est-ce que je suis?', translation: 'Jestem tym, kim jestem, a jeśli jestem tym, kim jestem, to kim jestem?' },
        { phrase: 'La pie niche haut, l\'oie niche bas. Où niche l\'hibou? L\'hibou niche ni haut ni bas.', translation: 'Sroka gniazduje wysoko, gęś gniazduje nisko. Gdzie gniazduje sowa? Sowa nie gniazduje ani wysoko, ani nisko.' },
        { phrase: 'Son chat chante sa chanson.', translation: 'Jego kot śpiewa swoją piosenkę.' },
        { phrase: 'Cinq gros rats grillent dans la grosse graisse grasse.', translation: 'Pięć dużych szczurów grilluje się w dużym tłustym tłuszczu.' },
        { phrase: 'Petit pot de beurre, quand te dépetitpodebeurreriseras-tu?', translation: 'Mały słoiczku masła, kiedy się odmaślisz?' },
        { phrase: 'Le ver vert va vers le verre vert.', translation: 'Zielony robak idzie w kierunku zielonego szkła.' },
        { phrase: 'Suis-je bien chez ce cher Serge?', translation: 'Czy jestem u tego drogiego Serge\'a?' },
        { phrase: 'Un dragon gradé dégrade un gradé dragon.', translation: 'Stopniowany smok degraduje stopniowanego smoka.' },
        { phrase: 'Ciel, si ceci se sait, ces soins sont sans succès.', translation: 'O rany, jeśli to się wyda, te zabiegi są bez powodzenia.' },
        { phrase: 'L\'abeille coule.', translation: 'Pszczoła tonie.' },
        { phrase: 'Fruits frais, fruits frits, fruits cuits, fruits crus.', translation: 'Świeże owoce, smażone owoce, gotowane owoce, surowe owoce.' },
        { phrase: 'La roue sur la rue roule; la rue sous la roue reste.', translation: 'Koło na ulicy się toczy; ulica pod kołem zostaje.' },
        { phrase: 'Un plein plat de blé pilé.', translation: 'Pełny talerz tłuczonej pszenicy.' },
        { phrase: 'Ta tante t\'attend.', translation: 'Twoja ciocia na ciebie czeka.' },
        { phrase: 'Kiki était cocotte, et Koko concasseur de cacao.', translation: 'Kiki była kurką, a Koko kruszarką do kakao.' }
      ]
    }
  },
  it: {
    'tongue-twisters': {
      title: 'Scioglilingua',
      phrases: [
        { phrase: 'Trentatré trentini entrarono a Trento, tutti e trentatré trotterellando.', translation: 'Trzydziestu trzech mieszkańców Trydentu weszło do Trydentu, wszyscy trzydziestu trzech truchtając.' },
        { phrase: 'Sopra la panca la capra campa, sotto la panca la capra crepa.', translation: 'Na ławce koza żyje, pod ławką koza zdycha.' },
        { phrase: 'Tre tigri contro tre tigri.', translation: 'Trzy tygrysy przeciwko trzem tygrysom.' },
        { phrase: 'Se l\'arcivescovo di Costantinopoli si disarcivescoviscostantinopolizzasse, vi disarcivescoviscostantinopolizzereste voi?', translation: 'Gdyby arcybiskup Konstantynopola się zdearcybiskupizowałkonstantynopolizował, czy wy byście się zdearcybiskupizowalikostantynopolizowali?' },
        { phrase: 'Apelle, figlio di Apollo, fece una palla di pelle di pollo.', translation: 'Apelles, syn Apolla, zrobił piłkę ze skóry kurczaka.' },
        { phrase: 'A quest\'ora il questore in questura non c\'è.', translation: 'O tej godzinie komendanta nie ma na komendzie.' },
        { phrase: 'Li vuoi quei kiwi? E se non vuoi quei kiwi che kiwi vuoi?', translation: 'Chcesz te kiwi? A jeśli nie chcesz tych kiwi, to jakie kiwi chcesz?' },
        { phrase: 'Chi ama chiama chi ama, chiamami tu che chi ami chiamo.', translation: 'Kto kocha, woła kogo kocha, zawołaj mnie ty, bo ja wołam kogo kochasz.' },
        { phrase: 'Sette zucche secche e storte stanno strette in un sacco.', translation: 'Siedem suchych i krzywych dyń ciasno siedzi w worku.' },
        { phrase: 'Filo fine dentro il foro, più è fine meno è il foro.', translation: 'Cienka nić w otworze, im cieńsza, tym mniejszy otwór.' },
        { phrase: 'Se la serva non ti serve, a che serve che ti serva di una serva che non serve?', translation: 'Jeśli służąca ci nie służy, na co ci służąca, która nie służy.' },
        { phrase: 'Sa chi sa se sa chi sa che se sa non sa se sa, sa sol chi sa che nulla sa.', translation: 'Wie ten, kto wie, czy wie ten, kto wie, że jeśli wie, nie wie, czy wie, wie tylko ten, kto wie, że nic nie wie.' },
        { phrase: 'Guglielmo coglie ghiaia dagli scogli.', translation: 'Guglielmo zbiera żwir ze skał.' },
        { phrase: 'Chi porta in porto le porte, le riporta in porto o le porta altrove?', translation: 'Kto nosi drzwi do portu, przynosi je z powrotem do portu czy zabiera gdzie indziej?' },
        { phrase: 'Nel pozzo di San Patrizio c\'è una pazza che lava una pezza.', translation: 'W studni Świętego Patryka jest wariatka, która pierze szmatkę.' },
        { phrase: 'Caro conte, chi ti canta tanto canta che t\'incanta.', translation: 'Drogi hrabio, kto ci śpiewa, tak śpiewa, że cię oczarowuje.' },
        { phrase: 'Scopo la casa, la scopa si sciupa.', translation: 'Zamiatam dom, miotła się niszczy.' },
        { phrase: 'Sul tagliere gli agli taglia, non tagliare la tovaglia.', translation: 'Na desce do krojenia czosnek krój, nie krój obrusu.' },
        { phrase: 'Il Papa pesa e pesta il pepe a Pisa.', translation: 'Papież waży i tłucze pieprz w Pizie.' },
        { phrase: 'Una platessa lessa lesse la stessa stressa.', translation: 'Gotowana flądra przeczytała tę samą stresującą rzecz.' },
        { phrase: 'Stanno stretti sotto i letti sette spettri a denti stretti.', translation: 'Siedem duchów z zaciśniętymi zębami ciasno mieści się pod łóżkami.' },
        { phrase: 'Ho in tasca l\'esca ed esco per la pesca.', translation: 'Mam w kieszeni przynętę i wychodzę na ryby.' },
        { phrase: 'Figlia, sfoglia la foglia, sfoglia la foglia, figlia.', translation: 'Córko, przekartkuj liść, przekartkuj liść, córko.' },
        { phrase: 'Sotto un cespo di rose paonazze c\'è un gran pozzo di pece.', translation: 'Pod krzakiem fioletowych róż jest wielka studnia smoły.' },
        { phrase: 'Un pezzo di pizza che puzza nel pozzo.', translation: 'Kawałek pizzy, który śmierdzi w studni.' },
        { phrase: 'Avevo un cavolo, l\'incavolai, ora non ho più il cavolo incavolato.', translation: 'Miałem kapustę, wkapuściłem ją, teraz nie mam już wkapuszczonej kapusty.' },
        { phrase: 'Sereno è, sereno sarà; se non sarà sereno si rasserenerà.', translation: 'Jest pogodnie, będzie pogodnie; jeśli nie będzie pogodnie, rozpogodzi się.' },
        { phrase: 'Dietro quel palazzo c\'è un povero cane pazzo.', translation: 'Za tamtym pałacem jest biedny szalony pies.' },
        { phrase: 'C\'è il questore in questura a quest\'ora?', translation: 'Czy jest komendant na komendzie o tej godzinie?' },
        { phrase: 'Vada, vadi, vado, vada dal podologo a podologarsi il dito.', translation: 'Idź, idź, idę, idź do podologa, aby wyleczyć sobie palec.' }
      ]
    }
  }
};
