import type { SynonymPair } from './synonym-match-data';

export const synonymQuestionsDe: SynonymPair[] = [
    { word1: 'glücklich', word2: 'froh' },
    { word1: 'groß', word2: 'riesig' },
    { word1: 'schnell', word2: 'rasch' },
    { word1: 'traurig', word2: 'betrübt' },
    { word1: 'klein', word2: 'winzig' },
    { word1: 'wütend', word2: 'zornig' },
    { word1: 'schön', word2: 'hübsch' },
    { word1: 'klug', word2: 'intelligent' },
    { word1: 'anfangen', word2: 'beginnen' },
    { word1: 'beenden', word2: 'abschließen' },
    { word1: 'reich', word2: 'wohlhabend' },
    { word1: 'arm', word2: 'bedürftig' },
    { word1: 'sprechen', word2: 'reden' },
    { word1: 'schauen', word2: 'sehen' },
    { word1: 'machen', word2: 'erschaffen' },
    { word1: 'zerstören', word2: 'ruinieren' },
    { word1: 'lustig', word2: 'komisch' },
    { word1: 'leise', word2: 'still' },
    { word1: 'laut', word2: 'lärmend' },
    { word1: 'müde', word2: 'erschöpft' },
    { word1: 'ängstlich', word2: 'furchtsam' },
    { word1: 'mutig', word2: 'tapfer' },
    { word1: 'froh', word2: 'erfreut' },
    { word1: 'helfen', word2: 'assistieren' },
    { word1: 'Beruf', word2: 'Tätigkeit' },
    { word1: 'Geschenk', word2: 'Präsent' },
    { word1: 'wahr', word2: 'richtig' },
    { word1: 'falsch', word2: 'inkorrekt' },
    { word1: 'alt', word2: 'antik' },
    { word1: 'neu', word2: 'modern' },
];
