import type { SynonymPair } from './synonym-match-data';

export const synonymQuestionsEs: SynonymPair[] = [
    { word1: 'feliz', word2: 'contento' },
    { word1: 'grande', word2: 'enorme' },
    { word1: 'rápido', word2: 'veloz' },
    { word1: 'triste', word2: 'apenado' },
    { word1: 'pequeño', word2: 'diminuto' },
    { word1: 'enfadado', word2: 'furioso' },
    { word1: 'bonito', word2: 'hermoso' },
    { word1: 'listo', word2: 'inteligente' },
    { word1: 'empezar', word2: 'comenzar' },
    { word1: 'terminar', word2: 'finalizar' },
    { word1: 'rico', word2: 'adinerado' },
    { word1: 'pobre', word2: 'necesitado' },
    { word1: 'hablar', word2: 'conversar' },
    { word1: 'mirar', word2: 'ver' },
    { word1: 'crear', word2: 'hacer' },
    { word1: 'destruir', word2: 'arruinar' },
    { word1: 'gracioso', word2: 'divertido' },
    { word1: 'tranquilo', word2: 'silencioso' },
    { word1: 'ruidoso', word2: 'estruendoso' },
    { word1: 'cansado', word2: 'agotado' },
    { word1: 'asustado', word2: 'atemorizado' },
    { word1: 'valiente', word2: 'corajudo' },
    { word1: 'alegre', word2: 'feliz' },
    { word1: 'ayudar', word2: 'asistir' },
    { word1: 'trabajo', word2: 'empleo' },
    { word1: 'regalo', word2: 'presente' },
    { word1: 'verdad', word2: 'cierto' },
    { word1: 'falso', word2: 'incorrecto' },
    { word1: 'viejo', word2: 'antiguo' },
    { word1: 'nuevo', word2: 'moderno' },
];
