import type { SynonymPair } from './synonym-match-data';

export const synonymQuestionsEn: SynonymPair[] = [
    { word1: 'happy', word2: 'joyful' },
    { word1: 'big', word2: 'large' },
    { word1: 'fast', word2: 'quick' },
    { word1: 'sad', word2: 'unhappy' },
    { word1: 'small', word2: 'tiny' },
    { word1: 'angry', word2: 'furious' },
    { word1: 'beautiful', word2: 'pretty' },
    { word1: 'smart', word2: 'intelligent' },
    { word1: 'start', word2: 'begin' },
    { word1: 'end', word2: 'finish' },
    { word1: 'rich', word2: 'wealthy' },
    { word1: 'poor', word2: 'needy' },
    { word1: 'speak', word2: 'talk' },
    { word1: 'look', word2: 'see' },
    { word1: 'create', word2: 'make' },
    { word1: 'destroy', word2: 'ruin' },
    { word1: 'funny', word2: 'hilarious' },
    { word1: 'quiet', word2: 'silent' },
    { word1: 'loud', word2: 'noisy' },
    { word1: 'tired', word2: 'exhausted' },
    { word1: 'scared', word2: 'afraid' },
    { word1: 'brave', word2: 'courageous' },
    { word1: 'glad', word2: 'pleased' },
    { word1: 'help', word2: 'assist' },
    { word1: 'job', word2: 'occupation' },
    { word1: 'present', word2: 'gift' },
    { word1: 'true', word2: 'correct' },
    { word1: 'false', word2: 'incorrect' },
    { word1: 'old', word2: 'ancient' },
    { word1: 'new', word2: 'modern' },
];
