import type { SynonymPair } from './synonym-match-data';

export const synonymQuestionsFr: SynonymPair[] = [
    { word1: 'heureux', word2: 'joyeux' },
    { word1: 'grand', word2: 'vaste' },
    { word1: 'rapide', word2: 'vite' },
    { word1: 'triste', word2: 'malheureux' },
    { word1: 'petit', word2: 'minuscule' },
    { word1: 'fâché', word2: 'en colère' },
    { word1: 'beau', word2: 'joli' },
    { word1: 'intelligent', word2: 'astucieux' },
    { word1: 'commencer', word2: 'débuter' },
    { word1: 'finir', word2: 'terminer' },
    { word1: 'riche', word2: 'fortuné' },
    { word1: 'pauvre', word2: 'indigent' },
    { word1: 'parler', word2: 'discuter' },
    { word1: 'regarder', word2: 'voir' },
    { word1: 'créer', word2: 'fabriquer' },
    { word1: 'détruire', word2: 'ruiner' },
    { word1: 'drôle', word2: 'amusant' },
    { word1: 'calme', word2: 'silencieux' },
    { word1: 'bruyant', word2: 'tapageur' },
    { word1: 'fatigué', word2: 'épuisé' },
    { word1: 'effrayé', word2: 'apeuré' },
    { word1: 'courageux', word2: 'brave' },
    { word1: 'content', word2: 'satisfait' },
    { word1: 'aider', word2: 'assister' },
    { word1: 'métier', word2: 'profession' },
    { word1: 'cadeau', word2: 'présent' },
    { word1: 'vrai', word2: 'correct' },
    { word1: 'faux', word2: 'incorrect' },
    { word1: 'vieux', word2: 'ancien' },
    { word1: 'nouveau', word2: 'moderne' },
];
