import type { SynonymPair } from './synonym-match-data';

export const synonymQuestionsIt: SynonymPair[] = [
    { word1: 'felice', word2: 'contento' },
    { word1: 'grande', word2: 'enorme' },
    { word1: 'veloce', word2: 'rapido' },
    { word1: 'triste', word2: 'addolorato' },
    { word1: 'piccolo', word2: 'minuscolo' },
    { word1: 'arrabbiato', word2: 'furioso' },
    { word1: 'bello', word2: 'carino' },
    { word1: 'intelligente', word2: 'astuto' },
    { word1: 'iniziare', word2: 'cominciare' },
    { word1: 'finire', word2: 'terminare' },
    { word1: 'ricco', word2: 'facoltoso' },
    { word1: 'povero', word2: 'bisognoso' },
    { word1: 'parlare', word2: 'conversare' },
    { word1: 'guardare', word2: 'vedere' },
    { word1: 'creare', word2: 'fare' },
    { word1: 'distruggere', word2: 'rovinare' },
    { word1: 'divertente', word2: 'comico' },
    { word1: 'calmo', word2: 'silenzioso' },
    { word1: 'rumoroso', word2: 'chiassoso' },
    { word1: 'stanco', word2: 'esausto' },
    { word1: 'spaventato', word2: 'impaurito' },
    { word1: 'coraggioso', word2: 'valoroso' },
    { word1: 'allegro', word2: 'felice' },
    { word1: 'aiutare', word2: 'assistere' },
    { word1: 'lavoro', word2: 'mestiere' },
    { word1: 'regalo', word2: 'dono' },
    { word1: 'vero', word2: 'corretto' },
    { word1: 'falso', word2: 'sbagliato' },
    { word1: 'vecchio', word2: 'antico' },
    { word1: 'nuovo', word2: 'moderno' },
];
