
import type { PhrasesContent } from '../phrases';

export const stationPhrases: PhrasesContent = {
  en: {
    station: {
        title: 'Station',
        phrases: [
            { phrase: 'A one-way ticket to London, please.', translation: 'Poproszę bilet w jedną stronę do Londynu.' },
            { phrase: 'A round-trip ticket, please.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'Which platform does the train to Berlin leave from?', translation: 'Z którego peronu odjeżdża pociąg do Berlina?' },
            { phrase: 'What time is the next train to Paris?', translation: 'O której jest następny pociąg do Paryża?' },
            { phrase: 'Is this train direct?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Where is the ticket office?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Where can I find the timetable?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'I need to validate my ticket.', translation: 'Muszę skasować bilet.' },
            { phrase: 'Is this seat taken?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'This is my stop.', translation: 'To mój przystanek.' },
            { phrase: 'I missed my train.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'The train is cancelled.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'First or second class?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'How many stops to the central station?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Does this bus go to the city center?', translation: 'Czy ten autobus jedzie do centrum miasta?' },
            { phrase: 'How long is the journey?', translation: 'Jak długa jest podróż?' },
            { phrase: 'Is there a toilet on the train?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Where are the lockers?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'I\'d like to reserve a seat.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'I have a rail pass.', translation: 'Mam bilet okresowy na pociąg.' },
            { phrase: 'I lost my ticket.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'The train is arriving at platform 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'Is there a dining car on this train?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Please mind the gap.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'I\'d like to buy a ticket from the machine.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'How much is a ticket for a child?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
  },
  de: {
    station: {
        title: 'Am Bahnhof',
        phrases: [
            { phrase: 'Eine einfache Fahrt nach Berlin, bitte.', translation: 'Poproszę bilet w jedną stronę do Berlina.' },
            { phrase: 'Eine Rückfahrkarte, bitte.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'Von welchem Gleis fährt der Zug nach Berlin ab?', translation: 'Z którego peronu odjeżdża pociąg do Berlina?' },
            { phrase: 'Wann fährt der nächste Zug nach Paris?', translation: 'O której jest następny pociąg do Paryża?' },
            { phrase: 'Ist das ein direkter Zug?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Wo ist der Fahrkartenschalter?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Wo finde ich den Fahrplan?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Ich muss meine Fahrkarte entwerten.', translation: 'Muszę skasować bilet.' },
            { phrase: 'Ist dieser Platz besetzt?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'Das ist meine Haltestelle.', translation: 'To mój przystanek.' },
            { phrase: 'Ich habe meinen Zug verpasst.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'Der Zug fällt aus.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'Erste oder zweite Klasse?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'Wie viele Haltestellen bis zum Hauptbahnhof?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Fährt dieser Bus ins Stadtzentrum?', translation: 'Czy ten autobus jedzie do centrum miasta?' },
            { phrase: 'Wie lange dauert die Fahrt?', translation: 'Jak długa jest podróż?' },
            { phrase: 'Gibt es eine Toilette im Zug?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Wo sind die Schließfächer?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Ich möchte einen Sitzplatz reservieren.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'Ich habe eine Monatskarte.', translation: 'Mam bilet miesięczny.' },
            { phrase: 'Ich habe meine Fahrkarte verloren.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'Der Zug kommt auf Gleis 5 an.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'Gibt es einen Speisewagen in diesem Zug?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Vorsicht an der Bahnsteigkante.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Ich möchte eine Fahrkarte am Automaten kaufen.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'Wie viel kostet eine Kinderfahrkarte?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
  },
  fr: {
    station: {
        title: 'À la Gare',
        phrases: [
            { phrase: 'Un aller simple pour Paris, s\'il vous plaît.', translation: 'Poproszę bilet w jedną stronę do Paryża.' },
            { phrase: 'Un aller-retour, s\'il vous plaît.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'De quel quai part le train pour Berlin?', translation: 'Z którego peronu odjeżdża pociąg do Berlina?' },
            { phrase: 'À quelle heure est le prochain train pour Paris?', translation: 'O której jest następny pociąg do Paryża?' },
            { phrase: 'Est-ce un train direct?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Où est le guichet?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Où puis-je trouver les horaires?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Je dois composter mon billet.', translation: 'Muszę skasować bilet.' },
            { phrase: 'Est-ce que cette place est libre?', translation: 'Czy to miejsce jest wolne?' },
            { phrase: 'C\'est mon arrêt.', translation: 'To mój przystanek.' },
            { phrase: 'J\'ai raté mon train.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'Le train est annulé.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'Première ou seconde classe?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'Combien d\'arrêts jusqu\'à la gare centrale?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Ce bus va-t-il au centre-ville?', translation: 'Czy ten autobus jedzie do centrum miasta?' },
            { phrase: 'Combien de temps dure le trajet?', translation: 'Jak długa jest podróż?' },
            { phrase: 'Y a-t-il des toilettes dans le train?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Où sont les consignes?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Je voudrais réserver une place.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'J\'ai un abonnement.', translation: 'Mam bilet okresowy.' },
            { phrase: 'J\'ai perdu mon billet.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'Le train arrive sur la voie 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'Y a-t-il un wagon-restaurant dans ce train?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Attention à la marche.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Je voudrais acheter un billet au distributeur.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'Combien coûte un billet pour enfant?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
  },
  es: {
    station: {
        title: 'En la Estación',
        phrases: [
            { phrase: 'Un billete de ida a Madrid, por favor.', translation: 'Poproszę bilet w jedną stronę do Madrytu.' },
            { phrase: 'Un billete de ida y vuelta, por favor.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: '¿De qué andén sale el tren para Barcelona?', translation: 'Z którego peronu odjeżdża pociąg do Barcelony?' },
            { phrase: '¿A qué hora es el próximo tren a Sevilla?', translation: 'O której jest następny pociąg do Sewilli?' },
            { phrase: '¿Este tren es directo?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: '¿Dónde está la taquilla?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: '¿Dónde puedo encontrar el horario?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Tengo que validar mi billete.', translation: 'Muszę skasować bilet.' },
            { phrase: '¿Está ocupado este asiento?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'Esta es mi parada.', translation: 'To mój przystanek.' },
            { phrase: 'He perdido mi tren.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'El tren está cancelado.', translation: 'Pociąg jest odwołany.' },
            { phrase: '¿Primera o segunda clase?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: '¿Cuántas paradas hasta la estación central?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: '¿Este autobús va al centro?', translation: 'Czy ten autobus jedzie do centrum?' },
            { phrase: '¿Cuánto dura el viaje?', translation: 'Jak długa jest podróż?' },
            { phrase: '¿Hay un baño en el tren?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: '¿Dónde están las consignas?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Quisiera reservar un asiento.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'Tengo un abono de transporte.', translation: 'Mam bilet okresowy.' },
            { phrase: 'He perdido mi billete.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'El tren llega al andén 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: '¿Hay vagón restaurante en este tren?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Cuidado con el hueco entre el tren y el andén.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Quisiera comprar un billete en la máquina.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: '¿Cuánto cuesta un billete para niño?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
  },
  it: {
    station: {
        title: 'Alla Stazione',
        phrases: [
            { phrase: 'Un biglietto di sola andata per Roma, per favore.', translation: 'Poproszę bilet w jedną stronę do Rzymu.' },
            { phrase: 'Un biglietto di andata e ritorno, per favore.', translation: 'Poproszę bilet w obie strony.' },
            { phrase: 'Da quale binario parte il treno per Milano?', translation: 'Z którego peronu odjeżdża pociąg do Mediolanu?' },
            { phrase: 'A che ora è il prossimo treno per Napoli?', translation: 'O której jest następny pociąg do Neapolu?' },
            { phrase: 'Questo treno è diretto?', translation: 'Czy ten pociąg jest bezpośredni?' },
            { phrase: 'Dov\'è la biglietteria?', translation: 'Gdzie jest kasa biletowa?' },
            { phrase: 'Dove posso trovare l\'orario ferroviario?', translation: 'Gdzie znajdę rozkład jazdy?' },
            { phrase: 'Devo convalidare il biglietto.', translation: 'Muszę skasować bilet.' },
            { phrase: 'È occupato questo posto?', translation: 'Czy to miejsce jest zajęte?' },
            { phrase: 'Questa è la mia fermata.', translation: 'To mój przystanek.' },
            { phrase: 'Ho perso il treno.', translation: 'Spóźniłem/am się na pociąg.' },
            { phrase: 'Il treno è stato cancellato.', translation: 'Pociąg jest odwołany.' },
            { phrase: 'Prima o seconda classe?', translation: 'Pierwsza czy druga klasa?' },
            { phrase: 'Quante fermate fino alla stazione centrale?', translation: 'Ile przystanków do dworca centralnego?' },
            { phrase: 'Questo autobus va in centro?', translation: 'Czy ten autobus jedzie do centrum?' },
            { phrase: 'Quanto dura il viaggio?', translation: 'Jak długa jest podróż?' },
            { phrase: 'C\'è un bagno sul treno?', translation: 'Czy w pociągu jest toaleta?' },
            { phrase: 'Dove sono i depositi bagagli?', translation: 'Gdzie są szafki na bagaż?' },
            { phrase: 'Vorrei prenotare un posto.', translation: 'Chciałbym/Chciałabym zarezerwować miejsce.' },
            { phrase: 'Ho un abbonamento.', translation: 'Mam bilet okresowy.' },
            { phrase: 'Ho perso il biglietto.', translation: 'Zgubiłem/am bilet.' },
            { phrase: 'Il treno arriva al binario 5.', translation: 'Pociąg wjeżdża na peron 5.' },
            { phrase: 'C\'è una carrozza ristorante su questo treno?', translation: 'Czy w tym pociągu jest wagon restauracyjny?' },
            { phrase: 'Attenzione alla distanza tra il treno e la banchina.', translation: 'Proszę uważać na odstęp (między pociągiem a peronem).' },
            { phrase: 'Vorrei comprare un biglietto alla macchinetta.', translation: 'Chciałbym/Chciałabym kupić bilet w automacie.' },
            { phrase: 'Quanto costa un biglietto per bambini?', translation: 'Ile kosztuje bilet dla dziecka?' }
        ]
    },
  },
};
