
import type { PhrasesContent } from '../phrases';

export const hotelPhrases: PhrasesContent = {
  en: {
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'I have a reservation.', translation: 'Mam rezerwację.' },
            { phrase: 'Can I check in, please?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'What time is check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'I\'d like to check out.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'Does the room have Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'What\'s the Wi-Fi password?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'A wake-up call at 7 AM, please.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'My key card doesn\'t work.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'The air conditioning is not working.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'There is no hot water.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'Can I have an extra towel?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Could you make up my room, please?', translation: 'Czy można posprzątać mój pokój?' },
            { phrase: 'Please do not disturb.', translation: 'Proszę nie przeszkadzać.' },
            { phrase: 'Can I have breakfast in my room?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'What time is breakfast served?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Can you call a taxi for me?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Can I leave my luggage here?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Where is the restaurant/gym?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'Does the hotel have a swimming pool?', translation: 'Czy hotel ma basen?' },
            { phrase: 'Can I pay by credit card?', translation: 'Czy mogę zapłacić kartą kredytową?' },
        ]
    },
  },
  de: {
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'Ich habe eine Reservierung.', translation: 'Mam rezerwację.' },
            { phrase: 'Kann ich bitte einchecken?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'Wann ist der Check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Ich möchte auschecken.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'Gibt es WLAN im Zimmer?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'Wie lautet das WLAN-Passwort?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Einen Weckruf um 7 Uhr, bitte.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Meine Schlüsselkarte funktioniert nicht.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'Die Klimaanlage funktioniert nicht.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'Es gibt kein heißes Wasser.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'Kann ich ein zusätzliches Handtuch haben?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Könnten Sie bitte mein Zimmer machen?', translation: 'Czy można posprzątać mój pokój?' },
            { phrase: 'Bitte nicht stören.', translation: 'Proszę nie przeszkadzać.' },
            { phrase: 'Kann ich das Frühstück auf dem Zimmer haben?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'Wann wird das Frühstück serviert?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Können Sie mir ein Taxi rufen?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Kann ich mein Gepäck hier lassen?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Wo ist das Restaurant/der Fitnessraum?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'Hat das Hotel einen Pool?', translation: 'Czy hotel ma basen?' },
            { phrase: 'Kann ich mit Kreditkarte bezahlen?', translation: 'Czy mogę zapłacić kartą kredytową?' },
        ]
    },
  },
  fr: {
    hotel: {
        title: 'Hôtel',
        phrases: [
            { phrase: 'J\'ai une réservation.', translation: 'Mam rezerwację.' },
            { phrase: 'Je peux m\'enregistrer, s\'il vous plaît?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'À quelle heure est le départ?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Je voudrais régler ma note.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'La chambre a-t-elle le Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'Quel est le mot de passe du Wi-Fi?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Un réveil à 7h, s\'il vous plaît.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Ma carte-clé ne fonctionne pas.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'La climatisation ne fonctionne pas.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'Il n\'y a pas d\'eau chaude.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'Puis-je avoir une serviette supplémentaire?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Pourriez-vous faire ma chambre, s\'il vous plaît?', translation: 'Czy można posprzątać mój pokój?' },
            { phrase: 'Ne pas déranger, s\'il vous plaît.', translation: 'Proszę nie przeszkadzać.' },
            { phrase: 'Puis-je avoir le petit-déjeuner dans ma chambre?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'À quelle heure le petit-déjeuner est-il servi?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Pouvez-vous m\'appeler un taxi?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Puis-je laisser mes bagages ici?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Où se trouve le restaurant/la salle de sport?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'L\'hôtel dispose-t-il d\'une piscine?', translation: 'Czy hotel ma basen?' },
            { phrase: 'Puis-je payer par carte de crédit?', translation: 'Czy mogę zapłacić kartą kredytową?' },
        ]
    },
  },
  es: {
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'Tengo una reserva.', translation: 'Mam rezerwację.' },
            { phrase: '¿Puedo registrarme, por favor?', translation: 'Czy mogę się zameldować?' },
            { phrase: '¿A qué hora es el check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Quisiera hacer el check-out.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: '¿La habitación tiene Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: '¿Cuál es la contraseña del Wi-Fi?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Una llamada de despertador a las 7, por favor.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'Mi tarjeta de la habitación no funciona.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'El aire acondicionado no funciona.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'No hay agua caliente.', translation: 'Nie ma ciepłej wody.' },
            { phrase: '¿Puedo tener una toalla extra?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: '¿Podría arreglar mi habitación, por favor?', translation: 'Czy można posprzątać mój pokój?' },
            { phrase: 'Por favor, no molestar.', translation: 'Proszę nie przeszkadzać.' },
            { phrase: '¿Puedo pedir el desayuno en la habitación?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: '¿A qué hora se sirve el desayuno?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: '¿Puede llamarme un taxi?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: '¿Puedo dejar mi equipaje aquí?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: '¿Dónde está el restaurante/gimnasio?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: '¿El hotel tiene piscina?', translation: 'Czy hotel ma basen?' },
            { phrase: '¿Puedo pagar con tarjeta de crédito?', translation: 'Czy mogę zapłacić kartą kredytową?' },
        ]
    },
  },
  it: {
    hotel: {
        title: 'Hotel',
        phrases: [
            { phrase: 'Ho una prenotazione.', translation: 'Mam rezerwację.' },
            { phrase: 'Posso fare il check-in, per favore?', translation: 'Czy mogę się zameldować?' },
            { phrase: 'A che ora è il check-out?', translation: 'O której godzinie jest wymeldowanie?' },
            { phrase: 'Vorrei fare il check-out.', translation: 'Chciałbym/Chciałabym się wymeldować.' },
            { phrase: 'La camera ha il Wi-Fi?', translation: 'Czy w pokoju jest Wi-Fi?' },
            { phrase: 'Qual è la password del Wi-Fi?', translation: 'Jakie jest hasło do Wi-Fi?' },
            { phrase: 'Una sveglia alle 7, per favore.', translation: 'Poproszę o budzenie o 7 rano.' },
            { phrase: 'La mia chiave elettronica non funziona.', translation: 'Moja karta-klucz nie działa.' },
            { phrase: 'L\'aria condizionata non funziona.', translation: 'Klimatyzacja nie działa.' },
            { phrase: 'Non c\'è acqua calda.', translation: 'Nie ma ciepłej wody.' },
            { phrase: 'Posso avere un asciugamano in più?', translation: 'Czy mogę prosić o dodatkowy ręcznik?' },
            { phrase: 'Potrebbe rifare la mia camera, per favore?', translation: 'Czy można posprzątać mój pokój?' },
            { phrase: 'Per favore, non disturbare.', translation: 'Proszę nie przeszkadzać.' },
            { phrase: 'Posso avere la colazione in camera?', translation: 'Czy mogę prosić o śniadanie do pokoju?' },
            { phrase: 'A che ora viene servita la colazione?', translation: 'O której godzinie podawane jest śniadanie?' },
            { phrase: 'Può chiamarmi un taxi?', translation: 'Czy może pan/pani wezwać dla mnie taksówkę?' },
            { phrase: 'Posso lasciare qui i miei bagagli?', translation: 'Czy mogę zostawić tutaj bagaż?' },
            { phrase: 'Dov\'è il ristorante/la palestra?', translation: 'Gdzie jest restauracja/siłownia?' },
            { phrase: 'L\'hotel ha una piscina?', translation: 'Czy hotel ma basen?' },
            { phrase: 'Posso pagare con la carta di credito?', translation: 'Czy mogę zapłacić kartą kredytową?' },
        ]
    },
  },
};
