
import type { PhrasesContent } from '../phrases';

export const shopPhrases: PhrasesContent = {
  en: {
    shop: {
        title: 'Shop',
        phrases: [
            { phrase: 'I\'m just looking, thanks.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'How much is this?', translation: 'Ile to kosztuje?' },
            { phrase: 'Can you help me?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Do you have this in a smaller/larger size?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'Do you have this in a different color?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Can I try this on?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Where are the fitting rooms?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'I\'ll take it.', translation: 'Wezmę to.' },
            { phrase: 'Can I pay by card?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Do you accept credit cards?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'I\'ll pay in cash.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Can I get a receipt, please?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Where is the checkout?', translation: 'Gdzie jest kasa?' },
            { phrase: 'Is this on sale?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'This is too expensive.', translation: 'To jest za drogie.' },
            { phrase: 'Do you have anything cheaper?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'I would like to return this.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'What is your return policy?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Can you gift wrap it for me?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'I am looking for a souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'I\'m looking for a gift for my friend.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Where can I find bread?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'I need a shopping cart.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'A plastic bag, please.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'What time do you close?', translation: 'O której zamykacie?' },
            { phrase: 'Can I have a tax-free form?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
  },
  de: {
    shop: {
        title: 'Im Geschäft',
        phrases: [
            { phrase: 'Ich schaue nur, danke.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'Wie viel kostet das?', translation: 'Ile to kosztuje?' },
            { phrase: 'Können Sie mir helfen?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Haben Sie das in einer kleineren/größeren Größe?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'Haben Sie das in einer anderen Farbe?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Kann ich das anprobieren?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Wo sind die Umkleidekabinen?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Ich nehme es.', translation: 'Wezmę to.' },
            { phrase: 'Kann ich mit Karte bezahlen?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Akzeptieren Sie Kreditkarten?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Ich zahle bar.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Kann ich bitte eine Quittung haben?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Wo ist die Kasse?', translation: 'Gdzie jest kasa?' },
            { phrase: 'Ist das im Angebot?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'Das ist zu teuer.', translation: 'To jest za drogie.' },
            { phrase: 'Haben Sie etwas Günstigeres?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Ich möchte das zurückgeben.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'Wie sind Ihre Rückgabebedingungen?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Können Sie es als Geschenk verpacken?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Ich suche ein Souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'Ich suche ein Geschenk für meinen Freund/meine Freundin.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Wo finde ich Brot?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'Ich brauche einen Einkaufswagen.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Eine Plastiktüte, bitte.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'Wann schließen Sie?', translation: 'O której zamykacie?' },
            { phrase: 'Kann ich ein Tax-Free-Formular haben?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
  },
  fr: {
    shop: {
        title: 'Au Magasin',
        phrases: [
            { phrase: 'Je regarde juste, merci.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'Combien ça coûte?', translation: 'Ile to kosztuje?' },
            { phrase: 'Pouvez-vous m\'aider?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Vous avez ça dans une taille plus petite/grande?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'L\'avez-vous dans une autre couleur?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Puis-je l\'essayer?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Où sont les cabines d\'essayage?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Je le prends.', translation: 'Wezmę to.' },
            { phrase: 'Je peux payer par carte?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Acceptez-vous les cartes de crédit?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Je paie en espèces.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Je peux avoir un reçu, s\'il vous plaît?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Où est la caisse?', translation: 'Gdzie jest kasa?' },
            { phrase: 'Est-ce que c\'est en solde?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'C\'est trop cher.', translation: 'To jest za drogie.' },
            { phrase: 'Avez-vous quelque chose de moins cher?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Je voudrais retourner cet article.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'Quelle est votre politique de retour?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Pouvez-vous me faire un paquet-cadeau?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Je cherche un souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'Je cherche un cadeau pour mon ami(e).', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Où puis-je trouver le pain?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'J\'ai besoin d\'un chariot.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Un sac en plastique, s\'il vous plaît.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'À quelle heure fermez-vous?', translation: 'O której zamykacie?' },
            { phrase: 'Puis-je avoir un formulaire de détaxe?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
  },
  es: {
    shop: {
        title: 'En la Tienda',
        phrases: [
            { phrase: 'Solo estoy mirando, gracias.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: '¿Cuánto cuesta esto?', translation: 'Ile to kosztuje?' },
            { phrase: '¿Me puede ayudar?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: '¿Tiene esto en una talla más pequeña/grande?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: '¿Lo tiene en otro color?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: '¿Puedo probármelo?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: '¿Dónde están los probadores?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Me lo llevo.', translation: 'Wezmę to.' },
            { phrase: '¿Puedo pagar con tarjeta?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: '¿Aceptan tarjetas de crédito?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Pago en efectivo.', translation: 'Zapłacę gotówką.' },
            { phrase: '¿Me da un recibo, por favor?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: '¿Dónde está la caja?', translation: 'Gdzie jest kasa?' },
            { phrase: '¿Está en oferta?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'Es demasiado caro.', translation: 'To jest za drogie.' },
            { phrase: '¿Tiene algo más barato?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Quisiera devolver esto.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: '¿Cuál es su política de devoluciones?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: '¿Puede envolverlo para regalo?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Estoy buscando un recuerdo.', translation: 'Szukam pamiątki.' },
            { phrase: 'Estoy buscando un regalo para mi amigo/a.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: '¿Dónde puedo encontrar el pan?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'Necesito un carrito de la compra.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Una bolsa de plástico, por favor.', translation: 'Poproszę torbę foliową.' },
            { phrase: '¿A qué hora cierran?', translation: 'O której zamykacie?' },
            { phrase: '¿Me puede dar el formulario de tax-free?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
  },
  it: {
    shop: {
        title: 'In Negozio',
        phrases: [
            { phrase: 'Sto solo guardando, grazie.', translation: 'Tylko się rozglądam, dziękuję.' },
            { phrase: 'Quanto costa questo?', translation: 'Ile to kosztuje?' },
            { phrase: 'Mi può aiutare?', translation: 'Czy może mi pan/pani pomóc?' },
            { phrase: 'Ce l\'ha in una taglia più piccola/grande?', translation: 'Czy macie to w mniejszym/większym rozmiarze?' },
            { phrase: 'Ce l\'ha di un altro colore?', translation: 'Czy macie to w innym kolorze?' },
            { phrase: 'Posso provarlo?', translation: 'Czy mogę to przymierzyć?' },
            { phrase: 'Dove sono i camerini?', translation: 'Gdzie są przymierzalnie?' },
            { phrase: 'Lo prendo.', translation: 'Wezmę to.' },
            { phrase: 'Posso pagare con la carta?', translation: 'Czy mogę zapłacić kartą?' },
            { phrase: 'Accettate carte di credito?', translation: 'Czy akceptujecie karty kredytowe?' },
            { phrase: 'Pago in contanti.', translation: 'Zapłacę gotówką.' },
            { phrase: 'Posso avere lo scontrino, per favore?', translation: 'Czy mogę prosić o paragon?' },
            { phrase: 'Dov\'è la cassa?', translation: 'Gdzie jest kasa?' },
            { phrase: 'È in saldo?', translation: 'Czy to jest na wyprzedaży?' },
            { phrase: 'È troppo caro.', translation: 'To jest za drogie.' },
            { phrase: 'Ha qualcosa di più economico?', translation: 'Czy macie coś tańszego?' },
            { phrase: 'Vorrei restituire questo articolo.', translation: 'Chciałbym/Chciałabym to zwrócić.' },
            { phrase: 'Qual è la vostra politica sui resi?', translation: 'Jaka jest wasza polityka zwrotów?' },
            { phrase: 'Può farmi un pacchetto regalo?', translation: 'Czy może pan/pani zapakować to na prezent?' },
            { phrase: 'Cerco un souvenir.', translation: 'Szukam pamiątki.' },
            { phrase: 'Cerco un regalo per un mio amico/una mia amica.', translation: 'Szukam prezentu dla przyjaciela/przyjaciółki.' },
            { phrase: 'Dove posso trovare il pane?', translation: 'Gdzie znajdę chleb?' },
            { phrase: 'Ho bisogno di un carrello.', translation: 'Potrzebuję wózka na zakupy.' },
            { phrase: 'Un sacchetto di plastica, per favore.', translation: 'Poproszę torbę foliową.' },
            { phrase: 'A che ora chiudete?', translation: 'O której zamykacie?' },
            { phrase: 'Posso avere il modulo per il tax-free?', translation: 'Czy mogę prosić o formularz zwrotu podatku?' }
        ]
    },
  },
};
