
import type { PhrasesContent } from '../phrases';

export const emergencyPhrases: PhrasesContent = {
  en: {
    emergency: {
        title: 'Emergency',
        phrases: [
            { phrase: 'Help!', translation: 'Pomocy!' },
            { phrase: 'Call an ambulance!', translation: 'Wezwij karetkę!' },
            { phrase: 'Call the police!', translation: 'Wezwij policję!' },
            { phrase: 'Call the fire department!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'What is the emergency number?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'There is a fire!', translation: 'Pali się!' },
            { phrase: 'There\'s been an accident.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'I need a doctor.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'Is there a hospital nearby?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'I don\'t feel well.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'I have a pain here.', translation: 'Boli mnie tutaj.' },
            { phrase: 'I can\'t breathe.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Someone stole my bag.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'I\'ve lost my wallet.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'I\'ve lost my passport.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'I am lost.', translation: 'Zgubiłem/am się.' },
            { phrase: 'My child is missing.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Leave me alone!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Watch out!', translation: 'Uważaj!' },
            { phrase: 'Please, hurry!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'I need help.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'Is anyone here a doctor?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'I think I broke my leg.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'I am allergic to penicillin.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Where is the nearest pharmacy?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'I need to go to the embassy.', translation: 'Muszę iść do ambasady.' }
        ]
    },
  },
  de: {
    emergency: {
        title: 'Notfall',
        phrases: [
            { phrase: 'Hilfe!', translation: 'Pomocy!' },
            { phrase: 'Rufen Sie einen Krankenwagen!', translation: 'Wezwij karetkę!' },
            { phrase: 'Rufen Sie die Polizei!', translation: 'Wezwij policję!' },
            { phrase: 'Rufen Sie die Feuerwehr!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'Wie lautet die Notrufnummer?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'Es brennt!', translation: 'Pali się!' },
            { phrase: 'Es gab einen Unfall.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'Ich brauche einen Arzt.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'Gibt es ein Krankenhaus in der Nähe?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'Ich fühle mich nicht wohl.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'Ich habe hier Schmerzen.', translation: 'Boli mnie tutaj.' },
            { phrase: 'Ich kann nicht atmen.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Jemand hat meine Tasche gestohlen.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'Ich habe meine Brieftasche verloren.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'Ich habe meinen Reisepass verloren.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Ich habe mich verlaufen.', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mein Kind wird vermisst.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Lassen Sie mich in Ruhe!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Achtung!', translation: 'Uważaj!' },
            { phrase: 'Bitte, beeilen Sie sich!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'Ich brauche Hilfe.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'Ist hier ein Arzt anwesend?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Ich glaube, ich habe mir das Bein gebrochen.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Ich bin allergisch gegen Penizillin.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Wo ist die nächste Apotheke?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Ich muss zur Botschaft.', translation: 'Muszę iść do ambasady.' }
        ]
    },
  },
  fr: {
    emergency: {
        title: 'Urgence',
        phrases: [
            { phrase: 'Au secours!', translation: 'Pomocy!' },
            { phrase: 'Appelez une ambulance!', translation: 'Wezwij karetkę!' },
            { phrase: 'Appelez la police!', translation: 'Wezwij policję!' },
            { phrase: 'Appelez les pompiers!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'Quel est le numéro d\'urgence?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'Au feu!', translation: 'Pali się!' },
            { phrase: 'Il y a eu un accident.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'J\'ai besoin d\'un médecin.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'Y a-t-il un hôpital près d\'ici?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'Je ne me sens pas bien.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'J\'ai mal ici.', translation: 'Boli mnie tutaj.' },
            { phrase: 'Je n\'arrive pas à respirer.', translation: 'Nie mogę oddychać.' },
            { phrase: 'On m\'a volé mon sac.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'J\'ai perdu mon portefeuille.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'J\'ai perdu mon passeport.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Je suis perdu(e).', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mon enfant a disparu.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Laissez-moi tranquille!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Attention!', translation: 'Uważaj!' },
            { phrase: 'Vite, s\'il vous plaît!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'J\'ai besoin d\'aide.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'Y a-t-il un médecin ici?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Je crois que je me suis cassé la jambe.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Je suis allergique à la pénicilline.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Où est la pharmacie la plus proche?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Je dois aller à l\'ambassade.', translation: 'Muszę iść do ambasady.' }
        ]
    },
  },
  es: {
    emergency: {
        title: 'Emergencia',
        phrases: [
            { phrase: '¡Socorro! / ¡Ayuda!', translation: 'Pomocy!' },
            { phrase: '¡Llame a una ambulancia!', translation: 'Wezwij karetkę!' },
            { phrase: '¡Llame a la policía!', translation: 'Wezwij policję!' },
            { phrase: '¡Llame a los bomberos!', translation: 'Wezwij straż pożarną!' },
            { phrase: '¿Cuál es el número de emergencias?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: '¡Fuego!', translation: 'Pali się!' },
            { phrase: 'Ha habido un accidente.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'Necesito un médico.', translation: 'Potrzebuję lekarza.' },
            { phrase: '¿Hay un hospital cerca?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'No me encuentro bien.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'Me duele aquí.', translation: 'Boli mnie tutaj.' },
            { phrase: 'No puedo respirar.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Alguien me ha robado el bolso.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'He perdido mi cartera.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'He perdido mi pasaporte.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Estoy perdido/a.', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mi hijo/a ha desaparecido.', translation: 'Moje dziecko zaginęło.' },
            { phrase: '¡Déjeme en paz!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: '¡Cuidado!', translation: 'Uważaj!' },
            { phrase: '¡Rápido, por favor!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'Necesito ayuda.', translation: 'Potrzebuję pomocy.' },
            { phrase: '¿Hay algún médico aquí?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Creo que me he roto la pierna.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Soy alérgico/a a la penicilina.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: '¿Dónde está la farmacia más cercana?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Necesito ir a la embajada.', translation: 'Muszę iść do ambasady.' }
        ]
    },
  },
  it: {
    emergency: {
        title: 'Emergenza',
        phrases: [
            { phrase: 'Aiuto!', translation: 'Pomocy!' },
            { phrase: 'Chiami un\'ambulanza!', translation: 'Wezwij karetkę!' },
            { phrase: 'Chiami la polizia!', translation: 'Wezwij policję!' },
            { phrase: 'Chiami i vigili del fuoco!', translation: 'Wezwij straż pożarną!' },
            { phrase: 'Qual è il numero di emergenza?', translation: 'Jaki jest numer alarmowy?' },
            { phrase: 'Al fuoco!', translation: 'Pali się!' },
            { phrase: 'C\'è stato un incidente.', translation: 'Wydarzył się wypadek.' },
            { phrase: 'Ho bisogno di un medico.', translation: 'Potrzebuję lekarza.' },
            { phrase: 'C\'è un ospedale qui vicino?', translation: 'Czy w pobliżu jest szpital?' },
            { phrase: 'Non mi sento bene.', translation: 'Nie czuję się dobrze.' },
            { phrase: 'Ho un dolore qui.', translation: 'Boli mnie tutaj.' },
            { phrase: 'Non riesco a respirare.', translation: 'Nie mogę oddychać.' },
            { phrase: 'Mi hanno rubato la borsa.', translation: 'Ktoś ukradł moją torbę.' },
            { phrase: 'Ho perso il portafoglio.', translation: 'Zgubiłem/am portfel.' },
            { phrase: 'Ho perso il passaporto.', translation: 'Zgubiłem/am paszport.' },
            { phrase: 'Mi sono perso/a.', translation: 'Zgubiłem/am się.' },
            { phrase: 'Mio/a figlio/a è scomparso/a.', translation: 'Moje dziecko zaginęło.' },
            { phrase: 'Mi lasci in pace!', translation: 'Zostaw mnie w spokoju!' },
            { phrase: 'Attenzione!', translation: 'Uważaj!' },
            { phrase: 'Presto, per favore!', translation: 'Proszę, pospiesz się!' },
            { phrase: 'Ho bisogno di aiuto.', translation: 'Potrzebuję pomocy.' },
            { phrase: 'C\'è un medico qui?', translation: 'Czy jest tu jakiś lekarz?' },
            { phrase: 'Credo di essermi rotto/a una gamba.', translation: 'Chyba złamałem/am nogę.' },
            { phrase: 'Sono allergico/a alla penicillina.', translation: 'Jestem uczulony/a na penicylinę.' },
            { phrase: 'Dov\'è la farmacia più vicina?', translation: 'Gdzie jest najbliższa apteka?' },
            { phrase: 'Devo andare all\'ambasciata.', translation: 'Muszę iść do ambasady.' }
        ]
    },
  },
};
