import type { GapWordCategory } from '.';

const category1: GapWordCategory = {
  title: 'Akcenty i nietypowe litery',
  words: [
    { wordWithGap: 'coraz__n', missingLetters: 'ó', fullWord: 'corazón', hint: 'serce' },
    { wordWithGap: 'canc__n', missingLetters: 'ió', fullWord: 'canción', hint: 'piosenka' },
    { wordWithGap: 'ár__l', missingLetters: 'bo', fullWord: 'árbol', hint: 'drzewo' },
    { wordWithGap: 'az__car', missingLetters: 'ú', fullWord: 'azúcar', hint: 'cukier' },
    { wordWithGap: 'ingl__s', missingLetters: 'é', fullWord: 'inglés', hint: 'angielski' },
    { wordWithGap: 'dif__cil', missingLetters: 'í', fullWord: 'difícil', hint: 'trudny' },
    { wordWithGap: 'f__tbol', missingLetters: 'ú', fullWord: 'fútbol', hint: 'piłka nożna' },
    { wordWithGap: 'l__piz', missingLetters: 'á', fullWord: 'lápiz', hint: 'ołówek' },
    { wordWithGap: 'tel__fono', missingLetters: 'é', fullWord: 'teléfono', hint: 'telefon' },
    { wordWithGap: 'm__sica', missingLetters: 'ú', fullWord: 'música', hint: 'muzyka' },
    { wordWithGap: 'r__pido', missingLetters: 'á', fullWord: 'rápido', hint: 'szybki' },
    { wordWithGap: 'últi__', missingLetters: 'mo', fullWord: 'último', hint: 'ostatni' },
    { wordWithGap: 'p__jaro', missingLetters: 'á', fullWord: 'pájaro', hint: 'ptak' },
    { wordWithGap: 'espa__ol', missingLetters: 'ñ', fullWord: 'español', hint: 'hiszpański' },
    { wordWithGap: 'ma__ana', missingLetters: 'ñ', fullWord: 'mañana', hint: 'jutro/rano' },
    { wordWithGap: 'pi__a', missingLetters: 'ñ', fullWord: 'piña', hint: 'ananas' },
    { wordWithGap: 'ni__o', missingLetters: 'ñ', fullWord: 'niño', hint: 'dziecko' },
    { wordWithGap: 'a__o', missingLetters: 'ñ', fullWord: 'año', hint: 'rok' },
    { wordWithGap: 'ver__enza', missingLetters: 'gü', fullWord: 'vergüenza', hint: 'wstyd' },
    { wordWithGap: 'pin__ino', missingLetters: 'gü', fullWord: 'pingüino', hint: 'pingwin' },
    { wordWithGap: 'ci__eña', missingLetters: 'gü', fullWord: 'cigüeña', hint: 'bocian' },
    { wordWithGap: 'anti__edad', missingLetters: 'gü', fullWord: 'antigüedad', hint: 'starożytność' },
    { wordWithGap: 'nicarag__nse', missingLetters: 'üe', fullWord: 'nicaragüense', hint: 'nikaraguański' },
    { wordWithGap: 'ling__stica', missingLetters: 'üí', fullWord: 'lingüística', hint: 'lingwistyka' },
    { wordWithGap: '__ito', missingLetters: 'éx', fullWord: 'éxito', hint: 'sukces' },
    { wordWithGap: '__ndice', missingLetters: 'í', fullWord: 'índice', hint: 'spis treści' },
    { wordWithGap: '__til', missingLetters: 'ú', fullWord: 'útil', hint: 'użyteczny' },
    { wordWithGap: '__poca', missingLetters: 'é', fullWord: 'época', hint: 'epoka' },
  ]
};

const category2: GapWordCategory = {
  title: 'C, S, Z & G, J, H',
  words: [
    { wordWithGap: 'cora__n', missingLetters: 'zó', fullWord: 'corazón', hint: 'serce' },
    { wordWithGap: '__mbra', missingLetters: 'so', fullWord: 'sombra', hint: 'cień' },
    { wordWithGap: '__reza', missingLetters: 'ce', fullWord: 'cereza', hint: 'czereśnia' },
    { wordWithGap: 'ca__a', missingLetters: 'z', fullWord: 'caza', hint: 'polowanie' },
    { wordWithGap: 'c__na', missingLetters: 'e', fullWord: 'cena', hint: 'kolacja' },
    { wordWithGap: 'pr__so', missingLetters: 'e', fullWord: 'preso', hint: 'więzień' },
    { wordWithGap: 'po__o', missingLetters: 'z', fullWord: 'pozo', hint: 'studnia' },
    { wordWithGap: '__neral', missingLetters: 'ge', fullWord: 'general', hint: 'ogólny' },
    { wordWithGap: 'via__', missingLetters: 'je', fullWord: 'viaje', hint: 'podróż' },
    { wordWithGap: 'ma__a', missingLetters: 'gi', fullWord: 'magia', hint: 'magia' },
    { wordWithGap: '__rafa', missingLetters: 'ji', fullWord: 'jirafa', hint: 'żyrafa' },
    { wordWithGap: 'reco__r', missingLetters: 'ge', fullWord: 'recoger', hint: 'zbierać' },
    { wordWithGap: 'prote__r', missingLetters: 'ge', fullWord: 'proteger', hint: 'chronić' },
    { wordWithGap: 'ele__r', missingLetters: 'gi', fullWord: 'elegir', hint: 'wybierać' },
    { wordWithGap: '__elo', missingLetters: 'hi', fullWord: 'hielo', hint: 'lód' },
    { wordWithGap: '__evo', missingLetters: 'hu', fullWord: 'huevo', hint: 'jajko' },
    { wordWithGap: 'almo__da', missingLetters: 'ha', fullWord: 'almohada', hint: 'poduszka' },
    { wordWithGap: 'a__ora', missingLetters: 'h', fullWord: 'ahora', hint: 'teraz' },
    { wordWithGap: 'pro__bir', missingLetters: 'hi', fullWord: 'prohibir', hint: 'zabraniać' },
    { wordWithGap: 've__culo', missingLetters: 'hí', fullWord: 'vehículo', hint: 'pojazd' },
    { wordWithGap: 'al__hol', missingLetters: 'co', fullWord: 'alcohol', hint: 'alkohol' },
    { wordWithGap: 'psicó__go', missingLetters: 'lo', fullWord: 'psicólogo', hint: 'psycholog' },
    { wordWithGap: 'exce__ional', missingLetters: 'pc', fullWord: 'excepcional', hint: 'wyjątkowy' },
    { wordWithGap: 'e__austo', missingLetters: 'xh', fullWord: 'exhausto', hint: 'wyczerpany' },
    { wordWithGap: 'exhi__ción', missingLetters: 'bi', fullWord: 'exhibición', hint: 'wystawa' },
    { wordWithGap: 'zana__ria', missingLetters: 'ho', fullWord: 'zanahoria', hint: 'marchewka' },
    { wordWithGap: 'a__gar', missingLetters: 'ho', fullWord: 'ahogar', hint: 'dusić' },
    { wordWithGap: '__untamiento', missingLetters: 'ay', fullWord: 'ayuntamiento', hint: 'ratusz' },
  ]
};

const category3: GapWordCategory = {
  title: 'Długie i złożone słowa',
  words: [
    { wordWithGap: 'desa__ollar', missingLetters: 'rr', fullWord: 'desarrollar', hint: 'rozwijać' },
    { wordWithGap: 'otorrinolaringó__go', missingLetters: 'lo', fullWord: 'otorrinolaringólogo', hint: 'otolaryngolog' },
    { wordWithGap: 'para__as', missingLetters: 'gu', fullWord: 'paraguas', hint: 'parasol' },
    { wordWithGap: 'ferroca__il', missingLetters: 'rr', fullWord: 'ferrocarril', hint: 'kolej żelazna' },
    { wordWithGap: 'aho__ar', missingLetters: 'rr', fullWord: 'ahorrar', hint: 'oszczędzać' },
    { wordWithGap: 'alre__dor', missingLetters: 'de', fullWord: 'alrededor', hint: 'dookoła' },
    { wordWithGap: 'desoxirribo__leico', missingLetters: 'nuc', fullWord: 'desoxirribonucleico', hint: 'deoksyrybonukleinowy' },
    { wordWithGap: 'electrocardio__ama', missingLetters: 'gr', fullWord: 'electrocardiograma', hint: 'elektrokardiogram' },
    { wordWithGap: 'esternocleido__stoideo', missingLetters: 'ma', fullWord: 'esternocleidomastoideo', hint: 'mięsień mostkowo-obojczykowo-sutkowy' },
    { wordWithGap: 'Guada__ara', missingLetters: 'laj', fullWord: 'Guadalajara', hint: 'miasto w Meksyku' },
    { wordWithGap: 'Que__taro', missingLetters: 'ré', fullWord: 'Querétaro', hint: 'stan w Meksyku' },
    { wordWithGap: 'chicha__ón', missingLetters: 'rr', fullWord: 'chicharrón', hint: 'skwarek' },
    { wordWithGap: 'Chihua__a', missingLetters: 'hu', fullWord: 'Chihuahua', hint: 'rasa psa' },
    { wordWithGap: 'xi__fono', missingLetters: 'ló', fullWord: 'xilófono', hint: 'ksylofon' },
    { wordWithGap: 'constitu__nalmente', missingLetters: 'cio', fullWord: 'constitucionalmente', hint: 'konstytucyjnie' },
    { wordWithGap: 'responsabi__dad', missingLetters: 'li', fullWord: 'responsabilidad', hint: 'odpowiedzialność' },
    { wordWithGap: 'contra__volucionario', missingLetters: 'rre', fullWord: 'contrarrevolucionario', hint: 'kontrrewolucyjny' },
    { wordWithGap: 'electroencefalo__fista', missingLetters: 'gra', fullWord: 'electroencefalografista', hint: 'elektroencefalografista' },
    { wordWithGap: 'inter__isciplinario', missingLetters: 'd', fullWord: 'interdisciplinario', hint: 'interdyscyplinarny' },
    { wordWithGap: 'incom__nsurable', missingLetters: 'me', fullWord: 'inconmensurable', hint: 'niezmierzony' },
    { wordWithGap: 'otorrino__ringólogo', missingLetters: 'la', fullWord: 'otorrinolaringólogo', hint: 'otolaryngolog' },
    { wordWithGap: 'paralele__pedo', missingLetters: 'pí', fullWord: 'paralelepípedo', hint: 'równoległościan' },
    { wordWithGap: 'calei__scopio', missingLetters: 'do', fullWord: 'caleidoscopio', hint: 'kalejdoskop' },
    { wordWithGap: 'espectrofoto__tría', missingLetters: 'me', fullWord: 'espectrofotometría', hint: 'spektrofotometria' },
    { wordWithGap: 'desproporcio__damente', missingLetters: 'na', fullWord: 'desproporcionadamente', hint: 'nieproporcjonalnie' },
    { wordWithGap: 'an__constitucionalmente', missingLetters: 'ti', fullWord: 'anticonstitucionalmente', hint: 'niekonstytucyjnie' },
    { wordWithGap: 'ex__ordinario', missingLetters: 'tra', fullWord: 'extraordinario', hint: 'niezwykły' },
    { wordWithGap: 'reconoci__ento', missingLetters: 'mi', fullWord: 'reconocimiento', hint: 'uznanie' },
  ]
};


export const gapWordsQuestionsEs: GapWordCategory[] = [category1, category2, category3];
