import type { GapWordCategory } from '.';

const category1: GapWordCategory = {
  title: 'Tricky Spellings',
  words: [
    { wordWithGap: 'consci__tious', missingLetters: 'en', fullWord: 'conscientious', hint: 'sumienny' },
    { wordWithGap: 'phenom__on', missingLetters: 'en', fullWord: 'phenomenon', hint: 'zjawisko' },
    { wordWithGap: 'rhy__m', missingLetters: 'th', fullWord: 'rhythm', hint: 'rytm' },
    { wordWithGap: 'que__', missingLetters: 'ue', fullWord: 'queue', hint: 'kolejka' },
    { wordWithGap: 'lia__on', missingLetters: 'is', fullWord: 'liaison', hint: 'łącznik' },
    { wordWithGap: 'parapherna__a', missingLetters: 'li', fullWord: 'paraphernalia', hint: 'rekwizyty' },
    { wordWithGap: 'misch__vous', missingLetters: 'ie', fullWord: 'mischievous', hint: 'psotny' },
    { wordWithGap: 'entrep__neur', missingLetters: 're', fullWord: 'entrepreneur', hint: 'przedsiębiorca' },
    { wordWithGap: 'bou__eois', missingLetters: 'rg', fullWord: 'bourgeois', hint: 'mieszczański' },
    { wordWithGap: 'ya__t', missingLetters: 'ch', fullWord: 'yacht', hint: 'jacht' },
    { wordWithGap: 'fu__sia', missingLetters: 'ch', fullWord: 'fuchsia', hint: 'fuksja' },
    { wordWithGap: 'co__oisseur', missingLetters: 'nn', fullWord: 'connoisseur', hint: 'znawca' },
    { wordWithGap: 'ac__iesce', missingLetters: 'qu', fullWord: 'acquiesce', hint: 'zgodzić się' },
    { wordWithGap: 'idiosyncra__', missingLetters: 'sy', fullWord: 'idiosyncrasy', hint: 'dziwactwo' },
    { wordWithGap: 'onomato__eia', missingLetters: 'po', fullWord: 'onomatopoeia', hint: 'onomatopeja' },
    { wordWithGap: 'mi__ennium', missingLetters: 'll', fullWord: 'millennium', hint: 'tysiąclecie' },
    { wordWithGap: 'chrysan__emum', missingLetters: 'th', fullWord: 'chrysanthemum', hint: 'chryzantema' },
    { wordWithGap: 'bureaucra__', missingLetters: 'cy', fullWord: 'bureaucracy', hint: 'biurokracja' },
    { wordWithGap: 'da__shund', missingLetters: 'ch', fullWord: 'dachshund', hint: 'jamnik' },
    { wordWithGap: 'psy__iatrist', missingLetters: 'ch', fullWord: 'psychiatrist', hint: 'psychiatra' },
    { wordWithGap: 'pseu__nym', missingLetters: 'do', fullWord: 'pseudonym', hint: 'pseudonim' },
    { wordWithGap: 'hemor__age', missingLetters: 'rh', fullWord: 'hemorrhage', hint: 'krwotok' },
    { wordWithGap: 'Wor__stershire', missingLetters: 'ce', fullWord: 'Worcestershire', hint: 'hrabstwo' },
    { wordWithGap: 'aes__etic', missingLetters: 'th', fullWord: 'aesthetic', hint: 'estetyczny' },
    { wordWithGap: 'ma__ver', missingLetters: 'neu', fullWord: 'maneuver', hint: 'manewr' },
    { wordWithGap: 'naus__us', missingLetters: 'eo', fullWord: 'nauseous', hint: 'mający mdłości' },
    { wordWithGap: 'susce__ible', missingLetters: 'pt', fullWord: 'susceptible', hint: 'podatny' },
    { wordWithGap: 'a__ommodate', missingLetters: 'cc', fullWord: 'accommodate', hint: 'zakwaterować' }
  ]
};

const category2: GapWordCategory = {
  title: 'Double Letters',
  words: [
    { wordWithGap: 'po__e__ion', missingLetters: 'ssess', fullWord: 'possession', hint: 'posiadanie' },
    { wordWithGap: 'nece__ary', missingLetters: 'ss', fullWord: 'necessary', hint: 'konieczny' },
    { wordWithGap: 'embarr__ment', missingLetters: 'ass', fullWord: 'embarrassment', hint: 'zakłopotanie' },
    { wordWithGap: 'mi__e__aneous', missingLetters: 'scell', fullWord: 'miscellaneous', hint: 'różnorodny' },
    { wordWithGap: 'o__a__ionally', missingLetters: 'ccasi', fullWord: 'occasionally', hint: 'czasami' },
    { wordWithGap: 'su__e__ful', missingLetters: 'ccess', fullWord: 'successful', hint: 'udany' },
    { wordWithGap: 'reco__end', missingLetters: 'mm', fullWord: 'recommend', hint: 'polecać' },
    { wordWithGap: 'co__i__ee', missingLetters: 'mmitt', fullWord: 'committee', hint: 'komitet' },
    { wordWithGap: 'a__re__ive', missingLetters: 'ggress', fullWord: 'aggressive', hint: 'agresywny' },
    { wordWithGap: 'a__arent', missingLetters: 'pp', fullWord: 'apparent', hint: 'oczywisty' },
    { wordWithGap: 'co__e__orate', missingLetters: 'mmem', fullWord: 'commemorate', hint: 'upamiętniać' },
    { wordWithGap: 'mi__i__ippi', missingLetters: 'ssiss', fullWord: 'mississippi', hint: 'rzeka w USA' },
    { wordWithGap: 'a__a__in', missingLetters: 'ssass', fullWord: 'assassin', hint: 'zabójca' },
    { wordWithGap: 'ba__oon', missingLetters: 'll', fullWord: 'balloon', hint: 'balon' },
    { wordWithGap: 'bro__oli', missingLetters: 'cc', fullWord: 'broccoli', hint: 'brokuł' },
    { wordWithGap: 'bu__erfly', missingLetters: 'tt', fullWord: 'butterfly', hint: 'motyl' },
    { wordWithGap: 'ci__amon', missingLetters: 'nn', fullWord: 'cinnamon', hint: 'cynamon' },
    { wordWithGap: 'co__ee', missingLetters: 'ff', fullWord: 'coffee', hint: 'kawa' },
    { wordWithGap: 'di__icult', missingLetters: 'ff', fullWord: 'difficult', hint: 'trudny' },
    { wordWithGap: 'gi__a__e', missingLetters: 'raff', fullWord: 'giraffe', hint: 'żyrafa' },
    { wordWithGap: 'ha__y', missingLetters: 'pp', fullWord: 'happy', hint: 'szczęśliwy' },
    { wordWithGap: 'le__er', missingLetters: 'tt', fullWord: 'letter', hint: 'list/litera' },
    { wordWithGap: 'o__ur', missingLetters: 'cc', fullWord: 'occur', hint: 'występować' },
    { wordWithGap: 'pa__enger', missingLetters: 'ss', fullWord: 'passenger', hint: 'pasażer' },
    { wordWithGap: 'po__ible', missingLetters: 'ss', fullWord: 'possible', hint: 'możliwy' },
    { wordWithGap: 'she__if', missingLetters: 'r', fullWord: 'sheriff', hint: 'szeryf' },
    { wordWithGap: 'su__enly', missingLetters: 'dd', fullWord: 'suddenly', hint: 'nagle' },
    { wordWithGap: 'va__uum', missingLetters: 'cu', fullWord: 'vacuum', hint: 'próżnia/odkurzacz' },
  ]
};

const category3: GapWordCategory = {
  title: 'Silent Letters',
  words: [
    { wordWithGap: '__ife', missingLetters: 'kn', fullWord: 'knife', hint: 'nóż' },
    { wordWithGap: 'psal__', missingLetters: 'm', fullWord: 'psalm', hint: 'psalm' },
    { wordWithGap: 'de__t', missingLetters: 'b', fullWord: 'debt', hint: 'dług' },
    { wordWithGap: 'i__and', missingLetters: 'sl', fullWord: 'island', hint: 'wyspa' },
    { wordWithGap: 'wri__le', missingLetters: 'nk', fullWord: 'wrinkle', hint: 'zmarszczka' },
    { wordWithGap: 'forei__', missingLetters: 'gn', fullWord: 'foreign', hint: 'obcy' },
    { wordWithGap: 'hono__', missingLetters: 'ur', fullWord: 'honour', hint: 'honor' },
    { wordWithGap: '__eumonia', missingLetters: 'pn', fullWord: 'pneumonia', hint: 'zapalenie płuc' },
    { wordWithGap: 'cas__le', missingLetters: 't', fullWord: 'castle', hint: 'zamek' },
    { wordWithGap: 'a__le', missingLetters: 'is', fullWord: 'aisle', hint: 'przejście' },
    { wordWithGap: 'whi__le', missingLetters: 'st', fullWord: 'whistle', hint: 'gwizdać' },
    { wordWithGap: '__ychology', missingLetters: 'ps', fullWord: 'psychology', hint: 'psychologia' },
    { wordWithGap: 'colum__', missingLetters: 'n', fullWord: 'column', hint: 'kolumna' },
    { wordWithGap: 'si__', missingLetters: 'gn', fullWord: 'sign', hint: 'znak' },
    { wordWithGap: 'thum__', missingLetters: 'b', fullWord: 'thumb', hint: 'kciuk' },
    { wordWithGap: 'we__nesday', missingLetters: 'd', fullWord: 'wednesday', hint: 'środa' },
    { wordWithGap: 'dou__t', missingLetters: 'b', fullWord: 'doubt', hint: 'wątpliwość' },
    { wordWithGap: '__ote', missingLetters: 'wr', fullWord: 'wrote', hint: 'pisał' },
    { wordWithGap: 'kno__', missingLetters: 'ck', fullWord: 'knock', hint: 'pukać' },
    { wordWithGap: 'recei__t', missingLetters: 'p', fullWord: 'receipt', hint: 'paragon' },
    { wordWithGap: 'rhuba__', missingLetters: 'rb', fullWord: 'rhubarb', hint: 'rabarbar' },
    { wordWithGap: 'sc__ssors', missingLetters: 'i', fullWord: 'scissors', hint: 'nożyczki' },
    { wordWithGap: 'mus__le', missingLetters: 'c', fullWord: 'muscle', hint: 'mięsień' },
    { wordWithGap: 'fore__ead', missingLetters: 'h', fullWord: 'forehead', hint: 'czoło' },
    { wordWithGap: 'g__ost', missingLetters: 'h', fullWord: 'ghost', hint: 'duch' },
    { wordWithGap: 'i__ony', missingLetters: 'r', fullWord: 'irony', hint: 'ironia' },
    { wordWithGap: '__eumatism', missingLetters: 'rh', fullWord: 'rheumatism', hint: 'reumatyzm' },
    { wordWithGap: 'wea__er', missingLetters: 'th', fullWord: 'weather', hint: 'pogoda' },
  ]
};

export const gapWordsQuestionsEn: GapWordCategory[] = [category1, category2, category3];
