import type { GapWordCategory } from '.';

const category1: GapWordCategory = {
  title: 'Doppie Lettere',
  words: [
    { wordWithGap: 'a__ommodare', missingLetters: 'cc', fullWord: 'accomodare', hint: 'zakwaterować, rozgościć się' },
    { wordWithGap: 'so__rattutto', missingLetters: 'pp', fullWord: 'soprattutto', hint: 'przede wszystkim' },
    { wordWithGap: 'a__entuare', missingLetters: 'cc', fullWord: 'accentuare', hint: 'akcentować' },
    { wordWithGap: 'progra__are', missingLetters: 'mm', fullWord: 'programmare', hint: 'programować' },
    { wordWithGap: 'scomm__tere', missingLetters: 'ett', fullWord: 'scommettere', hint: 'zakładać się' },
    { wordWithGap: 'a__arecchio', missingLetters: 'pp', fullWord: 'apparecchio', hint: 'urządzenie' },
    { wordWithGap: 'ca__uccino', missingLetters: 'pp', fullWord: 'cappuccino', hint: 'cappuccino' },
    { wordWithGap: 'ma__hina', missingLetters: 'cc', fullWord: 'macchina', hint: 'samochód, maszyna' },
    { wordWithGap: 'pa__eggiare', missingLetters: 'ss', fullWord: 'passeggiare', hint: 'spacerować' },
    { wordWithGap: 'me__aggio', missingLetters: 'ss', fullWord: 'messaggio', hint: 'wiadomość' },
    { wordWithGap: 'ca__ello', missingLetters: 'pp', fullWord: 'cappello', hint: 'kapelusz' },
    { wordWithGap: 'a__orre', missingLetters: 'gg', fullWord: 'allegro', hint: 'wesoły' },
    { wordWithGap: 'di__icile', missingLetters: 'ff', fullWord: 'difficile', hint: 'trudny' },
    { wordWithGap: 'po__eriggio', missingLetters: 'm', fullWord: 'pomeriggio', hint: 'popołudnie' },
    { wordWithGap: 'pa__aporto', missingLetters: 'ss', fullWord: 'passaporto', hint: 'paszport' },
    { wordWithGap: 'o__i', missingLetters: 'gg', fullWord: 'oggi', hint: 'dzisiaj' },
    { wordWithGap: 'a__endere', missingLetters: 'tt', fullWord: 'attendere', hint: 'czekać' },
    { wordWithGap: 'co__o', missingLetters: 'll', fullWord: 'collo', hint: 'szyja' },
    { wordWithGap: 'fra__ello', missingLetters: 't', fullWord: 'fratello', hint: 'brat' },
    { wordWithGap: 'so__ella', missingLetters: 'r', fullWord: 'sorella', hint: 'siostra' },
    { wordWithGap: 'a__ua', missingLetters: 'cq', fullWord: 'acqua', hint: 'woda' },
    { wordWithGap: 'a__uisire', missingLetters: 'cq', fullWord: 'acquisire', hint: 'nabywać' },
    { wordWithGap: 'ne__ure', missingLetters: 'pp', fullWord: 'neppure', hint: 'nawet nie' },
    { wordWithGap: 'su__esso', missingLetters: 'cc', fullWord: 'successo', hint: 'sukces' },
    { wordWithGap: 'do__ore', missingLetters: 'tt', fullWord: 'dottore', hint: 'lekarz' },
    { wordWithGap: 'be__issimo', missingLetters: 'll', fullWord: 'bellissimo', hint: 'przepiękny' },
    { wordWithGap: 'e__ere', missingLetters: 'ss', fullWord: 'essere', hint: 'być' },
    { wordWithGap: 'po__edere', missingLetters: 'ss', fullWord: 'possedere', hint: 'posiadać' },
  ]
};

const category2: GapWordCategory = {
  title: 'Dźwięki złożone (gl, gn, sc)',
  words: [
    { wordWithGap: 'fi__o', missingLetters: 'gli', fullWord: 'figlio', hint: 'syn' },
    { wordWithGap: 'fami__a', missingLetters: 'gli', fullWord: 'famiglia', hint: 'rodzina' },
    { wordWithGap: 'a__o', missingLetters: 'gli', fullWord: 'aglio', hint: 'czosnek' },
    { wordWithGap: 'bi__etto', missingLetters: 'gli', fullWord: 'biglietto', hint: 'bilet' },
    { wordWithGap: 'vo__a', missingLetters: 'gli', fullWord: 'voglia', hint: 'chęć' },
    { wordWithGap: 'sba__are', missingLetters: 'gli', fullWord: 'sbagliare', hint: 'popełniać błąd' },
    { wordWithGap: 'scio__ere', missingLetters: 'gli', fullWord: 'sciogliere', hint: 'rozpuszczać' },
    { wordWithGap: 'botti__a', missingLetters: 'gli', fullWord: 'bottiglia', hint: 'butelka' },
    { wordWithGap: 'ba__o', missingLetters: 'gn', fullWord: 'bagno', hint: 'łazienka' },
    { wordWithGap: 'se__o', missingLetters: 'gn', fullWord: 'segno', hint: 'znak' },
    { wordWithGap: 'inse__ante', missingLetters: 'gn', fullWord: 'insegnante', hint: 'nauczyciel' },
    { wordWithGap: 'monta__a', missingLetters: 'gn', fullWord: 'montagna', hint: 'góra' },
    { wordWithGap: 'la__a', missingLetters: 'gn', fullWord: 'lasagna', hint: 'lazania' },
    { wordWithGap: 'bisog__', missingLetters: 'no', fullWord: 'bisogno', hint: 'potrzeba' },
    { wordWithGap: 'so__o', missingLetters: 'gn', fullWord: 'sogno', hint: 'sen, marzenie' },
    { wordWithGap: 'cigno', missingLetters: '', fullWord: 'cigno', hint: 'łabędź' },
    { wordWithGap: 'pe__e', missingLetters: 'sc', fullWord: 'pesce', hint: 'ryba' },
    { wordWithGap: 'co__enza', missingLetters: 'sci', fullWord: 'coscienza', hint: 'świadomość, sumienie' },
    { wordWithGap: 'a__ensore', missingLetters: 'sc', fullWord: 'ascensore', hint: 'winda' },
    { wordWithGap: 'pro__utto', missingLetters: 'sci', fullWord: 'prosciutto', hint: 'szynka' },
    { wordWithGap: '__volo', missingLetters: 'sci', fullWord: 'scivolo', hint: 'zjeżdżalnia' },
    { wordWithGap: '__arpa', missingLetters: 'sc', fullWord: 'scarpa', hint: 'but' },
    { wordWithGap: 'na__ere', missingLetters: 'sc', fullWord: 'nascere', hint: 'rodzić się' },
    { wordWithGap: '__ena', missingLetters: 'sc', fullWord: 'scena', hint: 'scena' },
    { wordWithGap: '__gliere', missingLetters: 'sce', fullWord: 'scegliere', hint: 'wybierać' },
    { wordWithGap: '__mmietta', missingLetters: 'sci', fullWord: 'scimmietta', hint: 'małpka' },
    { wordWithGap: 'pi__ina', missingLetters: 'sc', fullWord: 'piscina', hint: 'basen' },
    { wordWithGap: '__arpa', missingLetters: 'sc', fullWord: 'sciarpa', hint: 'szalik' },
  ]
};

const category3: GapWordCategory = {
  title: 'Akcenty i apostrofy',
  words: [
    { wordWithGap: 'citt__', missingLetters: 'à', fullWord: 'città', hint: 'miasto' },
    { wordWithGap: 'caff__', missingLetters: 'è', fullWord: 'caffè', hint: 'kawa' },
    { wordWithGap: 'perch__', missingLetters: 'é', fullWord: 'perché', hint: 'dlaczego, ponieważ' },
    { wordWithGap: 'universit__', missingLetters: 'à', fullWord: 'università', hint: 'uniwersytet' },
    { wordWithGap: 'luned__', missingLetters: 'ì', fullWord: 'lunedì', hint: 'poniedziałek' },
    { wordWithGap: 'pi__', missingLetters: 'ù', fullWord: 'più', hint: 'więcej' },
    { wordWithGap: '__', missingLetters: 'è', fullWord: 'è', hint: 'jest' },
    { wordWithGap: 'lag__', missingLetters: 'iù', fullWord: 'laggiù', hint: 'tam na dole' },
    { wordWithGap: 't__', missingLetters: 'è', fullWord: 'tè', hint: 'herbata' },
    { wordWithGap: 'lass__', missingLetters: 'ù', fullWord: 'lassù', hint: 'tam na górze' },
    { wordWithGap: 'cos__', missingLetters: 'ì', fullWord: 'così', hint: 'tak, w ten sposób' },
    { wordWithGap: 'gi__', missingLetters: 'à', fullWord: 'già', hint: 'już' },
    { wordWithGap: '__amica', missingLetters: 'l\'', fullWord: 'l\'amica', hint: 'przyjaciółka' },
    { wordWithGap: '__idea', missingLetters: 'l\'', fullWord: 'l\'idea', hint: 'pomysł' },
    { wordWithGap: '__uomo', missingLetters: 'l\'', fullWord: 'l\'uomo', hint: 'mężczyzna' },
    { wordWithGap: '__acqua', missingLetters: 'l\'', fullWord: 'l\'acqua', hint: 'woda' },
    { wordWithGap: 'un__ora', missingLetters: '\'', fullWord: 'un\'ora', hint: 'godzina' },
    { wordWithGap: 'd__accordo', missingLetters: '\'', fullWord: 'd\'accordo', hint: 'zgoda' },
    { wordWithGap: 'un p__', missingLetters: 'o\'', fullWord: 'un po\'', hint: 'trochę' },
    { wordWithGap: 'poet__', missingLetters: 'à', fullWord: 'poetà', hint: 'poeta' },
    { wordWithGap: 'finch__', missingLetters: 'é', fullWord: 'finché', hint: 'dopóki' },
    { wordWithGap: 'verit__', missingLetters: 'à', fullWord: 'verità', hint: 'prawda' },
    { wordWithGap: 'met__', missingLetters: 'à', fullWord: 'metà', hint: 'połowa' },
    { wordWithGap: 'tirami__', missingLetters: 'sù', fullWord: 'tiramisù', hint: 'deser tiramisu' },
    { wordWithGap: 'perci__', missingLetters: 'ò', fullWord: 'perciò', hint: 'dlatego' },
    { wordWithGap: 'cio__', missingLetters: 'è', fullWord: 'cioè', hint: 'to znaczy' },
    { wordWithGap: 'p__', missingLetters: 'o\'', fullWord: 'po\'', hint: 'trochę (skrót)' },
    { wordWithGap: 'novit__', missingLetters: 'à', fullWord: 'novità', hint: 'nowość' },
  ]
};

export const gapWordsQuestionsIt: GapWordCategory[] = [category1, category2, category3];
