import type { GapWordCategory } from '.';

const category1: GapWordCategory = {
  title: 'Accents & Cédille',
  words: [
    { wordWithGap: 'gar__on', missingLetters: 'ç', fullWord: 'garçon', hint: 'chłopiec' },
    { wordWithGap: 'fran__ais', missingLetters: 'ç', fullWord: 'français', hint: 'francuski' },
    { wordWithGap: 'le__on', missingLetters: 'ç', fullWord: 'leçon', hint: 'lekcja' },
    { wordWithGap: 'p__re', missingLetters: 'è', fullWord: 'père', hint: 'ojciec' },
    { wordWithGap: 'm__re', missingLetters: 'è', fullWord: 'mère', hint: 'matka' },
    { wordWithGap: 'fr__re', missingLetters: 'è', fullWord: 'frère', hint: 'brat' },
    { wordWithGap: 'fen__tre', missingLetters: 'ê', fullWord: 'fenêtre', hint: 'okno' },
    { wordWithGap: 'for__t', missingLetters: 'ê', fullWord: 'forêt', hint: 'las' },
    { wordWithGap: 'h__pital', missingLetters: 'ô', fullWord: 'hôpital', hint: 'szpital' },
    { wordWithGap: 'g__teau', missingLetters: 'â', fullWord: 'gâteau', hint: 'ciasto' },
    { wordWithGap: '__le', missingLetters: 'î', fullWord: 'île', hint: 'wyspa' },
    { wordWithGap: 'cr__pe', missingLetters: 'ê', fullWord: 'crêpe', hint: 'naleśnik' },
    { wordWithGap: 'ch__teau', missingLetters: 'â', fullWord: 'château', hint: 'zamek' },
    { wordWithGap: '__ge', missingLetters: 'â', fullWord: 'âge', hint: 'wiek' },
    { wordWithGap: 'd__ner', missingLetters: 'î', fullWord: 'dîner', hint: 'kolacja' },
    { wordWithGap: 'ma__s', missingLetters: 'ï', fullWord: 'maïs', hint: 'kukurydza' },
    { wordWithGap: 'No__l', missingLetters: 'ë', fullWord: 'Noël', hint: 'Boże Narodzenie' },
    { wordWithGap: 'po__le', missingLetters: 'ê', fullWord: 'poêle', hint: 'patelnia' },
    { wordWithGap: 'ao__t', missingLetters: 'û', fullWord: 'août', hint: 'sierpień' },
    { wordWithGap: 'b__tir', missingLetters: 'â', fullWord: 'bâtir', hint: 'budować' },
    { wordWithGap: 'co__t', missingLetters: 'û', fullWord: 'coût', hint: 'koszt' },
    { wordWithGap: 'go__t', missingLetters: 'û', fullWord: 'goût', hint: 'smak' },
    { wordWithGap: 's__r', missingLetters: 'û', fullWord: 'sûr', hint: 'pewny' },
    { wordWithGap: 'gr__ce', missingLetters: 'â', fullWord: 'grâce', hint: 'łaska' },
    { wordWithGap: 'r__le', missingLetters: 'ô', fullWord: 'rôle', hint: 'rola' },
    { wordWithGap: 't__te', missingLetters: 'ê', fullWord: 'tête', hint: 'głowa' },
    { wordWithGap: 'cr__me', missingLetters: 'è', fullWord: 'crème', hint: 'śmietana' },
    { wordWithGap: 'r__gle', missingLetters: 'è', fullWord: 'règle', hint: 'zasada/linijka' },
  ]
};

const category2: GapWordCategory = {
  title: 'Lettres Muettes',
  words: [
    { wordWithGap: 'beaucou__', missingLetters: 'p', fullWord: 'beaucoup', hint: 'dużo' },
    { wordWithGap: 'tem__s', missingLetters: 'p', fullWord: 'temps', hint: 'czas' },
    { wordWithGap: 'lon__temps', missingLetters: 'g', fullWord: 'longtemps', hint: 'długo' },
    { wordWithGap: 'tro__', missingLetters: 'p', fullWord: 'trop', hint: 'zbyt' },
    { wordWithGap: 'p__tit', missingLetters: 'e', fullWord: 'petit', hint: 'mały' },
    { wordWithGap: 'gran__', missingLetters: 'd', fullWord: 'grand', hint: 'duży' },
    { wordWithGap: 'froi__', missingLetters: 'd', fullWord: 'froid', hint: 'zimny' },
    { wordWithGap: 'chau__', missingLetters: 'd', fullWord: 'chaud', hint: 'gorący' },
    { wordWithGap: 'blan__', missingLetters: 'c', fullWord: 'blanc', hint: 'biały' },
    { wordWithGap: 'pa__', missingLetters: 's', fullWord: 'pas', hint: 'nie (przeczenie)' },
    { wordWithGap: 'plu__', missingLetters: 's', fullWord: 'plus', hint: 'więcej' },
    { wordWithGap: 'toujour__', missingLetters: 's', fullWord: 'toujours', hint: 'zawsze' },
    { wordWithGap: 'jamai__', missingLetters: 's', fullWord: 'jamais', hint: 'nigdy' },
    { wordWithGap: 'do__t', missingLetters: 'ig', fullWord: 'doigt', hint: 'palec' },
    { wordWithGap: 'san__', missingLetters: 'g', fullWord: 'sang', hint: 'krew' },
    { wordWithGap: 'poi__s', missingLetters: 'd', fullWord: 'poids', hint: 'waga' },
    { wordWithGap: 'habi__', missingLetters: 't', fullWord: 'habit', hint: 'ubranie' },
    { wordWithGap: 'nui__', missingLetters: 't', fullWord: 'nuit', hint: 'noc' },
    { wordWithGap: 'li__', missingLetters: 't', fullWord: 'lit', hint: 'łóżko' },
    { wordWithGap: 'desse__t', missingLetters: 'r', fullWord: 'dessert', hint: 'deser' },
    { wordWithGap: 'concer__', missingLetters: 't', fullWord: 'concert', hint: 'koncert' },
    { wordWithGap: 'por__', missingLetters: 't', fullWord: 'port', hint: 'port' },
    { wordWithGap: 'com__ter', missingLetters: 'p', fullWord: 'compter', hint: 'liczyć' },
    { wordWithGap: 'scul__teur', missingLetters: 'p', fullWord: 'sculpteur', hint: 'rzeźbiarz' },
    { wordWithGap: 'complo__', missingLetters: 't', fullWord: 'complot', hint: 'spisek' },
    { wordWithGap: 'respec__', missingLetters: 't', fullWord: 'respect', hint: 'szacunek' },
    { wordWithGap: 'instinc__', missingLetters: 't', fullWord: 'instinct', hint: 'instynkt' },
    { wordWithGap: 'contrac__', missingLetters: 't', fullWord: 'contract', hint: 'umowa' },
  ]
};

const category3: GapWordCategory = {
  title: 'Combinaisons complexes',
  words: [
    { wordWithGap: 'accu__llir', missingLetters: 'ei', fullWord: 'accueillir', hint: 'witać, gościć' },
    { wordWithGap: 'chi__rgien', missingLetters: 'ru', fullWord: 'chirurgien', hint: 'chirurg' },
    { wordWithGap: 'œ__l', missingLetters: 'i', fullWord: 'œil', hint: 'oko' },
    { wordWithGap: 'aujo__d\'hui', missingLetters: 'ur', fullWord: 'aujourd\'hui', hint: 'dzisiaj' },
    { wordWithGap: 'oi__au', missingLetters: 'se', fullWord: 'oiseau', hint: 'ptak' },
    { wordWithGap: 'écu__uil', missingLetters: 're', fullWord: 'écureuil', hint: 'wiewiórka' },
    { wordWithGap: 'caout__ouc', missingLetters: 'ch', fullWord: 'caoutchouc', hint: 'guma' },
    { wordWithGap: 'quincai__erie', missingLetters: 'll', fullWord: 'quincaillerie', hint: 'sklep z art. metalowymi' },
    { wordWithGap: 'f__ille', missingLetters: 'eu', fullWord: 'feuille', hint: 'liść, kartka' },
    { wordWithGap: 'gre__uille', missingLetters: 'no', fullWord: 'grenouille', hint: 'żaba' },
    { wordWithGap: 'fau__uil', missingLetters: 'te', fullWord: 'fauteuil', hint: 'fotel' },
    { wordWithGap: 'enthou__asme', missingLetters: 'si', fullWord: 'enthousiasme', hint: 'entuzjazm' },
    { wordWithGap: 'psy__logie', missingLetters: 'cho', fullWord: 'psychologie', hint: 'psychologia' },
    { wordWithGap: 'rhi__céros', missingLetters: 'no', fullWord: 'rhinocéros', hint: 'nosorożec' },
    { wordWithGap: 'hélico__ère', missingLetters: 'pt', fullWord: 'hélicoptère', hint: 'helikopter' },
    { wordWithGap: 'extra__dinaire', missingLetters: 'or', fullWord: 'extraordinaire', hint: 'niezwykły' },
    { wordWithGap: 'hir__delle', missingLetters: 'on', fullWord: 'hirondelle', hint: 'jaskółka' },
    { wordWithGap: 'co__inelle', missingLetters: 'cc', fullWord: 'coccinelle', hint: 'biedronka' },
    { wordWithGap: 'pa__llon', missingLetters: 'pi', fullWord: 'papillon', hint: 'motyl' },
    { wordWithGap: 'broui__ard', missingLetters: 'll', fullWord: 'brouillard', hint: 'mgła' },
    { wordWithGap: 'cuei__ir', missingLetters: 'll', fullWord: 'cueillir', hint: 'zbierać' },
    { wordWithGap: 'f__illeton', missingLetters: 'eu', fullWord: 'feuilleton', hint: 'serial' },
    { wordWithGap: 'mervei__eux', missingLetters: 'll', fullWord: 'merveilleux', hint: 'cudowny' },
    { wordWithGap: 'tra__il', missingLetters: 'va', fullWord: 'travail', hint: 'praca' },
    { wordWithGap: 'con__il', missingLetters: 'se', fullWord: 'conseil', hint: 'rada' },
    { wordWithGap: 'so__eil', missingLetters: 'mm', fullWord: 'sommeil', hint: 'sen' },
    { wordWithGap: 'rév__l', missingLetters: 'ei', fullWord: 'réveil', hint: 'budzik' },
    { wordWithGap: 'so__il', missingLetters: 'le', fullWord: 'soleil', hint: 'słońce' }
  ]
};

export const gapWordsQuestionsFr: GapWordCategory[] = [category1, category2, category3];
