import type { GapWordCategory } from '.';

const category1: GapWordCategory = {
  title: 'Umlaute & ß',
  words: [
    { wordWithGap: 'Eichhö__chen', missingLetters: 'rn', fullWord: 'Eichhörnchen', hint: 'wiewiórka' },
    { wordWithGap: 'au__erordentlich', missingLetters: 'ß', fullWord: 'außerordentlich', hint: 'nadzwyczajny' },
    { wordWithGap: 'gemü__lich', missingLetters: 't', fullWord: 'gemütlich', hint: 'przytulny' },
    { wordWithGap: 'außergewö__lich', missingLetters: 'hn', fullWord: 'außergewöhnlich', hint: 'niezwykły' },
    { wordWithGap: 'Früh__ück', missingLetters: 'st', fullWord: 'Frühstück', hint: 'śniadanie' },
    { wordWithGap: 'Brö__en', missingLetters: 'tch', fullWord: 'Brötchen', hint: 'bułeczka' },
    { wordWithGap: 'Mä__en', missingLetters: 'dch', fullWord: 'Mädchen', hint: 'dziewczynka' },
    { wordWithGap: 'tat__chlich', missingLetters: 'sä', fullWord: 'tatsächlich', hint: 'faktycznie' },
    { wordWithGap: 'frö__ich', missingLetters: 'hl', fullWord: 'fröhlich', hint: 'wesoły' },
    { wordWithGap: 'gr__en', missingLetters: 'üß', fullWord: 'grüßen', hint: 'pozdrawiać' },
    { wordWithGap: 'F__e', missingLetters: 'üß', fullWord: 'Füße', hint: 'stopy' },
    { wordWithGap: 'Spa__', missingLetters: 'ß', fullWord: 'Spaß', hint: 'zabawa' },
    { wordWithGap: 'hei__en', missingLetters: 'ß', fullWord: 'heißen', hint: 'nazywać się' },
    { wordWithGap: 'Stra__e', missingLetters: 'ß', fullWord: 'Straße', hint: 'ulica' },
    { wordWithGap: 'sü__', missingLetters: 'ß', fullWord: 'süß', hint: 'słodki' },
    { wordWithGap: 'schlie__en', missingLetters: 'ß', fullWord: 'schließen', hint: 'zamykać' },
    { wordWithGap: 'gro__', missingLetters: 'ß', fullWord: 'groß', hint: 'duży' },
    { wordWithGap: 'schö__', missingLetters: 'n', fullWord: 'schön', hint: 'piękny' },
    { wordWithGap: 'L__we', missingLetters: 'ö', fullWord: 'Löwe', hint: 'lew' },
    { wordWithGap: 'B__cher', missingLetters: 'ü', fullWord: 'Bücher', hint: 'książki' },
    { wordWithGap: 'm__de', missingLetters: 'ü', fullWord: 'müde', hint: 'zmęczony' },
    { wordWithGap: 'erz__len', missingLetters: 'äh', fullWord: 'erzählen', hint: 'opowiadać' },
    { wordWithGap: 'K__se', missingLetters: 'ä', fullWord: 'Käse', hint: 'ser' },
    { wordWithGap: 'L__ffel', missingLetters: 'ö', fullWord: 'Löffel', hint: 'łyżka' },
    { wordWithGap: 'f__nf', missingLetters: 'ü', fullWord: 'fünf', hint: 'pięć' },
    { wordWithGap: 'zw__lf', missingLetters: 'ö', fullWord: 'zwölf', hint: 'dwanaście' },
    { wordWithGap: 'T__r', missingLetters: 'ü', fullWord: 'Tür', hint: 'drzwi' },
    { wordWithGap: 'gl__cklich', missingLetters: 'ü', fullWord: 'glücklich', hint: 'szczęśliwy' },
  ]
};

const category2: GapWordCategory = {
  title: 'Złożone spółgłoski',
  words: [
    { wordWithGap: 'Streichholzschä__telchen', missingLetters: 'ch', fullWord: 'Streichholzschächtelchen', hint: 'pudełeczko zapałek' },
    { wordWithGap: 'Recht__reibung', missingLetters: 'sch', fullWord: 'Rechtsschreibung', hint: 'ortografia' },
    { wordWithGap: 'qui__schend', missingLetters: 'et', fullWord: 'quietschend', hint: 'piszczący' },
    { wordWithGap: 'zwi__schern', missingLetters: 't', fullWord: 'zwitschern', hint: 'ćwierkać' },
    { wordWithGap: 'tsche__isch', missingLetters: 'ch', fullWord: 'tschechisch', hint: 'czeski' },
    { wordWithGap: 'Rhy__mus', missingLetters: 'th', fullWord: 'Rhythmus', hint: 'rytm' },
    { wordWithGap: '__lophon', missingLetters: 'Xy', fullWord: 'Xylophon', hint: 'ksylofon' },
    { wordWithGap: 'wahr__einlich', missingLetters: 'sch', fullWord: 'wahrscheinlich', hint: 'prawdopodobnie' },
    { wordWithGap: 'schre__lich', missingLetters: 'ck', fullWord: 'schrecklich', hint: 'straszny' },
    { wordWithGap: 'Ent__uldigung', missingLetters: 'sch', fullWord: 'Entschuldigung', hint: 'przepraszam' },
    { wordWithGap: 'Freund__aft', missingLetters: 'sch', fullWord: 'Freundschaft', hint: 'przyjaźń' },
    { wordWithGap: 'wi__en__aftlich', missingLetters: 'ssensch', fullWord: 'wissenschaftlich', hint: 'naukowy' },
    { wordWithGap: 'durch__nittlich', missingLetters: 'sch', fullWord: 'durchschnittlich', hint: 'przeciętny' },
    { wordWithGap: 'charakteris__isch', missingLetters: 't', fullWord: 'charakteristisch', hint: 'charakterystyczny' },
    { wordWithGap: 'plö__lich', missingLetters: 'tz', fullWord: 'plötzlich', hint: 'nagle' },
    { wordWithGap: 'se__s', missingLetters: 'ch', fullWord: 'sechs', hint: 'sześć' },
    { wordWithGap: 'Spra__e', missingLetters: 'ch', fullWord: 'Sprache', hint: 'język' },
    { wordWithGap: 'Wa__stum', missingLetters: 'chs', fullWord: 'Wachstum', hint: 'wzrost' },
    { wordWithGap: 'ni__ts', missingLetters: 'ch', fullWord: 'nichts', hint: 'nic' },
    { wordWithGap: 'Geschi__te', missingLetters: 'ch', fullWord: 'Geschichte', hint: 'historia' },
    { wordWithGap: 'Te__nik', missingLetters: 'ch', fullWord: 'Technik', hint: 'technika' },
    { wordWithGap: 'Quat__', missingLetters: 'sch', fullWord: 'Quatsch', hint: 'bzdura' },
    { wordWithGap: 'Zwi__ling', missingLetters: 'l', fullWord: 'Zwilling', hint: 'bliźniak' },
    { wordWithGap: 'Kran__eit', missingLetters: 'kh', fullWord: 'Krankheit', hint: 'choroba' },
    { wordWithGap: 'Flu__hafen', missingLetters: 'g', fullWord: 'Flughafen', hint: 'lotnisko' },
    { wordWithGap: 'Gebur__tag', missingLetters: 'ts', fullWord: 'Geburtstag', hint: 'urodziny' },
    { wordWithGap: 'Bibli__hek', missingLetters: 'ot', fullWord: 'Bibliothek', hint: 'biblioteka' },
    { wordWithGap: 'Sy__pathie', missingLetters: 'm', fullWord: 'Sympathie', hint: 'sympatia' },
  ]
};

const category3: GapWordCategory = {
  title: 'Złożone rzeczowniki',
  words: [
    { wordWithGap: 'Geschwindigkeitsbe__enzung', missingLetters: 'gr', fullWord: 'Geschwindigkeitsbegrenzung', hint: 'ograniczenie prędkości' },
    { wordWithGap: 'Unabhängigkeitser__ärung', missingLetters: 'kl', fullWord: 'Unabhängigkeitserklärung', hint: 'deklaracja niepodległości' },
    { wordWithGap: 'Sehenswür__gkeit', missingLetters: 'di', fullWord: 'Sehenswürdigkeit', hint: 'zabytek' },
    { wordWithGap: 'selbstver__ändlich', missingLetters: 'st', fullWord: 'selbstverständlich', hint: 'oczywiście' },
    { wordWithGap: 'Eifer__cht', missingLetters: 'su', fullWord: 'Eifersucht', hint: 'zazdrość' },
    { wordWithGap: 'Hand__uh', missingLetters: 'sch', fullWord: 'Handschuh', hint: 'rękawiczka' },
    { wordWithGap: 'Wochen__de', missingLetters: 'en', fullWord: 'Wochenende', hint: 'weekend' },
    { wordWithGap: 'Kinder__ten', missingLetters: 'gar', fullWord: 'Kindergarten', hint: 'przedszkole' },
    { wordWithGap: 'Kranken__gen', missingLetters: 'wa', fullWord: 'Krankenwagen', hint: 'karetka' },
    { wordWithGap: 'Feuer__hr', missingLetters: 'we', fullWord: 'Feuerwehr', hint: 'straż pożarna' },
    { wordWithGap: 'Bürger__eig', missingLetters: 'st', fullWord: 'Bürgersteig', hint: 'chodnik' },
    { wordWithGap: 'Haupt__dt', missingLetters: 'sta', fullWord: 'Hauptstadt', hint: 'stolica' },
    { wordWithGap: 'Sonnen__irm', missingLetters: 'sch', fullWord: 'Sonnenschirm', hint: 'parasol słoneczny' },
    { wordWithGap: 'Zeit__rift', missingLetters: 'sch', fullWord: 'Zeitschrift', hint: 'czasopismo' },
    { wordWithGap: 'Schlaf__mer', missingLetters: 'zim', fullWord: 'Schlafzimmer', hint: 'sypialnia' },
    { wordWithGap: 'Geburts__g', missingLetters: 'ta', fullWord: 'Geburtstag', hint: 'urodziny' },
    { wordWithGap: 'Erdbe__re', missingLetters: 'e', fullWord: 'Erdbeere', hint: 'truskawka' },
    { wordWithGap: 'Schlüssel__nd', missingLetters: 'bu', fullWord: 'Schlüsselbund', hint: 'pęk kluczy' },
    { wordWithGap: 'Wasser__ll', missingLetters: 'fa', fullWord: 'Wasserfall', hint: 'wodospad' },
    { wordWithGap: 'Fußba__', missingLetters: 'll', fullWord: 'Fußball', hint: 'piłka nożna' },
    { wordWithGap: 'Lebens__ttel', missingLetters: 'mi', fullWord: 'Lebensmittel', hint: 'artykuły spożywcze' },
    { wordWithGap: 'Bücher__al', missingLetters: 'reg', fullWord: 'Bücherregal', hint: 'regał na książki' },
    { wordWithGap: 'Finger__t', missingLetters: 'hu', fullWord: 'Fingerhut', hint: 'naparstek' },
    { wordWithGap: 'Arbeits__mmer', missingLetters: 'zi', fullWord: 'Arbeitszimmer', hint: 'gabinet' },
    { wordWithGap: 'Mülle__er', missingLetters: 'im', fullWord: 'Mülleimer', hint: 'kosz na śmieci' },
    { wordWithGap: 'Regen__irm', missingLetters: 'sch', fullWord: 'Regenschirm', hint: 'parasol' },
    { wordWithGap: 'Schreibtisch__mpe', missingLetters: 'la', fullWord: 'Schreibtischlampe', hint: 'lampka na biurko' },
    { wordWithGap: 'Zahn__ste', missingLetters: 'bür', fullWord: 'Zahnbürste', hint: 'szczoteczka do zębów' },
  ]
};

export const gapWordsQuestionsDe: GapWordCategory[] = [category1, category2, category3];
