import type { GapWordQuestion } from '.';

export const gapWordsQuestionsEs: GapWordQuestion[] = [
  { wordWithGap: 'desa__ollar', missingLetters: 'rr', fullWord: 'desarrollar', hint: 'rozwijać' },
  { wordWithGap: 'otorrinolaringó__go', missingLetters: 'lo', fullWord: 'otorrinolaringólogo', hint: 'otolaryngolog' },
  { wordWithGap: 'para__as', missingLetters: 'gu', fullWord: 'paraguas', hint: 'parasol' },
  { wordWithGap: 'g__rra', missingLetters: 'ue', fullWord: 'guerra', hint: 'wojna' },
  { wordWithGap: 'verg__nza', missingLetters: 'üe', fullWord: 'vergüenza', hint: 'wstyd' },
  { wordWithGap: 'pin__ino', missingLetters: 'gü', fullWord: 'pingüino', hint: 'pingwin' },
  { wordWithGap: 'ci__eña', missingLetters: 'gü', fullWord: 'cigüeña', hint: 'bocian' },
  { wordWithGap: 'anti__edad', missingLetters: 'gü', fullWord: 'antigüedad', hint: 'starożytność' },
  { wordWithGap: 'nicarag__nse', missingLetters: 'üe', fullWord: 'nicaragüense', hint: 'nikaraguański' },
  { wordWithGap: 'psi__iatra', missingLetters: 'qu', fullWord: 'psiquiatra', hint: 'psychiatra' },
  { wordWithGap: 'psicó__go', missingLetters: 'lo', fullWord: 'psicólogo', hint: 'psycholog' },
  { wordWithGap: 'exce__ional', missingLetters: 'pc', fullWord: 'excepcional', hint: 'wyjątkowy' },
  { wordWithGap: 'e__austo', missingLetters: 'xh', fullWord: 'exhausto', hint: 'wyczerpany' },
  { wordWithGap: 'exhi__ción', missingLetters: 'bi', fullWord: 'exhibición', hint: 'wystawa' },
  { wordWithGap: 'zana__ria', missingLetters: 'ho', fullWord: 'zanahoria', hint: 'marchewka' },
  { wordWithGap: 'almo__da', missingLetters: 'ha', fullWord: 'almohada', hint: 'poduszka' },
  { wordWithGap: 'a__gar', missingLetters: 'ho', fullWord: 'ahogar', hint: 'dusić, topić' },
  { wordWithGap: 'aho__ar', missingLetters: 'rr', fullWord: 'ahorrar', hint: 'oszczędzać' },
  { wordWithGap: 'alre__dor', missingLetters: 'de', fullWord: 'alrededor', hint: 'dookoła' },
  { wordWithGap: 'ferroca__il', missingLetters: 'rr', fullWord: 'ferrocarril', hint: 'kolej żelazna' },
  { wordWithGap: 'desoxirribo__leico', missingLetters: 'nuc', fullWord: 'desoxirribonucleico', hint: 'deoksyrybonukleinowy' },
  { wordWithGap: 'electrocardio__ama', missingLetters: 'gr', fullWord: 'electrocardiograma', hint: 'elektrokardiogram' },
  { wordWithGap: 'esternocleido__stoideo', missingLetters: 'ma', fullWord: 'esternocleidomastoideo', hint: 'mięsień mostkowo-obojczykowo-sutkowy' },
  { wordWithGap: 'Guada__ara', missingLetters: 'laj', fullWord: 'Guadalajara', hint: 'miasto w Meksyku' },
  { wordWithGap: 'Que__taro', missingLetters: 'ré', fullWord: 'Querétaro', hint: 'stan w Meksyku' },
  { wordWithGap: 'chicha__ón', missingLetters: 'rr', fullWord: 'chicharrón', hint: 'skwarek' },
  { wordWithGap: 'Chihua__a', missingLetters: 'hu', fullWord: 'Chihuahua', hint: 'rasa psa' },
  { wordWithGap: 'xi__fono', missingLetters: 'ló', fullWord: 'xilófono', hint: 'ksylofon' },
  { wordWithGap: 'a__untamiento', missingLetters: 'y', fullWord: 'ayuntamiento', hint: 'ratusz, gmina' },
  { wordWithGap: 'pro__ibir', missingLetters: 'h', fullWord: 'prohibir', hint: 'zakazywać' }
];
