import type { GapWordQuestion } from '.';

export const gapWordsQuestionsDe: GapWordQuestion[] = [
  { wordWithGap: 'Eichhö__chen', missingLetters: 'rn', fullWord: 'Eichhörnchen', hint: 'wiewiórka' },
  { wordWithGap: 'Streichholzschä__telchen', missingLetters: 'ch', fullWord: 'Streichholzschächtelchen', hint: 'pudełeczko od zapałek' },
  { wordWithGap: 'Recht__reibung', missingLetters: 'sch', fullWord: 'Rechtsschreibung', hint: 'ortografia' },
  { wordWithGap: 'Fünfhundertfünfundfü__ig', missingLetters: 'nfz', fullWord: 'Fünfhundertfünfundfünfzig', hint: 'pięćset pięćdziesiąt pięć' },
  { wordWithGap: 'Geschwindigkeitsbe__enzung', missingLetters: 'gr', fullWord: 'Geschwindigkeitsbegrenzung', hint: 'ograniczenie prędkości' },
  { wordWithGap: 'Unabhängigkeitser__ärung', missingLetters: 'kl', fullWord: 'Unabhängigkeitserklärung', hint: 'deklaracja niepodległości' },
  { wordWithGap: 'au__erordentlich', missingLetters: 'ß', fullWord: 'außerordentlich', hint: 'nadzwyczajny' },
  { wordWithGap: 'qui__schend', missingLetters: 'et', fullWord: 'quietschend', hint: 'piszczący' },
  { wordWithGap: 'zwi__schern', missingLetters: 't', fullWord: 'zwitschern', hint: 'ćwierkać' },
  { wordWithGap: 'tsche__isch', missingLetters: 'ch', fullWord: 'tschechisch', hint: 'czeski' },
  { wordWithGap: 'Rhy__mus', missingLetters: 'th', fullWord: 'Rhythmus', hint: 'rytm' },
  { wordWithGap: '__lophon', missingLetters: 'Xy', fullWord: 'Xylophon', hint: 'ksylofon' },
  { wordWithGap: 'gemü__lich', missingLetters: 't', fullWord: 'gemütlich', hint: 'przytulny' },
  { wordWithGap: 'wahr__einlich', missingLetters: 'sch', fullWord: 'wahrscheinlich', hint: 'prawdopodobnie' },
  { wordWithGap: 'außergewö__lich', missingLetters: 'hn', fullWord: 'außergewöhnlich', hint: 'niezwykły' },
  { wordWithGap: 'Sehenswür__gkeit', missingLetters: 'di', fullWord: 'Sehenswürdigkeit', hint: 'zabytek/atrakcja turystyczna' },
  { wordWithGap: 'Eifer__cht', missingLetters: 'su', fullWord: 'Eifersucht', hint: 'zazdrość' },
  { wordWithGap: 'schre__lich', missingLetters: 'ck', fullWord: 'schrecklich', hint: 'straszny' },
  { wordWithGap: 'Früh__ück', missingLetters: 'st', fullWord: 'Frühstück', hint: 'śniadanie' },
  { wordWithGap: 'selbstver__ändlich', missingLetters: 'st', fullWord: 'selbstverständlich', hint: 'oczywiście' },
  { wordWithGap: 'Ent__uldigung', missingLetters: 'sch', fullWord: 'Entschuldigung', hint: 'przepraszam' },
  { wordWithGap: 'Freund__aft', missingLetters: 'sch', fullWord: 'Freundschaft', hint: 'przyjaźń' },
  { wordWithGap: 'wi__en__aftlich', missingLetters: 'ss', fullWord: 'wissenschaftlich', hint: 'naukowy' },
  { wordWithGap: 'durch__nittlich', missingLetters: 'sch', fullWord: 'durchschnittlich', hint: 'przeciętny' },
  { wordWithGap: 'charakteris__isch', missingLetters: 't', fullWord: 'charakteristisch', hint: 'charakterystyczny' },
  { wordWithGap: 'Brö__en', missingLetters: 'tch', fullWord: 'Brötchen', hint: 'bułeczka' },
  { wordWithGap: 'Mä__en', missingLetters: 'dch', fullWord: 'Mädchen', hint: 'dziewczynka' },
  { wordWithGap: 'tat__chlich', missingLetters: 'sä', fullWord: 'tatsächlich', hint: 'faktycznie' },
  { wordWithGap: 'plö__lich', missingLetters: 'tz', fullWord: 'plötzlich', hint: 'nagle' },
  { wordWithGap: 'frö__ich', missingLetters: 'hl', fullWord: 'fröhlich', hint: 'wesoły' }
];
