import type { GapWordQuestion } from '.';

export const gapWordsQuestionsIt: GapWordQuestion[] = [
  { wordWithGap: 'psi__logo', missingLetters: 'co', fullWord: 'psicologo', hint: 'psycholog' },
  { wordWithGap: 'gno__hi', missingLetters: 'cc', fullWord: 'gnocchi', hint: 'kluski gnocchi' },
  { wordWithGap: 'co__ienza', missingLetters: 'sc', fullWord: 'coscienza', hint: 'sumienie, świadomość' },
  { wordWithGap: 'ghia__io', missingLetters: 'cc', fullWord: 'ghiaccio', hint: 'lód' },
  { wordWithGap: 'sc__nza', missingLetters: 'ie', fullWord: 'scienza', hint: 'nauka' },
  { wordWithGap: 'a__uario', missingLetters: 'cq', fullWord: 'acquario', hint: 'akwarium' },
  { wordWithGap: 'chia__hierare', missingLetters: 'cc', fullWord: 'chiacchierare', hint: 'gawędzić' },
  { wordWithGap: 'a__io', missingLetters: 'gl', fullWord: 'aglio', hint: 'czosnek' },
  { wordWithGap: 'fi__i', missingLetters: 'gl', fullWord: 'figli', hint: 'dzieci, synowie' },
  { wordWithGap: 'sba__iare', missingLetters: 'gl', fullWord: 'sbagliare', hint: 'popełniać błąd' },
  { wordWithGap: 'circonfere__a', missingLetters: 'nz', fullWord: 'circonferenza', hint: 'obwód' },
  { wordWithGap: 'scio__iere', missingLetters: 'gl', fullWord: 'sciogliere', hint: 'rozpuszczać' },
  { wordWithGap: 'a__ensore', missingLetters: 'sc', fullWord: 'ascensore', hint: 'winda' },
  { wordWithGap: 'inge__ere', missingLetters: 'gn', fullWord: 'ingegnere', hint: 'inżynier' },
  { wordWithGap: 'ragio__ere', missingLetters: 'ni', fullWord: 'ragioniere', hint: 'księgowy' },
  { wordWithGap: 'auto__rada', missingLetters: 'st', fullWord: 'autostrada', hint: 'autostrada' },
  { wordWithGap: 'aero__rto', missingLetters: 'po', fullWord: 'aeroporto', hint: 'lotnisko' },
  { wordWithGap: 'zan__ra', missingLetters: 'za', fullWord: 'zanzara', hint: 'komar' },
  { wordWithGap: 'z__no', missingLetters: 'ai', fullWord: 'zaino', hint: 'plecak' },
  { wordWithGap: 'zu__hero', missingLetters: 'cc', fullWord: 'zucchero', hint: 'cukier' },
  { wordWithGap: 'pi__a', missingLetters: 'zz', fullWord: 'pizza', hint: 'pizza' },
  { wordWithGap: 'pa__o', missingLetters: 'zz', fullWord: 'pazzo', hint: 'szalony' },
  { wordWithGap: 'a__iacciare', missingLetters: 'ggh', fullWord: 'agghiacciare', hint: 'mrozić' },
  { wordWithGap: 'chiun__e', missingLetters: 'qu', fullWord: 'chiunque', hint: 'ktokolwiek' },
  { wordWithGap: 's__alo', missingLetters: 'qu', fullWord: 'squalo', hint: 'rekin' },
  { wordWithGap: 'a__ila', missingLetters: 'qu', fullWord: 'aquila', hint: 'orzeł' },
  { wordWithGap: 's__erzo', missingLetters: 'ch', fullWord: 'scherzo', hint: 'żart' },
  { wordWithGap: 'ghia__', missingLetters: 'ia', fullWord: 'ghiaia', hint: 'żwir' },
  { wordWithGap: 'scio__ro', missingLetters: 'pe', fullWord: 'sciopero', hint: 'strajk' },
  { wordWithGap: 'ghi__', missingLetters: 'ro', fullWord: 'ghiro', hint: 'suseł' }
];
