import type { GapWordQuestion } from '.';

export const gapWordsQuestionsEn: GapWordQuestion[] = [
  { wordWithGap: 'consci__tious', missingLetters: 'en', fullWord: 'conscientious', hint: 'sumienny' },
  { wordWithGap: 'phenom__on', missingLetters: 'en', fullWord: 'phenomenon', hint: 'zjawisko' },
  { wordWithGap: 'rhy__m', missingLetters: 'th', fullWord: 'rhythm', hint: 'rytm' },
  { wordWithGap: 'que__', missingLetters: 'ue', fullWord: 'queue', hint: 'kolejka' },
  { wordWithGap: 'lia__on', missingLetters: 'is', fullWord: 'liaison', hint: 'łącznik, współpraca' },
  { wordWithGap: 'fl__rescent', missingLetters: 'uo', fullWord: 'fluorescent', hint: 'fluorescencyjny' },
  { wordWithGap: 'parapherna__a', missingLetters: 'li', fullWord: 'paraphernalia', hint: 'rekwizyty, akcesoria' },
  { wordWithGap: 'misch__vous', missingLetters: 'ie', fullWord: 'mischievous', hint: 'psotny, szelmowski' },
  { wordWithGap: 'entrep__neur', missingLetters: 're', fullWord: 'entrepreneur', hint: 'przedsiębiorca' },
  { wordWithGap: 'bou__eois', missingLetters: 'rg', fullWord: 'bourgeois', hint: 'mieszczański' },
  { wordWithGap: 'ya__t', missingLetters: 'ch', fullWord: 'yacht', hint: 'jacht' },
  { wordWithGap: 'fu__sia', missingLetters: 'ch', fullWord: 'fuchsia', hint: 'fuksja (kolor)' },
  { wordWithGap: 'co__oisseur', missingLetters: 'nn', fullWord: 'connoisseur', hint: 'znawca, koneser' },
  { wordWithGap: 'ac__iesce', missingLetters: 'qu', fullWord: 'acquiesce', hint: 'zgodzić się, przystać na coś' },
  { wordWithGap: 'idiosyncra__', missingLetters: 'sy', fullWord: 'idiosyncrasy', hint: 'specyficzna cecha, dziwactwo' },
  { wordWithGap: 'onoma__poeia', missingLetters: 'to', fullWord: 'onomatopoeia', hint: 'onomatopeja' },
  { wordWithGap: 'mi__ennium', missingLetters: 'll', fullWord: 'millennium', hint: 'tysiąclecie' },
  { wordWithGap: 'chrysan__emum', missingLetters: 'th', fullWord: 'chrysanthemum', hint: 'chryzantema' },
  { wordWithGap: 'zu__hini', missingLetters: 'cc', fullWord: 'zucchini', hint: 'cukinia' },
  { wordWithGap: 'bureaucra__', missingLetters: 'cy', fullWord: 'bureaucracy', hint: 'biurokracja' },
  { wordWithGap: 'da__shund', missingLetters: 'ch', fullWord: 'dachshund', hint: 'jamnik' },
  { wordWithGap: 'psy__iatrist', missingLetters: 'ch', fullWord: 'psychiatrist', hint: 'psychiatra' },
  { wordWithGap: 'pseu__nym', missingLetters: 'do', fullWord: 'pseudonym', hint: 'pseudonim' },
  { wordWithGap: 'hemor__age', missingLetters: 'rh', fullWord: 'hemorrhage', hint: 'krwotok' },
  { wordWithGap: 'Wor__stershire', missingLetters: 'ce', fullWord: 'Worcestershire', hint: 'nazwa hrabstwa i sosu' },
  { wordWithGap: 'aes__etic', missingLetters: 'th', fullWord: 'aesthetic', hint: 'estetyczny' },
  { wordWithGap: 'man__ver', missingLetters: 'eu', fullWord: 'maneuver', hint: 'manewr' },
  { wordWithGap: 'naus__us', missingLetters: 'eo', fullWord: 'nauseous', hint: 'mający mdłości' },
  { wordWithGap: 'susce__ible', missingLetters: 'pt', fullWord: 'susceptible', hint: 'podatny' },
  { wordWithGap: 'a__ommodate', missingLetters: 'cc', fullWord: 'accommodate', hint: 'zakwaterować, pomieścić' }
];
