import type { GapWordQuestion } from '.';

export const gapWordsQuestionsFr: GapWordQuestion[] = [
  { wordWithGap: 'accu__llir', missingLetters: 'ei', fullWord: 'accueillir', hint: 'witać, gościć' },
  { wordWithGap: 'chi__rgien', missingLetters: 'ru', fullWord: 'chirurgien', hint: 'chirurg' },
  { wordWithGap: 'œ__l', missingLetters: 'i', fullWord: 'œil', hint: 'oko' },
  { wordWithGap: 'aujo__d\'hui', missingLetters: 'ur', fullWord: 'aujourd\'hui', hint: 'dzisiaj' },
  { wordWithGap: 'oi__au', missingLetters: 'se', fullWord: 'oiseau', hint: 'ptak' },
  { wordWithGap: 'écu__uil', missingLetters: 're', fullWord: 'écureuil', hint: 'wiewiórka' },
  { wordWithGap: 'y__ourt', missingLetters: 'ao', fullWord: 'yaourt', hint: 'jogurt' },
  { wordWithGap: 'caout__ouc', missingLetters: 'ch', fullWord: 'caoutchouc', hint: 'kauczuk, guma' },
  { wordWithGap: 'quincai__erie', missingLetters: 'll', fullWord: 'quincaillerie', hint: 'sklep z artykułami metalowymi' },
  { wordWithGap: 'f__ille', missingLetters: 'eu', fullWord: 'feuille', hint: 'liść, kartka' },
  { wordWithGap: 'gre__uille', missingLetters: 'no', fullWord: 'grenouille', hint: 'żaba' },
  { wordWithGap: 'fau__uil', missingLetters: 'te', fullWord: 'fauteuil', hint: 'fotel' },
  { wordWithGap: 'enthou__asme', missingLetters: 'si', fullWord: 'enthousiasme', hint: 'entuzjazm' },
  { wordWithGap: 'psy__logie', missingLetters: 'cho', fullWord: 'psychologie', hint: 'psychologia' },
  { wordWithGap: 'rhi__céros', missingLetters: 'no', fullWord: 'rhinocéros', hint: 'nosorożec' },
  { wordWithGap: 'hélico__ère', missingLetters: 'pt', fullWord: 'hélicoptère', hint: 'helikopter' },
  { wordWithGap: 'extra__dinaire', missingLetters: 'or', fullWord: 'extraordinaire', hint: 'niezwykły' },
  { wordWithGap: 'hir__delle', missingLetters: 'on', fullWord: 'hirondelle', hint: 'jaskółka' },
  { wordWithGap: 'co__inelle', missingLetters: 'cc', fullWord: 'coccinelle', hint: 'biedronka' },
  { wordWithGap: 'pa__llon', missingLetters: 'pi', fullWord: 'papillon', hint: 'motyl' },
  { wordWithGap: 'broui__ard', missingLetters: 'll', fullWord: 'brouillard', hint: 'mgła' },
  { wordWithGap: 'cuei__ir', missingLetters: 'll', fullWord: 'cueillir', hint: 'zbierać, zrywać' },
  { wordWithGap: 'f__illeton', missingLetters: 'eu', fullWord: 'feuilleton', hint: 'serial, powieść w odcinkach' },
  { wordWithGap: 'mervei__eux', missingLetters: 'll', fullWord: 'merveilleux', hint: 'cudowny' },
  { wordWithGap: 'tra__il', missingLetters: 'va', fullWord: 'travail', hint: 'praca' },
  { wordWithGap: 'con__il', missingLetters: 'se', fullWord: 'conseil', hint: 'rada' },
  { wordWithGap: 'so__eil', missingLetters: 'mm', fullWord: 'sommeil', hint: 'sen' },
  { wordWithGap: 'rév__l', missingLetters: 'ei', fullWord: 'réveil', hint: 'budzik, pobudka' },
  { wordWithGap: 'ab__lle', missingLetters: 'ei', fullWord: 'abeille', hint: 'pszczoła' },
  { wordWithGap: 'so__il', missingLetters: 'le', fullWord: 'soleil', hint: 'słońce' }
];
